# -*- coding: utf-8 -*-
"""Johdatus biotekniikkaan: sanaston toinen kierros (omistaja 12.9.2026: 'tee jokaikisesta sanasta!'). Kalvojen loput termit:
historian nimet, tuotto-organismit, teollisuuden ja diagnostiikan arkisanat. Liitetaan biotek_sanasto.py:n listojen jatkoksi."""
from biotek_taivutus import L
from pakka_rakenna import K

def N(*forms):
    return list(forms)

L1 = [
K("Mikä on AIV-rehu?",
  "A. I. Virtasen 1920-luvulla kehittämä säilörehu, jossa happo estää pilaantumisen. Toi Suomeen kemian Nobelin 1945.",
  "",
  2, L(N('AIV-rehu', 'AIV-rehun', 'AIV-rehua', 'AIV', 'AIV:n', 'AIV-rehunsäilytysmenetelmä', 'AIV-rehunsäilytysmenetelmän', 'säilörehu', 'säilörehun', 'säilörehua', 'Virtanen', 'Virtasen', 'A. I. Virtanen', 'A. I. Virtasen', 'Artturi Ilmari Virtanen'))),
K("Mikä on alkio?",
  "Hedelmöityneestä munasolusta kehittyvä varhainen yksilö. Alkion kantasolut ovat kaikkikykyisiä.",
  "",
  2, L('alkio', ['alkion kantasolu', 'alkion kantasolun', 'alkion kantasolut', 'alkion kantasoluja', 'alkionkantasolu', 'alkionkantasolut'])),
K("Mikä on Alzheimerin tauti?",
  "Yleisin muistisairaus, jossa beeta-amyloidi kertyy aivoihin plakeiksi. Vasta-aine aducanumab poistaa amyloidia mutta tehoaa heikosti.",
  "",
  2, L(N('Alzheimerin tauti', 'Alzheimerin taudin', 'Alzheimerin tautia', 'Alzheimerin taudissa', 'Alzheimer', 'Alzheimerin', 'muistisairaus', 'muistisairauden', 'muistisairautta', 'muistisairaudet', 'beeta-amyloidi', 'beeta-amyloidin', 'beeta-amyloidia', 'amyloidi', 'amyloidin', 'amyloidia', 'amyloidiplakki', 'amyloidiplakin', 'amyloidiplakit', 'amyloidiplakkeja', 'amyloidifibrilli', 'amyloidifibrillin', 'amyloidifibrillit', 'aducanumab', 'aducanumabin', 'aducanumabia', 'Aduhelm'))),
K("Mikä on ABE-fermentaatio?",
  "Clostridium-bakteerin käyminen, joka tuottaa asetonia, butanolia ja etanolia. Weizmannin menetelmä 1916 räjähdysaineiden asetoniin.",
  "",
  1, L(N('ABE-fermentaatio', 'ABE-fermentaation', 'ABE-fermentaatiota', 'asetoni', 'asetonin', 'asetonia', 'butanoli', 'butanolin', 'butanolia', 'Weizmann', 'Weizmannin', 'Clostridium', 'Clostridiumin'))),
K("Mikä on A-vitamiini?",
  "Näölle ja iholle välttämätön rasvaliukoinen vitamiini. Kultainen riisi on muokattu tuottamaan sen esiastetta beetakaroteenia.",
  "",
  2, L(N('A-vitamiini', 'A-vitamiinin', 'A-vitamiinia', 'A-vitamiinin puute', 'A-vitamiinin puutteen', 'kultainen riisi', 'kultaisen riisin', 'kultaista riisiä', 'beetakaroteeni', 'beetakaroteenin', 'beetakaroteenia', 'riisi', 'riisin', 'riisiä'))),
K("Mikä on biojäte?",
  "Eloperäinen jäte, kuten ruoantähteet, joka mädätetään biokaasuksi tai kompostoidaan mikrobien avulla.",
  "",
  1, L('biojäte', ['biojätteen', 'biojätettä', 'biojätteet', 'biojätteiden', 'biojätteitä', 'jätehuolto', 'jätehuollon', 'jätehuoltoa', 'kierrätys', 'kierrätyksen', 'kierrätystä', 'kompostointi', 'kompostoinnin', 'kompostoida', 'mädätys', 'mädätyksen', 'mädättää', 'mädättämällä'])),
K("Mitä biostatistiikka on?",
  "Tilastotieteen soveltamista biologiaan ja lääketieteeseen: koeasetelmat, hajonnan arviointi ja tulosten merkitsevyys.",
  "",
  1, L('biostatistiikka', ['tilastotiede', 'tilastotieteen', 'tilastotiedettä', 'tilastollinen', 'tilastollisen', 'tilastollista', 'tilastolliset', 'tilastollisesti', 'matematiikka', 'matematiikan', 'matematiikkaa'])),
K("Kuka oli Charles Darwin?",
  "Luonnonvalintaan perustuvan evoluutioteorian esittäjä (Lajien synty 1859). Kasvinjalostus on ihmisen ohjaamaa valintaa.",
  "",
  2, L(N('Darwin', 'Darwinin', 'Darwinia', 'Charles Darwin', 'Charles Darwinin', 'Lajien synty', 'Lajien synnyn'))),
K("Kuka oli Dolly?",
  "Ensimmäinen aikuisen nisäkkään solusta kloonattu eläin, lammas, syntyi 1996 Skotlannissa tumansiirrolla.",
  "",
  2, L(N('Dolly', 'Dollyn', 'Dollya', 'Dolly-lammas', 'Dolly-lampaan', 'tumansiirto', 'tumansiirron', 'tumansiirtoa', 'tumansiirrolla'))),
K("Kuka oli Károly Ereky?",
  "Unkarilainen insinööri, joka otti sanan biotekniikka (biotechnologie) käyttöön 1919 sikojen teollisesta kasvatuksesta.",
  "",
  1, L(N('Ereky', 'Erekyn', 'Erekyä', 'Károly Ereky', 'Karl Ereky', 'Károly Erekyn'))),
K("Mitä etiikka on biotekniikassa?",
  "Oikean ja väärän pohdinta: saako ihmisen perimää muokata, eläimiä kloonata tai geenejä patentoida. Kutsutaan myös: bioetiikka.",
  "",
  2, L('etiikka', ['eettinen', 'eettisen', 'eettistä', 'eettiset', 'eettisiä', 'eettisiin', 'eettisesti', 'bioetiikka', 'bioetiikan', 'bioetiikkaa'])),
K("Kuka oli Alexander Fleming?",
  "Löysi 1928, että Penicillium-home tappaa bakteereja. Penisilliinin teollinen tuotanto alkoi 1940-luvulla.",
  "",
  2, L(N('Fleming', 'Flemingin', 'Flemingiä', 'Alexander Fleming', 'Alexander Flemingin', 'Penicillium', 'Penicilliumin', 'Penicillium-home', 'Penicillium-homeen'))),
K("Mikä on GM-ruoka?",
  "Muuntogeenisestä eliöstä valmistettu elintarvike, kuten Bt-maissi tai Flavr Savr -tomaatti (1994, ensimmäinen GM-ruoka).",
  "",
  2, L(N('GM-ruoka', 'GM-ruoan', 'GM-ruokaa', 'GM-ruuan', 'GMO-tomaatti', 'GMO-tomaatin', 'GM-tomaatti', 'Flavr Savr', 'Flavr Savr -tomaatti', 'muuntogeeninen elintarvike', 'muuntogeenisen elintarvikkeen', 'muuntogeeniset elintarvikkeet', 'GM-kasvi', 'GM-kasvin', 'GM-kasvit', 'GM-kasvien', 'Bt-maissi', 'Bt-maissin', 'Bt-toksiini', 'Bt-toksiinin'))),
K("Mikä on hematopoieettinen kantasolu?",
  "Luuytimen kantasolu, josta kaikki verisolut syntyvät. Luuydinsiirto siirtää niitä potilaaseen.",
  "",
  2, L(N('hematopoieettinen kantasolu', 'hematopoieettisen kantasolun', 'hematopoieettista kantasolua', 'hematopoieettiset kantasolut', 'hematopoieettisia kantasoluja', 'hematopoieettisista kantasoluista', 'hematopoieettinen', 'hematopoieettisen', 'verisolujen kantasolu', 'verisolujen kantasolut', 'luuydin', 'luuytimen', 'luuydintä', 'luuytimessä', 'luuydinsiirto', 'luuydinsiirron', 'luuydinsiirtoa'))),
K("Mikä on hermosolu?",
  "Sähköisiä impulsseja johtava solu, jolla on pitkä viejähaarake eli aksoni. Kutsutaan myös: neuroni.",
  "",
  2, L('hermosolu', 'neuroni', ['aksoni', 'aksonin', 'aksonia', 'aksonit', 'hermosoluja', 'hermosoluista'])),
K("Mikä on Huomen-lehmä?",
  "Suomen ensimmäinen siirtogeeninen nauta (1993), muokattu tuottamaan maitoonsa ihmisen proteiinia.",
  "",
  1, L(N('Huomen', 'Huomenen', 'Huomen-lehmä', 'Huomen-lehmän'))),
K("Mikä on biologinen hyönteismyrkky?",
  "Eliöperäinen tuholaisten torjunta-aine, kuten Bacillus thuringiensis -bakteerin Bt-toksiini tai krysanteemin pyretriini.",
  "",
  2, L(N('hyönteismyrkky', 'hyönteismyrkyn', 'hyönteismyrkkyä', 'hyönteismyrkyt', 'torjunta-aine', 'torjunta-aineen', 'torjunta-ainetta', 'torjunta-aineet', 'torjunta-aineiden', 'torjunta-aineita', 'tuholaismyrkky', 'tuholaismyrkyn', 'tuholaismyrkyt', 'pyretriini', 'pyretriinin', 'pyretriiniä', 'krysanteemi', 'krysanteemin', 'krysanteemista', 'Bacillus thuringiensis', 'Bacillus thuringiensiksen', 'tuhohyönteinen', 'tuhohyönteisen', 'tuhohyönteiset', 'tuhohyönteisiä', 'tuhohyönteisten'))),
K("Mikä oli isorokko?",
  "Tappava virustauti, jonka Jenner ehkäisi 1796 lehmänrokolla, ensimmäisellä rokotteella. Hävitetty maailmasta 1980.",
  "",
  2, L(N('isorokko', 'isorokon', 'isorokkoa', 'isorokkovirus', 'isorokkoviruksen', 'lehmänrokko', 'lehmänrokon', 'lehmänrokkoa', 'lehmänrokolla', 'Jenner', 'Jennerin', 'Edward Jenner', 'Edward Jennerin'))),
K("Mitä ovat perinteiset fermentoidut elintarvikkeet?",
  "Mikrobien valmistamat ruoat: olut ja viini hiivalla, leipä hiivalla, jugurtti ja juusto maitohappobakteereilla, etikka Acetobacterilla.",
  "Käyminen on vanhinta biotekniikkaa. Sumerilaiset ja egyptiläiset panivat olutta ja leipoivat hapatettua leipää tuhansia vuosia ennen kuin hiivan olemassaolo tiedettiin, ja babylonialaiset kirjasivat oluen reseptejä savitauluihin. Maitohappobakteerit happamoittavat maidon jugurtiksi ja juustoksi ja säilövät hapankaalin, Acetobacter hapettaa viinin etanolin etikaksi. Pasteur osoitti 1850-luvulla, että käyminen on elävien mikrobien työtä.",
  2, L(N('olut', 'oluen', 'olutta', 'oluessa', 'oluet', 'oluiden', 'viini', 'viinin', 'viiniä', 'viinit', 'leipä', 'leivän', 'leipää', 'leivät', 'jugurtti', 'jugurtin', 'jugurttia', 'juusto', 'juuston', 'juustoa', 'juustot', 'juustojen', 'hapankaali', 'hapankaalin', 'fermentoitu elintarvike', 'fermentoidun elintarvikkeen', 'fermentoidut elintarvikkeet', 'sumerilaiset', 'sumerilaisten', 'babylonialaiset', 'babylonialaisten', 'egyptiläiset', 'egyptiläisten'))),
K("Mikä on maitohappobakteeri?",
  "Bakteeri, joka käyttää sokerin maitohapoksi. Happamoittaa jugurtin, juuston ja hapankaalin ja estää pilaajien kasvun.",
  "",
  2, L('maitohappobakteeri', ['Lactobacillus', 'Lactobacilluksen', 'Lactococcus', 'maitohappokäyminen', 'maitohappokäymisen', 'maitohappokäymistä'])),
K("Mikä on koeputki?",
  "Laboratorion pieni lasi- tai muoviputki reaktioita ja näytteitä varten. In vitro tarkoittaa kirjaimellisesti lasissa.",
  "",
  1, L('koeputki', ['koeputket', 'koeputkia', 'koeputkessa', 'putki', 'putken', 'putkea', 'putket', 'putkia', 'putkilo', 'putkilon', 'putkiloon'])),
K("Kuka oli Daniel Koshland?",
  "Biokemisti, joka esitti 1958 entsyymin indusoidun sopivuuden mallin: substraatti muovaa entsyymin aktiivista kohtaa.",
  "",
  1, L(N('Koshland', 'Koshlandin', 'Koshlandia', 'Daniel Koshland', 'Daniel Koshlandin'))),
K("Keitä olivat Köhler ja Milstein?",
  "Kehittivät 1975 hybridoomatekniikan, jolla monoklonaalisia vasta-aineita tuotetaan rajattomasti. Nobel 1984.",
  "",
  2, L(N('Köhler', 'Köhlerin', 'Milstein', 'Milsteinin', 'Köhler ja Milstein', 'Köhlerin ja Milsteinin', 'Georges Köhler', 'César Milstein'))),
K("Mikä on kynsisammakko?",
  "Xenopus laevis, afrikkalainen sammakko, jonka suuria munasoluja käytetään kehitysbiologian ja proteiinitutkimuksen mallina.",
  "",
  1, L('kynsisammakko', ['kynsisammakon', 'kynsisammakkoa', 'kynsisammakot', 'Xenopus', 'Xenopuksen', 'Xenopus laevis', 'Xenopus laeviksen'])),
K("Mitä massatuotanto tarkoittaa biotekniikassa?",
  "Tuotteen valmistamista teollisessa mittakaavassa, kuten penisilliiniä satojen kuutioiden fermentoreissa. Kutsutaan myös: suurtuotanto.",
  "",
  1, L('massatuotanto', ['suurtuotanto', 'suurtuotannon', 'suurtuotantoa', 'suurtuotannossa', 'teollinen mittakaava', 'teollisen mittakaavan', 'teollisessa mittakaavassa'])),
K("Kuka oli Gregor Mendel?",
  "Munkki, jonka herneristeytykset 1865 paljastivat periytymisen lait: ominaisuudet siirtyvät erillisinä tekijöinä, geeneinä.",
  "",
  2, L(N('Mendel', 'Mendelin', 'Mendeliä', 'Gregor Mendel', 'Gregor Mendelin', 'Mendelin lait', 'Mendelin lakien', 'herneristeytys', 'herneristeytykset', 'herneristeytyksistä'))),
K("Mikä on metylaatio?",
  "Metyyliryhmän –CH<sub>3</sub> liittäminen DNA:n sytosiiniin tai histoniin. Hiljentää geenejä muuttamatta emäsjärjestystä: epigeneettinen merkki.",
  "",
  2, L('metylaatio', ['metyloida', 'metyloidaan', 'metyloitu', 'metyloitua', 'metyloituu', 'DNA-metylaatio', 'DNA-metylaation', 'epigeneettinen', 'epigeneettisen', 'epigeneettistä', 'epigeneettiset', 'epigenetiikka', 'epigenetiikan', 'epigenetiikkaa'])),
K("Kuka oli Friedrich Miescher?",
  "Eristi 1869 solun tumista fosforipitoisen aineen, nukleiinin, eli löysi DNA:n vuosikymmeniä ennen sen merkityksen ymmärtämistä.",
  "",
  1, L(N('Miescher', 'Miescherin', 'Friedrich Miescher', 'Friedrich Miescherin', 'nukleiini', 'nukleiinin', 'nukleiinia'))),
K("Mikä on mikroskooppi?",
  "Laite, joka suurentaa pieniä kohteita linsseillä (valomikroskooppi) tai elektronisuihkulla (elektronimikroskooppi). Leeuwenhoek näki sillä mikrobit 1670-luvulla.",
  "",
  2, L('mikroskooppi', ['mikroskopia', 'mikroskopian', 'mikroskopiaa', 'valomikroskooppi', 'valomikroskoopin', 'valomikroskoopilla', 'elektronimikroskooppi', 'elektronimikroskoopin', 'elektronimikroskoopilla', 'elektronimikroskopia', 'elektronimikroskopian', 'Leeuwenhoek', 'Leeuwenhoekin'])),
K("Mikä on mikro-RNA?",
  "Noin 22 nukleotidin RNA, joka sitoutuu lähetti-RNA:han ja hiljentää geenin. Nobel 2024. Kutsutaan myös: miRNA.",
  "",
  2, L(N('mikro-RNA', 'mikro-RNA:n', 'mikro-RNA:ta', 'miRNA', 'miRNA:n', 'miRNA:ta', 'miRNA:t', 'mikroRNA', 'mikroRNA:n', 'RNA-interferenssi', 'RNA-interferenssin', 'RNA-interferenssiä', 'RNAi', 'siRNA', 'siRNA:n'))),
K("Mikä on Papa-testi?",
  "Kohdunkaulan solunäyte, josta syövän esiasteet tunnistetaan mikroskoopilla. Ensimmäisiä seulontatestejä (Papanicolaou 1940-luku).",
  "",
  1, L(N('Papa-testi', 'Papa-testin', 'Papa-testiä', 'Papa-koe', 'Papa-kokeen', 'papa-testi', 'papa-näyte', 'papa-näytteen', 'Papanicolaou', 'Papanicolaoun', 'kohdunkaulan syöpä', 'kohdunkaulan syövän', 'kohdunkaulansyöpä', 'kohdunkaulansyövän'))),
K("Kuka oli Louis Pasteur?",
  "Osoitti 1850–60-luvuilla, että käyminen ja taudit ovat mikrobien aiheuttamia, kehitti pastöroinnin ja raivotautirokotteen.",
  "",
  2, L(N('Pasteur', 'Pasteurin', 'Pasteuria', 'Louis Pasteur', 'Louis Pasteurin'))),
K("Mikä on radioimmunomääritys?",
  "Ensimmäinen immunomääritys (Yalow 1959): radioaktiivisesti leimattu antigeeni kilpailee näytteen antigeenin kanssa vasta-aineesta. Kutsutaan myös: RIA.",
  "",
  2, L('radioimmunomääritys', ['RIA', 'RIA:n', 'RIA:ta', 'radioimmunomäärityksiä', 'radioaktiivinen leima', 'radioaktiivisen leiman', 'radioaktiivisella leimalla', 'radioaktiivinen', 'radioaktiivisen', 'radioaktiivista', 'radioaktiiviset', 'radioaktiivisesti', 'Yalow', 'Yalowin'])),
K("Kuka oli Frederick Sanger?",
  "Kaksinkertainen kemian nobelisti: selvitti insuliinin aminohappojärjestyksen (1958) ja kehitti DNA:n sekvensointimenetelmän (1980).",
  "",
  2, L(N('Sanger', 'Sangerin', 'Sangeria', 'Frederick Sanger', 'Frederick Sangerin', 'Sangerin menetelmä', 'Sangerin menetelmän', 'Sangerin menetelmää', 'Sanger-sekvensointi', 'Sanger-sekvensoinnin', 'dideoksisekvensointi', 'dideoksisekvensoinnin'))),
K("Mikä on soijapapumaito?",
  "Soijapavuista tehty kasvijuoma. Esimerkki elintarvikkeesta, jonka valmistuksessa entsyymejä käytetään maun ja koostumuksen parantamiseen.",
  "",
  1, L(N('soijapapumaito', 'soijapapumaidon', 'soijapapumaitoa', 'soijamaito', 'soijamaidon', 'soijamaitoa', 'kasvijuoma', 'kasvijuoman', 'kasvijuomaa', 'kasvijuomat', 'kasvijuomissa', 'kauramaito', 'kauramaidon', 'kauramaitoa', 'kaurajuoma', 'kaurajuoman', 'kaurajuomat', 'kaurajuomia', 'soija', 'soijan', 'soijaa', 'soijapapu', 'soijapavun', 'soijapapua', 'soijapavut'))),
K("Mitä termostabiili tarkoittaa?",
  "Lämpöä kestävä. Termostabiili DNA-polymeraasi (Taq) kestää PCR:n kuumennukset, termostabiilit entsyymit toimivat pesukoneissa.",
  "",
  2, L(N('termostabiili', 'termostabiilin', 'termostabiilia', 'termostabiilit', 'termostabiileja', 'termostabiilien', 'lämpöstabiili', 'lämpöstabiilin', 'lämpöstabiilit', 'lämmönkestävä', 'lämmönkestävän', 'lämmönkestävät', 'Taq-polymeraasi', 'Taq-polymeraasin', 'Taq-polymeraasia', 'Taq', 'Thermus aquaticus'))),
K("Mikä on viljelykasvi?",
  "Ihmisen ravinnoksi tai raaka-aineeksi kasvattama kasvi, kuten vehnä, riisi, maissi ja soija. Jalostuksen ja GM-muokkauksen kohde.",
  "",
  2, L('viljelykasvi', ['viljelykasvit', 'viljelykasveja', 'viljelykasvien', 'viljellä', 'viljellään', 'viljelty', 'viljeltyjä', 'viljely', 'viljelyn', 'viljelyä', 'viljelyssä', 'maatalous', 'maatalouden', 'maataloutta', 'maatalouteen', 'maataloudessa', 'maataloussovellus', 'maataloussovellukset', 'maataloussovelluksia'])),
K("Mikä on zymaasi?",
  "Buchnerin 1897 hiivan solunesteestä löytämä entsyymiseos, joka käytti sokeria ilman eläviä soluja. Osoitti käymisen olevan kemiaa.",
  "",
  2, L('zymaasi', ['Buchner', 'Buchnerin', 'Eduard Buchner', 'Eduard Buchnerin', 'soluton uute', 'soluttoman uutteen', 'solutonta uutetta'])),
K("Mitä eläinlääketiede on biotekniikan sovellusalana?",
  "Eläinten tautien hoito ja ehkäisy: rokotteet, diagnostiikka ja hormonit tuotantoeläimille ja lemmikeille.",
  "",
  1, L(N('eläinlääketiede', 'eläinlääketieteen', 'eläinlääketiedettä', 'eläinlääketieteessä', 'eläinlääketieteellinen', 'eläinlääketieteellisen', 'kotieläin', 'kotieläimen', 'kotieläimet', 'kotieläinten', 'kotieläimiä', 'tuotantoeläin', 'tuotantoeläimen', 'tuotantoeläimet', 'tuotantoeläinten'))),
K("Mitä metsätaloustieteet ovat biotekniikan rinnalla?",
  "Metsän kasvatuksen ja puun jalostuksen tieteet. Metsäbiotekniikka tuottaa puusta sellua, biopolttoaineita ja uusia materiaaleja.",
  "",
  1, L(N('metsätaloustiede', 'metsätaloustieteen', 'metsätaloustieteet', 'metsätaloustieteiden', 'metsätalous', 'metsätalouden', 'metsätaloutta', 'metsäbiotekniikka', 'metsäbiotekniikan', 'metsäteollisuus', 'metsäteollisuuden', 'metsäteollisuutta', 'puunjalostus', 'puunjalostuksen', 'puunjalostusta', 'puunjalostuksessa'))),
K("Mitä ympäristönsuojelu on biotekniikan sovellusalana?",
  "Saastuneen maan ja veden puhdistus mikrobeilla (bioremediaatio), jätevesien käsittely ja päästöjen vähentäminen.",
  "",
  2, L(N('ympäristönsuojelu', 'ympäristönsuojelun', 'ympäristönsuojelua', 'ympäristönsuojelussa', 'jätevesi', 'jäteveden', 'jätevettä', 'jätevedet', 'jätevesien', 'ympäristöystävällinen', 'ympäristöystävällisen', 'ympäristöystävälliset', 'ympäristöystävällisyys', 'ympäristöystävällisyyden', 'ympäristökuormitus', 'ympäristökuormituksen', 'ympäristökuormitusta'))),
K("Mitä perustutkimus on?",
  "Tutkimus, jonka tavoite on uusi tieto ilman välitöntä sovellusta. Soveltava tutkimus ja tuotekehitys rakentuvat sen päälle.",
  "",
  2, L('perustutkimus', ['soveltava tutkimus', 'soveltavan tutkimuksen', 'soveltavaa tutkimusta', 'tuotekehitys', 'tuotekehityksen', 'tuotekehitystä', 'tuotekehityksessä', 'lääkekehitys', 'lääkekehityksen', 'lääkekehitystä', 'lääkekehityksessä'])),
K("Mikä on sovellus?",
  "Tiedon tai menetelmän käyttö käytännön tarkoitukseen. Biotekniikan sovellusalueita ovat lääketiede, elintarvikkeet, teollisuus ja ympäristö.",
  "",
  1, L('sovellus', ['sovellusalue', 'sovellusalueen', 'sovellusalueet', 'sovellusalueita', 'sovellusalueilla', 'sovelluskohde', 'sovelluskohteen', 'sovelluskohteet', 'sovelluskohteita', 'soveltaa', 'sovelletaan', 'soveltaminen', 'soveltamisen', 'soveltamista', 'soveltamalla', 'sovellettu', 'käyttökohde', 'käyttökohteen', 'käyttökohteet', 'käyttökohteita', 'käyttötarkoitus', 'käyttötarkoituksen', 'käyttötarkoitukset', 'käyttötarkoituksia'])),
K("Mikä on bioala?",
  "Biotieteisiin perustuvat ammatit ja yritykset: lääke-, diagnostiikka-, elintarvike- ja teollisuusbiotekniikka. Kutsutaan myös: bioteollisuus.",
  "",
  1, L(N('bioala', 'bioalan', 'bioalaa', 'bioalalla', 'bioalaan', 'bioteollisuus', 'bioteollisuuden', 'bioteollisuutta', 'bioyritys', 'bioyrityksen', 'bioyritykset', 'bioyritysten', 'bioyrityksiä'))),
K("Mitä tietotekniikka on biotekniikan rinnalla?",
  "Tiedon käsittelyn tekniikka. Bioinformatiikka yhdistää sen biologiaan: sekvenssien, rakenteiden ja mittausdatan analyysi.",
  "",
  1, L('tietotekniikka', ['konetekniikka', 'konetekniikan', 'konetekniikkaa', 'sähköinen', 'sähköisen', 'sähköistä', 'sähköiset', 'digitaalinen', 'digitaalisen', 'digitaalista', 'digitaaliset', 'digitaalisia'])),
K("Mikä on lääke?",
  "Aine, jolla ehkäistään, lievitetään tai parannetaan sairautta. Biotekniikka tuottaa proteiinilääkkeitä, rokotteita ja antibiootteja.",
  "",
  2, L(N('lääke', 'lääkkeen', 'lääkettä', 'lääkkeessä', 'lääkkeeseen', 'lääkkeenä', 'lääkkeet', 'lääkkeiden', 'lääkkeitä', 'lääkkeissä', 'lääkkeistä', 'lääkeaine', 'lääkeaineen', 'lääkeainetta', 'lääkeaineet', 'lääkeaineiden', 'lääkeaineita', 'lääkeaineella', 'lääkemolekyyli', 'lääkemolekyylin', 'lääkemolekyylit', 'lääkemolekyylien', 'lääketeollisuus', 'lääketeollisuuden', 'lääketeollisuutta', 'lääketeollisuudesta'))),
K("Mikä on Nobel-palkinto biotekniikassa?",
  "Alan käännekohtien palkintoja: penisilliini 1945, DNA:n rakenne 1962, hybridooma 1984, PCR 1993, CRISPR 2020, AlphaFold 2024.",
  "",
  1),
K("Mitä terveysvaikutteinen elintarvike tarkoittaa?",
  "Ruoka, jolla on osoitettu terveyshyöty tavallisen ravinnon lisäksi, kuten kolesterolia alentava margariini tai probioottijugurtti.",
  "",
  1, L(N('terveysvaikutteinen', 'terveysvaikutteisen', 'terveysvaikutteista', 'terveysvaikutteiset', 'terveysvaikutteisia', 'terveysvaikutteinen elintarvike', 'terveysvaikutteiset elintarvikkeet', 'funktionaalinen elintarvike', 'funktionaalisen elintarvikkeen', 'funktionaaliset elintarvikkeet', 'probiootti', 'probiootin', 'probioottia', 'probiootit', 'probioottien', 'probiootteja'))),
K("Mikä on Fischer biokemian historiassa?",
  "Emil Fischer, joka selvitti sokerien rakenteet ja esitti 1894 entsyymin lukko ja avain -mallin. Nobel 1902.",
  "",
  1, L(N('Fischer', 'Fischerin', 'Fischeriä', 'Emil Fischer', 'Emil Fischerin', 'lukko ja avain', 'lukko ja avain -malli', 'lukko ja avain -mallin', 'lukko-avain-malli', 'lukko-avain-mallin', 'avain-lukko-malli'))),
K("Mikä on Kiilto Clean?",
  "Suomalainen pesu- ja puhdistusaineyritys, esimerkki kotimaisesta entsyymejä hyödyntävästä teollisuudesta.",
  "",
  1, L(N('Kiilto Clean', 'Kiilto Cleanin', 'Kiilto', 'Kiillon'))),
K("Mikä on Raisio?",
  "Suomalainen elintarvikeyhtiö, tunnettu kolesterolia alentavasta Benecol-margariinista, ensimmäisiä terveysvaikutteisia elintarvikkeita.",
  "",
  1, L(N('Raisio', 'Raision', 'Raisiota', 'Benecol', 'Benecolin', 'Benecolia'))),
K("Mikä on Thermo Fisher Scientific?",
  "Maailman suurimpia laboratoriolaitteiden ja reagenssien valmistajia, jolla on Suomessa tuotantoa Vantaalla.",
  "",
  1, L(N('Thermo Fisher', 'Thermo Fisherin', 'Thermo Fisher Scientific', 'ThermoFisher', 'Thermofisher'))),
K("Mikä on Radiometer?",
  "Tanskalainen diagnostiikkayritys, jonka verikaasuanalysaattoreita valmistetaan Turussa. Esimerkki kotimaisesta diagnostiikkateollisuudesta.",
  "",
  1, L(N('Radiometer', 'Radiometerin', 'verikaasuanalysaattori', 'verikaasuanalysaattorin', 'verikaasuanalysaattorit'))),
K("Mikä on Biovian?",
  "Turkulainen sopimusvalmistaja, joka tuottaa biologisia lääkkeitä ja virusvektoreita muille yrityksille.",
  "",
  1, L(N('Biovian', 'Biovianin', 'sopimusvalmistaja', 'sopimusvalmistajan', 'sopimusvalmistajat', 'sopimusvalmistus', 'sopimusvalmistuksen'))),
K("Mitä ovat lääkeyhtiöt kuten Bayer, Pfizer ja Novo Nordisk?",
  "Kansainväliset lääkeyritykset, jotka kehittävät ja valmistavat bioteknisiä lääkkeitä: rokotteita, vasta-aineita, insuliinia ja GLP-1-lääkkeitä.",
  "",
  1, L(N('Bayer', 'Bayerin', 'Pfizer', 'Pfizerin', 'Novo Nordisk', 'Novo Nordiskin', 'Roche', 'Rochen', 'Merck', 'Merckin', 'AstraZeneca', 'AstraZenecan', 'BioNTech', 'BioNTechin', 'Moderna', 'Modernan', 'Sanofi', 'Sanofin', 'Genzyme', 'Genzymen', 'Gilead', 'Gileadin', 'AbbVie', 'AbbVien', 'Janssen', 'Janssenin', 'Regeneron', 'Regeneronin', 'Eli Lilly', 'Lilly', 'Lillyn', 'GlaxoSmithKline', 'Bristol Myers Squibb', 'lääkeyhtiö', 'lääkeyhtiön', 'lääkeyhtiöt', 'lääkeyhtiöiden', 'lääkeyritys', 'lääkeyrityksen', 'lääkeyritykset', 'lääkeyritysten', 'CureVac', 'CureVacin', 'argenx', 'Ascendis'))),
]

L2 = [
K("Mikä on Acetobacter?",
  "Etikkahappobakteeri, joka hapettaa etanolin etikkahapoksi hapen läsnä ollessa. Viinietikan valmistaja.",
  "",
  2, L(N('Acetobacter', 'Acetobacterin', 'Acetobacteria', 'etikkahappobakteeri', 'etikkahappobakteerin', 'etikkahappobakteerit', 'viinietikka', 'viinietikan', 'viinietikkaa'))),
K("Mikä on aineenvaihduntareitti?",
  "Peräkkäisten entsyymireaktioiden sarja, jossa lähtöaine muuttuu tuotteeksi välituotteiden kautta. Kutsutaan myös: metaboliareitti, reaktiotie.",
  "",
  2, L('aineenvaihduntareitti', ['metaboliareitti', 'metaboliareitin', 'metaboliareittiä', 'metaboliareitit', 'metaboliareittejä', 'aineenvaihduntareittejä'])),
K("Mikä on entsyymin aktiivisuus?",
  "Entsyymin katalysoima reaktionopeus, ilmoitetaan yksikköinä: yksi yksikkö muuttaa mikromoolin substraattia minuutissa.",
  "",
  2, L('aktiivisuus', ['entsyymiaktiivisuus', 'entsyymiaktiivisuuden', 'entsyymiaktiivisuutta', 'aktiivinen', 'aktiivisen', 'aktiivista', 'aktiiviset', 'aktiivisia', 'aktiivisten', 'inaktiivinen', 'inaktiivisen', 'inaktiivista', 'inaktiiviset', 'inaktivoida', 'inaktivoidaan', 'inaktivoitu', 'inaktivoi', 'inaktivaatio', 'inaktivaation'])),
K("Mikä on ammoniumsulfaattisaostus?",
  "Proteiinien saostus lisäämällä suolaa: ammoniumsulfaatti vie proteiinien vesivaipan ja ne saostuvat pitoisuuden mukaan.",
  "",
  2, L(N('ammoniumsulfaattisaostus', 'ammoniumsulfaattisaostuksen', 'ammoniumsulfaattisaostusta', 'ammoniumsulfaatti', 'ammoniumsulfaatin', 'ammoniumsulfaattia', 'ammoniumsulfaatilla', 'suolasaostus', 'suolasaostuksen', 'suolasaostusta', 'ulossuolaus', 'ulossuolauksen'))),
K("Mikä on anti-adheesiomolekyyli?",
  "Molekyyli, joka estää bakteerin tarttumisen kudokseen, esimerkiksi karpalon proteiinit virtsatieinfektiossa.",
  "",
  1, L('anti-adheesiomolekyyli', ['adheesio', 'adheesion', 'adheesiota', 'adheesiomolekyyli', 'adheesiomolekyylin', 'adheesiomolekyylit'])),
K("Mitä antimikrobinen tarkoittaa?",
  "Mikrobeja tappava tai niiden kasvua estävä, kuten antibiootti, desinfiointiaine tai antimikrobinen peptidi.",
  "",
  2, L(N('antimikrobinen', 'antimikrobisen', 'antimikrobista', 'antimikrobiset', 'antimikrobisia', 'antimikrobiaalinen', 'antimikrobiaalisen', 'antimikrobiaalisia', 'antimikrobiaaliset', 'antimikrobinen peptidi', 'antimikrobiset peptidit', 'antimikrobisia peptidejä'))),
K("Mikä on anturi bioprosessissa?",
  "Fermentorin mittalaite: lämpötila-, pH-, happi- ja painemittarit, joiden perusteella prosessia säädetään.",
  "",
  1, L('anturi', ['sensori', 'sensorin', 'sensoria', 'sensorit', 'painemittari', 'painemittarin', 'painemittaria', 'pH-mittari', 'pH-mittarin', 'happimittari', 'happimittarin', 'happianturi', 'happianturin'])),
K("Mikä on Aspergillus?",
  "Homesuku, jonka lajeja käytetään teollisuudessa: A. niger tuottaa sitruunahappoa ja entsyymejä, A. oryzae soijakastikkeen.",
  "",
  2, L(N('Aspergillus', 'Aspergilluksen', 'Aspergillusta', 'Aspergillus niger', 'Aspergillus nigerin', 'Aspergillus oryzae', 'Aspergillus ochraceus', 'A. niger', 'A. oryzae'))),
K("Mikä on Bacillus subtilis?",
  "Maaperän gram-positiivinen bakteeri, joka erittää proteiineja ulos solusta. Teollinen entsyymien, kuten proteaasien, tuottaja.",
  "",
  2, L(N('Bacillus subtilis', 'Bacillus subtiliksen', 'Bacillus', 'Bacilluksen', 'B. subtilis', 'Bacillus licheniformis'))),
K("Mikä on Corynebacterium glutamicum?",
  "Bakteeri, jolla tuotetaan aminohappoja teollisesti: glutamaattia (umami-mauste) ja lysiiniä (rehun lisäaine) miljoonia tonneja.",
  "",
  2, L(N('Corynebacterium', 'Corynebacteriumin', 'Corynebacterium glutamicum', 'Corynebacterium glutamicumin', 'C. glutamicum', 'glutamaatti', 'glutamaatin', 'glutamaattia', 'natriumglutamaatti', 'natriumglutamaatin'))),
K("Mikä on lysiini?",
  "Välttämätön emäksinen aminohappo, jota viljassa on vähän. Rehuun lisätään bakteerilla tuotettua lysiiniä.",
  "",
  2, L('lysiini', ['metioniini', 'metioniinin', 'metioniinia', 'metioniiniä', 'treoniini', 'treoniinin', 'tryptofaani', 'tryptofaanin', 'välttämätön aminohappo', 'välttämättömän aminohapon', 'välttämättömät aminohapot', 'välttämättömiä aminohappoja'])),
K("Mikä on detergentti?",
  "Pinta-aktiivinen aine, jonka molekyylissä on hydrofobinen häntä ja hydrofiilinen pää. Liuottaa rasvat ja kalvot, hajottaa solut.",
  "",
  2, L('detergentti', ['pinta-aktiivinen aine', 'pinta-aktiivisen aineen', 'pinta-aktiiviset aineet', 'pinta-aktiivisia aineita', 'tensidi', 'tensidin', 'tensidit', 'saippua', 'saippuan', 'saippuaa', 'SDS', 'SDS:n'])),
K("Mitä solunulkoinen tarkoittaa?",
  "Solun ulkopuolella: solunulkoinen proteiini eritetään elatusliuokseen, mikä helpottaa sen puhdistusta. Kutsutaan myös: ekstrasellulaarinen.",
  "",
  2, L(N('solunulkoinen', 'solunulkoisen', 'solunulkoista', 'solunulkoiset', 'solunulkoisia', 'solunulkoisessa', 'solunulkoiseen', 'ekstrasellulaarinen', 'ekstrasellulaarisen', 'ekstrasellulaarista', 'ekstrasellulaariset', 'solunsisäinen', 'solunsisäisen', 'solunsisäistä', 'solunsisäiset', 'solunsisäisiä', 'solunsisäisessä', 'intrasellulaarinen', 'intrasellulaarisen', 'intrasellulaariset'))),
K("Mikä on elatusliuos?",
  "Nestemäinen elatusaine, jossa solut kasvavat ravistelupullossa tai fermentorissa. Kutsutaan myös: kasvatusliuos, medium.",
  "",
  2, L(N('elatusliuos', 'elatusliuoksen', 'elatusliuosta', 'elatusliuoksessa', 'kasvatusliuokseen', 'ravintoliuos', 'ravintoliuoksen', 'ravintoliuosta', 'ravintoliuokset', 'medium', 'mediumin', 'mediumia', 'elatusliuokseen'))),
K("Mikä on esikasvatus?",
  "Pieni kasvatus, jolla tuotto-organismi herätetään ja monistetaan ennen siirtoa suureen fermentoriin. Kutsutaan myös: siemenkasvatus.",
  "",
  2, L('esikasvatus', ['siemenkasvatus', 'siemenkasvatuksen', 'siemenkasvatusta', 'siirrostus', 'siirrostuksen', 'siirrostaa', 'siirroste', 'siirrosteen', 'siirrostetta', 'ymppi', 'ympin', 'ymppiä', 'ympätä', 'ympätään'])),
K("Mikä on etanoli?",
  "Kahden hiilen alkoholi C<sub>2</sub>H<sub>5</sub>OH, hiivan käymisen tuote. Juomien, polttoaineen ja desinfioinnin alkoholi.",
  "",
  3, L('etanoli', ['alkoholi', 'alkoholin', 'alkoholia', 'alkoholit', 'alkoholien', 'alkoholeja', 'etyylialkoholi', 'etyylialkoholin', 'etanolipitoisuus', 'etanolipitoisuuden', 'etanolipitoisuuksia'])),
K("Mikä on fruktoosi?",
  "Hedelmäsokeri, kuuden hiilen ketoosi. Glukoosi-isomeraasi muuttaa glukoosia fruktoosiksi makeampaa siirappia varten.",
  "",
  2, L('fruktoosi', ['hedelmäsokeri', 'hedelmäsokerin', 'hedelmäsokeria', 'glukoosi-isomeraasi', 'glukoosi-isomeraasin', 'fruktoosisiirappi', 'fruktoosisiirapin', 'fruktoosisiirappia'])),
K("Mikä on hiililähde?",
  "Elatusaineen aine, josta solu saa hiilensä ja energiansa, tavallisesti glukoosi, melassi tai tärkkelys.",
  "",
  2, L('hiililähde', ['typpilähde', 'typpilähteen', 'typpilähdettä', 'typpilähteet', 'melassi', 'melassin', 'melassia', 'hiililähteen', 'hiililähdettä'])),
K("Mikä on hivenaine?",
  "Pieninä määrinä välttämätön alkuaine, kuten rauta, sinkki, kupari tai magnesium, joita entsyymit tarvitsevat kofaktoreiksi.",
  "",
  2, L('hivenaine', ['hivenaineen', 'hivenainetta', 'hivenaineet', 'hivenaineiden', 'hivenaineita', 'kivennäisaine', 'kivennäisaineen', 'kivennäisaineet', 'kivennäisaineita'])),
K("Mikä on home?",
  "Rihmamainen sieni, kuten Aspergillus ja Penicillium. Tuottaa teollisuudelle entsyymejä, happoja ja antibiootteja.",
  "",
  2, L(N('home', 'homeen', 'hometta', 'homeessa', 'homeet', 'homeiden', 'homeita', 'homeista', 'homesieni', 'homesienen', 'homesienet', 'homesienten', 'rihmasieni', 'rihmasienen', 'rihmasienet', 'rihmasieniä', 'sieni', 'sienen', 'sientä', 'sienet', 'sienten', 'sieniä', 'sienissä', 'sienisolu', 'sienisolun', 'sienisolut', 'sienisoluissa'))),
K("Mikä on hyönteissolu?",
  "Hyönteisestä peräisin oleva solulinja, jossa proteiineja tuotetaan bakulovirusvektorilla. Laskostaa ja sokeroi lähes kuin nisäkässolu.",
  "",
  2, L('hyönteissolu', ['hyönteissolut', 'hyönteissoluja', 'hyönteissoluissa', 'hyönteissoluihin', 'bakulovirus', 'bakuloviruksen', 'bakulovirusta', 'bakulovirusvektori', 'bakulovirusvektorin', 'Sf9', 'Sf9-solu', 'Sf9-solut'])),
K("Mikä on ilmastus?",
  "Ilman tai hapen syöttö kasvatukseen kuplina, jotta aerobiset solut saavat happea. Vaahtoaminen estetään vaahdonestoaineella.",
  "",
  2, L('ilmastus', ['ilmastaa', 'ilmastetaan', 'ilmastettu', 'ilmakupla', 'ilmakuplan', 'ilmakuplat', 'ilmakuplia', 'vaahdonesto', 'vaahdoneston', 'vaahdonestoaine', 'vaahdonestoaineen', 'vaahdonestoainetta', 'vaahtoaminen', 'vaahtoamisen', 'vaahtoamista', 'vaahto', 'vaahdon'])),
K("Mitä induktio tarkoittaa proteiinituotossa?",
  "Tuottogeenin käynnistäminen halutulla hetkellä lisäämällä induktori, kuten IPTG lac-promoottorille, kun solumassa on kasvanut.",
  "",
  2, L('induktio', ['indusoida', 'indusoidaan', 'indusoitu', 'indusoituminen', 'indusoitumisen', 'indusoituu', 'induktori', 'induktorin', 'induktoria', 'induktorit', 'IPTG', 'IPTG:n', 'IPTG:tä', 'indusoituva', 'indusoituvan', 'indusoituvat'])),
K("Mikä on isäntäsolu?",
  "Solu, johon vieras geeni tuodaan ja joka tuottaa sen proteiinia: E. coli, hiiva, CHO tai hyönteissolu.",
  "",
  3, L('isäntäsolu', ['isäntä', 'isännän', 'isäntää', 'isännässä', 'isäntään', 'isännät', 'isäntien', 'tuottoisäntä', 'tuottoisännän', 'tuottoisäntää', 'tuottoisäntänä', 'tuottoisännät', 'tuottoisäntien', 'tuottoisäntiä', 'tuottoisäntinä', 'tuotto-isäntä', 'tuotto-isännän', 'tuotto-isäntään', 'tuotantoisäntä', 'tuotantoisännän', 'tuotto-organismi', 'tuotto-organismin', 'tuotto-organismia', 'tuotto-organismit', 'tuotto-organismien', 'tuotto-organismeja', 'tuottoorganismi', 'tuottokanta', 'tuottokannan', 'tuottokantaa', 'isäntäsoluun', 'isäntäsoluja'])),
K("Mikä on tuottogeeni?",
  "Vektoriin liitetty geeni, jonka proteiinia isäntäsolu valmistaa. Kutsutaan myös: kohdegeeni, tuottoproteiinin geeni.",
  "",
  2, L('tuottogeeni', ['tuottoproteiini', 'tuottoproteiinin', 'tuottoproteiinia', 'tuottoproteiinit', 'kohdegeeni', 'kohdegeenin', 'kohdegeeniä', 'kohde-DNA', 'kohde-DNA:n', 'kohde-DNA:ta'])),
K("Mikä on jäähdytys fermentorissa?",
  "Solujen aineenvaihdunta tuottaa lämpöä, joka johdetaan pois vesivaipalla tai kylmävesikierukoilla vakiolämpötilan pitämiseksi.",
  "",
  1, L('jäähdytys', ['jäähdyttää', 'jäähdytetään', 'jäähdytysvesi', 'jäähdytysveden', 'jäähdytysvettä', 'vesivaippa', 'vesivaipan', 'vesivaippaa', 'kylmävesikierukka', 'kylmävesikierukan', 'kylmävesikierukat', 'kylmävesikierukoiden', 'lämmönvaihdin', 'lämmönvaihtimen'])),
K("Mikä on kalkkisaostuma?",
  "Kovan veden kalsium- ja magnesiumsuolojen kerrostuma putkissa ja koneissa. Entsyymit ja kompleksinmuodostajat estävät sitä pesuaineissa.",
  "",
  1, L('kalkkisaostuma', ['kalkkisaostumat', 'kalkkisaostumien', 'kalkkisaostumia', 'kalkki', 'kalkin', 'kalkkia', 'kompleksinmuodostaja', 'kompleksinmuodostajan', 'kompleksinmuodostajana', 'kompleksinmuodostajat', 'kelaattori', 'kelaattorin', 'kelaattorit'])),
K("Mikä on kasvatusmalli?",
  "Tapa syöttää fermentoria: panos (kaikki alussa), syöttöpanos (ravinnetta lisätään) tai jatkuva (sisään ja ulos koko ajan).",
  "",
  2, L('kasvatusmalli', ['kasvatusmallit', 'kasvatusmalleja', 'kasvatusmallista', 'kasvatustapa', 'kasvatustavan', 'kasvatustavat', 'fermentointitapa', 'fermentointitavan', 'kasvatusolot', 'kasvatusolojen', 'kasvatusoloja', 'kasvatusolosuhteet', 'kasvatusolosuhteiden', 'kasvuolosuhteet', 'kasvuolosuhteiden', 'kasvuympäristö', 'kasvuympäristön', 'kasvuympäristöä'])),
K("Mikä on kasvunopeus?",
  "Solumäärän suhteellinen kasvu aikayksikössä. Log-vaiheessa vakio: E. coli kahdentuu 20 minuutissa, nisäkässolu vuorokaudessa.",
  "",
  2, L('kasvunopeus', ['kasvunopeuden', 'kasvunopeutta', 'generaatioaika', 'generaatioajan', 'kasvu', 'kasvun', 'kasvua', 'kasvussa', 'kasvulle', 'solumäärä', 'solumäärän', 'solumäärää', 'solumäärät', 'solumäärien', 'solutiheys', 'solutiheyden', 'solutiheyttä', 'solutiheydet', 'solumassa', 'solumassan', 'solumassaa', 'solumassat', 'solumassoja'])),
K("Mikä on kasvuvaihe?",
  "Panoskasvatuksen jakso: viive-, logaritminen, stationääri- ja kuolemisvaihe. Tuote kerätään usein stationäärivaiheessa.",
  "",
  2, L('kasvuvaihe', ['kasvuvaiheet', 'kasvuvaiheita', 'kasvuvaiheessa', 'kasvukäyrä', 'kasvukäyrän', 'kasvukäyrää', 'viivevaihe', 'viivevaiheen', 'viivevaihetta', 'kuolemisvaihe', 'kuolemisvaiheen', 'kuolemisvaihetta', 'solukuolema', 'solukuoleman', 'solukuolemaa', 'kasvatusvaihe', 'kasvatusvaiheen', 'kasvatusvaihetta', 'tuottovaihe', 'tuottovaiheen', 'tuottovaihetta', 'solukasvatusvaihe', 'solukasvatusvaiheen'])),
K("Mikä on kiintofaasi?",
  "Kiinteä kantaja, johon entsyymi, vasta-aine tai solu on sidottu, kuten kromatografiageeli, helmi tai levyn kuoppa.",
  "",
  2, L('kiintofaasi', ['kiinteä faasi', 'kiinteän faasin', 'kiinteää faasia', 'kiinteässä faasissa', 'kantaja', 'kantajan', 'kantajaa', 'kantajaan', 'kantajat', 'kantajamateriaali', 'kantajamateriaalin', 'kantajamateriaalia', 'kantajamateriaaliin', 'solid phase', 'solid-phase'])),
K("Mikä on kopioluku?",
  "Kuinka monta kopiota plasmidista tai geenistä solussa on. Korkea kopioluku lisää tuottoa mutta kuormittaa solua.",
  "",
  2, L('kopioluku', ['kopiolukua', 'kopioluvun', 'plasmidin kopioluku', 'plasmidin kopioluvun'])),
K("Mitä kudosläpäisevyys tarkoittaa lääkkeestä?",
  "Lääkemolekyylin kyky kulkeutua verestä kudokseen. Suuret vasta-aineet läpäisevät kudoksia huonosti, pienmolekyylit hyvin.",
  "",
  1, L('kudosläpäisevyys', ['läpäisevyys', 'läpäisevyyden', 'läpäisevyyttä', 'kudokseen pääsy', 'kudokseen pääsyn'])),
K("Mikä on käymistuote?",
  "Mikrobin käymisessä erittämä aine: etanoli, maitohappo, etikkahappo, hiilidioksidi tai sitruunahappo.",
  "",
  2, L('käymistuote', ['käymistuotteet', 'käymistuotteiden', 'käymistuotteita', 'käydä', 'käy', 'käyvät', 'käyttää sokeria', 'käyttämällä'])),
K("Mitä laadunvarmistus on?",
  "Menettelyt, joilla tuotteen tasalaatuisuus, puhtaus ja turvallisuus todennetaan jokaisesta erästä. Lääkkeissä viranomaisen valvomaa.",
  "",
  2, L('laadunvarmistus', ['laadunvalvonta', 'laadunvalvonnan', 'laadunvalvontaa', 'laatu', 'laadun', 'laatua', 'laadukas', 'laadukkaan', 'laadukkaita', 'tasalaatuinen', 'tasalaatuisen', 'tasalaatuista', 'tasalaatuiset', 'tasalaatuistaminen', 'tasalaatuistamisen', 'puhtausaste', 'puhtausasteen', 'puhtausastetta', 'puhtaustaso', 'puhtaustason', 'puhtaus', 'puhtauden', 'puhtautta', 'puhdistusaste', 'puhdistusasteen'])),
K("Mitä laajakirjoisuus tarkoittaa?",
  "Vaikutus moneen kohteeseen: laajakirjoinen antibiootti tappaa monenlaisia bakteereja, kapeakirjoinen vain tiettyjä.",
  "",
  1, L('laajakirjoisuus', ['laajakirjoinen', 'laajakirjoisen', 'laajakirjoista', 'laajakirjoiset', 'laajakirjoisia', 'kapeakirjoinen', 'kapeakirjoisen', 'kapeakirjoiset'])),
K("Mikä on lisäaine?",
  "Elintarvikkeeseen tai rehuun lisätty aine, joka parantaa säilyvyyttä, rakennetta tai ravintoarvoa, kuten entsyymi, vitamiini tai aminohappo.",
  "",
  2, L('lisäaine', ['lisäaineen', 'lisäainetta', 'lisäaineet', 'lisäaineiden', 'lisäaineita', 'lisäaineina', 'rehu', 'rehun', 'rehua', 'rehut', 'rehujen', 'rehuja', 'rehuun', 'ruokinta', 'ruokinnan', 'ruokintaa', 'ruokinnassa'])),
K("Mikä on meijerituote?",
  "Maidosta valmistettu elintarvike: juusto, jugurtti, voi ja vähälaktoosinen maito, jonka laktoosi on pilkottu laktaasilla.",
  "",
  1, L('meijerituote', ['meijerituotteet', 'meijerituotteiden', 'meijerituotteita', 'maitotuote', 'maitotuotteen', 'maitotuotteet', 'maitotuotteiden', 'maitotuotteita', 'vähälaktoosinen', 'vähälaktoosisen', 'vähälaktoosiset', 'vähälaktoosisia', 'vähälaktoosisissa', 'laktoositon', 'laktoosittoman', 'laktoosittomat', 'maito', 'maidon', 'maitoa', 'maidossa', 'maitoon'])),
K("Mikä on nettovaraus?",
  "Proteiinin positiivisten ja negatiivisten varausten summa tietyssä pH:ssa. Isoelektrisessä pisteessä nolla, ioninvaihdon peruste.",
  "",
  2, L('nettovaraus', ['nettovarausta', 'nettovarauksen', 'kokonaisvaraus', 'kokonaisvarauksen', 'kokonaisvarausta'])),
K("Mikä on pesuaine?",
  "Puhdistusaine, jossa detergenttien lisäksi on entsyymejä: proteaasi valkuaistahroihin, lipaasi rasvaan, amylaasi tärkkelykseen, sellulaasi nukkaan.",
  "",
  2, L('pesuaine', ['pesuaineen', 'pesuainetta', 'pesuaineet', 'pesuaineiden', 'pesuaineita', 'pesuaineissa', 'pesuainekäyttö', 'pyykinpesu', 'pyykinpesun', 'pesukone', 'pesukoneen', 'pesukoneet', 'pesukoneista', 'pesulämpötila', 'pesulämpötilan', 'pesulämpötilat', 'tahra', 'tahran', 'tahrat', 'tahrojen', 'tahroja'])),
K("Mitä pH-kontrolli tarkoittaa fermentoinnissa?",
  "Kasvatuksen pH:n mittaus ja säätö lisäämällä happoa tai emästä automaattisesti, koska aineenvaihdunta muuttaa pH:ta.",
  "",
  1, L(N('pH-kontrolli', 'pH-kontrollin', 'pH-kontrollia', 'pH-säätö', 'pH-säädön', 'pH-säätöä', 'pH:n säätö', 'pH:n säädön'))),
K("Mikä on pakastus proteiinin säilytyksessä?",
  "Proteiinin säilöminen −20 tai −80 asteessa, jotta proteaasit ja denaturaatio pysähtyvät. Toistuvat sulatus-pakastus-syklit vaurioittavat.",
  "",
  1, L('pakastus', ['pakastaa', 'pakastetaan', 'pakastettu', 'pakastuksen', 'jäädytys', 'jäädytyksen', 'jäädyttää', 'jäädytetään', 'jäädytetty', 'sulatus', 'sulatuksen', 'sulatus-pakastus', 'sulatus-sykli', 'säilytys', 'säilytyksen', 'säilytystä', 'säilyttäminen', 'säilyttämisen', 'säilöminen', 'säilömisen', 'säilömiseen', 'säilyvyys', 'säilyvyyden', 'säilyvyyttä', 'säilyvyyteen'])),
K("Mikä on esiaste?",
  "Molekyyli, josta lopullinen tuote tehdään yhdellä tai muutamalla reaktiolla, kuten proinsuliini. Kutsutaan myös: prekursori.",
  "",
  2, L('esiaste', ['esiasteen', 'esiastetta', 'esiasteet', 'esiasteiden', 'esiasteita', 'prekursori', 'prekursorin', 'prekursoria', 'prekursorit', 'prekursorien', 'prekursoreita', 'prekursoriantibiootti', 'prekursoriantibiootin', 'prekursoriantibiootit', 'prekursoriantibioottien'])),
K("Mikä on ravinne?",
  "Aine, jota eliö tarvitsee kasvuunsa: hiililähde, typpilähde, fosfaatti, rikki, hivenaineet ja vitamiinit.",
  "",
  2, L(N('ravinne', 'ravinteen', 'ravinnetta', 'ravinteessa', 'ravinteet', 'ravinteiden', 'ravinteita', 'ravinteista', 'ravinteisiin', 'ravitsemusvaatimus', 'ravitsemusvaatimuksen', 'ravitsemusvaatimukset', 'ravitsemusvaatimuksia'))),
K("Mikä on sellu?",
  "Puusta kemiallisesti erotettu selluloosakuitu, paperin raaka-aine. Entsyymit (ksylanaasi) vähentävät valkaisun klooria.",
  "",
  2, L(N('sellu', 'sellun', 'sellua', 'sellusta', 'selluun', 'paperimassa', 'paperimassan', 'paperimassaa', 'paperimassassa', 'paperi', 'paperin', 'paperia', 'paperiteollisuus', 'paperiteollisuuden', 'valkaisu', 'valkaisun', 'valkaisua', 'valkaista', 'valkaistaan', 'jätepaperi', 'jätepaperin', 'jätepaperista'))),
K("Mikä on sitruunahappo?",
  "Kolmiarvoinen hydroksihappo, sitruunahappokierron ensimmäinen välituote. Tuotetaan Aspergillus nigerillä miljoonia tonneja happamuudensäätöaineeksi.",
  "",
  2, L('sitruunahappo', ['sitraatti', 'sitraatin', 'sitraattia', 'sitraatti-ioni', 'happamuudensäätöaine', 'happamuudensäätöaineen', 'happamuudensäätöaineet'])),
K("Mikä on sivuryhmä sokeroinnissa?",
  "Proteiiniin liitetty sokeriketju tai muu ryhmä. Isäntäsolu määrää, millaiset sokeriryhmät tuottoproteiiniin tulevat.",
  "",
  1, L('sivuryhmä', ['sokeriryhmä', 'sokeriryhmän', 'sokeriryhmää', 'sokeriryhmät', 'sokeriryhmien', 'sokeriryhmiä', 'sokeriketju', 'sokeriketjun', 'sokeriketjua', 'sokeriketjut', 'sokeriketjujen', 'sokeriketjuja'])),
K("Mikä on steroidi?",
  "Neljän hiilirenkaan lipidi: kolesteroli, sukupuoli- ja stressihormonit, kortisoni. Mikrobit muokkaavat steroidilääkkeitä biokonversiolla.",
  "",
  2, L('steroidi', ['kortisoni', 'kortisonin', 'kortisonia', 'kortisoli', 'kortisolin', 'kortisolia', 'steroidilääke', 'steroidilääkkeen', 'steroidilääkkeet', 'steroidilääkkeitä', 'kolesteroli', 'kolesterolin', 'kolesterolia', 'kolesteroliin'])),
K("Mikä on Streptomyces?",
  "Maaperän rihmamainen bakteerisuku, joka tuottaa useimmat antibiootit: streptomysiinin, tetrasykliinit ja erytromysiinin.",
  "",
  2, L(N('Streptomyces', 'Streptomyceksen', 'Streptomycestä', 'Streptomyces-bakteeri', 'Streptomyces-bakteerin', 'Streptomyces-bakteerit', 'streptomysiini', 'streptomysiinin', 'streptomysiiniä', 'aktinomykeetti', 'aktinomykeetin', 'aktinomykeetit', 'aktinomykeettejä'))),
K("Mitä sublimointi on kylmäkuivauksessa?",
  "Jään haihtuminen suoraan höyryksi tyhjiössä. Kylmäkuivaus säilöö proteiinit ja rokotteet jauheeksi ilman lämpövauriota.",
  "",
  1, L('sublimointi', ['sublimoida', 'sublimoituu', 'sublimoimalla', 'sublimaatio', 'sublimaation'])),
K("Mikä on suodatus?",
  "Kiinteän aineen erotus nesteestä huokoisen materiaalin läpi: solut pois liuoksesta, mikrobit pois steriloitavasta liuoksesta.",
  "",
  2, L('suodatus', ['suodattaa', 'suodatetaan', 'suodatettu', 'suodattamalla', 'suodatin', 'suodattimen', 'suodatinta', 'suodattimet', 'suodattimilla', 'suodatukset', 'ultrasuodatus', 'ultrasuodatuksen', 'kalvosuodatus', 'kalvosuodatuksen', 'steriilisuodatus', 'steriilisuodatuksen'])),
K("Mikä on teurasjäte?",
  "Teurastuksen sivuvirta, kuten veri, luut ja sisäelimet, josta ennen eristettiin entsyymejä, nykyään biokaasua ja rehua.",
  "",
  1, L('teurasjäte', ['teurasjätteen', 'teurasjätettä', 'sivuvirta', 'sivuvirran', 'sivuvirtaa', 'sivuvirrat', 'sivuvirtoja', 'raaka-aine', 'raaka-aineen', 'raaka-ainetta', 'raaka-aineet', 'raaka-aineiden', 'raaka-aineita', 'raaka-aineena', 'raakaaine', 'raakaaineet'])),
K("Mikä on tislaus?",
  "Nesteiden erotus kiehumispisteen perusteella: seos kuumennetaan ja höyry lauhdutetaan. Etanoli väkevöidään tislaamalla.",
  "",
  2, L('tislaus', ['tislata', 'tislataan', 'tislattu', 'tislaamalla', 'tislaus', 'alkoholitislaus', 'alkoholitislauksen', 'tisle', 'tisleen', 'tislettä'])),
K("Mitä toksisuus tarkoittaa?",
  "Aineen myrkyllisyys soluille tai eliölle. Tuotteet testataan toksisuuden varalta, ja tuottoproteiini voi olla isännälle toksinen.",
  "",
  2, L('toksisuus', ['toksinen', 'toksisen', 'toksista', 'toksiset', 'toksisia', 'myrkyllinen', 'myrkyllisen', 'myrkyllistä', 'myrkylliset', 'myrkyllisiä', 'myrkyllisille', 'myrkky', 'myrkyn', 'myrkkyä', 'myrkyt', 'myrkkyjen', 'myrkkyjä', 'myrkyllisyys', 'myrkyllisyyden'])),
K("Mikä on transformaatio geenitekniikassa?",
  "Vieraan DNA:n vieminen bakteeriin tai hiivaan, esimerkiksi lämpöshokilla tai sähköpulssilla. Eläinsoluihin vienti on transfektio.",
  "",
  3, L('transformaatio', ['transformoida', 'transformoidaan', 'transformoitu', 'transformoitua', 'transformaatioprosessi', 'transformaatioprosessin', 'transfektio', 'transfektion', 'transfektiota', 'transfektoida', 'transfektoidaan', 'transfektoitu', 'lämpöshokki', 'lämpöshokin', 'lämpöshokkia', 'heat shock', 'elektroporaatio', 'elektroporaation', 'elektroporaatiota', 'kompetentti solu', 'kompetentin solun', 'kompetentit solut'])),
K("Mikä on yksisoluproteiini?",
  "Mikrobimassa ihmisten tai eläinten ravinnoksi, kuten Pekilo-home sellutehtaan jätteestä tai Quorn-sienimassa. Kutsutaan myös: SCP.",
  "",
  2, L('yksisoluproteiini', ['SCP', 'SCP:n', 'single cell protein', 'Pekilo', 'Pekilon', 'Pekilo-proteiini', 'Quorn', 'Quornin', 'mykoproteiini', 'mykoproteiinin', 'mykoproteiinia'])),
K("Mikä on Zymomonas mobilis?",
  "Bakteeri, joka käyttää sokerin etanoliksi hiivaa nopeammin ja suuremmalla saannolla. Bioetanolin tuottokandidaatti.",
  "",
  1, L(N('Zymomonas', 'Zymomonaksen', 'Zymomonas mobilis', 'Zymomonas mobiliksen', 'Z. mobilis'))),
K("Mikä on sonikointi?",
  "Solujen rikkominen ultraäänellä: ääniaallot muodostavat kuplia, joiden romahdus repii solukalvot. Kutsutaan myös: ultraäänihajotus.",
  "",
  1, L('sonikointi', ['sonikoida', 'sonikoidaan', 'sonikoitu', 'ultraäänihajotus', 'ultraäänihajotuksen', 'ääniaalto', 'ääniaallon', 'ääniaallot', 'ääniaaltojen', 'ääniaalloilla', 'ultraääni', 'ultraäänen', 'ultraääntä', 'ultraäänellä'])),
K("Mikä on solujen rikkominen?",
  "Solunsisäisen tuotteen vapautus: mekaanisesti (painehomogenisaattori, helmimylly, sonikointi), entsyymillä (lysotsyymi) tai detergentillä. Kutsutaan myös: lyysaus.",
  "",
  2, L(N('solujen rikkominen', 'solujen rikkomisen', 'solujen rikkomista', 'solujen hajotus', 'solujen hajotuksen', 'solujen hajottaminen', 'lyysaus', 'lyysauksen', 'lyysata', 'lyysataan', 'lyysattu', 'lysaatti', 'lysaatin', 'lysaattia', 'solulysaatti', 'solulysaatin', 'homogenisointi', 'homogenisoinnin', 'homogenisaattori', 'homogenisaattorin', 'painehomogenisaattori', 'painehomogenisaattorin', 'helmimylly', 'helmimyllyn', 'mekaaninen hajotus', 'mekaanisen hajotuksen', 'jauhaa', 'jauhamalla', 'jauhettu', 'jauhetusta'))),
K("Mikä on aducanumabin kaltainen tapaus lääkekehityksessä?",
  "Alzheimer-vasta-aine hyväksyttiin 2021 kiistanalaisesti, koska se poisti amyloidia mutta ei selvästi hidastanut tautia. Vedettiin markkinoilta 2024.",
  "",
  1),
K("Mikä on allergeeni?",
  "Antigeeni, joka laukaisee allergisen reaktion, kuten siitepölyn tai pähkinän proteiini. Muokatut elintarvikkeet testataan allergeenisyyden varalta.",
  "",
  2, L('allergeeni', ['allergia', 'allergian', 'allergiaa', 'allergiat', 'allerginen', 'allergisen', 'allergista', 'allergiset', 'allergeenisyys', 'allergeenisyyden', 'allergeenisyyttä', 'atooppinen', 'atooppisen', 'atooppinen ekseema', 'atooppisen ekseeman', 'ekseema', 'ekseeman', 'ekseemaa', 'astma', 'astman', 'astmaa'])),
K("Mikä on apuaine?",
  "Lääkevalmisteen aine, joka ei ole vaikuttava aine: täyteaine, säilöntäaine, liuotin tai stabiloija. Proteiinilääkkeissä sokerit ja puskurit.",
  "",
  2, L('apuaine', ['apuaineen', 'apuainetta', 'apuaineet', 'apuaineiden', 'apuaineita', 'vaikuttava aine', 'vaikuttavan aineen', 'vaikuttavaa ainetta', 'täyteaine', 'täyteaineen', 'täyteaineet', 'stabiloija', 'stabiloijan', 'stabiloijat', 'stabilointi', 'stabiloinnin'])),
K("Mikä on bromelaiini?",
  "Ananaksen proteaasi, jota käytetään lihan mureuttamiseen. Vastaavia kasviproteaaseja ovat papaijan papaiini ja viikunan fisiini.",
  "",
  1, L('bromelaiini', ['bromelaani', 'bromelaanin', 'bromelaanilla', 'papaiini', 'papaiinin', 'papaiinia', 'papaiinilla', 'fisiini', 'fisiinin', 'fisiinillä', 'mureutus', 'mureutuksen', 'mureuttaa', 'mureuttaminen', 'mureuttamisen', 'kasviproteaasi', 'kasviproteaasin', 'kasviproteaasit'])),
K("Kuka oli Paul Ehrlich?",
  "Immunologian uranuurtaja, joka esitti taikaluodin ajatuksen: lääke, joka hakeutuu vain taudinaiheuttajaan. Vasta-ainelääkkeet toteuttavat sen.",
  "",
  1, L(N('Ehrlich', 'Ehrlichin', 'Paul Ehrlich', 'Paul Ehrlichin', 'taikaluoti', 'taikaluodin', 'taikaluotia', 'magic bullet'))),
K("Mitä esihajottaminen tarkoittaa?",
  "Raaka-aineen osittainen pilkkominen entsyymeillä ennen jatkokäsittelyä, kuten tärkkelyksen nesteytys amylaasilla tai kuitujen pehmennys.",
  "",
  1, L(N('esihajottaminen', 'esihajottamisen', 'esihajottaa', 'esihajotus', 'esihajotuksen', 'esikäsittely', 'esikäsittelyn', 'esikäsittelyä', 'esikäsitellä', 'esikäsitelty', 'nesteytys', 'nesteytyksen', 'nesteyttää', 'nesteytetään', 'pehmennys', 'pehmennyksen', 'pehmennyksessä', 'pehmentää', 'pehmittää', 'pehmittäminen', 'pehmentäjä', 'pehmentäjänä'))),
K("Mikä on geeli?",
  "Hyytelömäinen verkko, joka pidättää nestettä. Kromatografian täyteaine, elektroforeesin alusta ja entsyymien immobilisointimateriaali.",
  "",
  2, L('geeli', ['agaroosigeeli', 'agaroosigeelin', 'agaroosigeeliä', 'polyakryyliamidigeeli', 'polyakryyliamidigeelin', 'geeliin', 'geelissä'])),
K("Mikä on HAART?",
  "HIV:n yhdistelmähoito useilla viruslääkkeillä, joka painaa viruksen pitoisuuden mittaamattomiin. Kutsutaan myös: antiretroviraalinen hoito.",
  "",
  1, L(N('HAART', 'HAART:n', 'HAART-hoito', 'HAART-hoidon', 'HAART-coktail', 'yhdistelmähoito', 'yhdistelmähoidon', 'yhdistelmähoitoa', 'antiretroviraalinen', 'antiretroviraalisen', 'antiretroviraaliset', 'viruslääke', 'viruslääkkeen', 'viruslääkkeet', 'viruslääkkeitä', 'HIV', 'HIV:n', 'HIV:tä', 'HI-virus', 'HI-viruksen', 'Biktarvy', 'Biktarvyn'))),
K("Mikä on hybridientsyymi?",
  "Kahden entsyymin osista koottu uusi entsyymi, jolla on molempien ominaisuuksia. Proteiinimuokkauksen työkalu. Kutsutaan myös: kimeerinen entsyymi.",
  "",
  1, L('hybridientsyymi', ['kimeerinen entsyymi', 'kimeerisen entsyymin', 'kimeeriset entsyymit', 'kimeerinen', 'kimeerisen', 'kimeeristä', 'kimeeriset', 'kimeera', 'kimeeran', 'kimeeraa'])),
K("Mikä on imusolu?",
  "Valkosolu, joka tunnistaa antigeenin: B-solu tuottaa vasta-aineita, T-solu tappaa tai ohjaa. Kutsutaan myös: lymfosyytti.",
  "",
  3, L('imusolu', ['lymfosyytti', 'lymfosyytin', 'lymfosyyttiä', 'lymfosyytit', 'lymfosyyttien', 'lymfosyyttejä', 'B-solu', 'B-solun', 'B-solua', 'B-solut', 'B-solujen', 'B-soluja', 'B-lymfosyytti', 'B-lymfosyytin', 'B-lymfosyytit', 'T-solu', 'T-solun', 'T-solua', 'T-solut', 'T-solujen', 'T-soluja', 'T-lymfosyytti', 'T-lymfosyytin', 'T-lymfosyytit', 'plasmasolu', 'plasmasolun', 'plasmasolut'])),
K("Mikä on influenssavirus?",
  "Nopeasti muuntuva RNA-virus, jonka vuoksi rokote uusitaan vuosittain. Rokote tuotetaan kananmunissa tai soluviljelmissä.",
  "",
  2, L('influenssavirus', ['influenssa', 'influenssan', 'influenssaa', 'influenssarokote', 'influenssarokotteen', 'influenssarokotetta', 'flunssa', 'flunssan'])),
K("Mikä on injektio?",
  "Lääkkeen antaminen ruiskulla ihon alle, lihakseen tai suoneen. Proteiinilääkkeet on injisoitava, koska suolisto hajottaisi ne.",
  "",
  2, L('injektio', ['injisoida', 'injisoidaan', 'injektoida', 'injektoimalla', 'pistos', 'pistoksen', 'pistosta', 'pistokset', 'pistoksena', 'ruiske', 'ruiskeen', 'ruiskeena', 'annostelu', 'annostelun', 'annostelua', 'annostella'])),
K("Mikä on vasta-aineen isotyyppi?",
  "Vasta-aineluokka raskaan ketjun mukaan: IgG, IgM, IgA, IgE ja IgD. Terapeuttiset vasta-aineet ovat yleensä IgG:tä.",
  "",
  2, L('isotyyppi', ['isotyyppiä', 'isotyypin', 'isotyypit', 'vasta-aineluokka', 'vasta-aineluokan', 'vasta-aineluokat', 'IgM', 'IgM:n', 'IgA', 'IgA:n', 'IgE', 'IgE:n', 'IgD', 'immunoglobuliini G', 'immunoglobuliini M'])),
K("Mitä eläimiä polyklonaalisten vasta-aineiden tuottoon käytetään?",
  "Immunisoidaan kani, vuohi, lammas tai hevonen ja kerätään seerumi. Suuret eläimet antavat litroja antiseerumia.",
  "",
  1, L(N('kani', 'kanin', 'kania', 'kanit', 'kaneja', 'vuohi', 'vuohen', 'vuohta', 'vuohet', 'hevonen', 'hevosen', 'hevosta', 'hevoset', 'lammas', 'lampaan', 'lammasta', 'lampaat', 'koe-eläin', 'koe-eläimen', 'koe-eläintä', 'koe-eläimet', 'koe-eläinten', 'koe-eläimiä'))),
K("Mikä on kasvain?",
  "Hallitsemattomasti jakautuvien solujen muodostama solukko. Pahanlaatuinen kasvain eli syöpä leviää etäpesäkkeinä.",
  "",
  2, L(N('kasvain', 'kasvaimen', 'kasvainta', 'kasvaimessa', 'kasvaimeen', 'kasvaimet', 'kasvainten', 'kasvaimia', 'kasvaimissa', 'tuumori', 'tuumorin', 'tuumoria', 'tuumorit', 'syöpä', 'syövän', 'syöpää', 'syövässä', 'syöpään', 'syövät', 'syöpien', 'syöpiä', 'syöpäsolu', 'syöpäsolun', 'syöpäsolua', 'syöpäsolut', 'syöpäsolujen', 'syöpäsoluja', 'syöpäsoluihin', 'kasvainsolu', 'kasvainsolun', 'kasvainsolut', 'etäpesäke', 'etäpesäkkeen', 'etäpesäkkeet', 'etäpesäkkeitä', 'rintasyöpä', 'rintasyövän', 'rintasyöpää', 'eturauhassyöpä', 'eturauhassyövän'))),
K("Mikä on kauppanimi?",
  "Lääkkeen tuotemerkki, kuten Keytruda tai Ozempic, erotuksena vaikuttavan aineen yleisnimestä (pembrolitsumabi, semaglutidi).",
  "",
  1, L('kauppanimi', ['kauppanimen', 'kauppanimeä', 'kauppanimet', 'kauppanimien', 'tuotemerkki', 'tuotemerkin', 'tuotemerkit', 'yleisnimi', 'yleisnimen', 'yleisnimeä', 'geneerinen nimi', 'geneerisen nimen'])),
K("Mitä kirkastus tarkoittaa mehun ja viinin valmistuksessa?",
  "Sameuden poisto pilkkomalla pektiini ja proteiinit entsyymeillä, jolloin hiukkaset laskeutuvat ja neste selkiytyy.",
  "",
  1, L('kirkastus', ['kirkastaa', 'kirkastetaan', 'kirkastettu', 'kirkastaja', 'kirkastajan', 'kirkastajana', 'kirkastuminen', 'sameus', 'sameuden', 'sameutta', 'mehu', 'mehun', 'mehua', 'mehut', 'mehujen', 'hedelmämehu', 'hedelmämehun', 'hedelmämehut', 'hedelmä', 'hedelmän', 'hedelmät', 'hedelmien', 'hedelmiä', 'vihannes', 'vihanneksen', 'vihannekset', 'vihannesten', 'vihanneksia'])),
K("Mitä kliininen tarkoittaa?",
  "Potilaisiin liittyvä: kliininen tutkimus testaa lääkettä ihmisillä vaiheissa I–III, kliininen laboratorio tutkii potilasnäytteitä.",
  "",
  2, L(N('kliininen', 'kliinisen', 'kliinistä', 'kliiniset', 'kliinisiä', 'kliinisessä', 'kliinisesti', 'kliininen tutkimus', 'kliinisen tutkimuksen', 'kliiniset tutkimukset', 'kliinisiä tutkimuksia', 'kliininen koe', 'kliinisen kokeen', 'kliiniset kokeet', 'lääketutkimus', 'lääketutkimuksen', 'lääketutkimukset', 'faasi I', 'faasi II', 'faasi III', 'vaihe I', 'vaihe II', 'vaihe III'))),
K("Mikä on kudosnäyte?",
  "Elävästä kudoksesta otettu pala, kuten syöpäepäilyn koepala, joka värjätään ja tutkitaan mikroskoopilla. Kutsutaan myös: biopsia.",
  "",
  2, L('kudosnäyte', ['kudosnäytteen', 'kudosnäytettä', 'kudosnäytteet', 'kudosnäytteitä', 'biopsia', 'biopsian', 'biopsiaa', 'biopsiat', 'koepala', 'koepalan', 'koepalaa', 'koepalat', 'kudos', 'kudoksen', 'kudosta', 'kudoksessa', 'kudokseen', 'kudokset', 'kudosten', 'kudoksia', 'kudoksissa', 'kudosneste', 'kudosnesteen', 'kudosnestettä', 'kudosnesteissä'])),
K("Mikä on lääkevirasto?",
  "Viranomainen, joka arvioi lääkkeen tehon ja turvallisuuden ja myöntää myyntiluvan: Euroopassa EMA, Yhdysvalloissa FDA, Suomessa Fimea.",
  "",
  2, L('lääkevirasto', ['EMA', 'EMA:n', 'Euroopan lääkevirasto', 'Euroopan lääkeviraston', 'FDA', 'FDA:n', 'Fimea', 'Fimean', 'myyntilupa', 'myyntiluvan', 'myyntilupaa', 'myyntiluvat', 'hyväksyntä', 'hyväksynnän', 'hyväksyntää', 'hyväksyä', 'hyväksyi', 'hyväksytty', 'hyväksyttyyn', 'viranomainen', 'viranomaisen', 'viranomaiset', 'viranomaisten', 'valvonta', 'valvonnan', 'valvontaa'])),
K("Mikä on lääke-enantiomeeri?",
  "Kiraalisen lääkkeen peilikuvamuoto. Usein vain toinen tehoaa ja toinen voi olla haitallinen, kuten talidomidilla.",
  "",
  2, L(N('lääke-enantiomeeri', 'lääke-enantiomeerin', 'lääke-enantiomeerit', 'lääke-enantiomeereistä', 'enantiopuhdas', 'enantiopuhtaan', 'enantiopuhtaat', 'talidomidi', 'talidomidin', 'talidomidia', 'D-peilikuvaisomeeri', 'D-peilikuvaisomeerin', 'D-peilikuvaisomeereistä'))),
K("Mikä on migreeni?",
  "Kohtauksittainen päänsärkysairaus. CGRP-vasta-aineet ovat ensimmäiset migreenin estoon kehitetyt biologiset lääkkeet.",
  "",
  1, L('migreeni', ['CGRP', 'CGRP:n', 'CGRP-vasta-aine', 'CGRP-vasta-aineen', 'CGRP-vasta-aineet'])),
K("Mitä mutatointi tarkoittaa proteiinimuokkauksessa?",
  "Mutaatioiden tekeminen geeniin tarkoituksella, joko satunnaisesti (ohjattu evoluutio) tai kohdennetusti (paikkaspesifinen mutageneesi).",
  "",
  2, L(N('mutatointi', 'mutatoinnin', 'mutatointia', 'mutatoida', 'mutatoidaan', 'mutatoitu', 'mutageneesi', 'mutageneesin', 'mutageneesiä', 'paikkaspesifinen mutageneesi', 'paikkaspesifisen mutageneesin', 'paikkaspesifistä mutageneesiä', 'paikkaspesifinen', 'paikkaspesifisen', 'paikkaspesifistä', 'kohdennettu mutageneesi', 'kohdennetun mutageneesin', 'satunnaismutageneesi', 'satunnaismutageneesin', 'satunnainen mutageneesi', 'satunnaisen mutageneesin'))),
K("Mikä on nahkateollisuus entsyymien käyttäjänä?",
  "Nahan valmistuksessa proteaasit poistavat karvat ja pehmentävät nahan, lipaasit rasvan. Korvaa rikkiyhdisteitä ja kalkkia.",
  "",
  1, L('nahkateollisuus', ['nahka', 'nahan', 'nahkaa', 'nahat', 'nahkojen', 'nahkoja', 'karvanpoisto', 'karvanpoiston', 'karvapeite', 'karvapeitteen', 'karvapeitettä', 'tekstiiliteollisuus', 'tekstiiliteollisuuden', 'tekstiiliteollisuutta', 'tekstiili', 'tekstiilin', 'tekstiilit', 'tekstiilien', 'tekstiilejä', 'kangas', 'kankaan', 'kangasta', 'kankaat', 'kankaiden', 'villa', 'villan', 'villaa', 'farkku', 'farkun', 'farkut', 'farkkujen'])),
K("Mikä on osteoporoosi?",
  "Luukato: luun tiheys pienenee ja murtumariski kasvaa. Hoidetaan muun muassa denosumabi-vasta-aineella ja lisäkilpirauhashormonilla.",
  "",
  1, L('osteoporoosi', ['luukato', 'luukadon', 'luukatoa', 'denosumabi', 'denosumabin'])),
K("Mikä on pembrolitsumabi?",
  "PD-1-vasta-aine (Keytruda), joka vapauttaa T-solut tappamaan syöpäsoluja. Maailman myydyin lääke, immuunihoidon esimerkki.",
  "",
  2, L(N('pembrolitsumabi', 'pembrolitsumabin', 'pembrolitsumabia', 'pembrolizumab', 'pembrolizumabin', 'Keytruda', 'Keytrudan', 'Keytrudaa', 'PD-1', 'PD-1:n', 'PD-1-vasta-aine', 'PD-1-vasta-aineen', 'PD-L1', 'PD-L1:n', 'immuunihoito', 'immuunihoidon', 'immuunihoitoa', 'immuunivasteen vapauttaja', 'tarkistuspiste', 'tarkistuspisteen', 'tarkistuspisteet', 'checkpoint', 'checkpoint-estäjä', 'checkpoint-estäjän', 'checkpoint-estäjät'))),
K("Mikä on penisilliiniasylaasi?",
  "Entsyymi, joka katkaisee penisilliinin sivuketjun ja tuottaa 6-APA:n, puolisynteettisten penisilliinien lähtöaineen.",
  "",
  2, L('penisilliiniasylaasi', ['penisilliiniamidaasi', 'penisilliiniamidaasin', '6-APA', '6-APA:n', '6-aminopenisillaanihappo', '6-aminopenisillaanihapon', 'puolisynteettinen', 'puolisynteettisen', 'puolisynteettiset', 'puolisynteettisiä', 'puolisynteettinen penisilliini', 'puolisynteettiset penisilliinit', 'amoksisilliini', 'amoksisilliinin', 'ampisilliini', 'ampisilliinin'])),
K("Mikä on piikkiantigeeni?",
  "SARS-CoV-2:n piikkiproteiini, jota vastaan koronarokotteet on suunnattu: mRNA-rokote saa solut tuottamaan sitä.",
  "",
  2, L('piikkiantigeeni', ['piikkiproteiini', 'piikkiproteiinin', 'piikkiproteiinia', 'piikkiproteiiniin', 'spike', 'spike-proteiini', 'spike-proteiinin', 'SARS-CoV-2', 'SARS-CoV-2:n', 'SARS-CoV-2:ta', 'koronavirus', 'koronaviruksen', 'koronavirusta', 'korona', 'koronan', 'COVID-19', 'COVID-19:n', 'covid', 'koronarokote', 'koronarokotteen', 'koronarokotetta', 'koronarokotteet', 'Comirnaty', 'Spikevax', 'Sputnik V', 'Sputnik-V'])),
K("Mikä on psoriaasi?",
  "Autoimmuuni-ihosairaus, jossa ihosolut jakautuvat liian nopeasti hilseileviksi läiskiksi. Hoidetaan sytokiineja estävillä vasta-aineilla.",
  "",
  1, L('psoriaasi', ['psoriasis', 'psoriasiksen', 'risankitsumabi', 'risankitsumabin', 'risankizumab', 'Skyrizi', 'Skyrizin', 'dupilumabi', 'dupilumabin', 'dupilumab', 'Dupixent', 'Dupixentin', 'iho', 'ihon', 'ihoa', 'ihossa', 'ihosairaus', 'ihosairauden', 'ihosairaudet'])),
K("Mikä on trastutsumabi?",
  "HER2-reseptorin vasta-aine (Herceptin), joka hoitaa HER2-positiivista rintasyöpää. Ensimmäisiä kohdennettuja syöpälääkkeitä (1998).",
  "",
  2, L(N('trastutsumabi', 'trastutsumabin', 'trastutsumabia', 'trastuzumab', 'trastuzumabin', 'Herceptin', 'Herceptinin', 'HER2', 'HER2:n', 'HER2-reseptori', 'HER2-reseptorin', 'HER2-positiivinen', 'HER2-positiivisen', 'HER2-positiivista', 'daratumumabi', 'daratumumabin', 'daratumumab', 'Darzalex', 'kohdennettu syöpälääke', 'kohdennetun syöpälääkkeen', 'kohdennetut syöpälääkkeet', 'täsmälääke', 'täsmälääkkeen', 'täsmälääkkeet', 'täsmälääkkeitä'))),
K("Mikä on semaglutidi?",
  "GLP-1-hormonin pitkävaikutteinen muunnos (Ozempic, Wegovy), joka hoitaa diabetesta ja lihavuutta. Tirtsepatidi (Mounjaro) toimii samoin.",
  "",
  2, L(N('semaglutidi', 'semaglutidin', 'semaglutidia', 'Ozempic', 'Ozempicin', 'Wegovy', 'Wegovyn', 'tirtsepatidi', 'tirtsepatidin', 'tirzepatidi', 'tirzepatidin', 'Mounjaro', 'Mounjaron', 'Zepbound', 'GLP-1', 'GLP-1:n', 'GLP-1-analogi', 'GLP-1-analogin', 'GLP-1-analogit', 'GLP-1-lääke', 'GLP-1-lääkkeen', 'GLP-1-lääkkeet', 'lihavuus', 'lihavuuden', 'lihavuutta', 'laihdutuslääke', 'laihdutuslääkkeen', 'laihdutuslääkkeet', 'Novo Nordiskin Ozempic'))),
K("Mikä on sidosaine?",
  "Aine, joka liittää hiukkasia yhteen: entsyymit immobilisoidaan sidosaineella kantajaan, tabletin aineet sidotaan sidosaineella.",
  "",
  1, L('sidosaine', ['sidosaineen', 'sidosainetta', 'sidosaineet', 'sidosaineeseen', 'sidottu', 'sidotun', 'sidotut', 'sitoa', 'sidotaan'])),
K("Mitä in silico tarkoittaa?",
  "Tietokoneella tehty: proteiinin rakenteen mallinnus, lääkemolekyylin sovitus kohteeseen tai entsyymin suunnittelu ennen laboratoriokoetta.",
  "",
  2, L(N('in silico', 'in silico -malli', 'in silico -mallin', 'in silico -mallit', 'silico-malli', 'silico-mallien', 'tietokonemallinnus', 'tietokonemallinnuksen', 'tietokonemallinnusta', 'mallinnus', 'mallinnuksen', 'mallinnusta', 'mallintaa', 'mallinnetaan', 'mallinnettu', 'molekyylimallinnus', 'molekyylimallinnuksen'))),
K("Mitä somaattinen tarkoittaa?",
  "Ruumiin soluihin liittyvä, ei sukusoluihin. Somaattinen geeniterapia ei periydy, somaattinen mutaatio syntyy elämän aikana.",
  "",
  2, L(N('somaattinen', 'somaattisen', 'somaattista', 'somaattiset', 'somaattisia', 'somaattinen solu', 'somaattisen solun', 'somaattiset solut', 'somaattisia soluja', 'somaattinen mutaatio', 'somaattisen mutaation', 'somaattiset mutaatiot', 'somaattinen geeniterapia', 'somaattisen geeniterapian', 'ituratageeniterapia', 'ituratageeniterapian', 'iturata', 'ituradan', 'iturataa'))),
K("Mikä on tulehdusvälittäjäaine?",
  "Tulehdusta kiihdyttävä molekyyli, kuten TNF-alfa tai interleukiini. Niitä estävät vasta-aineet hoitavat reumaa, psoriaasia ja suolistotulehduksia.",
  "",
  2, L('tulehdusvälittäjäaine', ['tulehdus-välittäjäaine', 'tulehdus-välittäjäaineen', 'tulehdusvälittäjäaineen', 'tulehdusvälittäjäaineet', 'tulehdusvälittäjäaineita', 'TNF', 'TNF:n', 'TNF-alfa', 'TNF-alfan', 'tuumorinekroositekijä', 'tuumorinekroositekijän', 'tulehdus', 'tulehduksen', 'tulehdusta', 'tulehduksessa', 'tulehdukset', 'tulehdusten', 'tulehduksia', 'tulehdussairaus', 'tulehdussairauden', 'tulehdussairaudet', 'tulehdussairauksia', 'tulehdussairauksiin', 'nivelreuma', 'nivelreuman', 'nivelreumaa', 'reuma', 'reuman', 'reumaa'])),
K("Mikä on viskositeetti?",
  "Nesteen sitkeys eli virtausvastus. Suuri solutiheys ja rihmasienet nostavat sitä ja vaikeuttavat sekoitusta ja hapensiirtoa.",
  "",
  1, L('viskositeetti', ['viskositeettia', 'viskositeetin', 'viskoosi', 'viskoosin', 'viskoosia', 'sitkeys', 'sitkeyden', 'juoksevuus', 'juoksevuuden'])),
K("Mitä yliekspressio tarkoittaa?",
  "Geenin ilmentäminen paljon luonnollista voimakkaammin, jolloin tuottoproteiinia kertyy jopa puolet solun proteiinista. Kutsutaan myös: yli-ilmentäminen.",
  "",
  2, L('yliekspressio', ['yliekspressoida', 'yliekspressoidaan', 'yliekspressoitu', 'yliekspressoidun', 'yli-ilmentäminen', 'yli-ilmentämisen', 'yli-ilmentää', 'yli-ilmennetty', 'yli-ilmentyä', 'ylituotto', 'ylituoton', 'ylituottoa', 'ekspressoida', 'ekspressoitu'])),
K("Mikä on äidinmaidonvastike?",
  "Vauvan korvikeruoka lehmänmaidosta. Rikastetaan äidinmaidon aineilla, kuten rekombinantilla laktoferriinillä ja oligosakkarideilla.",
  "",
  1, L('äidinmaidonvastike', ['äidinmaidonvastikkeen', 'äidinmaidonvastiketta', 'äidinmaito', 'äidinmaidon', 'äidinmaitoa', 'laktoferriini', 'laktoferriinin', 'laktoferriiniä', 'vauva', 'vauvan', 'vauvat', 'vauvoille'])),
K("Mikä on öljyteollisuus entsyymien käyttäjänä?",
  "Öljyn ja kaasun poraus, jossa entsyymit hajottavat porausnesteiden polymeereja, ja biodieselin valmistus lipaasilla.",
  "",
  1, L('öljyteollisuus', ['öljy', 'öljyn', 'öljyä', 'öljyt', 'öljyjen', 'raakaöljy', 'raakaöljyn', 'poraus', 'porauksen', 'porausta', 'poraukset', 'porausten', 'kasviöljy', 'kasviöljyn', 'kasviöljyä', 'kasviöljyt', 'kasviöljyistä'])),
K("Mikä on farmakologia?",
  "Lääkeaineiden vaikutusten, annostelun ja aineenvaihdunnan tiede. Biologisten lääkkeiden farmakologia eroaa pienmolekyyleistä.",
  "",
  1, L('farmakologia', ['farmakologinen', 'farmakologisen', 'farmakologiset', 'farmakokinetiikka', 'farmakokinetiikan', 'farmakokinetiikkaa'])),
K("Mikä on ravistelu solukasvatuksessa?",
  "Pullojen jatkuva heiluttaminen ravistelijassa, jotta solut pysyvät suspensiossa ja happea liukenee nesteeseen.",
  "",
  1, L('ravistelu', ['ravistella', 'ravistellaan', 'ravisteleva', 'ravistelija', 'ravistelijan', 'ravistelijassa', 'ravistelussa', 'sekoitus', 'sekoituksen', 'sekoitusta', 'sekoittaa', 'sekoitetaan', 'sekoittaminen', 'sekoittamisen', 'sekoituksella', 'sekoitin', 'sekoittimen', 'sekoittimet', 'moottori', 'moottorin', 'moottoria'])),
K("Mikä on kosmetiikka biotekniikan sovellusalana?",
  "Ihonhoito- ja kauneustuotteet, joissa käytetään bioteknisesti tuotettuja aineita: hyaluronihappoa, kollageenia, entsyymejä ja peptidejä.",
  "",
  1, L('kosmetiikka', ['kosmetiikan', 'kosmetiikkaa', 'kosmetiikassa', 'kosmeettinen', 'kosmeettisen', 'kosmeettiset', 'kosmeettisia', 'hyaluronihappo', 'hyaluronihapon', 'hyaluronihappoa'])),
K("Mikä on muovi biotekniikan yhteydessä?",
  "Öljystä tehty polymeeri, jota biomuovit ja entsymaattinen kierrätys (PET-hydrolaasi) korvaavat ja purkavat.",
  "",
  1, L('muovi', ['muovin', 'muovia', 'muovit', 'muovien', 'muoveja', 'muovinen', 'muovisen', 'muovipinta', 'muovipinnan', 'muovipinnalle', 'PET', 'PET-muovi', 'PET-muovin', 'PETaasi', 'PETaasin'])),
K("Mikä on polttoaine biotekniikan yhteydessä?",
  "Poltettava energianlähde. Biotekniikka tuottaa etanolia, biodieseliä, biokaasua ja vetyä fossiilisten polttoaineiden tilalle.",
  "",
  1, L('polttoaine', ['polttoaineen', 'polttoainetta', 'polttoaineet', 'polttoaineiden', 'polttoaineita', 'polttoaineeksi', 'fossiilinen polttoaine', 'fossiilisen polttoaineen', 'fossiiliset polttoaineet', 'fossiilisia polttoaineita', 'uusiutuva', 'uusiutuvan', 'uusiutuvat', 'uusiutuvia', 'uusiutuvaa'])),
K("Mikä on rekombinanttinen tuotto?",
  "Proteiinin valmistus geenitekniikalla muokatussa isäntäsolussa vieraan geenin avulla. Kutsutaan myös: rekombinanttituotto.",
  "",
  2, L(N('rekombinanttituotto', 'rekombinanttituoton', 'rekombinanttituottoa', 'rekombinanttituotolla', 'rekombinanttinen tuotto', 'rekombinanttisen tuoton', 'rekombinanttinen', 'rekombinanttisen', 'rekombinanttista', 'rekombinanttiset', 'rekombinanttisia', 'rekombinanttisten', 'rekombinantisti', 'rekombinantti', 'rekombinantin', 'rekombinanttia', 'rekombinantit'))),
K("Mikä on viherlevä biotekniikassa?",
  "Fotosynteettinen mikrolevä, kuten Chlorella, jota kasvatetaan altaissa proteiiniksi, öljyksi, väriaineiksi ja biopolttoaineeksi.",
  "",
  1, L(N('mikrolevä', 'mikrolevän', 'mikrolevää', 'mikrolevät', 'mikrolevien', 'mikroleviä', 'Chlorella', 'Chlorellan', 'Spirulina', 'Spirulinan', 'leväkasvatus', 'leväkasvatuksen', 'leväbiotekniikka', 'leväbiotekniikan'))),
K("Mikä on skaalaus?",
  "Prosessin suurentaminen laboratoriopullosta tuotantofermentoriin. Sekoitus, hapensiirto ja lämmönpoisto muuttuvat koon mukana.",
  "",
  2, L('skaalaus', ['skaalata', 'skaalataan', 'skaalattu', 'skaala', 'skaalan', 'skaalaa', 'skaalassa', 'mittakaava', 'mittakaavan', 'mittakaavaa', 'mittakaavassa', 'tuottoskaala', 'tuottoskaalan', 'kokoluokka', 'kokoluokan', 'kokoluokat', 'kokoluokille', 'laboratoriomittakaava', 'laboratoriomittakaavan', 'laboratoriomittakaavassa', 'pilottimittakaava', 'pilottimittakaavan', 'pilotti', 'pilotin'])),
K("Mikä on tuotantokustannus?",
  "Tuotteen valmistuksen hinta: raaka-aineet, laitteet, energia, työ ja puhdistus. Puhdistus on usein proteiinituotannon kallein osa.",
  "",
  1, L('tuotantokustannus', ['tuotantokustannukset', 'tuotantokustannusten', 'tuotantokustannuksia', 'kustannus', 'kustannuksen', 'kustannukset', 'kustannusten', 'kustannuksia', 'laitekustannus', 'laitekustannukset', 'laitekustannusten', 'ympäristökustannus', 'ympäristökustannukset', 'ympäristökustannusten', 'taloudellinen', 'taloudellisen', 'taloudellista', 'taloudelliset', 'taloudellisesti', 'talous', 'talouden', 'taloutta', 'hinta', 'hinnan', 'hintaa', 'hinnat', 'kallis', 'kalliin', 'kallista', 'kalliit', 'edullinen', 'edullisen', 'edullista', 'edulliset', 'edullisia', 'edullisin'])),
]

L3 = [
K("Mikä on kaivo mikrotiitterilevyllä?",
  "Levyn pieni kuoppa (96 tai 384 levyllä), jossa yksi määritys tehdään mikrolitratilavuuksissa. Kutsutaan myös: kuoppa, well.",
  "",
  2, L('kaivo', ['kuoppa', 'kuopan', 'kuoppaa', 'kuopat', 'kuoppien', 'kuoppia', 'well', 'wells', 'levy', 'levyn', 'levyä', 'levyt', 'levyjen', 'levyjä', 'levyllä', 'plate', 'microtiter', 'microtiter plate'])),
K("Mikä on levyinkubaattori?",
  "Laite, joka pitää mikrotiitterilevyn vakiolämpötilassa ja ravistelee sitä reaktion ajan. Kutsutaan myös: hautomakone.",
  "",
  1, L('levyinkubaattori', ['hautomakone', 'hautomakoneen', 'hautomakonetta', 'hautoa', 'haudotaan', 'hautominen', 'hautomisen', 'incubate', 'incubator'])),
K("Mikä on testiviiva?",
  "Pikatestin liuskalle ilmestyvä värillinen viiva, jonka leimattu vasta-aine muodostaa analyytin ollessa läsnä. Kontrolliviiva varmistaa toimivuuden.",
  "",
  2, L('testiviiva', ['kontrolliviiva', 'kontrolliviivan', 'kontrolliviivaa', 'kontrolliviivat', 'viiva', 'viivan', 'viivaa', 'viivat', 'viivojen', 'viivoja', 'testiliuska', 'testiliuskan', 'testiliuskaa', 'testiliuskat', 'liuska', 'liuskan', 'liuskaa', 'liuskat', 'liuskojen', 'liuskoja', 'line', 'test line', 'control line'])),
K("Mikä on nitroselluloosamembraani?",
  "Huokoinen kalvo, jota pitkin näyteneste virtaa pikatestissä kapillaari-ilmiöllä ja johon vasta-aineet on kiinnitetty viivoiksi.",
  "",
  2, L('nitroselluloosamembraani', ['nitroselluloosa', 'nitroselluloosan', 'nitroselluloosaa', 'nitroselluloosakalvo', 'nitroselluloosakalvon', 'membraani', 'membraanin', 'membraania', 'membraanit', 'membraanille', 'membrane', 'nestevirtaus', 'nestevirtauksen', 'nestevirtausta', 'kapillaarivirtaus', 'kapillaarivirtauksen', 'kapillaari-ilmiö', 'kapillaari-ilmiön'])),
K("Mitä spesifisyys tarkoittaa diagnostiikassa?",
  "Testin kyky antaa negatiivinen tulos terveille: terveiden osuus, jotka testi tunnistaa terveiksi. Herkkyys on vastaava sairaille.",
  "",
  3, L('spesifisyys', ['spesifinen', 'spesifisen', 'spesifistä', 'spesifiset', 'spesifisiä', 'spesifisesti', 'spesifisempi', 'spesifisemmän', 'epäspesifinen', 'epäspesifisen', 'epäspesifiset', 'epäspesifisiä', 'ei-spesifinen', 'ei-spesifisen', 'ei-spesifisiä', 'väärä positiivinen', 'väärän positiivisen', 'väärät positiiviset', 'väärä negatiivinen', 'väärän negatiivisen', 'väärät negatiiviset', 'epäherkkä', 'epäherkän', 'epäherkät', 'ultraherkkä', 'ultraherkän', 'ultraherkät'])),
K("Mikä on sitojavasta-aine?",
  "Kiintofaasiin kiinnitetty vasta-aine, joka pyydystää analyytin näytteestä sandwich-määrityksessä. Kutsutaan myös: pyydystävä vasta-aine, capture antibody.",
  "",
  2, L('sitojavasta-aine', ['sitojavasta-aineen', 'sitojavasta-ainetta', 'sitojavasta-aineet', 'sitojavasta-aineiden', 'sitojavasta-aineita', 'pyydystävä vasta-aine', 'pyydystävän vasta-aineen', 'capture antibody', 'capture', 'sitojapinta', 'sitojapinnan', 'sitojapintaa', 'detektiovasta-aine', 'detektiovasta-aineen', 'detektiovasta-aineet', 'detection antibody', 'tunnistava vasta-aine', 'tunnistavan vasta-aineen', 'osoittava vasta-aine', 'osoittavan vasta-aineen'])),
K("Mitä pesu tarkoittaa immunomäärityksessä?",
  "Sitoutumattoman näytteen ja leiman huuhtelu pois kiintofaasista puskurilla, jotta vain sitoutunut leima antaa signaalin.",
  "",
  2, L(N('pesu', 'pesun', 'pesua', 'pesut', 'pesujen', 'pesuja', 'pesussa', 'pestä', 'pestään', 'pesty', 'pesuvaihe', 'pesuvaiheen', 'pesuvaiheet', 'pesuvaiheita', 'pesuneste', 'pesunesteen', 'pesunestettä', 'pesupuskuri', 'pesupuskurin', 'pesupuskuria', 'sitoutumaton', 'sitoutumattoman', 'sitoutumatonta', 'sitoutumattomat', 'sitoutumattomien', 'sitoutumattomia', 'sitoutumatta', 'ylimääräinen', 'ylimääräisen', 'ylimääräistä', 'ylimääräiset', 'ylimääräisiä', 'ylimäärin'))),
K("Mikä on mikropartikkeli?",
  "Mikrometrikokoinen muovi- tai magneettihelmi, johon vasta-aine on kiinnitetty. Suuri pinta-ala nopeuttaa sitoutumista ja magneetti erottelun.",
  "",
  2, L('mikropartikkeli', ['muovipartikkeli', 'muovipartikkelin', 'muovipartikkelia', 'muovipartikkelit', 'muovipartikkeleita', 'magneettipartikkeli', 'magneettipartikkelin', 'magneettipartikkelit', 'magneettipartikkeleita', 'helmi', 'helmen', 'helmeä', 'helmet', 'helmien', 'helmiä', 'lateksipartikkeli', 'lateksipartikkelin', 'lateksipartikkelit'])),
K("Mikä on sormenpäänäyte?",
  "Pisara kapillaariverta sormenpäästä lansetilla. Vieritestien ja verensokerimittarin näyte, ei tarvitse laskimopunktiota.",
  "",
  2, L('sormenpäänäyte', ['sormenpäänäytteen', 'sormenpäänäytettä', 'sormenpäänäytteestä', 'sormenpää', 'sormenpään', 'sormenpäästä', 'kapillaariveri', 'kapillaariveren', 'kapillaariverta', 'lansetti', 'lansetin', 'lansetilla', 'laskimoveri', 'laskimoveren', 'laskimoverta', 'laskimonäyte', 'laskimonäytteen'])),
K("Mikä on virtsanäyte?",
  "Helposti saatava näyte, josta mitataan raskaushormoni, glukoosi, proteiini, huumausaineet ja virtsatieinfektion merkit.",
  "",
  2, L(N('virtsanäyte', 'virtsanäytteen', 'virtsanäytettä', 'virtsanäytteestä', 'virtsanäytteet', 'virtsa', 'virtsan', 'virtsaa', 'virtsassa', 'virtsasta', 'virtsatieinfektio', 'virtsatieinfektion', 'virtsatieinfektiota', 'virtsatieinfektiot', 'virtsatulehdus', 'virtsatulehduksen'))),
K("Mikä on sylkinäyte?",
  "Kivuton näyte, josta mitataan hormoneja, huumeita, vasta-aineita ja virusten nukleiinihappoja, kuten koronatestissä.",
  "",
  1, L(N('sylkinäyte', 'sylkinäytteen', 'sylkinäytettä', 'sylkinäytteestä', 'sylki', 'syljen', 'sylkeä', 'syljessä', 'syljestä'))),
K("Mikä on syöpämerkkiaine?",
  "Veressä mitattava aine, jonka pitoisuus kertoo kasvaimesta: PSA eturauhassyövässä, CA-125 munasarjasyövässä, CEA suolistosyövässä.",
  "",
  2, L('syöpämerkkiaine', ['syöpämerkkiaineen', 'syöpämerkkiainetta', 'syöpämerkkiaineet', 'syöpämerkkiaineiden', 'syöpämerkkiaineita', 'PSA', 'PSA:n', 'PSA:ta', 'CA-125', 'CA-125:n', 'CEA', 'CEA:n', 'kasvainmerkkiaine', 'kasvainmerkkiaineen', 'kasvainmerkkiaineet', 'eturauhanen', 'eturauhasen', 'eturauhasta', 'munasarja', 'munasarjan', 'munasarjat', 'munasarjasyöpä', 'munasarjasyövän', 'haimasyöpä', 'haimasyövän', 'suolistosyöpä', 'suolistosyövän', 'paksusuolisyöpä', 'paksusuolisyövän', 'virtsarakkosyöpä', 'virtsarakkosyövän'])),
K("Mikä on sydäninfarkti diagnostiikan kohteena?",
  "Sydänlihaksen hapenpuutteesta johtuva vaurio, jonka merkkiaineet troponiini ja CK-MB nousevat veressä tunneissa. Kutsutaan myös: sydänkohtaus.",
  "",
  2, L('sydäninfarkti', ['sydänkohtaus', 'sydänkohtauksen', 'sydänkohtausta', 'sydänkohtaukset', 'sydänkohtausmerkkiaine', 'sydänkohtausmerkkiaineen', 'sydänkohtausmerkkiaineet', 'sydän', 'sydämen', 'sydäntä', 'sydämessä', 'sydänlihas', 'sydänlihaksen', 'sydänlihasta', 'sydänmerkkiaine', 'sydänmerkkiaineen', 'sydänmerkkiaineet', 'CK-MB', 'CK-MB:n', 'ctni', 'cTnI', 'cTnT', 'sydämen vajaatoiminta', 'sydämen vajaatoiminnan', 'vajaatoiminta', 'vajaatoiminnan', 'vajaatoimintaa', 'BNP', 'BNP:n', 'NT-proBNP'])),
K("Mikä on kilpirauhasen toimintakoe?",
  "TSH:n ja tyroksiinin mittaus verestä immunomäärityksellä: vajaa- ja liikatoiminnan diagnostiikka ja hoidon seuranta.",
  "",
  2, L(N('kilpirauhanen', 'kilpirauhasen', 'kilpirauhasta', 'kilpirauhasessa', 'kilpirauhashormoni', 'kilpirauhashormonin', 'kilpirauhashormonit', 'kilpirauhashormoneja', 'TSH', 'TSH:n', 'TSH:ta', 'tyroksiini', 'tyroksiinin', 'tyroksiinia', 'T4', 'T4:n', 'T3', 'T3:n', 'kilpirauhasen vajaatoiminta', 'kilpirauhasen vajaatoiminnan', 'kilpirauhasen liikatoiminta', 'kilpirauhasen liikatoiminnan'))),
K("Mikä on PAPP-A?",
  "Istukan proteiini, jonka matala pitoisuus äidin veressä alkuraskaudessa viittaa sikiön kromosomipoikkeavuuteen. Osa raskausseulontaa.",
  "",
  1, L(N('PAPP-A', 'PAPP-A:n', 'PAPP-A:ta', 'raskausseulonta', 'raskausseulonnan', 'raskausseulontaa', 'sikiöseulonta', 'sikiöseulonnan', 'sikiöseulontaa', 'istukka', 'istukan', 'istukkaa', 'istukkahormoni', 'istukkahormonin', 'istukkahormonia', 'hCG', 'hCG:n', 'hCG:tä', 'raskaushormoni', 'raskaushormonin', 'raskaushormonia', 'raskaus', 'raskauden', 'raskautta', 'raskaudessa'))),
K("Mikä on hepatiitti?",
  "Maksatulehdus, yleisimmin B- tai C-viruksen aiheuttama. Todetaan vasta-aine- ja antigeenitesteillä sekä PCR:llä, B ehkäistään rokotteella.",
  "",
  2, L('hepatiitti', ['maksatulehdus', 'maksatulehduksen', 'maksatulehdusta', 'hepatiitti B', 'hepatiitti B:n', 'hepatiitti C', 'hepatiitti C:n', 'B-hepatiitti', 'B-hepatiitin', 'C-hepatiitti', 'C-hepatiitin', 'hepatiittivirus', 'hepatiittiviruksen', 'hepatiittirokote', 'hepatiittirokotteen'])),
K("Mikä on hinkuyskä?",
  "Bordetella pertussis -bakteerin aiheuttama pitkittynyt yskätauti, jota vastaan rokotetaan soluttomalla rokotteella. Todetaan PCR:llä ja vasta-aineista.",
  "",
  1, L('hinkuyskä', ['hinkuyskän', 'hinkuyskää', 'Bordetella', 'Bordetellan', 'Bordetella pertussis', 'pertussis', 'pertussiksen', 'hinkuyskärokote', 'hinkuyskärokotteen'])),
K("Mikä on malaria?",
  "Plasmodium-loisen aiheuttama hyttysten levittämä kuumetauti. Pikatesti tunnistaa loisen antigeenin sormenpääverestä minuuteissa.",
  "",
  2, L('malaria', ['Plasmodium', 'Plasmodiumin', 'Plasmodium falciparum', 'malariapikatesti', 'malariapikatestin', 'malariatesti', 'malariatestin', 'malariahyttynen', 'malariahyttysen', 'malariahyttyset', 'malariahyttysiä', 'malarialääke', 'malarialääkkeen', 'malarialääkkeet', 'artemisiniini', 'artemisiniinin', 'artemisiniinia', 'loinen', 'loisen', 'loista', 'loiset', 'loisten', 'loisia'])),
K("Mikä on huumausainetesti?",
  "Virtsan tai syljen immunomääritys, joka seuloo huumeet ja lääkeaineet. Positiivinen tulos varmistetaan massaspektrometrialla.",
  "",
  2, L('huumausainetesti', ['huumausaine', 'huumausaineen', 'huumausainetta', 'huumausaineet', 'huumausaineiden', 'huumausaineita', 'huume', 'huumeen', 'huumetta', 'huumeet', 'huumeiden', 'huumeita', 'huumeaine', 'huumeaineen', 'huumeaineet', 'huumeaineiden', 'huumetesti', 'huumetestin', 'huumetestit', 'huumeseula', 'huumeseulan', 'huumeseulat', 'massaspektrometria', 'massaspektrometrian', 'massaspektrometriaa', 'massaspektrometrialla', 'massaspektrometri', 'massaspektrometrin'])),
K("Mikä on sinilevätesti?",
  "Uimaveden pikatesti, joka tunnistaa syanobakteerien toksiinit tai pigmentin vasta-aineella. Kutsutaan myös: ympäristödiagnostiikka.",
  "",
  1, L('sinilevätesti', ['sinilevätestin', 'sinilevätestiä', 'sinilevä', 'sinilevän', 'sinilevää', 'sinilevät', 'sinilevien', 'sinileviä', 'uimavesi', 'uimaveden', 'uimavettä', 'uimavedessä', 'ympäristödiagnostiikka', 'ympäristödiagnostiikan', 'ympäristödiagnostiikkaa', 'ympäristönäyte', 'ympäristönäytteen', 'ympäristönäytteet', 'vesinäyte', 'vesinäytteen', 'vesinäytteet'])),
K("Mikä on keskoskaappi?",
  "Ennenaikaisesti syntyneen vauvan lämmitetty hoitokaappi. Esimerkki lääkintälaitteesta diagnostiikkalaitteiden rinnalla. Kutsutaan myös: inkubaattori.",
  "",
  1, L('keskoskaappi', ['keskoskaapin', 'keskoskaappia', 'keskonen', 'keskosen', 'keskosta', 'keskoset', 'lääkintälaite', 'lääkintälaitteen', 'lääkintälaitteet', 'lääkintälaitteiden', 'lääkintälaitteita', 'lääkinnällinen laite', 'lääkinnällisen laitteen', 'lääkinnälliset laitteet', 'lääkinnällisiä laitteita', 'lääkinnälliset', 'lääkinnällisten'])),
K("Mikä on kuvantaminen diagnostiikassa?",
  "Sairauden toteaminen kuvasta: röntgen, magneettikuvaus, ultraääni ja tietokonetomografia. In vitro -diagnostiikka tutkii sen sijaan näytettä.",
  "",
  2, L('kuvantaminen', ['kuvantamisen', 'kuvantamista', 'kuvantamismenetelmä', 'kuvantamismenetelmän', 'kuvantamismenetelmät', 'kuvantamismenetelmiä', 'röntgenkuvaus', 'röntgenkuvauksen', 'röntgenkuvausta', 'röntgenkuva', 'röntgenkuvan', 'röntgenkuvat', 'magneettikuvaus', 'magneettikuvauksen', 'magneettikuvausta', 'magneettikuva', 'magneettikuvan', 'MRI', 'MRI:n', 'ultraäänitutkimus', 'ultraäänitutkimuksen', 'ultraäänitutkimusta', 'ultraäänikuvaus', 'ultraäänikuvauksen', 'tietokonetomografia', 'tietokonetomografian', 'tietokonetomografiaa', 'TT-kuvaus', 'TT-kuvauksen', 'tietokonediagnostiikka', 'tietokonediagnostiikan', 'tietokonediagnostiikkaa'])),
K("Mitä laboratoriolääketiede on?",
  "Lääketieteen ala, joka tutkii potilasnäytteitä: kliininen kemia, hematologia, mikrobiologia, immunologia ja genetiikka.",
  "",
  2, L('laboratoriolääketiede', ['laboratoriolääketieteen', 'laboratoriolääketiedettä', 'laboratoriolääketieteessä', 'kliininen kemia', 'kliinisen kemian', 'kliinistä kemiaa', 'kliininen laboratorio', 'kliinisen laboratorion', 'kliiniset laboratoriot', 'laboratoriomenetelmä', 'laboratoriomenetelmän', 'laboratoriomenetelmät', 'laboratoriomenetelmien', 'laboratoriomenetelmiä', 'laboratoriotutkimus', 'laboratoriotutkimuksen', 'laboratoriotutkimukset', 'laboratoriotutkimuksia', 'laboratoriokoe', 'laboratoriokokeen', 'laboratoriokokeet', 'laboratoriokokeita'])),
K("Mitä ennaltaehkäisy on diagnostiikan tavoitteena?",
  "Sairauden estäminen ennen oireita: riskitekijöiden ja esiasteiden tunnistaminen seulonnalla ja rokotuksin. Kutsutaan myös: preventio.",
  "",
  2, L('ennaltaehkäisy', ['ennaltaehkäisyn', 'ennaltaehkäisyä', 'ennaltaehkäistä', 'ennaltaehkäisevä', 'ennaltaehkäisevän', 'ennaltaehkäisevät', 'ehkäisy', 'ehkäisyn', 'ehkäisyä', 'ehkäistä', 'ehkäisee', 'preventio', 'prevention', 'preventiota', 'preventiivinen', 'preventiivisen', 'preventiiviset', 'riskitekijä', 'riskitekijän', 'riskitekijät', 'riskitekijöiden', 'riskitekijöitä'])),
K("Mikä on taustasignaali?",
  "Signaali ilman analyyttiä: leiman epäspesifinen sitoutuminen ja laitteen kohina. Määrittää herkkyyden alarajan. Kutsutaan myös: nollataso.",
  "",
  2, L('taustasignaali', ['taustasignaalin', 'taustasignaalia', 'taustasignaalitaso', 'taustasignaalitason', 'tausta', 'taustan', 'taustaa', 'taustalla', 'nollataso', 'nollatason', 'nollatasoa', 'nollatasosta', 'nollapitoisuus', 'nollapitoisuuden', 'nollapitoisuudessa', 'nollanäyte', 'nollanäytteen', 'nollanäytettä', 'kohina', 'kohinan', 'kohinaa', 'signaali-kohina-suhde', 'signaali-kohina-suhteen', 'toteamisraja', 'toteamisrajan', 'toteamisrajaa', 'detektioraja', 'detektiorajan', 'alaraja', 'alarajan', 'alarajalla', 'detection limit'])),
K("Mikä on signaali määrityksessä?",
  "Mitattava vaste, kuten väri, valo tai sähkövirta, jonka voimakkuus riippuu analyytin pitoisuudesta ja muunnetaan tulokseksi kalibraatiolla.",
  "",
  2, L('signaali', ['signaalitaso', 'signaalitason', 'signaalitasoa', 'signaalin voimakkuus', 'signaalin voimakkuuden', 'vaste', 'vasteen', 'vastetta', 'vasteet', 'vasteen mittaus', 'värireaktio', 'värireaktion', 'värireaktiota', 'värimuutos', 'värimuutoksen', 'värimuutosta', 'väri', 'värin', 'väriä', 'värit', 'värien', 'värillinen', 'värillisen', 'värillistä', 'värilliset', 'värikartta', 'värikartan', 'värikartalta', 'valo', 'valon', 'valoa', 'valossa', 'valosignaali', 'valosignaalin', 'luminesenssi', 'luminesenssin', 'luminesenssia', 'kemiluminesenssi', 'kemiluminesenssin', 'kemiluminesenssia', 'absorbanssi', 'absorbanssin', 'absorbanssia'])),
K("Mikä on mikrosiruteknologia diagnostiikassa?",
  "Sirulle pakatut tuhannet määrityskohdat tai kanavat: DNA-sirut, proteiinisirut ja lab-on-a-chip-laitteet. Kutsutaan myös: sirutekniikka.",
  "",
  1, L('mikrosiruteknologia', ['mikrosiru', 'mikrosirun', 'mikrosirua', 'mikrosirut', 'mikrosirujen', 'siru', 'sirun', 'sirua', 'sirut', 'sirujen', 'sirulla', 'sirulle', 'DNA-siru', 'DNA-sirun', 'DNA-sirut', 'mikrosirutekniikka', 'mikrosirutekniikan', 'sirutekniikka', 'sirutekniikan', 'microarray', 'biosiru', 'biosirun', 'biosirut'])),
K("Mitä elintarvikeanalytiikka on?",
  "Ruoan koostumuksen, allergeenien, toksiinien, GMO-ainesten ja taudinaiheuttajien mittaus vasta-aine- ja PCR-menetelmillä. Kutsutaan myös: elintarvikediagnostiikka.",
  "",
  1, L('elintarvikeanalytiikka', ['elintarvikeanalytiikan', 'elintarvikeanalytiikkaa', 'elintarvikediagnostiikka', 'elintarvikediagnostiikan', 'elintarvikediagnostiikkaa', 'elintarviketurvallisuus', 'elintarviketurvallisuuden', 'elintarviketurvallisuutta', 'GMO-tuote', 'GMO-tuotteen', 'GMO-tuotteet', 'GMO-tuotteiden', 'GMO-tuotteita', 'aitous', 'aitouden', 'aitoutta', 'analytiikka', 'analytiikan', 'analytiikkaa'])),
K("Mitä in vivo tarkoittaa?",
  "Elävässä eliössä tehty, vastakohtana in vitro -kokeelle koeputkessa. In vivo -diagnostiikkaa ovat kuvantaminen ja merkkiainetutkimukset potilaassa.",
  "",
  2, L(N('in vivo', 'in vivo -diagnostiikka', 'in vivo -diagnostiikan', 'in vivo -koe', 'in vivo -kokeen', 'in vivo -kokeet', 'vivo', 'in vitro -koe', 'in vitro -kokeen', 'in vitro -kokeet', 'vitro', 'in-vitro', 'vitrodiagnostiikka', 'merkkiainetutkimus', 'merkkiainetutkimuksen', 'merkkiainetutkimukset', 'isotooppitutkimus', 'isotooppitutkimuksen', 'isotooppitutkimukset'))),
K("Mikä on potilasnäyte?",
  "Potilaasta tutkimusta varten otettu materiaali: veri, virtsa, sylki, uloste, kudos tai likvori. Kutsutaan myös: näytemateriaali.",
  "",
  2, L('potilasnäyte', ['potilasnäytteen', 'potilasnäytettä', 'potilasnäytteet', 'potilasnäytteiden', 'potilasnäytteitä', 'potilasnäytteistä', 'näytemateriaali', 'näytemateriaalin', 'näytemateriaalia', 'näytemateriaalissa', 'näytemateriaalit', 'näyte', 'näytteen', 'näytettä', 'näytteessä', 'näytteestä', 'näytteeseen', 'näytteet', 'näytteiden', 'näytteitä', 'näytteissä', 'näytteistä', 'potilas', 'potilaan', 'potilasta', 'potilaat', 'potilaiden', 'potilaita', 'potilaille', 'potilaalle', 'uloste', 'ulosteen', 'ulostetta', 'ulostenäyte', 'ulostenäytteen', 'likvori', 'likvorin', 'likvoria', 'selkäydinneste', 'selkäydinnesteen', 'selkäydinnestettä'])),
K("Mikä on taudinmääritys?",
  "Sairauden tunnistaminen oireiden, tutkimusten ja laboratoriotulosten perusteella. Kutsutaan myös: diagnosointi.",
  "",
  2, L('taudinmääritys', ['taudinmäärityksen', 'taudinmääritystä', 'taudinmääritysoppi', 'taudinmääritysopin', 'diagnoosit', 'diagnoosien', 'diagnooseja', 'diagnosoida', 'diagnosoidaan', 'diagnosoitu', 'diagnostinen', 'diagnostisen', 'diagnostista', 'diagnostiset', 'diagnostisia', 'tautitila', 'tautitilan', 'tautitilaa', 'tautitilaan', 'terveydentila', 'terveydentilan', 'terveydentilaa', 'oire', 'oireen', 'oiretta', 'oireet', 'oireiden', 'oireita', 'oireeton', 'oireettoman', 'oireettomat', 'oireettomia', 'sairaus', 'sairauden', 'sairautta', 'sairaudessa', 'sairaudesta', 'sairaudet', 'sairauksien', 'sairauksia', 'sairauksiin', 'tauti', 'taudin', 'tautia', 'taudissa', 'tautiin', 'taudit', 'tautien', 'tauteja'])),
K("Mikä on seurantatesti?",
  "Määritys, jolla hoidon tehoa ja taudin kulkua seurataan toistuvasti, kuten HbA1c diabeteksessa tai viruskuorma HIV:ssä.",
  "",
  2, L('seurantatesti', ['seurantatestin', 'seurantatestiä', 'seurantatestit', 'seurantatestejä', 'seuranta', 'seurannan', 'seurantaa', 'seurannassa', 'seurata', 'seurataan', 'seurattava', 'hoidon seuranta', 'hoidon seurannan', 'hoidon seurantaa', 'HbA1c', 'HbA1c:n', 'sokerihemoglobiini', 'sokerihemoglobiinin', 'viruskuorma', 'viruskuorman', 'viruskuormaa'])),
K("Mikä on aktiivisuusmääritys?",
  "Entsyymin määrä mitataan sen katalysoiman reaktion nopeudesta, ei massasta: esimerkiksi maksa-arvot ALAT ja ASAT.",
  "",
  2, L('aktiivisuusmääritys', ['aktiivisuusmäärityksen', 'aktiivisuusmääritystä', 'aktiivisuusmääritykset', 'ALAT', 'ALAT:n', 'ASAT', 'ASAT:n', 'maksa-arvo', 'maksa-arvon', 'maksa-arvot', 'maksa-arvojen', 'maksa-arvoja', 'kinetiikka', 'kinetiikan', 'kinetiikkaa', 'kineettinen', 'kineettisen', 'kineettiset', 'kineettinen määritys', 'kineettisen määrityksen', 'reaktionopeus', 'reaktionopeuden', 'reaktionopeutta'])),
K("Mikä on kalsiummääritys?",
  "Veren kalsiumin mittaus värireaktiolla tai ioniselektiivisellä elektrodilla. Esimerkki kliinisen kemian ei-immunologisesta määrityksestä.",
  "",
  1, L('kalsiummääritys', ['kalsium', 'kalsiumin', 'kalsiumia', 'kalsiumpitoisuus', 'kalsiumpitoisuuden', 'kalsiumpitoisuutta', 'ioniselektiivinen elektrodi', 'ioniselektiivisen elektrodin', 'ioniselektiiviset elektrodit', 'elektrolyytti', 'elektrolyytin', 'elektrolyytit', 'elektrolyyttien', 'elektrolyyttejä', 'elektrolyyttimääritys', 'elektrolyyttimäärityksen'])),
K("Mikä on fenolisulfonftaleiini?",
  "Fenolipuna, pH-indikaattori, jonka väri vaihtuu keltaisesta punaiseksi pH 6,8–8,2. Solukasvatusliuoksen ja vanhojen munuaiskokeiden väriaine.",
  "",
  1, L('fenolisulfonftaleiini', ['fenolsulfoneftaleiini', 'fenolsulfoneftaleiinin', 'fenolipuna', 'fenolipunan', 'fenolipunaa', 'pH-indikaattori', 'pH-indikaattorin', 'pH-indikaattoria', 'pH-indikaattorit', 'indikaattori', 'indikaattorin', 'indikaattoria', 'indikaattorit', 'indikaattorien', 'indikaattoreita', 'väriaine', 'väriaineen', 'väriainetta', 'väriaineet', 'väriaineiden', 'väriaineita', 'väriaineina', 'väriaineiksi'])),
K("Mikä on eläinlääketieteellinen diagnostiikka?",
  "Eläinten tautien testaus: tuotantoeläinten tarttuvat taudit, lemmikkien pikatestit ja elintarvikeketjun tautiseuranta.",
  "",
  1, L(N('eläinlääketieteellinen diagnostiikka', 'eläinlääketieteellisen diagnostiikan', 'eläinlääketieteellistä diagnostiikkaa', 'eläindiagnostiikka', 'eläindiagnostiikan', 'eläindiagnostiikkaa', 'eläinlääketiede diagnostiikassa', 'eläintauti', 'eläintaudin', 'eläintaudit', 'eläintautien', 'eläintauteja'))),
K("Mikä on Piilaakso biotekniikan yhteydessä?",
  "Kalifornian teknologiakeskittymä, jossa syntyivät ensimmäiset bioteknologiayritykset (Genentech 1976) ja jossa startupit rahoitetaan riskipääomalla.",
  "",
  1, L(N('Piilaakso', 'Piilaakson', 'Piilaaksoa', 'Piilaaksossa', 'Silicon Valley', 'Genentech', 'Genentechin', 'startup', 'startupin', 'startupit', 'startup-yritys', 'startup-yrityksen', 'startup-yritykset', 'riskipääoma', 'riskipääoman', 'riskipääomaa', 'kasvuyritys', 'kasvuyrityksen', 'kasvuyritykset'))),
K("Mikä on hyvä diagnostinen testi?",
  "Herkkä, spesifinen, nopea, halpa, helppo ja toistettava. Vaatimukset painottuvat käyttötarkoituksen mukaan: seulonnassa herkkyys, varmistuksessa spesifisyys.",
  "",
  2, L(N('toistettavuus', 'toistettavuuden', 'toistettavuutta', 'toistettava', 'toistettavan', 'toistettavat', 'toistettavia', 'luotettavuus', 'luotettavuuden', 'luotettavuutta', 'luotettava', 'luotettavan', 'luotettavat', 'luotettavia', 'luotettavasti', 'tarkkuus', 'tarkkuuden', 'tarkkuutta', 'tarkka', 'tarkan', 'tarkat', 'tarkkoja', 'suorituskyky', 'suorituskyvyn', 'suorituskykyä', 'suorituskykyyn', 'hajonta', 'hajonnan', 'hajontaa', 'nopeus', 'nopeuden', 'nopeutta', 'nopea', 'nopean', 'nopeat', 'nopeita', 'nopeasti', 'yksinkertainen', 'yksinkertaisen', 'yksinkertaista', 'yksinkertaiset', 'yksinkertaisia'))),
]

# kolmas kierros: sanasto3.py
import sanasto3
L1 += sanasto3.BIOTEK_L1
L2 += sanasto3.BIOTEK_L2
L3 += sanasto3.BIOTEK_L3
