# -*- coding: utf-8 -*-
"""Johdatus biotekniikkaan: sanaston taydennys luentoihin 1-3 (termit, joita kalvoilla kaytetaan mutta joilla ei ollut
maaritelmakorttia). L1 numerot 1.101-, L2 ja L3 jatkavat omia listojaan. Rakentaa tyokalut/biotek_kortit.py."""
from biotek_taivutus import L
from pakka_rakenna import K

L1 = dict(LEHTI='Luento 1 - Mitä biotekniikka on', TIEDOSTO='Luento 1 - Sanasto (lisays)', NRO=1, ALKU=100, KUVAT={}, KORTIT=[
K("Mitä genetiikka on?",
  "Perinnöllisyystiede: geenien, periytymisen ja perinnöllisen vaihtelun tutkimus.",
  "Genetiikka tutkii, miten ominaisuudet periytyvät, mitä geenit ovat ja miten ne toimivat. Se alkoi Mendelin herneristeytyksistä 1860-luvulla ja sai molekyylitason, kun DNA:n rakenne selvisi 1953. Nykygenetiikka ulottuu perimän sekvensoinnista geenien muokkaukseen ja populaatioiden evoluutioon. Biotekniikalle genetiikka antaa välineet valita ja muokata tuotto-organismeja sekä ymmärtää perinnöllisiä sairauksia. Kutsutaan myös: perinnöllisyystiede.",
  3, L('genetiikka', ['perinnöllisyystiede', 'perinnöllisyystieteen', 'perinnöllisyystiedettä', 'geneettinen', 'geneettisen', 'geneettistä', 'geneettisesti'])),
K("Mitä mikrobiologia on?",
  "Mikrobien eli bakteerien, arkeonien, sienten, alkueliöiden ja virusten tutkimus.",
  "Mikrobiologia tutkii paljain silmin näkymättömiä eliöitä: bakteereja, arkeoneja, hiivoja ja homeita, alkueliöitä ja leviä sekä viruksia. Ala syntyi, kun Leeuwenhoek näki mikrobit mikroskoopilla 1670-luvulla ja Pasteur ja Koch osoittivat 1800-luvulla niiden aiheuttavan käymisen ja taudit. Biotekniikka nojaa mikrobiologiaan, koska mikrobit ovat sen yleisimmät tuotto-organismit ja monet sen tuotteet ovat mikrobien torjuntaa.",
  2, L('mikrobiologia', ['mikrobi', 'mikrobin', 'mikrobia', 'mikrobissa', 'mikrobista', 'mikrobiin', 'mikrobit', 'mikrobien', 'mikrobeja', 'mikrobeissa', 'mikrobeista', 'mikro-organismi', 'mikro-organismin', 'mikro-organismia', 'mikro-organismit', 'mikro-organismien', 'mikro-organismeja', 'mikro-organismeissa', 'mikroorganismi', 'mikroorganismit', 'mikroorganismien'])),
K("Mitä virologia on?",
  "Virusten rakenteen, lisääntymisen ja aiheuttamien tautien tutkimus.",
  "",
  1, L('virologia')),
K("Mikä on mikrobiomi?",
  "Tietyssä ympäristössä, kuten ihmisen suolistossa, elävien mikrobien kokonaisuus.",
  "Mikrobiomi on kaikkien tietyn elinympäristön mikrobien yhteisö ja niiden geenit. Ihmisen suolistossa elää tuhansia bakteerilajeja, joita on solumäärältään yhtä paljon kuin omia soluja. Suolistomikrobiomi pilkkoo kuituja, tuottaa vitamiineja, kouluttaa immuunijärjestelmää ja torjuu taudinaiheuttajia, ja sen häiriöt liittyvät tulehdussairauksiin ja lihavuuteen. Mikrobiomi tutkitaan sekvensoimalla näytteen DNA ilman viljelyä. Kutsutaan myös: mikrobisto.",
  2, L('mikrobiomi', ['mikrobisto', 'mikrobiston', 'mikrobistoa', 'suolistomikrobiomi', 'suolistomikrobiomin', 'suolistomikrobisto', 'suolistomikrobiston'])),
K("Mikä on insuliini?",
  "Haiman erittämä peptidihormoni, joka laskee veren glukoosipitoisuutta. Ensimmäinen rekombinanttinen lääke.",
  "Insuliini on haiman beetasolujen tuottama pieni proteiinihormoni, joka ohjaa glukoosin soluihin ja varastoon aterian jälkeen. Sen puute tai tehottomuus aiheuttaa diabeteksen. Insuliini eristettiin 1921 ja sitä valmistettiin sian ja naudan haimasta, kunnes 1982 ihmisinsuliini tuotettiin ensimmäisenä rekombinanttiproteiinina Escherichia coli -bakteerissa. Se oli geenitekniikan ensimmäinen kaupallinen lääke ja nykyään suurtuotannon vakiotuote.",
  3, L('insuliini', ['diabetes', 'diabeteksen', 'diabetesta', 'diabeteksessa'])),
K("Mikä on aptameeri?",
  "Lyhyt yksinauhainen DNA- tai RNA-molekyyli, joka laskostuu sitomaan tiettyä kohdemolekyyliä kuin vasta-aine.",
  "Aptameeri on 20–80 nukleotidin pituinen nukleiinihappo, jonka kolmiulotteinen rakenne sitoo valikoivasti proteiinia, pienmolekyyliä tai solua. Aptameerit valitaan laboratoriossa satunnaisesta kirjastosta toistuvilla sitoutumis- ja monistuskierroksilla ilman eläimiä. Ne ovat vasta-aineita pienempiä, kemiallisesti syntetisoitavia, halpoja ja lämpöä kestäviä, joten niitä käytetään diagnostiikan tunnistusmolekyyleinä, biosensoreissa ja lääkkeiden kohdennuksessa.",
  1, L('aptameeri')),
K("Mikä on biomateriaali?",
  "Elävän kudoksen kanssa kosketuksiin tarkoitettu materiaali, kuten implantin pinnoite tai kudosteknologian tukirakenne.",
  "",
  1, L('biomateriaali')),
K("Mikä on biomuovi?",
  "Uusiutuvasta raaka-aineesta valmistettu tai biohajoava muovi, kuten maitohaposta tehty polylaktidi.",
  "Biomuovi on joko biopohjainen, valmistettu kasviperäisestä raaka-aineesta kuten tärkkelyksestä tai sokerista, tai biohajoava, jonka mikrobit pilkkovat vedeksi ja hiilidioksidiksi, tai molempia. Polylaktidi PLA tehdään fermentoimalla sokerista maitohappoa ja polymeroimalla se. Jotkin bakteerit valmistavat polyhydroksialkanoaatteja varastoaineikseen, ja ne kerätään suoraan soluista. Biomuovit korvaavat öljypohjaisia pakkauksissa ja lääketieteen implanteissa.",
  1, L('biomuovi')),
K("Mikä on biopolttoaine?",
  "Eloperäisestä raaka-aineesta valmistettu polttoaine, kuten bioetanoli sokerista tai biodiesel rasvasta.",
  "Biopolttoaine valmistetaan biomassasta, jonka hiili on sidottu ilmakehästä fotosynteesissä, joten sen polttaminen ei lisää ilmakehän hiilidioksidia nettona. Bioetanoli tehdään fermentoimalla sokeria tai tärkkelystä hiivalla tai Zymomonas-bakteerilla, biodiesel kasviöljyistä ja jäterasvoista, ja biokaasu mädättämällä jätettä. Toisen sukupolven polttoaineet käyttävät selluloosaa, jotta ne eivät kilpaile ruoan kanssa. Kutsutaan myös: bioenergia.",
  2, L('biopolttoaine', ['bioetanoli', 'bioetanolin', 'bioetanolia', 'biodiesel', 'biodieselin', 'biodieseliä', 'bioenergia', 'bioenergian', 'bioenergiaa', 'biokaasu', 'biokaasun', 'biokaasua'])),
K("Mitä kudosteknologia on?",
  "Elävän kudoksen kasvattamista soluista ja tukirakenteesta korvaamaan vaurioitunutta kudosta.",
  "Kudosteknologiassa potilaan tai kantasoluista kasvatetaan soluja biohajoavan tukirakenteen päällä, joka ohjaa ne oikeaan muotoon ja korvautuu vähitellen solujen omalla soluväliaineella. Näin on tehty ihoa palovammoihin, rustoa, virtsarakkoja ja verisuonia. Tavoitteena ovat kokonaiset siirrettävät elimet, joita 3D-biotulostus ja luovutettujen elinten solutyhjennetyt tukirangat lähestyvät. Kutsutaan myös: tissue engineering.",
  1, L('kudosteknologia')),
K("Mikä on DNA-sormenjälkitekniikka?",
  "Yksilön tunnistaminen perimän vaihtelevista toistojaksoista, esimerkiksi rikostutkinnassa ja isyystesteissä.",
  "DNA-sormenjälki perustuu genomin kohtiin, joissa lyhyt jakso toistuu yksilöllisen monta kertaa. Näytteestä monistetaan PCR:llä kymmenkunta tällaista kohtaa, ja toistojen lukumäärien yhdistelmä on käytännössä ainutlaatuinen paitsi identtisillä kaksosilla. Alec Jeffreys kehitti menetelmän 1984, ja sitä käytetään rikospaikkanäytteiden, isyyden ja vainajien tunnistamiseen sekä lajien ja lajikkeiden aitouden todentamiseen. Kutsutaan myös: DNA-tunnistus, DNA-profilointi.",
  2, L(['DNA-sormenjälkitekniikka', 'DNA-sormenjälkitekniikan', 'DNA-sormenjälkitekniikkaa', 'DNA-sormenjälki', 'DNA-sormenjäljen', 'DNA-sormenjälkeä', 'DNA-sormenjälkimenetelmä', 'DNA-sormenjälkimenetelmän', 'DNA-tunnistus', 'DNA-tunnistuksen', 'DNA-profilointi', 'DNA-profiloinnin'])),
K("Mikä on gene drive?",
  "Geenimuokkaus, joka saa geenin periytymään lähes kaikille jälkeläisille ja leviämään populaatioon.",
  "Tavallisesti jälkeläinen perii geenin toisen vaihtoehdon 50 prosentin todennäköisyydellä. Gene drive -rakenne sisältää CRISPR-koneiston, joka kopioi itsensä myös toiseen kromosomiin, joten lähes kaikki jälkeläiset kantavat sitä ja se leviää populaatiossa sukupolvi sukupolvelta. Sillä halutaan hävittää malariahyttysiä tai tehdä niistä taudille vastustuskykyisiä. Riskinä on peruuttamaton muutos luonnossa, joten kokeet ovat toistaiseksi rajattuja. Kutsutaan myös: geeniajuri.",
  1, L(['gene drive', 'gene driven', 'gene drivea', 'gene drive -tekniikka', 'geeniajuri', 'geeniajurin', 'geeniajuria'])),
K("Mitä synteettinen biologia on?",
  "Biologisten järjestelmien suunnittelua ja rakentamista osista kuin insinööritieteessä, aina keinotekoisiin genomeihin asti.",
  "Synteettinen biologia yhdistää geenitekniikan ja suunnittelun: geeneistä ja säätelyelementeistä kootaan standardiosia, joista rakennetaan uusia reaktioteitä ja piirejä soluihin. Hiivaan on siirretty malarialääke artemisiniinin koko synteesireitti, ja bakteerille on kirjoitettu kokonainen synteettinen genomi. Tekoäly suunnittelee jo proteiineja tyhjästä. Sovelluksia ovat lääkkeet, biomateriaalit, elävät sensorit ja polttoaineet.",
  1, L(['synteettinen biologia', 'synteettisen biologian', 'synteettistä biologiaa', 'synteettisessä biologiassa'])),
K("Mikä on restriktioentsyymi?",
  "Bakteerin entsyymi, joka katkaisee DNA:n tietyn lyhyen nukleoemäsjärjestyksen kohdalta.",
  "Restriktioentsyymit tunnistavat DNA:sta 4–8 emäksen jakson ja leikkaavat molemmat juosteet sen kohdalta, usein niin, että jää lyhyt yksinauhainen tarttuva pää. Bakteerit käyttävät niitä puolustuksena viruksia vastaan ja suojaavat oman DNA:nsa metyloimalla. Geenitekniikassa ne ovat sakset: samalla entsyymillä leikatut palat sopivat yhteen ja ligaasi liittää ne, minkä varaan yhdistelmä-DNA-tekniikka rakennettiin 1970-luvulla. Kutsutaan myös: restriktaasi.",
  3, L('restriktioentsyymi', ['restriktaasi', 'restriktaasin', 'restriktaasit'])),
K("Mikä on ligaasi?",
  "Entsyymi, joka liittää kaksi DNA-päätä yhteen fosfodiesterisidoksella ATP:n energialla.",
  "DNA-ligaasi muodostaa fosfodiesterisidoksen yhden DNA-ketjun 3'-hydroksyylin ja toisen 5'-fosfaatin väliin ja sulkee näin katkoksen. Solussa se liittää replikaation Okazakin fragmentit ja korjaa katkenneen DNA:n. Geenitekniikassa ligaasi liimaa restriktioentsyymillä leikatun geenin vektoriin, jolloin syntyy yhdistelmä-DNA. Yleisimmin käytetään T4-bakteriofagin ligaasia. Muut ligaasit liittävät esimerkiksi aminohappoja siirtäjä-RNA:han tai rakentavat rasvahappoja.",
  3, L('ligaasi', ['DNA-ligaasi', 'DNA-ligaasin', 'DNA-ligaasia'])),
K("Mikä on patentti?",
  "Keksijälle myönnetty määräaikainen yksinoikeus keksinnön kaupalliseen hyödyntämiseen.",
  "Patentti antaa keksijälle tavallisesti 20 vuoden yksinoikeuden käyttää keksintöään ja kieltää muilta sen käytön vastineeksi siitä, että keksintö julkaistaan. Biotekniikassa patentoidaan menetelmiä, kuten PCR ja CRISPR, muokattuja organismeja ja proteiineja, ja lääkkeen kehityskulut katetaan patentin suojassa. Kiistanalaisia ovat olleet geenien patentointi ja se, kuka omistaa CRISPR-tekniikan. Kun patentti raukeaa, syntyy biosimilaareja ja rinnakkaisvalmisteita.",
  1, L('patentti', ['patentointi', 'patentoinnin', 'patentointia', 'patentoida', 'patentoitu'])),
K("Mitä kasvinjalostus on?",
  "Viljelykasvien perinnöllisten ominaisuuksien parantamista valitsemalla ja risteyttämällä, nykyään myös geenimuokkauksella.",
  "Kasvinjalostuksessa parhaita yksilöitä valitaan ja risteytetään sukupolvi sukupolvelta, jotta sato, kestävyys ja laatu paranevat. Sitä on tehty maanviljelyn alusta, ja se muutti villit heinät vehnäksi ja maissiksi. Moderni jalostus käyttää mutaatioiden aikaansaamista, solukkoviljelyä, merkkigeenejä ja geeninsiirtoa. Muuntogeeniset lajikkeet kestävät tuhohyönteisiä tai rikkakasvimyrkkyä, ja CRISPR mahdollistaa täsmämuutokset ilman vierasta DNA:ta. Kutsutaan myös: jalostus.",
  2, L('kasvinjalostus', ['jalostus', 'jalostuksen', 'jalostusta', 'jalostuksessa', 'jalostaa', 'jalostettu', 'jalostetut', 'lajike', 'lajikkeen', 'lajiketta', 'lajikkeet', 'lajikkeita'])),
K("Mikä on tekoäly biotekniikassa?",
  "Koneoppimismalli, joka ennustaa esimerkiksi proteiinin rakenteen sekvenssistä (AlphaFold) tai suunnittelee uusia proteiineja.",
  "Tekoäly oppii suurista aineistoista säännönmukaisuuksia, joita ihminen ei erota. AlphaFold ennusti 2020 proteiinin kolmiulotteisen rakenteen aminohappojärjestyksestä kokeellista tarkkuutta lähestyen ja ratkaisi 50 vuotta avoinna olleen ongelman, mistä myönnettiin Nobelin kemianpalkinto 2024. Mallit suunnittelevat nyt entsyymejä ja vasta-aineita tyhjästä, seulovat lääkeaineita ja tulkitsevat sekvensointi- ja kuvantamisdataa. Kutsutaan myös: koneoppiminen.",
  1, L(['tekoäly', 'tekoälyn', 'tekoälyä', 'tekoälyllä', 'AlphaFold', 'AlphaFoldin', 'koneoppiminen', 'koneoppimisen', 'koneoppimista'])),
K("Mitä on sirppisoluanemia?",
  "Perinnöllinen sairaus, jossa hemoglobiinin yhden aminohapon mutaatio vääntää punasolut sirpin muotoisiksi.",
  "Sirppisoluanemiassa hemoglobiinin beetaketjun kuudes aminohappo, glutamaatti, on vaihtunut valiiniksi yhden nukleotidin mutaation vuoksi. Hapeton hemoglobiini tarttuu toisiinsa säikeiksi, jotka vääntävät punasolun sirpiksi, ja jäykät solut tukkivat hiussuonia ja hajoavat. Tauti oli ensimmäinen molekyylitasolla selitetty perinnöllinen sairaus, ja siihen hyväksyttiin vuonna 2023 maailman ensimmäinen CRISPR-pohjainen geeniterapia.",
  1, L('sirppisoluanemia')),
K("Mikä on vitamiini?",
  "Pieninä määrinä välttämätön orgaaninen ravintoaine, jota elimistö ei itse valmista riittävästi. Monet ovat koentsyymien osia.",
  "",
  2, L('vitamiini')),
K("Mikä on amylaasi?",
  "Tärkkelystä pilkkova entsyymi, jota on syljessä, haimassa ja monissa mikrobeissa.",
  "Amylaasi katkaisee tärkkelyksen ja glykogeenin glukoosiyksiköiden välisiä alfa-glykosidisidoksia ja tuottaa maltoosia ja lyhyitä sokeriketjuja. Ihmisellä sylki- ja haima-amylaasi aloittavat tärkkelyksen ruoansulatuksen. Takamine eristi vuonna 1894 homeen amylaasin, joka oli ensimmäinen patentoitu mikrobientsyymi. Teollisuudessa amylaaseilla nesteytetään tärkkelys glukoosisiirapiksi, tehdään olutta, leipää ja kaurajuomia sekä poistetaan tärkkelystahroja pesuaineissa.",
  2, L('amylaasi')),
], )

L2 = dict(LEHTI='Luento 2 - Proteiinit biotekniikassa', TIEDOSTO='Luento 2 - Sanasto (lisays)', NRO=2, ALKU=100, KUVAT={}, KORTIT=[
K("Mitä translaation jälkeinen muokkaus tarkoittaa?",
  "Proteiinin kemiallista muokkausta synteesin jälkeen: glykosylaatiota, fosforylaatiota, leikkausta tai lipidin liittämistä.",
  "Ribosomilta tuleva polypeptidi ei ole vielä valmis. Siihen liitetään sokeriketjuja, fosfaatteja, lipidejä tai muita ryhmiä, siitä leikataan osia, kuten signaalipeptidi tai insuliinin keskiosa, ja kysteiinien välille tehdään disulfidisiltoja. Muokkaukset ohjaavat laskostumista, paikkaa, aktiivisuutta ja elinikää. Bakteerit eivät osaa useimpia eukaryoottien muokkauksia, minkä vuoksi monet lääkeproteiinit on tuotettava nisäkässoluissa. Kutsutaan myös: post-translationaalinen modifikaatio.",
  3, L(['translaation jälkeinen muokkaus', 'translaation jälkeisen muokkauksen', 'translaation jälkeistä muokkausta', 'translaation jälkeiset muokkaukset', 'translaation jälkeisiä muokkauksia', 'post-translationaalinen muokkaus', 'post-translationaalisen muokkauksen', 'post-translationaaliset muokkaukset', 'posttranslationaalinen', 'posttranslationaaliset', 'post-translationaalinen modifikaatio', 'post-translationaaliset modifikaatiot'])),
K("Mitä denaturaatio tarkoittaa?",
  "Proteiinin luonnollisen laskostuneen rakenteen purkautumista ja toiminnan menetystä esimerkiksi kuumennettaessa.",
  "Denaturaatiossa proteiinin sekundaari- ja tertiaarirakennetta ylläpitävät heikot sidokset katkeavat, ketju aukeaa ja proteiini menettää toimintansa. Sen aiheuttavat lämpö, äärimmäinen pH, detergentit, orgaaniset liuottimet ja voimakas sekoitus. Kananmunan valkuaisen hyytyminen on denaturaatiota. Denaturoituneet proteiinit tarttuvat toisiinsa ja saostuvat, joten proteiinituotteita käsitellään kylmässä ja varoen. Joskus laskostuminen palautuu, kun olot normalisoituvat.",
  3, L('denaturaatio', ['denaturoitua', 'denaturoituu', 'denaturoituvat', 'denaturoitunut', 'denaturoituneen', 'denaturoituneita', 'denaturoida', 'denaturoitu'])),
K("Mitä dialyysi on?",
  "Pienten molekyylien erottaminen suurista puoliläpäisevän kalvon läpi diffuusiolla.",
  "Dialyysissä proteiiniliuos suljetaan kalvopussiin, jonka huokoset päästävät läpi suolat ja pienet molekyylit mutta eivät proteiineja, ja pussi pannaan suureen määrään puskuria. Pienet molekyylit diffundoituvat ulos, kunnes pitoisuudet tasoittuvat, ja puskuria vaihtamalla proteiini saadaan haluttuun liuokseen. Menetelmällä poistetaan saostukseen käytetty ammoniumsulfaatti. Munuaisten dialyysihoito perustuu samaan ilmiöön: veri puhdistetaan kalvon läpi.",
  2, L('dialyysi')),
K("Mikä on biomassa?",
  "Eliöiden tuottama eloperäinen aines, kuten kasvatuksen solumassa tai polttoaineeksi kerätty kasviaines.",
  "",
  2, L('biomassa')),
K("Mikä on bioprosessi?",
  "Teollinen prosessi, jossa eläviä soluja tai entsyymejä käytetään tuotteen valmistamiseen.",
  "",
  2, L('bioprosessi', 'biokonversio')),
K("Mikä on kontaminaatio?",
  "Vieraan mikrobin tai aineen pääsy kasvatukseen tai näytteeseen.",
  "Fermentoinnissa kontaminaatio tarkoittaa, että kasvatukseen pääsee toinen mikrobi, joka kilpailee ravinteista, tuottaa haitallisia aineita tai pilkkoo tuotteen. Pitkät kasvatukset ja hitaasti kasvavat nisäkässolut ovat alttiimpia. Kontaminaatio torjutaan steriloimalla fermentori ja elatusaine autoklaavissa, suodattamalla tulo- ja lähtöilma ja työskentelemällä aseptisesti. Diagnostiikassa kontaminaatio antaa vääriä tuloksia, ja elintarvikkeissa se on turvallisuusriski.",
  2, L('kontaminaatio', ['kontaminoitua', 'kontaminoituu', 'kontaminoitunut', 'kontaminoituneen'])),
K("Mitä sterilointi on?",
  "Kaikkien mikrobien ja itiöiden tuhoaminen, tavallisesti autoklaavissa 121 °C:n paineistetulla höyryllä 20 minuuttia.",
  "Sterilointi eroaa desinfioinnista siinä, että se tuhoaa myös kestävät bakteeri-itiöt. Autoklaavi on paineastia, jossa vesihöyry kuumennetaan 121 asteeseen, mikä denaturoi kaikkien mikrobien proteiinit noin 20 minuutissa. Fermentorit, elatusaineet ja välineet autoklavoidaan ennen kasvatusta. Lämpöherkät liuokset steriloidaan suodattamalla 0,2 mikrometrin kalvon läpi, ja ilma suodattimilla. Kutsutaan myös: autoklaavaus.",
  2, L('sterilointi', ['autoklaavi', 'autoklaavin', 'autoklaavia', 'autoklaavissa', 'autoklaavaus', 'autoklaavauksen', 'autoklavointi', 'autoklavoida', 'autoklaavaamalla', 'steriili', 'steriilin', 'steriiliä', 'steriilit', 'steriilissä', 'steriloida', 'steriloidaan', 'steriloitu'])),
K("Mikä on petrimalja?",
  "Matala kannellinen lasi- tai muovimalja, jossa mikrobeja kasvatetaan kiinteällä agar-alustalla.",
  "",
  1, L('petrimalja', ['ravistelupullo', 'ravistelupullon', 'ravistelupulloa', 'ravistelupullot', 'ravistelupulloissa', 'agar', 'agarin', 'agaria', 'agarmalja', 'agarmaljan'])),
K("Mikä on ligandi?",
  "Molekyyli, joka sitoutuu spesifisesti toiseen molekyyliin, kuten reseptoriin tai kromatografiageeliin kiinnitettyyn vasta-aineeseen.",
  "Ligandi on sitoutuva osapuoli: hormoni on reseptorinsa ligandi, substraatti entsyymin ja antigeeni vasta-aineen. Affiniteettikromatografiassa geeliin kiinnitetty ligandi, esimerkiksi vasta-aine tai metalli-ioni, pidättää vain siihen sitoutuvan proteiinin. Kemiassa ligandi on keskusatomiin sitoutunut atomi tai ryhmä, kuten hemin rautaa ympäröivät typet. Sitoutumisen voimakkuutta kuvaa affiniteetti eli kuinka tiukasti pari pysyy yhdessä.",
  2, L('ligandi', ['affiniteetti', 'affiniteetin', 'affiniteettia', 'affiniteetilla'])),
K("Mikä on CHO-solu?",
  "Kiinanhamsterin munasarjasolulinja, yleisin nisäkässolu terapeuttisten proteiinien tuottoon.",
  "CHO-solut, Chinese hamster ovary, ovat 1950-luvulla eristetty solulinja, joka kasvaa suspensiossa bioreaktoreissa, sietää muokkausta ja tekee ihmisen kaltaisen glykosylaation. Yli puolet terapeuttisista proteiineista, kuten useimmat monoklonaaliset vasta-aineet, tuotetaan CHO-soluissa. Kasvatus on kallista ja hidasta bakteereihin verrattuna, mutta oikea laskostuminen ja sokerointi vaativat nisäkässolun. Kutsutaan myös: nisäkässolulinja.",
  2, L(['CHO-solu', 'CHO-solun', 'CHO-solua', 'CHO-solut', 'CHO-solujen', 'CHO-soluja', 'CHO-soluissa', 'nisäkässolu', 'nisäkässolun', 'nisäkässolua', 'nisäkässolut', 'nisäkässolujen', 'nisäkässoluja', 'nisäkässoluissa', 'solulinja', 'solulinjan', 'solulinjaa', 'solulinjat'])),
K("Mikä on kasvutekijä?",
  "Proteiini, joka sitoutuu solun reseptoriin ja käskee solua jakautumaan, kasvamaan tai erilaistumaan.",
  "Kasvutekijät ovat viestiproteiineja, jotka ohjaavat solujen jakautumista ja erilaistumista. Erytropoietiini kiihdyttää punasolujen tuotantoa, ja sitä annetaan munuaispotilaille, kasvuhormoni ohjaa kasvua ja epidermaalinen kasvutekijä haavan paranemista. Ylitoimiva kasvutekijäreseptori, kuten HER2 rintasyövässä, ajaa syöpäsolujen jakautumista, ja siihen kohdistuvat vasta-aineet ovat syöpälääkkeitä. Kasvutekijöitä tuotetaan rekombinantisti nisäkässoluissa tai bakteereissa.",
  2, L('kasvutekijä', ['kasvuhormoni', 'kasvuhormonin', 'kasvuhormonia', 'erytropoietiini', 'erytropoietiinin'])),
K("Mikä on sytokiini?",
  "Immuunijärjestelmän solujen erittämä pieni viestiproteiini, kuten interferoni tai interleukiini.",
  "Sytokiinit välittävät viestejä immuunisolujen välillä ja säätelevät tulehdusta ja immuunivastetta. Interferonit ovat virusinfektion hälytysmerkkejä ja hidastavat virusten lisääntymistä, interleukiinit ohjaavat valkosolujen kasvua ja aktivoitumista, ja tuumorinekroositekijä ajaa tulehdusta. Rekombinantit sytokiinit ovat lääkkeitä, kuten interferoni MS-tautiin, ja sytokiineja estävät vasta-aineet hoitavat nivelreumaa ja psoriaasia. Sytokiinimyrsky on hallitsematon sytokiinien vapautuminen.",
  2, L('sytokiini', 'interferoni', 'interleukiini')),
K("Mikä on hyytymistekijä?",
  "Veren proteiini, joka osallistuu veren hyytymisen reaktioketjuun. Hemofiliassa jokin niistä puuttuu.",
  "Veren hyytyminen on proteaasien ketju, jossa kukin hyytymistekijä aktivoi seuraavan, ja lopulta trombiini muuttaa fibrinogeenin fibriiniverkoksi. Hemofiliassa tekijä VIII tai IX puuttuu, ja potilas saa rekombinanttia hyytymistekijää, joka korvasi luovutetusta verestä eristetyt valmisteet. Antikoagulantit, kuten hepariini ja apiksabaani, estävät hyytymistä, ja trombolyyttiset proteiinit, kuten kudosplasminogeeniaktivaattori, liuottavat sydäninfarktin ja aivoveritulpan hyytymän.",
  2, L('hyytymistekijä', 'antikoagulantti', ['trombolyytti', 'trombolyytin', 'trombolyytit', 'trombolyyttinen', 'trombolyyttisen', 'trombolyyttiset', 'hemofilia', 'hemofilian', 'hemofiliaa'])),
K("Mikä on fuusioproteiini?",
  "Yhdeksi molekyyliksi liitetty kahden proteiinin yhdistelmä, jonka geeni on koottu kahden geenin osista.",
  "Fuusioproteiini valmistetaan liittämällä kahden geenin koodaavat alueet peräkkäin, jolloin solu tuottaa yhden polypeptidin, jossa on molempien osat. Lääkkeissä esimerkiksi reseptorin sitova osa on liitetty vasta-aineen häntään, joka pidentää elinikää veressä. Tutkimuksessa proteiiniin liitetään vihreä fluoresoiva proteiini, jotta sen paikka solussa nähdään, tai histidiinihäntä, jolla se puhdistetaan affiniteettikromatografialla. Syövissä kromosomien katkokset synnyttävät haitallisia fuusioproteiineja.",
  2, L('fuusioproteiini')),
K("Mikä on seerumi?",
  "Veren nestemäinen osa ilman soluja ja hyytymistekijöitä. Immunisoidun eläimen seerumista eristetään vasta-aineita.",
  "",
  2, L('seerumi', ['antiseerumi', 'antiseerumin', 'antiseerumia'])),
K("Mikä on autoimmuunisairaus?",
  "Sairaus, jossa immuunijärjestelmä hyökkää elimistön omia kudoksia vastaan, kuten tyypin 1 diabetes tai nivelreuma.",
  "Autoimmuunisairaudessa puolustus menettää kykynsä erottaa oma vieraasta ja tuottaa vasta-aineita tai T-soluja omia rakenteita vastaan. Tyypin 1 diabeteksessa tuhoutuvat haiman insuliinisolut, nivelreumassa nivelkalvot, MS-taudissa hermojen myeliini ja keliakiassa suolen limakalvo. Hoidoksi käytetään tulehdusta estäviä terapeuttisia vasta-aineita, jotka neutraloivat sytokiineja tai estävät immuunisolujen toimintaa, sekä puuttuvan hormonin korvausta.",
  2, L('autoimmuunisairaus')),
K("Mikä on toksiini?",
  "Eliön tuottama myrkyllinen aine, kuten bakteerin erittämä proteiini, joka vaurioittaa isäntää.",
  "Bakteeritoksiinit ovat usein proteiineja: jäykkäkouristus- ja botuliinitoksiini lamauttavat hermoja, koleratoksiini avaa suolen kloridikanavat ja difteriatoksiini pysäyttää proteiinisynteesin. Endotoksiini on gram-negatiivisen ulkokalvon lipopolysakkaridi, joka laukaisee kuumeen. Sinilevät tuottavat maksa- ja hermotoksiineja uimaveteen kesän kukinnoissa. Inaktivoidusta toksiinista tehdään toksoidirokote, ja toksiineja vastaan tehdään terapeuttisia vasta-aineita, kuten käärmeenpureman vastamyrkky.",
  2, L('toksiini', ['endotoksiini', 'endotoksiinin', 'endotoksiinit', 'sinilevätoksiini', 'sinilevätoksiinin', 'sinilevätoksiinit', 'sinilevätoksiineja'])),
K("Mikä on lipidinanopartikkeli?",
  "Muutaman kymmenen nanometrin lipidipallo, jonka sisällä lähetti-RNA kuljetetaan soluihin.",
  "",
  2, L('lipidinanopartikkeli')),
K("Mikä on biokatalyytti?",
  "Entsyymi tai kokonainen solu, jota käytetään teollisen reaktion katalyyttinä.",
  "Biokatalyytti on entsyymi, joko liukoisena, immobilisoituna tai elävän solun sisällä, joka katalysoi tuotteen synteesiä teollisessa mittakaavassa. Se toimii miedoissa oloissa, on selektiivinen ja stereospesifinen eikä tuota sivutuotteita, mutta sietää huonosti kuumuutta ja orgaanisia liuottimia. Enantioselektiivisyys tekee biokatalyyteistä tärkeitä lääkeaineiden synteesissä, jossa vain toinen peilikuvamuoto kelpaa. Kutsutaan myös: biokatalyysi.",
  2, L('biokatalyytti', ['biokatalyysi', 'biokatalyysin', 'biokatalyysiä', 'enantioselektiivisyys', 'enantioselektiivisyyden', 'enantioselektiivinen', 'enantioselektiivisen', 'stereospesifisyys', 'stereospesifisyyden', 'stereospesifinen', 'stereospesifisen', 'selektiivisyys', 'selektiivisyyden', 'selektiivinen', 'selektiivisen'])),
K("Mikä on sellulaasi?",
  "Selluloosaa pilkkova entsyymi, jota sienet ja bakteerit tuottavat ja jota käytetään mehun, paperin ja tekstiilien käsittelyssä.",
  "",
  2, L('sellulaasi')),
K("Mikä on lipaasi?",
  "Rasvoja pilkkova entsyymi, joka katkaisee triglyseridin esterisidokset rasvahapoiksi ja glyseroliksi.",
  "",
  2, L('lipaasi')),
K("Mikä on laktaasi?",
  "Laktoosin glukoosiksi ja galaktoosiksi pilkkova entsyymi. Sen puute aikuisilla on laktoosi-intoleranssi.",
  "",
  2, L('laktaasi', ['laktoosi-intoleranssi', 'laktoosi-intoleranssin', 'laktoosi-intoleranssia'])),
K("Mikä on kymosiini?",
  "Juuston juoksutuksessa käytetty proteaasi, joka saostaa maidon kaseiinin. Tuotetaan nykyään mikrobeissa.",
  "",
  1, L('kymosiini', ['renniini', 'renniinin', 'renniiniä', 'juoksute', 'juoksutteen', 'juoksutetta'])),
K("Mikä on pektinaasi?",
  "Kasvien soluseinän pektiiniä pilkkova entsyymi, joka kirkastaa mehua ja viiniä ja parantaa saantoa.",
  "",
  1, L('pektinaasi', ['pektiini', 'pektiinin', 'pektiiniä', 'ksylanaasi', 'ksylanaasin', 'ksylanaasit', 'ksylanaaseja'])),
K("Mikä on ligniini?",
  "Puun soluseinän kova aromaattinen polymeeri, joka sitoo selluloosakuidut yhteen ja on poistettava paperimassasta.",
  "",
  1, L('ligniini')),
K("Mikä on kofaktori teollisessa biokatalyysissä?",
  "Entsyymin tarvitsema apuaine, kuten NADH, jonka hinta ja kierrätys rajoittavat entsyymiprosessien käyttöä.",
  "",
  1),
])

L3 = dict(LEHTI='Luento 3 - In vitro -diagnostiikka, immunomääritykset', TIEDOSTO='Luento 3 - Sanasto (lisays)', NRO=3, ALKU=100, KUVAT={}, KORTIT=[
K("Mitä kalibrointi tarkoittaa?",
  "Mittauksen sitomista tunnettuun vertailuun: standardien avulla signaali muunnetaan pitoisuudeksi.",
  "",
  2, L('kalibrointi', ['kalibroida', 'kalibroidaan', 'kalibroitu'])),
K("Mikä on laimennossarja?",
  "Sarja liuoksia, joissa kantaliuosta laimennetaan askeleittain tunnetuiksi pitoisuuksiksi, esimerkiksi standardisuoraa varten.",
  "",
  2, L('laimennossarja', ['laimennos', 'laimennoksen', 'laimennosta', 'laimennokset', 'laimennoksia', 'laimentaa', 'laimennetaan', 'laimennettu'])),
K("Mikä on reagenssi?",
  "Määrityksessä tai reaktiossa käytettävä tunnettu aine, kuten leimattu vasta-aine tai substraatti.",
  "",
  2, L('reagenssi')),
K("Mitä fluoresenssi on?",
  "Valon säteilyä, jonka molekyyli lähettää heti absorboituaan lyhyempiaaltoista valoa.",
  "Fluoresoiva molekyyli absorboi fotonin, virittyy ja palaa perustilaan lähettämällä fotonin, jonka aallonpituus on pidempi kuin absorboidun, koska osa energiasta on kulunut lämmöksi. Säteily lakkaa heti, kun viritys loppuu. Immunomäärityksissä fluoresoiva leima kiinnitetään vasta-aineeseen ja mitataan tietyn värisellä valolla virittäen. Fluoresenssimikroskopia ja virtaussytometria perustuvat samaan, ja vihreä fluoresoiva proteiini näyttää proteiinin paikan solussa.",
  2, L('fluoresenssi', ['fluoresoiva', 'fluoresoivan', 'fluoresoivaa', 'fluoresoivat', 'fluoresoida', 'fluoresoi', 'fluoroforikin', 'fluorofori', 'fluoroforin', 'fluoroforit'])),
K("Mikä on nanopartikkeli?",
  "Muutamasta nanometristä sataan nanometriin oleva hiukkanen, jota käytetään leimana ja lääkkeen kantajana.",
  "",
  2, L('nanopartikkeli')),
K("Mitä mikrofluidiikka on?",
  "Nesteiden käsittelyä hiuksenohuissa kanavissa sirulla, jolloin koko määritys mahtuu pieneen laitteeseen.",
  "Mikrofluidiikassa nesteitä liikutellaan kymmenien mikrometrien levyisissä kanavissa, joissa virtaus on tasaista ja pintavoimat hallitsevat. Näytettä ja reagenssia tarvitaan mikrolitroja, reaktiot ovat nopeita lyhyiden diffuusiomatkojen vuoksi, ja sekoitus, inkubointi, pesu ja mittaus voidaan tehdä samalla sirulla. Näin rakennetaan vieritestejä ja lab-on-a-chip-laitteita, joissa laboratorion työvaiheet on pakattu kämmenen kokoon. Kutsutaan myös: lab-on-a-chip.",
  1, L('mikrofluidiikka', ['mikrofluidistinen', 'mikrofluidistisen', 'mikrofluidistiset', 'mikrofluidistisia', 'lab-on-a-chip', 'lab-on-a-chip-laite', 'lab-on-a-chip-laitteen'])),
K("Mitä seulonta tarkoittaa diagnostiikassa?",
  "Oireettoman väestön tutkimista taudin tai riskin löytämiseksi varhain, kuten vastasyntyneiden ja syöpäseulonnat.",
  "",
  2, L('seulonta', ['seulontatesti', 'seulontatestin', 'seulontatestit', 'seulontatestejä', 'seuloa', 'seulotaan'])),
K("Mikä on troponiini?",
  "Sydänlihaksen proteiini, jonka nousu veressä on sydäninfarktin merkkiaine.",
  "",
  1, L('troponiini')),
K("Mikä on C-reaktiivinen proteiini?",
  "Maksan tulehduksen aikana erittämä proteiini, jonka pitoisuus veressä kertoo tulehduksen voimakkuudesta. Mitataan CRP-pikatestillä.",
  "",
  1, L(['C-reaktiivinen proteiini', 'C-reaktiivisen proteiinin', 'C-reaktiivista proteiinia', 'CRP', 'CRP:n', 'CRP:tä', 'CRP-pikatesti', 'CRP-pikatestin', 'tulehdusmerkkiaine', 'tulehdusmerkkiaineen', 'tulehdusmerkkiainetta'])),
K("Mikä on transaminaasi?",
  "Aminoryhmän siirtävä entsyymi, jonka määrä veressä kertoo maksasolujen vauriosta.",
  "",
  1, L('transaminaasi')),
K("Mikä on glukoosioksidaasi?",
  "Entsyymi, joka hapettaa glukoosin ja jonka reaktiota käytetään veren glukoosimittareissa.",
  "",
  1, L('glukoosioksidaasi')),
K("Mikä on hormonipitoisuuden määritys?",
  "Immunomääritys, jossa hormonin, kuten kilpirauhashormonin tai istukkahormonin, pitoisuus näytteessä mitataan vasta-aineella.",
  "",
  2),
])
