# -*- coding: utf-8 -*-
"""Johdatus biotekniikkaan, Luento 2 - Proteiinit biotekniikassa. Osa 1: proteiinien kayttosovelluksia
(Aihe2_proteiinit biotekniikassa sovelluksia.pdf), osa 2: proteiinien tuotto (Aihe2_Proteiinit biotekniikassa
proteeinien tuotto.pdf). Rakentaa tyokalut/biotek_kortit.py."""
from biotek_taivutus import L

def K(q, s, l, tt, links='', kuva=None):
    return {'q': q, 's': s, 'l': l, 'tt': str(tt), 'ls': links, 'kuva': kuva}

LEHTI = 'Luento 2 - Proteiinit biotekniikassa'
NRO = 2
KUVAT = {   # tiedosto -> (pdf, sivu, 'sivu' = renderoi koko dia | 'kuva' = dian suurin kuva)
    'biotek_fermentori.png':  ('Aihe2_Proteiinit biotekniikassa proteeinien tuotto.pdf', 24, 'sivu'),
    'biotek_kasvukayra.jpg':  ('Aihe2_Proteiinit biotekniikassa proteeinien tuotto.pdf', 31, 'kuva'),
    'biotek_erottelu.jpg':    ('Aihe2_Proteiinit biotekniikassa proteeinien tuotto.pdf', 44, 'kuva'),
    'biotek_igg.png':         ('Aihe2_proteiinit biotekniikassa sovelluksia.pdf', 12, 'kuva'),
}

KORTIT = [
# ── Osa 1: proteiinit tyokaluna ja kohteena ─────────────────────────────────────────────
K("Millä kahdella tavalla proteiinit liittyvät biotekniikkaan?",
  "Proteiinit ovat biotekniikan työkaluja ja sen kohteita.",
  "Työkaluina proteiinit valjastetaan töihin: entsyymit katalysoivat teollisia reaktioita ja vasta-aineet tunnistavat molekyylejä diagnostiikassa ja hoidossa. Kohteina luonnollisia proteiineja muokataan rekombinantti-DNA-tekniikalla paremmin tehtäväänsä sopiviksi ja tehokkaammiksi. Molemmissa keskeinen haaste on sama: proteiinia on saatava tuotettua riittävän puhtaana ja riittäviä määriä, jotta kaupallinen sovellus on mahdollinen. Esimerkiksi pesuaineen proteaasi on työkalu, ja sen muokkaaminen kestämään kuumaa pesua tekee siitä kohteen.",
  3),
K("Mitkä ovat proteiinien kolme pääsovellusaluetta biotekniikassa?",
  "Lääkinnälliset proteiinit ja vasta-aineet, rokotteet sekä entsyymit ja entsyymireaktorit.",
  "Lääkinnälliset proteiinit, kuten insuliini ja terapeuttiset vasta-aineet, ovat biologisia lääkkeitä. Rokotteissa proteiinit ovat antigeeneja, jotka opettavat immuunipuolustuksen tunnistamaan taudinaiheuttajan. Entsyymit toimivat teollisuuden biokatalyytteinä joko liukoisina tai reaktoriin sidottuina. Kaikissa kolmessa tuotanto nojaa samaan kysymykseen: miten proteiinia tuotetaan puhtaana ja suuria määriä. Osa proteiineista on samalla myös kohteita, joita muokataan rekombinantti-DNA-tekniikalla paremmin tehtäväänsä sopiviksi.",
  3),
K("Mikä on biologinen lääke?",
  "Elävistä soluista tuotettu lääke, yleensä proteiini, joka on tavallista lääkemolekyyliä paljon suurempi ja monimutkaisempi.",
  "Biologinen lääke valmistetaan elävissä soluissa, ei kemiallisesti syntetisoimalla. Se on tyypillisesti proteiini, kuten vasta-aine, hormoni tai entsyymi, joka on satoja kertoja tavallista lääkemolekyyliä suurempi ja rakenteeltaan herkkä. Biologisia lääkkeitä myytiin Yhdysvalloissa yli 300 miljardin dollarin arvosta vuonna 2020, ja ne ovat jo yli kolmannes kliinisissä tutkimuksissa olevista lääkkeistä. Kutsutaan myös: biolääke, biologinen lääkevalmiste.",
  3, L('biologinen lääke', ['biologisen lääkkeen', 'biologista lääkettä', 'biologisessa lääkkeessä', 'biologiseen lääkkeeseen', 'biologiset lääkkeet', 'biologisten lääkkeiden', 'biologisia lääkkeitä', 'biolääke', 'biolääkkeen', 'biolääkettä', 'biolääkkeet', 'biolääkkeitä'])),
K("Millä viidellä tavalla lääkinnällinen proteiini voi vaikuttaa?",
  "Korvaa puuttuvan proteiinin, tehostaa reaktiotietä, tuo uuden toiminnon, estää toiminnan tai kuljettaa yhdisteitä.",
  "Lääkinnällinen proteiini voi ensinnäkin korvata puuttuvan tai viallisen proteiinin, kuten insuliini diabeteksessa tai hyytymistekijä hemofiliassa. Se voi tehostaa elimistön omaa reaktiotietä, kuten kasvutekijät, tai tuoda kokonaan uuden toiminnon, kuten hyytymiä liuottavat entsyymit. Vasta-aineet estävät kohdemolekyylin tai taudinaiheuttajan toiminnan, ja kuljettajaproteiinit vievät lääkeaineen tai myrkyn kohdesoluihin.",
  2),
K("Millaisia lääkinnällisiä proteiineja on markkinoilla?",
  "Vasta-aineita, hormoneja, kasvutekijöitä, fuusioproteiineja, sytokiineja, veren hyytymistekijöitä, antikoagulantteja, trombolyyttejä ja rokotteita.",
  "Suurin ryhmä on vasta-aineet. Hormoneista tunnetuimmat ovat insuliini ja kasvuhormoni, ja kasvutekijät ohjaavat esimerkiksi verisolujen muodostusta. Sytokiineihin kuuluvat interferonit ja interleukiinit, jotka säätelevät immuunivastetta. Veren komponentteja ovat hyytymistekijät, ja niiden vastakohtana antikoagulantit estävät hyytymistä ja trombolyyttiset proteiinit liuottavat hyytymiä. Fuusioproteiinissa kaksi proteiinia on yhdistetty yhdeksi molekyyliksi. Ryhmän myynti oli 60 miljardia dollaria jo vuonna 2010.",
  2),
# ── Vasta-aineet ────────────────────────────────────────────────────────────────────────
K("Mikä on immunoglobuliini?",
  "Selkärankaisten immuunipuolustuksen tuottama vasta-aineproteiini, jota on veressä ja kudosnesteissä.",
  "Immunoglobuliinit ovat vasta-aineiden proteiiniperhe. Ne koostuvat pallomaisista alayksiköistä, ja niitä on viisi isotyyppiä, jotka eroavat molekyylikooltaan, rakenteeltaan, varaukseltaan, aminohappokoostumukseltaan, hiilihydraattipitoisuudeltaan, toiminnaltaan, sijainniltaan ja alaluokiltaan. Biotekniikan sovelluksissa yleisin on IgG, noin 15 nm kokoinen Y:n muotoinen molekyyli, jonka kahdessa haarassa on antigeenia sitovat kohdat. Kuvassa on IgG-molekyylin pinta, ja vihreällä sen kaksi antigeenia sitovaa paratooppia haarojen kärjissä.",
  2, L('immunoglobuliini', ['IgG', 'IgG:n', 'IgG:tä', 'IgG:ta']), 'biotek_igg.png'),
K("Mikä on vasta-aineen biologinen tehtävä?",
  "Tunnistaa vieras rakenne eli antigeeni, estää sen toiminta ja aktivoida muu immuunipuolustus tuhoamaan se.",
  "Vasta-aine tarttuu elimistölle vieraaseen rakenteeseen, esimerkiksi bakteerin tai viruksen pintamolekyyliin. Sitoutuminen estää haitallisen molekyylin tai organismin toiminnan ja merkitsee sen tuhottavaksi: vasta-aineen häntäosa aktivoi fagosyytit, jotka nielevät kohteen, ja komplementtijärjestelmän, joka puhkaisee sen. Tehtävä jakautuu siis kahtia, tunnista ja tuhoa, ja biotekniikka hyödyntää ennen kaikkea tunnistusosaa.",
  3),
K("Mikä on epitooppi?",
  "Antigeenin pinnan alue, johon vasta-aine sitoutuu.",
  "Epitooppi on antigeenin pinnalla oleva tietynmuotoinen rakenne, jonka vasta-aine tunnistaa. Yksi vasta-aine sitoutuu vain omaan epitooppiinsa, mutta samassa antigeenissa on yleensä useita erilaisia epitooppeja, joihin eri vasta-aineet sitoutuvat. Jos kahdessa eri molekyylissä on samanlainen epitooppi, vasta-aine sitoutuu molempiin, mitä kutsutaan ristireaktioksi. Kutsutaan myös: antigeeninen determinantti.",
  3, L('epitooppi')),
K("Mikä on paratooppi?",
  "Vasta-aineen rakenneosa, joka sitoutuu epitooppiin.",
  "Paratooppi on vasta-aineen antigeenia sitova kohta, joka sijaitsee Y:n muotoisen molekyylin haarojen kärjissä. Sen muoto ja pinnan ominaisuudet sopivat epitooppiin kuin avain lukkoon, ja sitoutuminen tapahtuu monilla heikoilla ei-kovalenttisilla vuorovaikutuksilla. Koska molemmissa haaroissa on paratooppi, yksi vasta-aine voi sitoa kaksi antigeenimolekyyliä. Paratoopin muodostavat raskaan ja kevyen ketjun vaihtelevat alueet, joiden aminohappojärjestys eroaa vasta-aineesta toiseen.",
  2, L('paratooppi')),
K("Mikä on ristireaktio?",
  "Vasta-aineen sitoutuminen myös toiseen molekyyliin, jossa on samanlainen epitooppi.",
  "Ristireaktiossa vasta-aine tunnistaa epitoopin, joka esiintyy kahdessa erilaisessa molekyylissä, ja sitoutuu siksi molempiin. Diagnostiikassa se antaa vääriä positiivisia tuloksia ja tutkimuksessa harhaanjohtavia havaintoja. Polyklonaalisilla vasta-ainevalmisteilla ristireaktiot ovat aina mahdollisia, koska seos sisältää monia eri epitooppeja tunnistavia vasta-aineita. Monoklonaalinen vasta-aine on spesifisempi, mutta liian tarkkana se ei tunnista muunnoksia.",
  2, L('ristireaktio')),
K("Mitä immunisointi tarkoittaa?",
  "Antigeenin antamista eläimelle tai ihmiselle, jotta se alkaa tuottaa vasta-aineita.",
  "Immunisoinnissa antigeeni ruiskutetaan eläimeen, kuten hiireen, kaniin, vuoheen tai hevoseen, jolloin sen immuunipuolustus tuottaa antigeenia vastaan vasta-aineita. Ihmisillä immunisointi tehdään rokotteilla. Yleensä antigeenit ovat suuria molekyylejä, joiden moolimassa on yli 10 000 g/mol. Immuniteetin aiheuttavaa antigeenia kutsutaan immunogeeniksi. Immunisoinnin jälkeen vasta-aineet kerätään eläimen seerumista polyklonaalisena seoksena tai sen pernasoluista tehdään hybridoomia.",
  3, L('immunisointi', ['immunisoida', 'immunisoitu', 'immunisoidun', 'immunisoitua'])),
K("Mikä on immunogeeni?",
  "Antigeeni, joka saa aikaan immuunivasteen ja vasta-aineiden muodostumisen.",
  "Kaikki antigeenit eivät yksinään herätä immuunipuolustusta. Immunogeeni on antigeeni, joka riittää käynnistämään immuunivasteen, ja tyypillisesti se on suuri molekyyli, moolimassaltaan yli 10 000 g/mol, kuten proteiini tai polysakkaridi. Pienet molekyylit eivät ole immunogeeneja sellaisenaan vaan hapteeneja, jotka herättävät vasteen vasta kantajamolekyyliin kiinnitettyinä. Immunogeenisyyttä voidaan lisätä adjuvantilla, joka vahvistaa immuunivastetta rokotteissa.",
  2, L('immunogeeni')),
K("Mikä on hapteeni?",
  "Pieni molekyyli, joka herättää immuunivasteen vain isompaan kantajamolekyyliin kiinnitettynä.",
  "Hapteeni on pieni molekyyli, moolimassaltaan alle 1000 g/mol, kuten steroidi tai lääkeaine. Yksinään se ei ole immunogeeni, mutta suureen kantajaproteiiniin kytkettynä se saa immuunipuolustuksen aktivoitumaan ja tuottamaan hapteenia tunnistavia vasta-aineita. Näin saadaan vasta-aineita esimerkiksi hormoneille ja huumausaineille, joita immunomäärityksissä mitataan. Kantajaan kytkettynä hapteeni toimii epitooppina, ja syntyvät vasta-aineet tunnistavat sen myös vapaana.",
  2, L('hapteeni')),
K("Mikä on polyklonaalinen vasta-aine?",
  "Usean eri vasta-aineen seos, jonka jäsenet sitoutuvat saman antigeenin eri epitooppeihin.",
  "Polyklonaalinen vasta-ainevalmiste on eläimen immunisoinnin tuote: antigeenilla immunisoidun vuohen tai kanin seerumista puhdistettu seos, jossa monet eri solukloonit ovat tuottaneet antigeenin eri epitooppeihin eri voimakkuuksilla sitoutuvia vasta-aineita. Se tunnistaa antigeenin monelta puolelta ja sietää muunnoksia, mutta erät vaihtelevat ja ristireaktiot ovat mahdollisia. Kutsutaan myös: pAb.",
  3, L('polyklonaalinen vasta-aine', ['polyklonaalisen vasta-aineen', 'polyklonaalista vasta-ainetta', 'polyklonaalisessa vasta-aineessa', 'polyklonaaliseen vasta-aineeseen', 'polyklonaaliset vasta-aineet', 'polyklonaalisten vasta-aineiden', 'polyklonaalisia vasta-aineita', 'polyklonaalisissa vasta-aineissa', 'pAb', 'pAb:n', 'pAb:ta'])),
K("Mitä ongelmia polyklonaalisissa vasta-aineissa on?",
  "Erät vaihtelevat, eläimiä tarvitaan paljon, samankaltaisia kohteita ei eroteta ja ristireaktiot ovat mahdollisia.",
  "Eri eläinyksilöt vastaavat samaan antigeeniin eri tavalla, joten vasta-aine-erät eroavat toisistaan ja koetulokset vaihtelevat erästä toiseen. Valmistus vaatii useita eläimiä ja aiheuttaa niille kärsimystä. Seos ei pysty erottelemaan täsmällisesti samankaltaisia kohdemolekyylejä, mitä esimerkiksi syöpävarianttien diagnostiikka vaatisi. Spesifisyys on heikko, sillä odottamattomat ristireaktiot ovat aina mahdollisia.",
  2),
K("Miten hybridoomasolu tehdään ja mitä se tuottaa?",
  "Vasta-ainetta tuottava imusolu fuusioidaan kasvainsoluun. Hybridi tuottaa yhtä vasta-ainetta ja jakautuu loputtomasti.",
  "Hiiri immunisoidaan antigeenilla, ja sen pernasta eristetään vasta-ainetta tuottavia B-imusoluja. Ne fuusioidaan somaattisesti kudosviljelmässä kasvavien kasvainsolujen kanssa. Syntynyt hybridooma perii imusolulta kyvyn tuottaa yhtä tiettyä vasta-ainetta ja kasvainsolulta rajattoman jakautumiskyvyn. Haluttua vasta-ainetta tuottava klooni valitaan ja kasvatetaan, jolloin saadaan monoklonaalista vasta-ainetta samanlaisena erästä toiseen. Hybridoomasolut säilyvät pakastettuina, joten solulinja tuottaa samaa vasta-ainetta vuosikymmeniä.",
  2),
K("Mitkä ovat monoklonaalisten vasta-aineiden edut ja haitat polyklonaalisiin verrattuna?",
  "Etuja puhtaus, standardoitavuus ja vähäisempi eläinten käyttö. Haittoja matalampi affiniteetti ja liian tarkka spesifisyys.",
  "Monoklonaalinen vasta-aine sitoutuu yhteen tiettyyn epitooppiin, joten valmiste on puhdas ja sen ominaisuudet ovat samat erästä toiseen. Yhdestä hiirestä saadaan solulinja, joka tuottaa vasta-ainetta pysyvästi, joten eläinten kärsimys on vähäisempää. Haittana sitoutuminen on usein heikompaa kuin polyklonaalisella seoksella, ja liian korkea epitooppispesifisyys voi jättää antigeenin uudet muunnokset tunnistamatta.",
  2),
K("Miten vasta-aineita voidaan tehdä ilman eläimiä?",
  "Rekombinanttisilla vasta-ainegeenikirjastoilla ja faaginäytöllä soluissa.",
  "Synteettisesti luoduista rekombinanttisista vasta-ainegeenikirjastoista seulotaan esimerkiksi faaginäyttötekniikalla vasta-aineet, jotka sitoutuvat haluttuun kohteeseen, ja ne tuotetaan soluissa. Menetelmä on nopeampi kuin immunisointi ja tuottaa vasta-aineita, joita hybridoomamenetelmällä ei saada: myrkyllisille molekyyleille, ihmisen ja hiiren välillä samankaltaisille molekyyleille sekä lähisukuisille molekyyleille niin, että tunnistetaan joko kaikki tai vain yksi niistä.",
  2, L(['faaginäyttö', 'faaginäytön', 'faaginäyttöä', 'faaginäytössä', 'faaginäyttöön', 'faaginäyttötekniikka', 'faaginäyttötekniikan', 'faaginäyttötekniikkaa', 'faaginäyttötekniikalla', 'vasta-ainekirjasto', 'vasta-ainekirjaston', 'vasta-ainekirjastoa', 'vasta-ainekirjastosta', 'vasta-ainekirjastot'])),
K("Mitkä ovat vasta-aineiden neljä käyttökohdetta biotekniikassa?",
  "Affiniteettikromatografia, kudoskuvantaminen, immunomääritykset ja terapeuttiset vasta-aineet.",
  "Affiniteettikromatografiassa geeliin sidotut vasta-aineet poimivat seoksesta kohdeproteiinin. Kudoskuvantamisessa eli immunohistokemiassa leimattu vasta-aine paljastaa, missä kudoksen soluissa antigeenia on. Immunomäärityksissä vasta-aine tunnistaa näytteestä analyytin ja sen pitoisuus mitataan in vitro -diagnostiikassa. Terapeuttiset vasta-aineet ovat lääkkeitä, jotka estävät kohdemolekyylin toiminnan tai ohjaavat immuunipuolustuksen tai lääkeaineen kohdesoluihin. Kaikki neljä perustuvat samaan ominaisuuteen: vasta-aine sitoutuu spesifisesti yhteen kohteeseen monien joukosta.",
  3),
K("Mitä affiniteettikromatografia on?",
  "Puhdistusmenetelmä, jossa kiinteään geeliin sidottu vasta-aine tai muu ligandi pidättää vain siihen sitoutuvan proteiinin.",
  "Geeliin sidotaan vasta-aineita ja geeli pakataan onttoon putkiloon. Kun lähtömateriaali, jossa on paljon eri proteiineja, valutetaan läpi, vasta-aineeseen sitoutuvat proteiinit jäävät kiinni ja muut tulevat läpi. Sitoutuneet proteiinit irrotetaan lopuksi esimerkiksi laskemalla pH:ta. Menetelmä perustuu spesifisen ligandin tunnistukseen, joten se erottaa kohteen yhdessä vaiheessa hyvin puhtaaksi.",
  3, L('affiniteettikromatografia')),
K("Mitä on immunohistokemia?",
  "Kudosnäytteen värjäys leimatulla vasta-aineella, jolloin nähdään, missä soluissa antigeenia on.",
  "Ohut kudossiivu käsitellään leimatulla vasta-aineella. Leiman signaali, väri tai fluoresenssi, näyttää, millä kudoksen alueilla ja minkä solujen pinnalla vasta-aineen antigeenia esiintyy. Menetelmää käytetään syöpädiagnostiikassa syöpäsolujen tunnistamiseen, sillä ne ilmentävät pinnallaan normaalista poikkeavia proteiineja, sekä solujen toiminnan tutkimuksessa. Kutsutaan myös: kudoskuvantaminen, immunohistochemistry. Näytteen mikroskooppikuvassa syöpäsolut erottuvat normaaleista soluista värjäytymisensä perusteella.",
  2, L('immunohistokemia', ['kudoskuvantaminen', 'kudoskuvantamisen', 'kudoskuvantamista', 'kudoskuvantamisessa', 'kudoskuvantamiseen'])),
K("Mikä on terapeuttinen vasta-aine?",
  "Lääkkeenä käytettävä vasta-aine, jonka kohteena on usein elimistön oma molekyyli tai solu.",
  "Terapeuttinen vasta-aine on sairauden hoitoon annettava, yleensä monoklonaalinen vasta-aine. Sen kohteena on usein elimistön oma molekyyli tai solu, jolle elimistö ei itse tuota vasta-aineita, esimerkiksi syöpäsolun reseptori tai tulehduksen välittäjäaine. Hoitokohteita ovat syövät, autoimmuunisairaudet, virukset ja bakteerien toksiinit sekä osteoporoosi, korkea kolesteroli ja migreeni. Terapeuttiset vasta-aineet ovat myydyimpien lääkkeiden joukossa.",
  3, L('terapeuttinen vasta-aine', ['terapeuttisen vasta-aineen', 'terapeuttista vasta-ainetta', 'terapeuttisessa vasta-aineessa', 'terapeuttiseen vasta-aineeseen', 'terapeuttiset vasta-aineet', 'terapeuttisten vasta-aineiden', 'terapeuttisia vasta-aineita', 'terapeuttisissa vasta-aineissa', 'vasta-ainelääke', 'vasta-ainelääkkeen', 'vasta-ainelääkettä', 'vasta-ainelääkkeet'])),
K("Millä mekanismeilla terapeuttiset vasta-aineet vaikuttavat?",
  "Aktivoivat immuunipuolustuksen kohdetta vastaan, estävät molekyylin toiminnan tai kuljettavat myrkyn tai lääkkeen kohdesoluihin.",
  "Ensimmäinen mekanismi on immuunipuolustuksen aktivoiminen elimistön omaa molekyyliä tai syöpäsolua vastaan, jolloin vasta-aineen merkitsemä solu tuhotaan. Toinen on molekyylin toiminnan estäminen: vasta-aine tukkii esimerkiksi solun pintareseptorin, jolloin aktivoivat molekyylit eivät pääse sitoutumaan, tai neutraloi tulehduksen välittäjäaineen. Kolmas on kohdistaminen: vasta-aineeseen kiinnitetty radioaktiivinen molekyyli tai lääkeaine kuljetetaan juuri syöpäsoluihin.",
  2),
K("Miten trastutsumabi toimii rintasyövän hoidossa?",
  "Sitoutuu HER2-reseptoriin, estää sen aktivoitumisen ja aktivoi immuunipuolustuksen tuhoamaan syöpäsolun.",
  "Osassa rintasyövistä HER2-reseptoria on solun pinnalla ylimäärin ja se aktivoituu jatkuvasti ilman kasvutekijää, mikä johtaa rajoittamattomaan solunjakautumiseen ja kasvaimen verisuonten muodostumiseen. Trastutsumabi on monoklonaalinen vasta-aine, joka sitoutuu HER2-reseptoriin, estää sen aktivoitumisen ja merkitsee syöpäsolun immuunipuolustuksen tuhottavaksi. Trastutsumabiemtansiinissa vasta-aineeseen on lisäksi kiinnitetty solumyrkky, joka päätyy kohdistetusti syöpäsoluihin. Koko hoitojakso maksaa noin 70 000 dollaria.",
  1),
K("Mikä oli adukanumabi ja miksi se oli kiistanalainen?",
  "Ensimmäinen Alzheimerin taudin terapeuttinen vasta-aine. Vähentää amyloidiplakkeja, mutta hyöty oireisiin jäi todistamatta.",
  "Adukanumabi, kauppanimeltään Aduhelm, on monoklonaalinen vasta-aine, joka sitoutuu aivojen beeta-amyloidiin ja todistetusti vähentää amyloidiplakkeja. Yhdysvaltain lääkevirasto FDA hyväksyi sen kesäkuussa 2021 ensimmäiseksi Alzheimerin taudin vasta-ainehoidoksi. Euroopan lääkevirasto ei suositellut sitä, koska riittäviä todisteita oireiden vähenemisestä ei ollut. Hoito maksoi 60 000 dollaria vuodessa. Tapaus osoittaa, että merkkiaineen vähentäminen ei vielä todista lääkkeen hyötyä potilaalle.",
  1),
# ── Rokotteet ───────────────────────────────────────────────────────────────────────────
K("Mitä rokote sisältää mikrobikomponenttien lisäksi?",
  "Apuaineita, jotka vaikuttavat liukoisuuteen ja säilyvyyteen ja vahvistavat immuunivastetta.",
  "Rokotteessa on antigeenina toimiva mikrobin osa tai koko heikennetty mikrobi sekä apuaineita. Apuaineet parantavat liukoisuutta ja säilyvyyttä, ja adjuvantti vahvistaa immuunivastetta. Tavoitteena on, että rokotteeseen tulee vain se mikrobin osa, jota vastaan syntyvä immuunivaste antaa suojan tautia vastaan, jolloin sivuvaikutukset jäävät vähäisiksi. Esimerkiksi influenssarokotteessa antigeenina on viruksen pintaproteiini, ei koko virus.",
  2),
K("Mikä on adjuvantti?",
  "Rokotteen apuaine, joka vahvistaa antigeenin herättämää immuunivastetta.",
  "Adjuvantti on rokotteeseen lisättävä aine, joka voimistaa immuunipuolustuksen reaktiota antigeeniin. Sitä tarvitaan erityisesti silloin, kun antigeeni yksinään on heikosti immunogeeninen, kuten inaktivoiduissa patogeenirokotteissa ja puhdistettuun antigeeniin perustuvissa alayksikkörokotteissa. Adjuvantti pidentää antigeenin viipymää ja aktivoi synnynnäisen immuunipuolustuksen soluja, jolloin syntyy voimakkaampi ja pitkäkestoisempi suoja. Yleisimpiä adjuvantteja ovat alumiinisuolat, joita on käytetty rokotteissa lähes sata vuotta.",
  2, L('adjuvantti')),
K("Mitkä ovat rokotetyypit?",
  "Perinteiset: heikennetty ja inaktivoitu patogeeni sekä alayksikkörokote. Uudet: viruksenkaltaiset partikkelit, virusvektori- ja nukleiinihapporokotteet.",
  "Perinteisiä rokotteita ovat heikennetty eli attenuoitu patogeeni, lämmöllä tai kemikaaleilla inaktivoitu patogeeni ja alayksikkörokote, jossa on vain puhdistettu antigeeni. Uusia teknologioita ovat viruksenkaltaiset partikkelit, jotka esittelevät antigeenin ilman perimää, virusvektorirokotteet, joissa vaaraton virus kantaa antigeenin geenin, sekä nukleiinihapporokotteet, joissa soluille annetaan antigeenin DNA tai lähetti-RNA.",
  3),
K("Mikä on heikennetty patogeenirokote?",
  "Perinteisin rokote: elävä mutta heikennetty virus tai bakteeri, joka ei aiheuta tautia.",
  "Heikennetty eli attenuoitu rokote sisältää elävän taudinaiheuttajan, joka on sopeutettu esimerkiksi apinan soluihin niin, ettei se enää lisäänny hyvin ihmisessä. Se antaa vahvan ja pitkäkestoisen immuniteetin, koska infektio jäljittelee oikeaa tautia. Ongelmana on, että mutaatio tai rekombinaatio voi palauttaa virulenssin, ja heikon immuniteetin potilaalla heikennettykin virus voi kasvaa.",
  2, L(['heikennetty rokote', 'heikennetyn rokotteen', 'heikennettyä rokotetta', 'heikennetyt rokotteet', 'attenuoitu rokote', 'attenuoidun rokotteen', 'attenuoitua rokotetta', 'attenuoidut rokotteet', 'heikennetty patogeenirokote'])),
K("Mikä on inaktivoitu patogeenirokote?",
  "Rokote, jonka taudinaiheuttaja on tapettu lämmöllä tai kemikaaleilla.",
  "Patogeeninen virus kasvatetaan puhtaana soluissa ja inaktivoidaan lämmöllä tai kemikaaleilla, jolloin se ei voi lisääntyä eikä aiheuttaa tautia. Rokote on turvallisempi kuin heikennetty patogeeni, mutta inaktivaatio voi heikentää immunogeenisyyttä, joten mukaan tarvitaan adjuvantti. Erityisesti soluvälitteinen immuniteetti ei välttämättä muodostu, koska virus ei infektoi soluja. Esimerkkejä ovat polio- ja hepatiitti A -rokotteet sekä useimmat influenssarokotteet.",
  2, L(['inaktivoitu rokote', 'inaktivoidun rokotteen', 'inaktivoitua rokotetta', 'inaktivoidut rokotteet', 'inaktivoitu patogeenirokote'])),
K("Mikä on alayksikkörokote?",
  "Rokote, jossa on vain puhdistettu antigeeni, joko viljellystä viruksesta eristetty tai rekombinanttisesti tuotettu.",
  "Alayksikkörokote sisältää taudinaiheuttajasta vain halutun antigeenin. Perinteisesti virus viljeltiin soluissa ja antigeeni puhdistettiin siitä. Tehokkaampaa on rekombinanttituotto: antigeenin DNA siirretään hiivaan tai hyönteissoluihin, jotka tuottavat antigeenin, ja se puhdistetaan. Puhdas antigeeni aiheuttaa vähemmän sivuvaikutuksia, mutta sen immunogeenisyys on heikko, joten adjuvantti tarvitaan. Hepatiitti B -rokote on hiivassa tuotettu pinta-antigeeni, ja papilloomavirusrokote tuotetaan samaan tapaan.",
  2, L(['alayksikkörokote', 'alayksikkörokotteen', 'alayksikkörokotetta', 'alayksikkörokotteessa', 'alayksikkörokotteet', 'alayksikkörokotteiden', 'alayksikkörokotteita'])),
K("Mikä on viruksenkaltainen partikkeli?",
  "Viruksen rakenneproteiineista koottu kuori ilman perimää. Esittelee antigeenin turvallisesti.",
  "Viruksen rakenneproteiinien geenit siirretään hiiva- tai kasvisoluihin, jotka kokoavat niistä viruksenkaltaisia partikkeleita: viruksen rakenne, jonka pinnalla on antigeeni mutta jossa ei ole geneettistä materiaalia. Partikkeli herättää vahvan immuniteetin ilman patogeenin riskejä, koska se ei voi lisääntyä. Covid-19-rokotteista Medicagon ja GlaxoSmithKlinen kasveissa tuotettu rokote oli VLP, jonka pinnalla oli piikkiantigeeni. Kutsutaan myös: VLP, virus-like particle.",
  2, L(['viruksenkaltainen partikkeli', 'viruksenkaltaisen partikkelin', 'viruksenkaltaista partikkelia', 'viruksenkaltaiset partikkelit', 'viruksenkaltaisia partikkeleita', 'VLP', 'VLP:n', 'VLP:tä', 'VLP:t'])),
K("Mikä on virusvektorirokote?",
  "Muokattu vaaraton virus, jonka perimään on lisätty antigeenin geeni. Infektoidut solut esittelevät antigeenin.",
  "Virusvektorirokotteessa käytetään ei-patogeenista, yleensä lisääntymiskyvytöntä adenovirusta, jonka genomiin on lisätty antigeenin DNA. Vektori infektoi solut, jotka tuottavat antigeenin ja esittelevät sen tehokkaasti, jolloin syntyy vahva immuunivaste myös soluvälitteisenä. Heikkoutena aikaisempi immuniteetti vektorivirusta vastaan heikentää tehoa. Covid-19-rokotteista tämän tyypin edustajia olivat AstraZeneca, Janssen ja Sputnik V.",
  2, L(['virusvektorirokote', 'virusvektorirokotteen', 'virusvektorirokotetta', 'virusvektorirokotteet', 'virusvektorirokotteita', 'virusvektori', 'virusvektorin', 'virusvektoria', 'virusvektorit'])),
K("Mikä on lähetti-RNA-rokote?",
  "Rokote, jossa antigeenin lähetti-RNA viedään soluihin lipidinanopartikkeleissa ja solut tuottavat antigeenin.",
  "Lähetti-RNA-rokotteessa antigeenin lähetti-RNA annostellaan lipidinanopartikkeleissa. Riittää, että se pääsee soluliman ribosomeille, jotka tuottavat antigeenin, ja solut esittelevät sen immuunipuolustukselle. Rokotteet on nopea kehittää ja niiden tuotanto on helppo skaalata, koska mitään ei tarvitse viljellä. Lähetti-RNA on kuitenkin epästabiilia ja vaatii pakastuksen. Covid-19-rokotteista BioNTechin ja Pfizerin sekä Modernan rokotteet olivat tätä tyyppiä. Kutsutaan myös: mRNA-rokote, nukleiinihapporokote.",
  2, L(['nukleiinihapporokote', 'nukleiinihapporokotteen', 'nukleiinihapporokotetta', 'nukleiinihapporokotteet'])),
# ── Entsyymit ───────────────────────────────────────────────────────────────────────────
K("Mitä etuja entsyymeillä on kemiallisiin katalyytteihin verrattuna?",
  "Selektiivisyys ja stereospesifisyys, ei sivureaktioita, toimivat miedoissa oloissa ja ovat biohajoavia.",
  "Entsyymi tunnistaa substraattinsa tarkasti, joten reaktio on selektiivinen ja stereospesifinen eikä tuota sivureaktioita tai vaadi reaktiivisten ryhmien suojausta. Entsyymit toimivat vallitsevissa olosuhteissa, pH:ssa 5–9, lämpötilassa 15–50 °C ja normaalipaineessa, kun kemiallinen katalyytti vaatii usein kuumuutta ja painetta. Ne ovat täysin biohajoavia. Prosessissa on siksi vähemmän vaiheita, vähemmän jätettä ja pienempi energiankulutus.",
  3),
K("Mitä haittapuolia entsyymeillä on katalyytteinä?",
  "Kalliita, vaativat vesiympäristön, usein kertakäyttöisiä ja epästabiileja teollisissa oloissa.",
  "Entsyymi ja sen mahdollisesti tarvitsema kofaktori ovat kalliita. Entsyymi tarvitsee vesiympäristön, mutta lähtöaineet tai tuotteet voivat vaatia orgaanisen liuottimen, jolloin liuottimet ovat yhteensopimattomia. Liukoinen entsyymi on usein kertakäyttöinen, koska sitä ei saada erotettua tuotteesta. Lisäksi entsyymi on epästabiili ja voi menettää aktiivisuutensa rajuissa teollisuusolosuhteissa. Immobilisointi lievittää monia näistä ongelmista.",
  2),
K("Mikä on entsyymireaktori?",
  "Reaktori, jossa entsyymiä ei tuoteta vaan käytetään liukoisena tai kantajaan sidottuna toisen tuotteen valmistukseen.",
  "Entsyymireaktorissa tapahtuu entsyymireaktio: entsyymi katalysoi lähtöaineen muuttumisen tuotteeksi. Entsyymi on joko liukoisena reaktioliuoksessa tai immobilisoituna eli kiinnitettynä kantajamateriaaliin, jolloin tuote virtaa läpi ja entsyymi jää reaktoriin uudelleen käytettäväksi. Samaa periaatetta voidaan soveltaa kokonaisille soluille, jolloin puhutaan solureaktorista. Immobilisoitu entsyymi mahdollistaa jatkuvasyöttöisen reaktorin, jossa lähtöaine virtaa sisään ja tuote ulos ilman entsyymin hävikkiä.",
  2, L('entsyymireaktori', 'solureaktori')),
K("Mitä entsyymien immobilisointi tarkoittaa ja miksi se tehdään?",
  "Entsyymin kiinnittämistä kiinteään kantajaan. Lisää stabiilisuutta, mahdollistaa uudelleenkäytön ja helpottaa tuotteen erottelua.",
  "Immobilisoinnissa entsyymi sidotaan kiintokantajaan eli sidosaineeseen, matriisiin. Kiinnitetty entsyymi kestää paremmin proteolyysiä eli pilkkoutumista ja denaturaatiota eli aktiivisuuden menetystä. Sitä voidaan käyttää uudelleen, mikä säästää kustannuksia, tuote on helppo erottaa entsyymistä ja mahdollinen allergeenisyys vähenee. Immobilisointi tekee mahdollisiksi jatkuvasyöttöiset entsyymireaktorit. Kiinnitys voi olla adsorptio, kovalenttinen sidos tai entsyymin sulkeminen geelin tai kapselin sisään.",
  3, L('immobilisointi', ['immobilisoida', 'immobilisoitu', 'immobilisoidun', 'immobilisoitua', 'immobilisoituna'])),
K("Miten entsyymejä käytetään hedelmien ja vihannesten prosessoinnissa?",
  "Pektinaasi ja sellulaasit parantavat mehun saantoa ja kirkastavat, amylaasit hajottavat tärkkelystä.",
  "Pektinaasi pilkkoo pektiiniä, mikä parantaa mehun saantoa ja kirkastaa viinin. Sellulaasit pilkkovat selluloosaa ja tuhoavat kasvisolujen kovaa soluseinärakennetta, mikä tehostaa mehun saantoa ja laskee viskositeettia. Amylaasit hajottavat tärkkelystä sokereiksi. Samoja entsyymejä käytetään myös leivonnassa tasalaatuistamiseen, rakenteen ja säilyvyyden parantamiseen sekä soseiden valmistuksessa. Ilman entsyymejä sameus ja viskositeetti tukkisivat suodattimet ja pienentäisivät saantoa.",
  2),
K("Miten entsyymejä käytetään maitotuotteiden valmistuksessa?",
  "Laktaasi pilkkoo laktoosin, kymosiini juoksuttaa juuston ja proteaasit vähentävät allergeeneja.",
  "Vähälaktoosisissa tuotteissa laktoosi pilkotaan laktaasilla glukoosiksi ja galaktoosiksi. Juuston juoksuttamiseen käytetään mikrobeissa tuotettua kymosiinia eli renniiniä, joka on puhdasta ja edullista verrattuna vasikan juoksutinmahasta eristettyyn. Proteaaseilla pilkotaan äidinmaidonvastikkeen proteiineja allergeenien vähentämiseksi. Kasvijuomissa, kuten kauramaidossa, makeus luodaan pilkkomalla tärkkelystä amylaasilla. Kymosiini oli ensimmäisiä geenitekniikalla tuotettuja elintarvike-entsyymejä, hyväksytty 1990.",
  2),
K("Miten entsyymejä käytetään lihan ja nahan käsittelyssä?",
  "Lihaa mureutetaan papaiinilla, fisiinillä ja bromelaiinilla. Nahasta poistetaan karvat ja ihon osat trypsiinillä.",
  "Kasviperäiset proteaasit papaiini, fisiini ja bromelaiini pilkkovat lihan sidekudosproteiineja ja mureuttavat lihaa. Nahkateollisuudessa nahkaa pehmennetään poistamalla karvapeite ja ihon komponentteja muun muassa trypsiinillä. Entsyymin on oltava tehokas, mutta se ei saa pilkkoa kollageenia, joka antaa nahalle lujuuden. Nämä proteaasit ovat peräisin papaijasta, viikunasta ja ananaksesta, ja ne toimivat jo huoneenlämmössä.",
  1),
K("Miten entsyymejä käytetään pesuaineissa?",
  "Proteaasit, amylaasit ja lipaasit pilkkovat tahroja ja sellulaasi kirkastaa värejä.",
  "Pesuaineen entsyymit pilkkovat tahrojen ainesosia: proteaasit proteiineja, amylaasit tärkkelystä ja lipaasit rasvoja, jolloin tahra irtoaa alhaisessakin pesulämpötilassa. Sellulaasi poistaa kankaan pinnan nukkaa ja toimii värin kirkastajana. Entsyymin on oltava erittäin stabiili, koska pesulämpötilat ovat korkeita ja pesuaineen pH on emäksinen. Entsyymit ovat mahdollistaneet pesulämpötilojen laskemisen, mikä säästää energiaa ja kangasta.",
  1),
K("Miten entsyymejä käytetään metsä- ja tekstiiliteollisuudessa?",
  "Sellulaasit ja ksylanaasit paperimassan käsittelyssä, valkaisussa ja musteen poistossa. Tekstiileissä valkaisu ja kuitujen pehmennys.",
  "Paperimassan valmistuksessa sellulaasit pilkkovat selluloosaa, ligniiniä esihajotetaan sienten avulla ja valkaisu ksylanaasilla on ympäristöystävällisempää kuin kloorin käyttö. Jätepaperista muste poistetaan sellulaaseilla, ksylanaaseilla ja lipaaseilla. Tekstiiliteollisuus kuluttaa paljon energiaa ja vettä, joten kankaat valkaistaan entsyymeillä kemikaalien sijasta, kuituja pehmennetään ja villaa puhdistetaan, pehmennetään ja suojataan kutistumiselta entsyymeillä. Öljyteollisuudessa entsyymit parantavat öljyn virtausta ja tekevät biodieseliä.",
  1),
K("Miten entsyymejä käytetään molekyylibiologiassa?",
  "Termostabiili DNA-polymeraasi PCR:ssä, restriktioentsyymit DNA:n leikkaamiseen ja ligaasit liittämiseen.",
  "Molekyylibiologian työkaluentsyymit ovat biotekniikan tunnetuimpia sovelluksia. Kuumuutta kestävä DNA-polymeraasi monistaa DNA:ta polymeraasiketjureaktiossa, jossa lämpötila nousee toistuvasti yli 90 asteeseen. Restriktioentsyymit leikkaavat DNA:n täsmällisistä kohdista ja ligaasit liittävät katkaistut päät yhteen, mikä on yhdistelmä-DNA-tekniikan perusta. Diagnostiikassa entsyymejä käytetään analyyttisinä leimoina. Restriktioentsyymien löytäminen 1970-luvulla teki geenien leikkaamisesta ja yhdistelemisestä mahdollista.",
  2),
K("Miksi entsyymejä käytetään lääkeaineiden synteesissä?",
  "Koska ne ovat enantioselektiivisiä: tuottavat vain lääkkeenä toimivan peilikuvamuodon.",
  "Monet lääkemolekyylit ovat kiraalisia, ja vain toinen peilikuvaisomeeri on tehokas tai turvallinen. Talidomidi on varoittava esimerkki: toinen enantiomeeri lievitti pahoinvointia, toinen aiheutti sikiövaurioita. Entsyymi tuottaa stereospesifisesti vain halutun isomeerin. Esimerkiksi penisilliini valmistetaan penisilliiniasylaasin avulla. Kemianteollisuudessa entsyymipohjaisia prosesseja on silti vielä vähän. Entsyymikatalyysi säästää myös reaktiovaiheita, koska reaktiivisia ryhmiä ei tarvitse suojata.",
  2),
K("Mikä rajoittaa entsyymien käyttöä ja miten uusia entsyymejä kehitetään?",
  "Vaikeat sidokset, poolittomat liuottimet, kofaktorien hinta ja hidas pystytys. Uusia entsyymejä muokataan ja etsitään ääriolojen eliöistä.",
  "Tärkeitä synteettisiä sidoksia, kuten hiili–hiili-sidoksia, on entsyymeillä vaikea valmistaa, poolittomat orgaaniset liuottimet ovat entsyymille haastava ympäristö, kofaktorin tarve kasvattaa kuluja ja entsyymiprosessin pystyttäminen on hidasta. Ratkaisuksi olemassa olevaa entsyymiä muokataan halutunlaiseksi, tehdään minimaalisia entsyymejä ja hybridientsyymejä, muokataan spesifisyyttä tai etsitään uusia entsyymejä ääriolojen organismeista, kuten kuumista lähteistä.",
  2),
K("Mitä eroa on rationaalisella proteiinimuokkauksella ja ohjatulla evoluutiolla?",
  "Rationaalisessa muokkauksessa tehdään paikkaspesifinen mutaatio tunnettuun rakenteeseen, ohjatussa evoluutiossa mutatoidaan satunnaisesti ja valikoidaan parhaat.",
  "Proteiinin rakenne eli aminohappojärjestys ja siten geeni määrää sen toiminnan. Kun rakenne ja toiminta tunnetaan tarkasti, entsyymiä voidaan parantaa rationaalisesti muuttamalla tietty aminohappo paikkaspesifisellä mutaatiolla. Ohjatussa evoluutiossa geeniä mutatoidaan satunnaisesti, suuresta joukosta valikoidaan parhaat muunnokset ja kierros toistetaan. Uusimpana tekoäly mahdollistaa entsyymien suunnittelun täysin tyhjästä, de novo.",
  2, L(['ohjattu evoluutio', 'ohjatun evoluution', 'ohjattua evoluutiota', 'ohjatussa evoluutiossa', 'ohjatulla evoluutiolla', 'rationaalinen proteiinimuokkaus', 'rationaalisen proteiinimuokkauksen', 'rationaalista proteiinimuokkausta', 'proteiinimuokkaus', 'proteiinimuokkauksen', 'proteiinimuokkausta'])),
# ── Osa 2: proteiinien tuotto ───────────────────────────────────────────────────────────
K("Mitä edellytyksiä teollisella proteiinituotolla on?",
  "Yksinkertainen, toistettava prosessi, alhaiset kustannukset, suuri saanto lyhyessä ajassa edullisista raaka-aineista.",
  "Proteiinien tuotto on teollinen prosessi, joten sen on oltava yksinkertainen ja toistettava. Henkilö- ja laitekustannusten on oltava riittävän alhaisia ja saantojen suuria lyhyessä ajassa. Raaka-aineiden on oltava helposti saatavia, edullisia ja laadukkaita, energiankulutuksen mahdollisimman alhainen ja ympäristökustannusten, kuten jäteveden käsittelyn, pieniä. Vaatimukset ovat samat kuin missä tahansa kemianteollisuuden prosessissa, vaikka katalyytti on elävä solu.",
  2),
K("Mikä on rekombinanttiproteiini?",
  "Proteiini, joka tuotetaan siirtämällä sen geeni tuotto-isäntään, usein mikro-organismiin.",
  "Proteiineja voidaan tuottaa niiden luonnollisissa organismeissa, mutta yleensä geeni siirretään yhdistelmä-DNA-tekniikalla tuotto-isäntään, kuten Escherichia coli -bakteeriin, hiivaan tai nisäkässoluihin, jotka tuottavat proteiinia suuria määriä. Tällaista proteiinia kutsutaan rekombinanttiproteiiniksi. Esimerkkejä ovat ihmisinsuliini, terapeuttiset vasta-aineet ja pesuaine-entsyymit. Rekombinanttituotanto tekee mahdolliseksi ihmisen proteiinien valmistuksen ilman eläin- tai ihmiskudosta, ja tuottokantaa voidaan parantaa lisäämällä geenin kopiolukua.",
  3, L('rekombinanttiproteiini')),
K("Mitkä ovat rekombinanttiproteiinin tuottoprosessin vaiheet?",
  "Tuotto-isännän valinta ja muokkaus, esikasvatus ja fermentointi, sitten kerääminen, puhdistus, laadunvarmistus ja säilöminen.",
  "Prosessi jakautuu ylä- ja alavirtaan. Ylävirrassa valitaan tuotto-isäntä ja muokataan se geneettisesti, tehdään esikasvatus ja fermentoidaan suuressa mittakaavassa, jolloin proteiini tuottuu soluissa. Alavirrassa tuote kerätään, puhdistetaan soluista ja muista proteiineista, sen toiminnallisuus varmistetaan ja se säilötään aktiivisuuden säilyttävällä tavalla. Alussa tuote ei ole kovin puhdasta, lopussa erittäin puhdasta.",
  3),
K("Mikä on ylävirran prosessi?",
  "Proteiinin tuotto solussa: tuotto-organismin valinta, muokkaus ja kasvatus fermentorissa.",
  "Ylävirran prosessi kattaa kaiken, mikä tapahtuu ennen tuotteen keräämistä: sopivan tuotto-organismin valinnan, sen geneettisen muokkauksen, esikasvatuksen ja fermentoinnin. Tuotto-isäntä voi olla mikro-organismi, joka on yleisin, yksinkertaisin ja edullisin, hiiva tai muu sienisolu, nisäkäs- tai hyönteissolu, kasvi tai eläin, joka tuottaa polyklonaalisia vasta-aineita immunisoituna. Kutsutaan myös: upstream processing.",
  3, L(['ylävirran prosessi', 'ylävirran prosessin', 'ylävirran prosessia', 'ylävirran prosessissa', 'ylävirran prosessiin', 'upstream', 'upstream-prosessi', 'upstream-prosessin', 'upstream-prosessia'])),
K("Mikä on alavirran prosessi?",
  "Tuotteen kerääminen, puhdistus, laadunvarmistus ja säilöminen fermentoinnin jälkeen.",
  "Alavirran prosessi alkaa, kun solut ovat tuottaneet proteiinin. Tuote kerätään joko solujen sisältä tai kasvatusliuoksesta, puhdistetaan soluista ja muista proteiineista, sen toiminnallisuus varmistetaan laadunvarmistuksessa ja se säilötään niin, että aktiivisuus säilyy. Puhdistus voi olla prosessin kallein osa: se vie 20–80 prosenttia kustannuksista, tuotto vain 10–50. Kutsutaan myös: downstream processing, jälkikäsittely.",
  3, L(['alavirran prosessi', 'alavirran prosessin', 'alavirran prosessia', 'alavirran prosessissa', 'alavirran prosessiin', 'downstream', 'downstream-prosessi', 'downstream-prosessin', 'downstream-prosessia', 'jälkikäsittelyprosessi', 'jälkikäsittelyprosessin'])),
K("Mitä tuotto-isäntiä proteiinien tuottoon käytetään ja miten ne eroavat?",
  "Mikrobit, hiiva, nisäkäs-, hyönteis- ja kasvisolut sekä eläimet. Erot ovat hinnassa ja proteiinin muokkauskyvyssä.",
  "Mikro-organismi on yleisin, yksinkertaisin ja edullisin, mutta ei osaa glykosyloida. Hiiva ja muut sienisolut pystyvät translaation jälkeisiin muokkauksiin. Nisäkässolut ovat monimutkaisempia ja kalliita mutta joskus välttämättömiä, hyönteissolujen muokkaukset eroavat nisäkkäistä. Kasvien kovat soluseinät vaikeuttavat puhdistusta ja glykosylaatio eroaa eläimistä. Eläimiä käytetään polyklonaalisten vasta-aineiden tuottoon immunisoimalla.",
  3),
K("Mikä vaikuttaa tuottotavan ja puhdistustavan valintaan?",
  "Proteiinin alkuperä, käyttökohde ja tuottoskaala sekä proteiinin luonne ja vaadittu puhtaustaso.",
  "Proteiinit ovat arvokkaita mutta monimutkaisia ja herkkiä, helposti hajoavia. Tuottotapaan vaikuttavat proteiinin alkuperä, siis onko se peräisin mikro-organismista, kasvista vai eläimestä, käyttökohteen vaatima puhtausaste ja tuottoskaala milligrammoista kilogrammoihin. Puhdistustapaan vaikuttavat proteiinin luonne, liukoinen tai kalvoproteiini, stabiili tai epästabiili, sekä vaadittu puhtaustaso: tekninen, analyyttinen vai terapeuttinen käyttö.",
  2),
K("Mitä fermentointi tarkoittaa modernissa biotekniikassa verrattuna elintarvikkeisiin?",
  "Modernissa biotekniikassa steriili, säädelty bioreaktoriprosessi rekombinanttituotteille. Elintarvikkeissa käyminen tapahtuu itse tuotteessa.",
  "Fermentaatio on uusiutuvan raaka-aineen muuntamista elävän organismin avulla tuotteeksi, jota kertyy elatusaineeseen. Modernissa biotekniikassa se tarkoittaa fermentorissa steriileissä ja kontrolloiduissa oloissa tapahtuvaa prosessia, jossa mikro-organismit tuottavat rekombinanttisia tuotteita, joiden puhdistus on vaativaa. Perinteisessä elintarvikebiotekniikassa fermentointi tapahtuu itse elintarvikkeessa, joka on tuote sellaisenaan, kuten olut, juusto tai hapankaali.",
  2),
K("Mikä on fermentori?",
  "Suljettu steriili bioreaktori, jossa soluja kasvatetaan hallitusti kasvatusliuoksessa.",
  "Fermentori on bioreaktori: suljettu, steriloitava laite, jossa fermentaatio tapahtuu ja jossa solut ovat tyypillisesti vapaana kasvatusliuoksessa. Prosessi voi olla aerobinen tai anaerobinen käytetystä solusta riippuen. Fermentorissa on sekoitin, ilmastus ja anturit, joilla seurataan pH:ta, happea ja lämpötilaa, sekä syötöt hapolle, emäkselle, ravinteille ja vaahdonestolle. Kutsutaan myös: bioreaktori.",
  3, L('fermentori', 'bioreaktori')),
K("Millaisia fermentointiprosesseja on?",
  "Biomassan, mikrobien entsyymien, metaboliittien ja rekombinanttiproteiinien tuotto sekä transformaatioprosessit.",
  "Biomassan tuotossa tuote on itse solumassa, kuten leivinhiiva. Mikrobien entsyymien tuotossa kerätään solujen erittämiä entsyymejä. Metaboliittien tuotossa tuote on aineenvaihdunnan tuote, kuten etanoli tai sitruunahappo. Rekombinanttiproteiinien tuotossa solu valmistaa siirrettyä geeniä, esimerkiksi vasta-ainefragmentteja. Transformaatioprosessissa solun entsyymit muuntavat lähtöaineen tuotteeksi, kuten steroidien valmistuksessa. Sama fermentori sopii kaikkiin, mutta tuotteen sijainti solussa tai liuoksessa ratkaisee talteenoton.",
  2),
K("Mitkä ovat suurimmat teolliset soluprosessien tuotteet?",
  "Käymistuotteet 100 miljoonaa tonnia, etanoli 90, orgaaniset hapot ja aminohapot miljoonia tonneja. Arvokkaimpia terapeuttiset proteiinit.",
  "Määrältään suurimmat ovat hiivoilla ja maitohappobakteereilla tehdyt käymistuotteet, olut, viini ja meijerituotteet, noin 100 miljoonaa tonnia ja 600 miljardia euroa vuodessa, sekä hiivalla tuotettu etanoli, 90 miljoonaa tonnia. Aminohappoja tuotetaan 2 ja orgaanisia happoja 3 miljoonaa tonnia. Arvoltaan suurin ryhmä on hiivoissa, bakteereissa ja eläinsoluissa tuotetut terapeuttiset proteiinit, yli 140 miljardia euroa. Antibiootteja tehdään 20 000 tonnia.",
  1),
K("Miten aminohappoja valmistetaan teollisesti?",
  "Fermentoimalla mikrobeissa, erottelemalla proteiinilähteestä, kemiallisesti syntetisoimalla tai biokonversiolla entsyymeillä.",
  "Aminohapot ovat primaarimetaboliitteja, joita tuotettiin vuonna 2025 yli 44 miljardin dollarin arvosta ruoan lisäaineiksi, eläinten rehuun, potilaiden ravintoliuoksiin ja kosmetiikkaan. Paras tapa on yleensä fermentointi Corynebacterium-bakteereilla. Vaihtoehtoja ovat erottelu teurasjätteestä tai kasvista happokäsittelyllä, kemiallinen synteesi, joka tuottaa L- ja D-peilikuvaisomeerien seoksen, sekä biokonversio entsyymireaktiolla. Fermentointi voittaa synteesin, koska solu tuottaa vain biologisesti aktiivisen L-muodon.",
  2),
K("Miten etanolia tuotetaan fermentoimalla?",
  "Hiivalla tai Zymomonas-bakteerilla sokereista: aerobinen kasvatus, anaerobinen tuotanto, tislaus 96-prosenttiseksi.",
  "Etanoli on teollinen liuotin, synteesien lähtöaine ja biopolttoaine. Siitä 70 prosenttia tehdään fermentoimalla ja 30 kemiallisesti. Tuotto-organismi on Saccharomyces cerevisiae -hiiva tai Zymomonas mobilis -bakteeri ja lähtöaine sokerit. Solut kasvatetaan ensin aerobisesti ja etanoli tuotetaan anaerobisesti. Käytetään syöttöpanosfermentointia, koska liika glukoosi estää reaktiotien, tai jatkuvaa fermentointia, koska etanoli on soluille myrkyllistä. Tuote eristetään tislaamalla 96-prosenttiseksi.",
  2),
K("Mitkä ovat Zymomonas mobilis -bakteerin edut ja haitat etanolin tuotossa?",
  "Nopea ja tuottoisa, sietää 16 % etanolia, mutta tekee hajuyhdisteitä ja käyttää vain harvoja sokereita.",
  "Anaerobinen Zymomonas mobilis kasvaa ja fermentoi nopeasti, sietää 16 tilavuusprosentin etanolipitoisuuden ja tuottaa etanolia eri synteesireittiä 2–5 kertaa enemmän kuin hiiva. Haittana se tuottaa pahanhajuisia rikkiyhdisteitä, vaatii lysiiniä ja metioniinia ja käyttää vain glukoosia, fruktoosia tai sakkaroosia, ei sellua. Biopolttoaineessa haju ei haittaa, joten muokkauskohteita ovat rikkiyhdisteiden poisto, kasvuvaatimusten keventäminen ja hiililähteen laajentaminen.",
  1),
K("Miten etikkahappoa tuotetaan fermentoimalla?",
  "Acetobacter hapettaa etanolin etikkahapoksi syöttöpanosfermentoinnissa, kunnes pitoisuus on noin 20 %.",
  "Tuotto-organismi on Acetobacter-bakteeri ja lähtöaine etanoli, jonka alkoholidehydrogenaasi ja aldehydidehydrogenaasi hapettavat etikkahapoksi. Viinistä saadaan viinietikkaa, jossa on 6 prosenttia etikkahappoa. Syöttöpanosfermentoinnissa etanolia on aina oltava vähintään 0,2 prosenttia jäljellä, muuten bakteeri hapettaa lopputuotteen hiilidioksidiksi. Fermentointi lopetetaan, kun etikkahappoa on noin 20 prosenttia. Prosessi on aerobinen, koska hapetus vaatii happea, toisin kuin etanolin anaerobinen käyminen.",
  1),
K("Miten sitruunahappoa tuotetaan ja mihin sitä käytetään?",
  "Aspergillus niger -home tuottaa sitä sokereista syöttöpanosfermentoinnissa. Käyttö happamoittamiseen, säilömiseen ja kalkin poistoon.",
  "Tuotto-organismi on Aspergillus niger -home ja lähtöaine sokerit. Kun solukasvatusvaihe on ohi parin vuorokauden jälkeen, sokerin määrää ja ilmastusta lisätään, jolloin sitruunahapon tuotto käynnistyy ja happo erittyy solun ulkopuolelle elatusaineeseen. Sitruunahappoa käytetään elintarvikkeiden happamoittamiseen ja säilömiseen, kompleksinmuodostajana metalliteollisuudessa, veden pehmentäjänä pesuaineissa ja kalkkisaostumien poistoon pesukoneista.",
  1),
K("Mitä mikro-organismeja käytetään tuottoisäntinä?",
  "Bakteereja ja arkkeja sekä eukaryooteista hiivoja, homeita, alkueliöitä ja viherleviä.",
  "Mikro-organismeja ovat prokaryootit eli bakteerit ja arkit sekä eukaryooteista hiivat, jotka ovat yksisoluisia sieniä, homeet, alkueliöt ja viherlevät. Virukset eivät ole eläviä. Mikrobit kattavat yli puolet maapallon elävästä materiaalista, mutta alle prosentti lajeista on tunnistettu, viljelty ja tutkittu laboratoriossa, joten uusia tuottoisäntiä ja entsyymejä on vielä paljon löytämättä. Tunnetuimmat ovat Escherichia coli ja Saccharomyces cerevisiae.",
  2),
K("Miksi Escherichia coli on yleisin tuotto-organismi ja mikä on sen haittapuoli?",
  "Prosessi tunnetaan hyvin, kasvu on nopeaa, skaalaus ja geneettinen muokkaus helppoja. Se ei osaa glykosyloida.",
  "Escherichia colin fermentointiprosessi on hyvin ymmärretty, suuria solumääriä saadaan lyhyessä ajassa, tuotto onnistuu suuressa mittakaavassa ja geneettinen muokkaus on helppoa. Tuottoa voidaan tehostaa lisäämällä tuotettavan proteiinin geenin kopiolukua tai asettamalla geeni tehokkaamman säätelyalueen alaisuuteen. Haittapuoli on, etteivät mikrobit osaa glykosyloida eli liittää proteiiniin sokeriryhmiä, joita monet eläinproteiinit tarvitsevat. Muita bakteeri-isäntiä ovat Bacillus subtilis ja Corynebacterium.",
  3),
K("Mikä on glykosylaatio?",
  "Sokeriryhmien liittäminen proteiiniin entsymaattisesti translaation jälkeen.",
  "Glykosylaatiossa proteiiniin liitetään entsymaattisesti hiilihydraattiketjuja. Se on tärkein translaation jälkeinen muokkaus, joka vaikuttaa proteiinin laskostumiseen, stabiilisuuteen, liukoisuuteen ja tunnistukseen elimistössä. Bakteerit eivät osaa glykosyloida, hiivan ja kasvien glykosylaatio eroaa nisäkkäistä, joten monet terapeuttiset proteiinit on tuotettava nisäkässoluissa, kuten kiinanhamsterin munasarjasoluissa. Terapeuttisen vasta-aineen glykosylaatio vaikuttaa myös sen puoliintumisaikaan veressä ja kykyyn aktivoida immuunipuolustusta.",
  2, L('glykosylaatio', ['glykosyloida', 'glykosyloitu', 'glykosyloidun', 'glykosyloitua', 'glykosylointi', 'glykosyloinnin', 'glykosylointia'])),
K("Mitä elatusaine sisältää ja miten kasvatus skaalataan?",
  "Hiili- ja typpilähteen, vitamiinit ja hivenaineet. Pienessä skaalassa maljoilla ja ravistelupulloissa, suuressa fermentoreissa.",
  "Elatusaineen koostumus on tärkeä tuotteen saannon kannalta, sillä tavoitteena on saada tuotetta, ei vain kasvattaa mikrobia. Se sisältää hiililähteen, usein glukoosin, typpilähteen, vitamiinit ja hivenaineet. Kasvatus tehdään kiinteässä tai nestemäisessä elatusaineessa: pienessä skaalassa petrimaljoilla tai ravistelupulloissa alle litran tilavuuksissa, suuressa skaalassa fermentoreissa. Tuottoympäristö pidetään steriilinä kontaminaatioiden välttämiseksi.",
  2, L('elatusaine', ['kasvatusliuos', 'kasvatusliuoksen', 'kasvatusliuosta', 'kasvatusliuoksessa'])),
K("Miten fermentori ja elatusaine steriloidaan?",
  "Autoklaavaamalla 121 °C:ssa 20 minuuttia. Tulo- ja lähtöilma steriloidaan suodattamalla.",
  "",
  1),
K("Millainen on fermentorin perusrakenne?",
  "Sekoittimella varustettu säiliö, jossa on ilmastus suodattimineen, jäähdytysvaippa, syötöt ja pH-, happi- ja lämpötila-anturit.",
  "Kuvassa on fermentorin perusrakenne. Moottori pyörittää sekoitinta säiliön keskellä. Ilma tulee sisään steriilisuodattimen kautta ja poistuu toisen suodattimen kautta. Vaippaan johdetaan jäähdytysvettä ja sterilointiin höyryä, ja painemittari valvoo painetta. Ylhäältä syötetään ravinteet, lisäaineet, happo ja emäs pH:n säätöön sekä vaahdonesto. Anturit mittaavat pH:ta, happea ja lämpötilaa, ja poistovesi lasketaan alhaalta.",
  3, '', 'biotek_fermentori.png'),
K("Mitä parametreja fermentaatiossa seurataan ja säädetään?",
  "Liuenneen hapen pitoisuutta, pH:ta ja lämpötilaa. Tiheissä kasvatuksissa myös ravinteiden ja metaboliittien aiheuttamaa inhibitiota.",
  "Aerobisissa prosesseissa tärkein on liuenneen hapen pitoisuus, jota säädetään ilmastuksella ja sekoituksella. pH pidetään optimissa lisäämällä happoa tai emästä ja lämpötila jäähdyttämällä. Korkean solutiheyden fermentaatiossa on lisäksi huomioitava, että ylimäärä ravinteita tai kertyvät aineenvaihduntatuotteet voivat inhiboida kasvua, mitä automaattinen pH-säätö ei korjaa. Anturit mittaavat arvot jatkuvasti, ja säätöjärjestelmä syöttää happoa, emästä, ilmaa tai jäähdytystä automaattisesti.",
  3),
K("Miksi fermentoria ilmastetaan ja miten se tehdään?",
  "Happi liukenee veteen huonosti, joten sitä lisätään jatkuvasti ilmana tai puhtaana happena ja kuplat rikotaan sekoittamalla.",
  "Happea liukenee veteen vain 8,4 mg/ℓ 25 °C:ssa, joten aerobisessa kasvatuksessa sitä on lisättävä jatkuvasti elatusliuokseen joko ilmana tai puhtaana happena. Tulo- ja lähtöilma steriloidaan suodattamalla. Sekoitus rikkoo ilmakuplat pieniksi, jolloin nesteen ja ilman välinen rajapinta kasvaa ja happi siirtyy liuokseen paremmin. Hapensiirto on usein suuren fermentorin tuottoa rajoittava tekijä.",
  2),
K("Mikä on sekoituksen tehtävä fermentorissa ja mikä sen ongelma on?",
  "Pitää lämpötilan, ravinteet ja hapen tasaisina. Liian kova sekoitus vahingoittaa soluja, suuressa mittakaavassa se on vaikeaa.",
  "Sekoitus varmistaa homogeenisen eli tasalaatuisen kasvuympäristön: lämpötila, ravinteet ja happi jakautuvat tasaisesti koko tilavuuteen, ja ilmakuplat rikkoutuvat pieniksi. Liian kova sekoittaminen kuitenkin vahingoittaa soluja leikkausvoimillaan, ja erityisesti nisäkässolut ovat herkkiä. Suuressa mittakaavassa sekoituksen järjestäminen on yksi suurimmista ongelmista, koska kymmenien kuutiometrien säiliötä ei saada tasaiseksi yhdellä sekoittimella.",
  2),
K("Miten pH:ta säädetään fermentaatiossa?",
  "Lisäämällä happoa tai emästä automaattisesti. Useimpien mikrobien optimi on pH 5,5–8,5.",
  "Mikrobien aineenvaihdunta muuttaa kasvatusliuoksen pH:ta, esimerkiksi hapot happamoittavat ja ammoniakki emäksöi. Automaattinen pH-kontrolli mittaa pH:n anturilla ja lisää happoa tai emästä niin, että se pysyy useimpien mikro-organismien optimissa 5,5–8,5. Säätö ei kuitenkaan korjaa metaboliittien aiheuttamia muita ongelmia, kuten kasvun inhibitiota. pH vaikuttaa entsyymien toimintaan ja ravinteiden liukoisuuteen, joten sen karkaaminen pysäyttää tuoton.",
  2),
K("Miten lämpötilaa hallitaan fermentaatiossa?",
  "Aineenvaihdunnan ja sekoituksen lämpö poistetaan vesivaipalla tai kylmävesikierukoilla.",
  "Solujen aineenvaihdunta ja sekoitus tuottavat lämpöä, joka poistetaan säiliön vesivaipan tai kylmävesikierukoiden avulla. Liian alhainen lämpötila hidastaa prosessia ja vähentää tuotteen määrää. Liian korkea lämpötila laukaisee lämpöshokkivasteen ja indusoi proteaaseja, jotka pilkkovat tuotettavaa proteiinia. Herkät rekombinanttiproteiinit tuottuvat joskus paremmin alhaisessa lämpötilassa, koska kiinnostuksen kohde on proteiinituote, ei solumassa.",
  2),
K("Mitkä ovat fermentoinnin kolme kasvatusmallia?",
  "Panoskasvatus, syöttöpanoskasvatus ja jatkuva kasvatus. Ne eroavat siinä, lisätäänkö ravinteita ja poistetaanko tuotetta.",
  "Panoskasvatuksessa ravinteet annetaan alussa eikä kasvatuksen aikana lisätä mitään, joten koostumus, biomassa ja tuote muuttuvat koko ajan. Syöttöpanoskasvatuksessa ravinteita lisätään, kun niiden puute alkaa rajoittaa kasvua, mutta mitään ei poisteta. Jatkuvassa kasvatuksessa ravinteita lisätään ja tuotetta poistetaan jatkuvasti, jolloin reaktorin olosuhteet pysyvät vakiona. Malli valitaan tuotteen mukaan: inhibitiot puoltavat syöttöpanosta, myrkyllinen tuote jatkuvaa kasvatusta.",
  3),
K("Mikä on panoskasvatus?",
  "Kasvatus, jossa ravinteita ei lisätä kasvatuksen aikana ja joka jatkuu, kunnes ravinteet loppuvat tai solut kuolevat.",
  "Panoskasvatuksessa fermentoriin pannaan elatusaine ja siemensolut, eikä mitään lisätä kasvatuksen kuluessa. Elatusaineen koostumus, biomassan määrä ja tuotteen määrä muuttuvat koko ajan. Fermentointia jatketaan, kunnes ravinteet loppuvat, solujen tuottamat metaboliitit alkavat inhiboida lisääntymistä tai solut alkavat kuolla. Kasvu noudattaa lag-, log-, stationääri- ja kuolemavaiheiden käyrää. Kutsutaan myös: batch-kasvatus.",
  3, L('panoskasvatus', ['panosfermentointi', 'panosfermentoinnin', 'panosfermentointia', 'batch-kasvatus', 'batch-kasvatuksen'])),
K("Mitkä ovat mikrobikasvun vaiheet panoskasvatuksessa?",
  "Lag-vaihe, siirtymävaihe, logaritminen kasvu, toinen siirtymävaihe, stationäärivaihe ja solukuolema.",
  "Kuvassa on solumäärän logaritmi ajan funktiona. Lag-vaiheessa solut sopeutuvat uuteen ympäristöön eivätkä vielä jakaudu. Lyhyen siirtymävaiheen jälkeen seuraa logaritmisen kasvun vaihe, jossa solumäärä kaksinkertaistuu vakioajassa, jota kuvaavat kasvunopeus ja kahdentumisaika. Toisen siirtymävaiheen jälkeen ravinteiden loppuminen tai metaboliittien kertyminen pysäyttää kasvun stationäärivaiheeseen, jonka jälkeen solut alkavat kuolla.",
  3, L(['lag-vaihe', 'lag-vaiheen', 'lag-vaihetta', 'lag-vaiheessa', 'logaritminen kasvuvaihe', 'logaritmisen kasvuvaiheen', 'logaritmisessa kasvuvaiheessa', 'log-vaihe', 'log-vaiheen', 'log-vaiheessa', 'stationäärivaihe', 'stationäärivaiheen', 'stationäärivaihetta', 'stationäärivaiheessa', 'stationäärivaiheeseen', 'kahdentumisaika', 'kahdentumisajan', 'kahdentumisaikaa']), 'biotek_kasvukayra.jpg'),
K("Mikä on syöttöpanoskasvatus?",
  "Kasvatus, jossa ravinteita lisätään kasvun rajoittuessa mutta mitään ei poisteta.",
  "Syöttöpanoskasvatuksessa ravinteita lisätään fermentoriin, kun niiden puute alkaa rajoittaa kasvua. Näin vältetään substraatti-inhibitio, jonka liian suuri ravinnepitoisuus aiheuttaisi, ja tuottovaihetta saadaan pidennettyä. Mitään ei poisteta kesken prosessin. Mallia käytetään esimerkiksi etanolin, etikkahapon ja sitruunahapon tuotossa. Kutsutaan myös: fed-batch-kasvatus. Se on teollisuuden yleisin malli, koska sillä päästään suuriin solutiheyksiin ilman panoskasvatuksen inhibitioita.",
  3, L('syöttöpanoskasvatus', ['syöttöpanosfermentointi', 'syöttöpanosfermentoinnin', 'syöttöpanosfermentointia', 'syöttöpanosfermentoinnissa', 'fed-batch', 'fed-batch-kasvatus'])),
K("Mikä on jatkuva kasvatus?",
  "Kasvatus, jossa ravinteita lisätään ja tuotetta poistetaan jatkuvasti, jolloin olosuhteet pysyvät vakiona.",
  "Jatkuvassa kasvatuksessa fermentoriin syötetään tuoretta elatusainetta ja siitä poistetaan kasvatusliuosta tuotteineen samaa tahtia. Reaktorin olosuhteet ja reaktioliuoksen koostumus pysyvät vakiona, ja solut voidaan pitää pitkään logaritmisessa kasvussa. Mallia käytetään esimerkiksi etanolin tuotossa, koska kertyvä etanoli olisi soluille myrkyllistä. Kontaminaatioriski kasvaa prosessin pidentyessä. Solut poistuvat tuotteen mukana, joten kasvunopeuden on vastattava laimennusta, muuten viljelmä huuhtoutuu ulos.",
  2, L(['jatkuva kasvatus', 'jatkuvan kasvatuksen', 'jatkuvaa kasvatusta', 'jatkuvassa kasvatuksessa', 'jatkuvaan kasvatukseen', 'jatkuva fermentointi', 'jatkuvan fermentoinnin', 'jatkuvaa fermentointia', 'jatkuvassa fermentoinnissa'])),
K("Miten proteiinin tuotto ajoitetaan kasvuvaiheisiin?",
  "Tuottogeeni aktivoidaan vasta, kun isännän omat aineenvaihduntaproteiinit on tuotettu, koska tuotto on suurimmillaan tietyssä kasvuvaiheessa.",
  "",
  2),
K("Mitkä ovat nisäkässolujen edut ja haitat tuottoisäntänä?",
  "Oikeat translaation jälkeiset muokkaukset ja laskostuminen, mutta monimutkaiset ravinnevaatimukset, hidas kasvu ja korkea hinta.",
  "Nisäkässolut tekevät proteiinille oikeanlaiset translaation jälkeiset muokkaukset, kuten glykosyloinnin, ja laskostavat sen oikein. Siksi niillä tuotetaan lääkeproteiineja, joita mikro-organismit eivät osaa tehdä. Haittoina ravitsemusvaatimukset ovat monimutkaisemmat kuin mikrobeilla ja kasvu on hidasta, joten tarvitaan suurempi alkupopulaatio ja kontaminaatioriski kasvaa ajan kuluessa. Tuotanto on kallista. Yleisin tuottosolu on kiinanhamsterin munasarjasolu CHO, jossa tehdään useimmat terapeuttiset vasta-aineet.",
  3),
K("Miten uusi antibiootti viedään teolliseen tuotantoon?",
  "Tunnistaminen seulomalla tai suunnittelemalla, tuottokannan parantaminen, tuotto fermentoimalla ja tuotteen kemiallinen muokkaus.",
  "Ensin potentiaalinen antibiootti tunnistetaan seulomalla mikrobeja tai rationaalisesti bakteerien aineenvaihduntaa ja patogeenisyyttä tutkimalla, jolloin voidaan suunnitella usealla mekanismilla vaikuttavia antibiootteja tai kiinnittymisen estäviä molekyylejä. Sitten tuottokantaa parannetaan mutaatiokierroksilla, joista paras valitaan jatkoon, ja lopuksi kahden mutaatiolinjan parhaat kannat yhdistetään. Tuotto tehdään fermentoimalla bioreaktoreissa, ja lopuksi esiasteen sivuryhmiä muokataan kemiallisesti stabiiliuden, kudosläpäisevyyden, imeytymisen ja laajakirjoisuuden parantamiseksi.",
  2),
K("Miksi antibiootit tuotetaan fermentoinnin stationäärivaiheessa?",
  "Koska ne ovat sekundaarimetaboliitteja, joita solu tuottaa vasta kasvun pysähdyttyä.",
  "Antibiootit ovat sekundaarimetaboliitteja: aineita, joita mikrobi ei tarvitse kasvuunsa vaan tuottaa stationäärivaiheessa kilpailuetuna. Kasvatusolot optimoidaan niin, että mikrobit kasvavat nopeasti, tuotto alkaa varhain ja tuottomäärät ovat mahdollisimman suuria fermentorin tilavuutta ja aikaa kohti. Antibiootit ovat usein solunulkoisia ja huonosti vesiliukoisia, joten ne puhdistetaan orgaanisilla liuottimilla ISO 9000- ja GMP-vaatimusten mukaisesti.",
  2, L('sekundaarimetaboliitti', 'primaarimetaboliitti')),
K("Mitä harvestointi tarkoittaa?",
  "Fermentaatiossa tuotetun tuotteen talteenottoa solujen sisältä tai kasvatusliuoksesta.",
  "Harvestoinnissa tuote kerätään: solunsisäinen proteiini vapautetaan hajottamalla solut, solunulkoinen erotetaan poistamalla solut. Vaihe on tärkeä myös taloudellisesti, koska saantoprosentti ratkaisee tuotteen hinnan. Tuotettava proteiini on yleensä alle prosentti solun kaikista proteiineista, joten talteenotto ja puhdistus vievät 20–80 prosenttia kustannuksista. Kutsutaan myös: talteenotto, harvest. Solunulkoisen tuotteen kerääminen on helpompaa, koska soluja ei tarvitse rikkoa ja epäpuhtauksia on vähemmän.",
  3, L('harvestointi', ['talteenotto', 'talteenoton', 'talteenottoa', 'talteenotossa', 'talteenottoon'])),
K("Miten solunsisäinen proteiini otetaan talteen?",
  "Solut hajotetaan jäädytys–sulatus-syklillä, detergentillä tai mekaanisesti jauhamalla tai ääniaalloilla.",
  "",
  2),
K("Miten tuotteen tuhoutuminen estetään talteenotossa?",
  "Työskennellään +4 °C:ssa, lisätään proteaasi-inhibiittoreita ja antimikrobisia aineita ja vältetään mekaanisia voimia.",
  "Talteenotossa minimoidaan tuotetun proteiinin tuhoutuminen. Lämpötilasta johtuva denaturaatio estetään pitämällä lämpötila noin +4 °C:ssa. Solun omien proteaasien toiminta estetään lisäämällä proteaasi-inhibiittoreita, ja mikrobikasvu antimikrobisilla aineilla, jotka molemmat poistetaan myöhemmässä vaiheessa. Mekaanisia voimia, kuten törmäilyä ja vaahtoamista, varotaan, koska ne denaturoivat proteiinia rajapinnoilla. Kaikki lisätyt suoja-aineet on poistettava ennen kuin tuote on valmis, mikä lisää puhdistusvaiheita.",
  2),
K("Mitkä ovat proteiinituotteen puhdistuksen kaksi vaihetta?",
  "Ensin proteiinit erotetaan muusta materiaalista saostamalla, sitten tuottoproteiini muista koon, tiheyden, affiniteetin tai liukoisuuden perusteella.",
  "Käyttötarkoitus määrää puhdistusasteen: tekniset proteiinit vaativat vähiten, diagnostiikka enemmän ja farmakologia eniten. Ensimmäisessä vaiheessa proteiinit erotetaan lipideistä, hiilihydraateista ja nukleiinihapoista saostamalla, yleensä ammoniumsulfaatilla. Toisessa vaiheessa tuottoproteiini erotetaan muista proteiineista koon ja tiheyden perusteella sentrifugoimalla, suodattamalla ja dialyysillä tai koon, affiniteetin ja liukoisuuden perusteella kromatografioilla. Kuva näyttää, mille kokoluokille kukin erottelumenetelmä sopii.",
  3, '', 'biotek_erottelu.jpg'),
K("Mikä on kromatografia?",
  "Erotusmenetelmä, jossa liikkuva faasi kuljettaa näytteen kiintofaasin läpi ja komponentit erottuvat erilaisten vuorovaikutustensa mukaan.",
  "Kromatografiassa puhdistettavan komponentin sisältävä liikkuva nestefaasi kulkee kiintofaasin läpi. Erottelu perustuu siihen, että näytteen eri komponentit vuorovaikuttavat kiintofaasin kanssa eri voimakkuudella ja kulkevat siksi eri nopeudella. Kiintofaasi on tavallisesti pylvääseen pakattu geeli, ja tuote kerätään ulos tulevista jakeista. Menetelmät jaetaan erotusperiaatteen mukaan, ja ne sopivat sekä laadunvarmistukseen että puhdistukseen.",
  3, L('kromatografia')),
K("Mitkä ovat kromatografian tyypit erotusperiaatteen mukaan?",
  "Geelisuodatus koon mukaan, adsorptiokromatografia hydrofobisuuden, ioninvaihto varauksen, affiniteettikromatografia ligandin ja kromatofokusointi isoelektrisen pisteen mukaan.",
  "Geelisuodatus erottelee koon, muodon ja massan perusteella, sillä pienet molekyylit viipyvät geelin huokosissa. Adsorptiokromatografia erottelee hydrofobisuuden, ioninvaihtokromatografia varauksen perusteella. Affiniteettikromatografia perustuu spesifisen ligandin, kuten vasta-aineen, tunnistukseen. Kromatofokusointi erottelee isoelektrisen pisteen mukaan, ja sitä käytetään lähinnä laadunvarmistuksessa, ei suuren mittakaavan puhdistuksessa. Käytännössä puhdistus yhdistää useita periaatteita peräkkäin, esimerkiksi ioninvaihdon ja geelisuodatuksen.",
  2, L('geelisuodatus', 'ioninvaihtokromatografia', 'adsorptiokromatografia', 'kromatofokusointi')),
K("Mikä on isoelektrinen piste?",
  "pH, jossa molekyylillä ei ole nettovarausta.",
  "Isoelektrisessä pisteessä proteiinin positiiviset ja negatiiviset varaukset kumoavat toisensa, joten sen nettovaraus on nolla. Sitä alemmassa pH:ssa proteiini on positiivinen ja korkeammassa negatiivinen. Piste riippuu happamien ja emäksisten aminohappojen suhteesta. Isoelektrisessä pisteessä proteiini liukenee huonoiten ja saostuu helposti, ja kromatofokusointi erottelee proteiinit juuri tämän pisteen perusteella. Kutsutaan myös: pI.",
  2, L(['isoelektrinen piste', 'isoelektrisen pisteen', 'isoelektristä pistettä', 'isoelektrisessä pisteessä', 'isoelektriseen pisteeseen', 'isoelektriset pisteet', 'pI', 'pI:n', 'pI:tä'])),
K("Mitä proteiinituotteen laadunvarmistus ja säilöminen sisältävät?",
  "Puhtauden, määrän ja aktiivisuuden mittauksen sekä pakastuksen sopivassa liuoksessa tai kylmäkuivauksen.",
  "Laadunvarmistuksessa mitataan proteiinin puhtaus, määrä ja aktiivisuus eli varmistetaan, että tuote toimii. Säilömisen on säilytettävä aktiivisuus varastoinnin aikana. Vaihtoehtoja ovat pakastus sopivassa liuoksessa ja kylmäkuivaus eli lyofilisointi, jossa proteiiniliuos jäädytetään ja vesi poistetaan sublimoimalla suoraan jäästä höyryksi. Kylmäkuivattu proteiini säilyy jopa huoneenlämmössä. Puhtaus mitataan esimerkiksi geelielektroforeesilla ja aktiivisuus entsyymimäärityksellä tai sitoutumistestillä.",
  2),
K("Mikä on kylmäkuivaus?",
  "Säilöntä, jossa jäädytetty proteiiniliuos kuivataan sublimoimalla vesi pois.",
  "Kylmäkuivauksessa proteiiniliuos jäädytetään ja vesi tai liuotin poistetaan alipaineessa sublimoimalla, jolloin jää muuttuu suoraan höyryksi eikä proteiini koskaan altistu nestemäiselle vedelle lämpimänä. Jäljelle jää kuiva jauhe, joka säilyttää aktiivisuutensa ja jota voidaan säilyttää jopa huoneenlämmössä. Näin säilötään esimerkiksi rokotteita, entsyymejä ja vasta-aineita. Kutsutaan myös: lyofilisointi, freeze-drying.",
  2, L('kylmäkuivaus', 'lyofilisointi')),
]
