# -*- coding: utf-8 -*-
"""Johdatus biotekniikkaan, Luento 3 - In vitro -diagnostiikka, immunomaaritykset
(Aihe 3_Diagnostiikka - Immunomääritykset.pdf). Rakentaa tyokalut/biotek_kortit.py."""
from biotek_taivutus import L

def K(q, s, l, tt, links='', kuva=None):
    return {'q': q, 's': s, 'l': l, 'tt': str(tt), 'ls': links, 'kuva': kuva}

LEHTI = 'Luento 3 - In vitro -diagnostiikka, immunomääritykset'
NRO = 3
KUVAT = {
    'biotek_standardisuora.png':  ('Aihe 3_Diagnostiikka - Immunomääritykset.pdf', 12, 'sivu'),
    'biotek_immunometrinen.png':  ('Aihe 3_Diagnostiikka - Immunomääritykset.pdf', 24, 'sivu'),
    'biotek_kilpaileva.png':      ('Aihe 3_Diagnostiikka - Immunomääritykset.pdf', 27, 'sivu'),
}

KORTIT = [
K("Mitä in vitro tarkoittaa?",
  "Elävän organismin ulkopuolella, koeputkessa tai laboratoriossa tehtyä tutkimusta.",
  "In vitro tarkoittaa sananmukaisesti lasissa: reaktio tai tutkimus tehdään elävän organismin ulkopuolella, koeputkessa, pullossa tai maljalla. Esimerkiksi solussa normaalisti tapahtuva reaktio suoritetaan koeputkessa tai soluja kasvatetaan laboratoriossa. Lääketieteessä in vitro -tutkimus tarkoittaa potilaan terveydentilan selvittämistä tutkimalla näytteitä, kuten verta, virtsaa, sylkeä tai kudosta, laboratoriomenetelmillä. Vastakohta on in vivo.",
  3, L(['in vitro', 'in vitro -tutkimus', 'in vitro -tutkimuksen', 'in vitro -tutkimusta', 'in vitro -testi', 'in vitro -testin', 'in vitro -testejä'])),
K("Mitä in vivo tarkoittaa?",
  "Elävässä organismissa tai potilaassa tehtyä tutkimusta.",
  "In vivo tarkoittaa elävässä: tutkitaan elävää potilasta tai organismia itseään, ei siitä otettua näytettä. Lääketieteessä in vivo -diagnostiikkaa ovat kliiniset oireet sekä kuvantaminen, kuten röntgenkuvaus, EKG, ultraäänitutkimus ja magneettikuvaus. Biotekniikan diagnostiikka on sen sijaan pääosin in vitro -diagnostiikkaa, jossa näytteestä mitataan molekyylejä. Sama jako pätee lääkekehitykseen: yhdiste testataan ensin in vitro soluilla ja sitten in vivo koe-eläimillä.",
  3, L(['in vivo', 'in vivo -tutkimus', 'in vivo -tutkimuksen', 'in vivo -tutkimusta', 'in vivo -diagnostiikka', 'in vivo -diagnostiikan'])),
K("Mitä on in vitro -diagnostiikka?",
  "Sairauden toteamista, hoidon seurantaa ja seulontaa tutkimalla potilaasta otettuja näytteitä laboratoriossa.",
  "In vitro -diagnostiikka on laboratoriolääketiedettä ja kliinistä kemiaa: terveydentila määritetään näytteistä, jotta sairaus todetaan sen parantamiseksi tai oireiden lievittämiseksi, hoitoa seurataan, tautia ehkäistään tai väestöä seulotaan. Diagnostiikka ylipäätään tarkoittaa sen selvittämistä, poikkeaako jokin normaalista, ja yleisessä merkityksessä puhutaan myös elintarvike- ja tietokonediagnostiikasta. Kutsutaan myös: IVD, laboratoriodiagnostiikka.",
  3, L(['in vitro -diagnostiikka', 'in vitro -diagnostiikan', 'in vitro -diagnostiikkaa', 'in vitro -diagnostiikassa', 'in vitro -diagnostiikasta', 'in vitro -diagnostiikkaan', 'IVD', 'IVD:n', 'IVD:ta', 'IVD-testi', 'IVD-testin', 'IVD-testit', 'IVD-testejä', 'laboratoriodiagnostiikka', 'laboratoriodiagnostiikan', 'laboratoriodiagnostiikkaa'])),
K("Kuinka suuri merkitys in vitro -diagnostiikalla on terveydenhuollossa?",
  "IVD-testit ovat taustalla 66 prosentissa lääkärin päätöksistä mutta vievät alle 3 prosenttia terveydenhuollon kuluista.",
  "",
  1),
K("Mitkä ovat in vitro -diagnostiikan sovellusalueita?",
  "Ihmis- ja eläinlääketiede, elintarvikeanalytiikka ja ympäristön valvonta.",
  "Ihmis- ja eläinlääketieteessä tehdään seulontatestejä oireettomille, diagnostisia testejä sairauden toteamiseksi ja seurantatestejä hoidon aikana. Elintarvikeanalytiikassa eli elintarvikediagnostiikassa valvotaan laatua ja turvallisuutta: mikrobi- ja antibioottikontaminaatioita, muuntogeenisiä tuotteita ja tuotteiden aitoutta. Ympäristön valvonnassa mitataan esimerkiksi uimaveden bakteereja, sinileviä ja sinilevätoksiineja. Kaikissa mitataan analyyttia näytteestä laboratoriomenetelmällä, mutta näytematriisi ja vaadittu herkkyys vaihtelevat.",
  2),
K("Miten biotekniikka liittyy in vitro -diagnostiikkaan?",
  "Määrityksissä hyödynnetään eliöistä peräisin olevia molekyylejä: vasta-aineita, entsyymejä ja nukleiinihappoja. Kaikki testit eivät ole bioteknisiä.",
  "Biotekniikka on elävien organismien tai niiden osien hyödyntämistä, ja in vitro -diagnostiikassa käytetään elävistä organismeista peräisin olevia molekyylejä ja niiden toimintoja: vasta-aineiden sitoutumista, entsyymien katalyysiä ja nukleiinihappojen pariutumista. Kaikki määritykset eivät ole bioteknisiä. Esimerkiksi veren kalsium mitataan kemiallisesti, koska kalsium muodostaa fenolisulfoneftaleiinin kanssa värillisen yhdisteen, ja verisolut lasketaan optisesti.",
  2),
K("Mikä on analyytti?",
  "Molekyyli tai muu asia, jonka pitoisuutta tai esiintymistä määrityksessä mitataan.",
  "Analyytti on testissä eli analyysissä analysoitava asia: mikrobi, proteiini, nukleiinihappo tai pieni molekyyli, kuten glukoosi. Lääketieteellisessä in vitro -testissä analyytin esiintyminen, lisääntyminen tai väheneminen näytteessä on merkki sairaudesta tai sen asteesta. Analyytti ei ole sama kuin antigeeni, joka on elimistölle vieras, immuunivasteen aiheuttava rakenne, vaikka immunomäärityksessä analyytti tunnistetaan vasta-aineella.",
  3, L('analyytti')),
K("Mikä on biomerkkiaine?",
  "Tekijä tai ominaisuus, joka ilmentää eliön biologisen tilan muutosta ja liittyy tiettyyn tautitilaan.",
  "Biomerkkiaine on analyytti, jonka pitoisuus kertoo tietystä tautitilasta. Runsas sydämen troponiini veressä merkitsee sydäninfarktia, korkea PSA eturauhassyöpää ja korkea TSH kilpirauhasen vajaatoimintaa. Merkkiaineen mittaus mahdollistaa diagnoosin, hoidon seurannan ja seulonnan ilman kudosnäytettä. Uusien merkkiaineiden etsiminen syöpiin ja sydänkohtaukseen on immunomääritystutkimuksen keskeinen kohde. Kutsutaan myös: biomarkkeri, merkkiaine.",
  3, L('biomerkkiaine', 'biomarkkeri', 'merkkiaine')),
K("Mikä on kvalitatiivinen määritys?",
  "Määritys, jonka tulos on laadullinen: positiivinen tai negatiivinen.",
  "Kvalitatiivinen määritys kertoo vain, onko analyyttia näytteessä vai ei. Tulos luetaan plussana tai miinuksena, kuten raskaustestissä, jossa virtsan istukkahormoni näkyy testiviivana tai jää näkymättä. Tällainen testi on nopea ja yksinkertainen tulkita, mutta se ei kerro analyytin määrää eikä siten sairauden astetta tai hoidon vaikutusta. Positiivisen ja negatiivisen raja on asetettu tietylle pitoisuudelle, jonka ylittyminen tulkitaan positiiviseksi.",
  3, L(['kvalitatiivinen määritys', 'kvalitatiivisen määrityksen', 'kvalitatiivista määritystä', 'kvalitatiivisessa määrityksessä', 'kvalitatiiviset määritykset', 'kvalitatiivisia määrityksiä', 'kvalitatiivinen', 'kvalitatiivisen', 'kvalitatiivista'])),
K("Mikä on kvantitatiivinen määritys?",
  "Määritys, jonka tulos on analyytin pitoisuus lukuarvona.",
  "Kvantitatiivinen määritys antaa määrällisen tuloksen: analyytin pitoisuuden lukuna, esimerkiksi veren glukoosin, jonka normaali pitoisuus on 4–7 mmol/ℓ. Tulos saadaan vertaamalla näytteen signaalia tunnetun pitoisuuden standardeista tehtyyn standardisuoraan, joten kvantitatiivinen määritys on aina kalibroitava. Se mahdollistaa sairauden asteen arvioinnin ja hoidon seurannan ajan mittaan. Esimerkiksi troponiinin pitoisuus kertoo sydänlihasvaurion laajuudesta.",
  3, L(['kvantitatiivinen määritys', 'kvantitatiivisen määrityksen', 'kvantitatiivista määritystä', 'kvantitatiivisessa määrityksessä', 'kvantitatiiviset määritykset', 'kvantitatiivisia määrityksiä', 'kvantitatiivinen', 'kvantitatiivisen', 'kvantitatiivista'])),
K("Mikä on semikvantitatiivinen määritys?",
  "Määritys, jonka tulos on karkea arvio määrästä tietyillä alueilla: ei yhtään, vähän tai paljon.",
  "Semikvantitatiivinen eli puolimäärällinen määritys sijoittaa tuloksen muutamaan luokkaan tarkan lukuarvon sijasta. Esimerkiksi tulehdusmerkkiaine CRP:n pikatestissä tulos luetaan värikartalta, joka kertoo, onko pitoisuus matala, kohonnut vai korkea. Tällainen testi sopii vieritestaukseen, jossa laite on yksinkertainen ja päätös tarvitaan nopeasti. Tarkkaan lukuarvoon ei päästä, mutta hoitopäätökseen luokka usein riittää, kuten antibiootin tarpeen arvioinnissa.",
  2, L(['semikvantitatiivinen määritys', 'semikvantitatiivisen määrityksen', 'semikvantitatiivista määritystä', 'semikvantitatiiviset määritykset', 'semikvantitatiivinen', 'semikvantitatiivisen', 'puolimäärällinen', 'puolimäärällisen'])),
K("Mikä on standardi määrityksessä?",
  "Näyte, joka sisältää tunnetun määrän analyyttia ja jolla määritys kalibroidaan.",
  "Standardit ovat liuoksia, joissa analyytin pitoisuus tunnetaan. Yleensä on yksi korkean pitoisuuden standardimateriaali, josta tehdään laimennossarja: yksi pitoisuus mitattavan alueen alapuolella tai alarajalla, yksi yläpuolella ja pitoisuuksia tasaisesti näiden välillä. Standardien antamista signaaleista piirretään standardisuora, jonka avulla tuntemattoman näytteen pitoisuus luetaan. Kutsutaan myös: kalibraattori. Standardit mitataan samassa ajossa kuin näytteet, jotta reagenssien ja laitteen vaihtelu ei vääristä tulosta.",
  2, L('standardi', ['kalibraattori', 'kalibraattorin', 'kalibraattoria', 'kalibraattorit'])),
K("Mikä on standardisuora?",
  "Standardien signaaleista piirretty suora, josta näytteen pitoisuus luetaan sen signaalin perusteella.",
  "Kuvassa standardit 1, 4, 8, 12, 16 ja 20 mmol/ℓ on mitattu ja niiden signaalit piirretty pitoisuuden funktiona. Pisteiden kautta sovitettu suora on standardisuora. Kun tuntemattoman näytteen signaali on 3031, sitä vastaava pitoisuus luetaan suoralta: 10 mmol/ℓ. Suora tehdään joka määrityskerralla, koska reagenssien ja laitteen vaste voi vaihtelevat. Kutsutaan myös: kalibrointisuora, standardikäyrä.",
  3, L('standardisuora', ['kalibrointisuora', 'kalibrointisuoran', 'kalibrointisuoraa', 'standardikäyrä', 'standardikäyrän', 'standardikäyrää']), 'biotek_standardisuora.png'),
K("Mitkä ovat bioteknisten määritysten kolme tyyppiä?",
  "Entsyymimääritykset, immunomääritykset ja nukleiinihappomääritykset.",
  "Entsyymimäärityksessä analyytin havaitseminen perustuu entsyymiaktiivisuuteen, ja analyytti on joko substraatti tai entsyymi itse. Immunomäärityksessä havaitseminen perustuu vasta-aineen sitoutumiseen analyyttiin, joka on proteiini tai pienmolekyyli, kuten hormoni. Nukleiinihappomäärityksessä tunnistetaan DNA:n tai RNA:n nukleoemäsjärjestys, esimerkiksi taudinaiheuttajan perimä. Immunomääritykset ovat näistä laajin ryhmä, koska vasta-aine voidaan tehdä lähes mille tahansa molekyylille. Nukleiinihappomäärityksistä kerrotaan tarkemmin seuraavalla luennolla.",
  3),
K("Mikä on entsyymimääritys?",
  "Määritys, jossa analyytti havaitaan entsyymiaktiivisuuden perusteella. Analyytti on substraatti tai entsyymi.",
  "Entsyymimääritykset olivat ensimmäisiä bioteknisiä määrityksiä. Entsyymin pitoisuus selvitetään mittaamalla sen aktiivisuus näytteessä, esimerkiksi maksan toiminnasta kertovat transaminaasit veressä. Substraatin pitoisuus mitataan käyttämällä hyväksi entsyymiä, joka muuttaa sen tuotteeksi havaittavalla tavalla, kuten värimuutoksena: veren glukoosi määritetään glukoosioksidaasilla. Reaktion nopeus on verrannollinen entsyymin määrään ja tuotteen määrä substraatin määrään, joten kumpikin voidaan lukea signaalista.",
  3, L('entsyymimääritys')),
K("Mikä on immunomääritys?",
  "Määritys, jossa analyytti tunnistetaan ja mitataan siihen sitoutuvan vasta-aineen avulla.",
  "Immunomääritys perustuu vasta-aineen sitoutumiseen antigeeniinsa. Potilasnäytteestä voidaan mitata hormonipitoisuuksia, lääke- ja huumausaineita, syöpään liittyviä proteiineja, tarttuvien tautien merkkiaineita ja potilaan omia vasta-aineita. Määritystyypit ovat ei-kilpaileva eli immunometrinen sandwich-määritys ja kilpaileva määritys, ja toteutukseltaan ne ovat heterogeenisiä, joissa sitoutumaton pestään pois, tai homogeenisia, joissa pesuja ei tarvita. Kutsutaan myös: immunoassay.",
  3, L('immunomääritys')),
K("Mikä on kiintokantaja?",
  "Kiinteä pinta, johon sitojavasta-aine on kiinnitetty ja joka mahdollistaa sitoutuneen erottamisen sitoutumattomasta.",
  "Kiintokantajaan kiinnitetty vasta-aine pidättää analyytin, ja kaikki sitoutumaton voidaan pestä pois, mikä tekee heterogeeniset määritykset mahdollisiksi. Vaihtoehtoja ovat mikrotiitterilevyn muovikaivo, magneettinen mikropartikkeli, muovipartikkeli ja nitroselluloosamembraani. Kantajan valinta vaikuttaa olennaisesti määrityksen toimintaan ja suorituskykyyn. Kutsutaan myös: solid phase, capture phase. Partikkelit tarjoavat suuremman sitojapinnan ja nopeamman kinetiikan kuin kaivon seinä, ja magneettiset partikkelit kerätään magneetilla.",
  2, L('kiintokantaja')),
K("Mikä on mikrotiitterilevy?",
  "Muovilevy, jossa on yleensä 96 kaivoa, joihin reaktiot tehdään 50–200 µℓ:n tilavuuksissa.",
  "",
  2, L(['mikrotiitterilevy', 'mikrotiitterilevyn', 'mikrotiitterilevyä', 'mikrotiitterilevyssä', 'mikrotiitterilevystä', 'mikrotiitterilevyyn', 'mikrotiitterilevyt', 'mikrotiitterilevyjen', 'mikrotiitterilevyjä', 'mikrotiitterilevyillä', 'kuoppalevy', 'kuoppalevyn', 'kuoppalevyä', 'kuoppalevyllä', 'mikrotiitterikaivo', 'mikrotiitterikaivon', 'mikrotiitterikaivoa'])),
K("Mikä on leima immunomäärityksessä?",
  "Vasta-aineeseen tai analyyttiin kiinnitetty molekyyli, joka tuottaa mitattavan signaalin.",
  "Leima tuottaa mitattavan signaalin ja mahdollistaa siten analyytin havaitsemisen ja pitoisuuden määrittämisen. Se kiinnitetään yleensä analyytin tunnistavaan vasta-aineeseen, kilpailevassa määrityksessä analyytin analogiin. Leima voi olla radioaktiivinen atomi, fluoresoiva molekyyli, entsyymi, joka tuottaa substraatista värin tai sähköisen signaalin, tai värillinen tai valoa tuottava nanopartikkeli. Kutsutaan myös: label.",
  3, L('leima', ['leimavasta-aine', 'leimavasta-aineen', 'leimavasta-ainetta', 'leimattu vasta-aine', 'leimatun vasta-aineen', 'leimattua vasta-ainetta'])),
K("Mitä leimoja immunomäärityksissä käytetään?",
  "Radioaktiivisia atomeja, fluoresoivia molekyylejä, entsyymejä ja värillisiä tai valoa tuottavia nanopartikkeleita.",
  "Radioaktiivinen atomi on vanhin leima, mutta epäherkkä ja epäkäytännöllinen säteilyn takia. Fluoresoiva molekyyli tuottaa valoa virittävässä valossa. Entsyymileima saa aikaan värireaktion tai sähköisen signaalin, kun substraattia lisätään, ja monistaa signaalia, koska yksi entsyymi tuottaa paljon tuotetta. Värilliset tai valoa tuottavat nanopartikkelit ovat vieritestien leimoja, kuten raskaustestin kultapartikkelit.",
  2),
K("Mitä inkubointi tarkoittaa immunomäärityksessä?",
  "Reaktion antamista tapahtua tietyissä olosuhteissa tietyn ajan, esimerkiksi 37 °C:ssa ravistelussa tunnin.",
  "",
  2, L('inkubointi', ['inkubaatio', 'inkubaation', 'inkubaatiota', 'inkubaatiossa', 'inkuboida', 'inkuboidaan', 'inkubaattori', 'inkubaattorin', 'inkubaattoria', 'inkubaattorissa'])),
K("Mitä määrityksen herkkyys tarkoittaa?",
  "Kykyä havaita luotettavasti hyvin pieniä analyytin pitoisuuksia. Mitä pienempi pitoisuus havaitaan, sitä parempi herkkyys.",
  "Herkkyys testataan mittaamalla signaalin taso ja hajonta nollapitoisuudessa, jossa analyyttia ei ole, sekä pienillä näytepitoisuuksilla. Pienin pitoisuus, jonka signaali erottuu luotettavasti nollanäytteen signaalin hajonnasta, on määrityksen havaitsemisraja. Immunometrinen määritys on yleensä herkempi kuin kilpaileva, koska sen nollasignaali on matala. Kutsutaan myös: sensitivity. Herkkyyttä parantavat voimakas leima, matala tausta ja tiheä sitojapinta.",
  3, L('herkkyys', ['havaitsemisraja', 'havaitsemisrajan', 'havaitsemisrajaa'])),
K("Mikä on immunometrinen määritys?",
  "Ei-kilpaileva sandwich-määritys, jossa analyytti jää kiintokantajan vasta-aineen ja leimatun vasta-aineen väliin.",
  "Immunometrisessä määrityksessä kiintokantajan sitojavasta-aine pidättää analyytin ja leimattu vasta-aine sitoutuu analyytin toiseen epitooppiin, joten analyytti jää kahden vasta-aineen väliin kuin voileivän täyte. Reagensseja käytetään ylimäärin ja sitoutumaton pestään pois. Mitä enemmän analyyttia näytteessä on, sitä enemmän leimaa sitoutuu ja sitä suurempi on signaali. Kutsutaan myös: sandwich-määritys, kaksipuoleinen määritys, ei-kilpaileva määritys.",
  3, L(['immunometrinen määritys', 'immunometrisen määrityksen', 'immunometristä määritystä', 'immunometrisessä määrityksessä', 'immunometriseen määritykseen', 'immunometriset määritykset', 'immunometrisiä määrityksiä', 'sandwich-määritys', 'sandwich-määrityksen', 'sandwich-määritystä', 'ei-kilpaileva määritys', 'ei-kilpailevan määrityksen', 'ei-kilpailevaa määritystä']), 'biotek_immunometrinen.png'),
K("Miten immunometrinen määritys etenee vaihe vaiheelta?",
  "Näyte kaivoon, analyytti sitoutuu ja loput pestään pois, leimattu vasta-aine ylimäärin, pesu, signaalin mittaus.",
  "Ensin näytemateriaali lisätään kaivoon, jonka pintaan on kiinnitetty sitojavasta-aine, ja analyytti sitoutuu siihen. Sitoutumaton näytemateriaali pestään pois. Sitten lisätään leimattua vasta-ainetta ylimäärin, ja se sitoutuu analyytin toiseen epitooppiin. Sitoutumaton leimavasta-aine pestään pois, ja lopuksi mitataan leiman signaali, esimerkiksi fluoresenssi, ja pitoisuus luetaan standardisuoralta. Pesut ovat olennaisia: ilman niitä sitoutumaton leima antaisi signaalin ilman analyyttia.",
  3),
K("Mikä on kilpaileva immunomääritys?",
  "Määritys, jossa näytteen analyytti ja leimattu analyytin analogi kilpailevat sitoutumisesta vasta-aineeseen. Enemmän analyyttia, vähemmän signaalia.",
  "Kilpailevassa määrityksessä näytteeseen lisätään leimattua analyyttia tai sen analogia, ja näytteen oma analyytti ja leimattu analyytti kilpailevat kiintokantajan vasta-aineen rajallisista sitoutumispaikoista. Sitoutuneen leimatun ja leimaamattoman analyytin suhde riippuu niiden pitoisuuksien suhteesta: mitä enemmän analyyttia näytteessä on, sitä vähemmän leimaa sitoutuu ja sitä pienempi on signaali. Kutsutaan myös: competitive assay, limited reagent assay.",
  3, L(['kilpaileva määritys', 'kilpailevan määrityksen', 'kilpailevaa määritystä', 'kilpailevassa määrityksessä', 'kilpailevaan määritykseen', 'kilpailevat määritykset', 'kilpailevia määrityksiä', 'kilpaileva immunomääritys', 'kilpailevan immunomäärityksen', 'kilpailevaa immunomääritystä', 'kilpailevassa immunomäärityksessä']), 'biotek_kilpaileva.png'),
K("Miten kilpaileva immunomääritys etenee vaihe vaiheelta?",
  "Näyte ja leimattu analyytti kaivoon, molemmat kilpailevat vasta-aineesta, sitoutumaton pestään pois, signaali mitataan.",
  "Näytemateriaali lisätään kaivoon yhdessä leimatun analyytin kanssa. Näytteen analyytti ja leimattu analyytti kilpailevat sitoutumisesta kiintokantajan vasta-aineeseen, jolloin sitoutuneiden suhde vastaa pitoisuuksien suhdetta. Ylimääräinen sitoutumaton näytteen analyytti ja leimattu analyytti pestään pois. Leiman signaali mitataan ja pitoisuus luetaan standardisuoralta, joka on laskeva. Kun analyyttia ei ole lainkaan, signaali on suurimmillaan.",
  3),
K("Miten kilpaileva ja immunometrinen määritys eroavat ja milloin kumpaakin käytetään?",
  "Immunometrinen on herkempi ja vaatii kaksi epitooppia. Kilpailevaa käytetään pienille analyyteille, joissa on vain yksi epitooppi.",
  "Kilpailevassa määrityksessä nollatason signaali on suuri, joten tarvitaan melko suuri pitoisuuden muutos, jotta signaali eroaa nollatasosta. Immunometrinen määritys mittaa siksi yleensä pienempiä pitoisuuksia. Immunometriseen määritykseen tarvitaan kuitenkin kahteen eri epitooppiin samanaikaisesti sitoutuvat vasta-aineet, eikä pienestä analyytista löydy kahta erillistä epitooppia. Siksi steroidit, lääke- ja huumausaineet, lipidit ja peptidit määritetään kilpailevalla määrityksellä.",
  3),
K("Mikä on heterogeeninen määritys?",
  "Määritys, jossa sitoutunut ja sitoutumaton erotetaan pesuvaiheilla kiintokantajan avulla.",
  "Heterogeenisessa määrityksessä reaktio tapahtuu kiintokantajan pinnalla, ja jokaisen vaiheen jälkeen sitoutumattomat molekyylit pestään pois. Pesut poistavat näytteen muut aineet ja ylimääräisen leiman, joten tausta on matala ja herkkyys hyvä, mutta määritys vaatii useita työvaiheita ja enemmän aikaa. Sekä immunometrinen että kilpaileva määritys voidaan tehdä heterogeenisena.",
  2, L(['heterogeeninen määritys', 'heterogeenisen määrityksen', 'heterogeenistä määritystä', 'heterogeenisessä määrityksessä', 'heterogeeniset määritykset', 'heterogeenisiä määrityksiä'])),
K("Mikä on homogeeninen määritys?",
  "Erotusvapaa määritys, jossa reaktio tapahtuu liuoksessa eikä pesuvaiheita tarvita.",
  "Homogeenisessa määrityksessä käytetään leimoja, joiden signaali muuttuu, kun leimattu vasta-aine sitoutuu analyyttiin. Sitoutumattomat vasta-aineet eivät tuota signaalia, joten ylimäärää ei tarvitse pestä pois. Etuja ovat nopea kinetiikka liuoksessa ja yksinkertainen laitteisto, mikä sopii vieritestaukseen ja suuriin näytemääriin. Kutsutaan myös: erotusvapaa määritys, separation-free assay. Esimerkiksi fluoresenssin energiansiirtoon perustuvat leimat syttyvät vasta, kun kaksi vasta-ainetta kohtaavat samalla analyytilla.",
  2, L(['homogeeninen määritys', 'homogeenisen määrityksen', 'homogeenistä määritystä', 'homogeenisessä määrityksessä', 'homogeeniset määritykset', 'homogeenisiä määrityksiä', 'erotusvapaa määritys', 'erotusvapaan määrityksen', 'erotusvapaata määritystä'])),
K("Mikä on monianalyyttimääritys?",
  "Testi, jossa samasta näytteestä määritetään useita analyytteja samalla kertaa.",
  "Monianalyyttimäärityksessä eri analyytteja tunnistavissa vasta-aineissa on eri leimat, tai analyytit erotellaan signaalin paikan perusteella mikrosiruteknologialla, jossa kukin vasta-aine on omassa pisteessään. Näin yhdestä näytteestä saadaan kerralla esimerkiksi kokonainen merkkiainepaneeli. Kutsutaan myös: multiplex-määritys. Näin säästetään näytettä, aikaa ja reagensseja, ja merkkiaineiden yhdistelmä voi olla yksittäistä tarkempi diagnoosin perusta.",
  1, L('monianalyyttimääritys', ['multiplex', 'multiplex-määritys', 'multiplex-määrityksen', 'multiplex-määritystä'])),
K("Mihin ultraherkät määritykset perustuvat?",
  "Enemmän signaalia tuottaviin leimoihin ja yksittäisten molekyylien havaitsemiseen eli digitaalisiin määrityksiin.",
  "",
  1),
K("Mikä on rekombinanttivasta-aine diagnostiikassa?",
  "Bioteknisesti muokattu vasta-aine tai sen osa, joka tunnistaa antigeenin tehokkaammin, spesifisemmin ja nopeammin.",
  "Rekombinanttivasta-aineet tuotetaan geenikirjastoista soluissa ilman eläimiä, ja niitä voidaan muokata: pienentää fragmenteiksi, parantaa sitoutumista ja poistaa ristireaktioita. Diagnostiikassa ne antavat tehokkaamman, spesifisemmän ja nopeamman antigeenin tunnistuksen, tiheän ja tehokkaan sitojapinnan kiintokantajalle sekä vähemmän näytteistä aiheutuvia häiriöitä. Todellisuudessa pinnalle kiinnittyneet vasta-aineet ovat kuitenkin harvemmassa ja sekalaisemmin kuin kaaviot lupaavat.",
  2, L('rekombinanttivasta-aine')),
K("Mikä on vieritesti?",
  "Potilaan lähellä, laboratorion ulkopuolella tehtävä nopea määritys.",
  "Vieritestaus tuo määrityksen potilaan luo: vastaanotolle, ambulanssiin tai kotiin, ilman keskuslaboratoriota. Testin on oltava yksinkertainen, nopea ja laitteistoltaan kevyt, joten ne perustuvat usein lateraalivirtaukseen tai homogeenisiin määrityksiin, ja tulos on kvalitatiivinen tai semikvantitatiivinen. Kehityssuuntia ovat mikrofluidiikka ja lab-on-a-chip-laitteet, joissa koko määritys tehdään pienellä sirulla. Kutsutaan myös: potilasläheinen diagnostiikka, point-of-care.",
  2, L('vieritesti', ['vieritestaus', 'vieritestauksen', 'vieritestausta', 'vieritestauksessa', 'potilasläheinen diagnostiikka', 'potilasläheisen diagnostiikan', 'potilasläheistä diagnostiikkaa', 'point-of-care'])),
K("Mikä on lateraalivirtaus-immunomääritys?",
  "Liuska, jossa näyte virtaa kapillaarisesti leimatun vasta-aineen ohi testiviivalle ja kontrolliviivalle.",
  "Näyte, kuten veri tai virtsa, imeytyy liuskaan ja liuottaa mukaansa partikkelilla leimatun vasta-aineen, joka sitoo analyytin. Neste virtaa testiviivalle, jonka kiinnitetty vasta-aine pysäyttää analyytti-leima-kompleksin, jolloin viiva värjäytyy positiivisessa näytteessä. Kontrolliviiva sitoo ylimääräisen leimavasta-aineen ja osoittaa, että testi toimi. Näin toimivat raskaustesti sekä malarian, koronan, hinkuyskän, HIV:n, hepatiitin ja sinilevien pikatestit. Kutsutaan myös: lateral flow, pikatesti.",
  2, L(['lateraalivirtaus-immunomääritys', 'lateraalivirtaus-immunomäärityksen', 'lateraalivirtaus-immunomääritystä', 'lateraalivirtaus', 'lateraalivirtauksen', 'lateraalivirtausta', 'lateraalivirtaustesti', 'lateraalivirtaustestin', 'lateraalivirtaustestiä', 'pikatesti', 'pikatestin', 'pikatestiä', 'pikatestissä', 'pikatestit', 'pikatestien', 'pikatestejä'])),
K("Mitä immunomäärityksiin liittyvää tutkitaan Turun yliopiston biotekniikan osastolla?",
  "Syövän ja sydänkohtauksen merkkiaineita, sitojavasta-aineita, leimoja ja määritysteknologioita, ympäristödiagnostiikkaa ja vieritestejä.",
  "Merkkiainetutkimuksessa etsitään syöpämerkkiaineita, kuten harvinaisia glykosylaatiomuunnoksia rinta-, rakko-, munasarja-, suoli-, haima- ja eturauhassyövissä, sekä sydänkohtauksen merkkiaineita, kuten sydämen troponiini I ja PAPP-A, joiden äkillisesti ilmestyviä pieniä määriä havaitaan. Lisäksi kehitetään sitojavasta-aineita, leimoja ja määritysteknologioita, ympäristödiagnostiikkaan sinilevätestiä ja potilasläheiseen diagnostiikkaan mikrofluidistisia immunomäärityksiä. Tutkimus yhdistää vasta-ainekehityksen, leimateknologian ja laitesuunnittelun kliiniseen tarpeeseen.",
  1),
K("Miten immunomäärityksiä käytetään lääkekehityksessä?",
  "Suuren kapasiteetin seulonnassa: mitataan, löytyykö lääkeaineella käsitellyistä soluista tautiin liittyvää proteiinia.",
  "",
  1),
K("Mikä oli Theranos?",
  "Piilaakson in vitro -diagnostiikan yritys, joka väitti mittaavansa satoja analyytteja sormenpäänäytteestä ja osoittautui huijaukseksi.",
  "",
  1),
]
