# -*- coding: utf-8 -*-
"""Kemian peruskurssi I: kortit luvuittain (kalvot kurssit/Kemian peruskurssi I/). Rakentaa tyokalut/kemia_kortit.py.
Luvun numero on korttinumeron etuosa (2.1 -> 21), koska sivusto lukee jarjestysnumeron liukulukuna."""
from biotek_taivutus import L
from pakka_rakenna import K

PDF1, PDF21, PDF22, PDF31, PDF32 = ('1. Johdanto.pdf', '2.1. Kemian historiaa lyhyesti.pdf', '2.2. Yksinkertaisten yhdisteiden nimeäminen.pdf',
                                     '3.1. Atomin rakenne ja jaksollinen järjestelmä.pdf', '3.2. Kvanttimekaaninen atomimalli.pdf')

LUENNOT = [
# ── 1. Johdanto ─────────────────────────────────────────────────────────────────────────
dict(LEHTI='Luento 1 - Johdanto', NRO=1, KUVAT={}, KORTIT=[
K("Mitä kemia tutkii?",
  "Mitä aine on, miksi se käyttäytyy niin, miten se muuttuu ja voiko muutoksia ennustaa.",
  "Kemia vastaa neljään kysymykseen. Mitä aine on: sen koostumus ja rakenne. Miksi aine käyttäytyy niin kuin käyttäytyy: sidokset, vuorovaikutukset ja energia. Miten aine muuttuu: kemialliset reaktiot. Voimmeko ennustaa ja kontrolloida muutoksia: mallit, mittaukset ja synteesi. Kemia yhdistää siis atomien ja molekyylien rakenteen aineen havaittaviin ominaisuuksiin, ja juuri tämä yhteys tekee siitä biokemian perustan.",
  3, L(['kemia', 'kemian', 'kemiaa', 'kemiassa', 'kemiasta', 'kemiaan'])),
K("Mikä on tieteellinen menetelmä?",
  "Havainnosta hypoteesiin, kokeelliseen testaukseen ja edelleen teoriaan tai lakiin etenevä tapa tuottaa tietoa.",
  "Tieteellinen menetelmä alkaa havainnosta: ilmiöstä tai ongelmasta, joka herättää kysymyksiä. Hypoteesi on perusteltu arvaus selityksestä. Kokeilussa suunnitellaan ja tehdään kokeita hypoteesin testaamiseksi ja kerätään dataa, joka analysoidaan ja jota verrataan hypoteesiin. Jos havainnot vastaavat ennusteita, hypoteesi saa tukea, muuten sitä muutetaan. Kokeet toistetaan luotettavuuden varmistamiseksi ja tulokset julkaistaan. Toistuvasti vahvistetusta hypoteesista kasvaa teoria eli malli, jonka ennusteita testataan edelleen.",
  3, L(['tieteellinen menetelmä', 'tieteellisen menetelmän', 'tieteellistä menetelmää', 'tieteellisessä menetelmässä', 'tieteelliseen menetelmään'])),
K("Mikä on hypoteesi?",
  "Perusteltu, testattava arvaus siitä, mikä selittää havaitun ilmiön.",
  "Hypoteesi on ehdotettu selitys havainnolle. Sen on oltava perusteltu eli sopusoinnussa tunnetun tiedon kanssa, ja ennen kaikkea testattava: siitä on voitava johtaa ennuste, jonka koe voi osoittaa vääräksi. Sama havainto sopii usein moneen hypoteesiin, joten koe suunnitellaan erottamaan vaihtoehdot toisistaan. Jos havainnot eivät vastaa ennustetta, hypoteesia tai sen taustaoletuksia on tarkasteltava uudelleen.",
  3, L('hypoteesi')),
K("Mitä eroa on teorialla ja luonnonlailla?",
  "Laki kuvaa, mitä toistuvasti tapahtuu. Teoria on malli, joka selittää, miksi.",
  "Luonnonlaki tiivistää toistuvasti havaitun säännönmukaisuuden, kuten massan säilymisen laki: se kertoo, mitä tapahtuu, mutta ei miksi. Teoria on kokeellisesti testattu malli, joka selittää lain ja tuottaa uusia ennusteita, kuten atomiteoria selittää massan säilymisen atomien uudelleenjärjestymisenä. Teoria ei ole arvaus vaan tiedon vahvin muoto, ja sitä tarkennetaan, kun uudet havainnot vaativat muutosta.",
  2, L(['luonnonlaki', 'luonnonlain', 'luonnonlakia', 'luonnonlait', 'luonnonlakien', 'luonnonlakeja', 'teoria', 'teorian', 'teoriaa', 'teoriassa', 'teoriasta', 'teoriaan', 'teoriat', 'teorioiden', 'teorioita'])),
K("Mitkä ovat kemiallisen ongelmanratkaisun vaiheet?",
  "Rajaa ongelma, tunnista muuttujat, muodosta hypoteesi, johda ennuste, suunnittele erotteleva koe, vertaa havaintoja, tarkenna mallia.",
  "Kemiallisessa ongelmassa on usein useita mahdollisia selityksiä ja muuttujia. Ensin rajataan, mitä tarkalleen halutaan selittää, ja tunnistetaan mahdolliset muuttujat. Sitten muodostetaan testattava hypoteesi ja johdetaan siitä ennuste. Koe suunnitellaan niin, että se erottaa vaihtoehtoiset selitykset toisistaan, ja havaintoja verrataan ennusteeseen. Lopuksi mallia tarkennetaan ja testataan uudelleen. Ratkaisu on iteratiivista, mutta ei satunnaista yrityksen ja erehdyksen menetelmää.",
  2),
K("Miksi rauta ruostuu nopeammin suolavedessä ja miten se selvitetään?",
  "Havainnolle on useita hypoteeseja, joita erotellaan kokeilla, joissa muutetaan yhtä muuttujaa kerrallaan.",
  "Havainto on, että teräs ruostuu suolavedessä nopeammin kuin puhtaassa vedessä, ja kemiallinen kysymys, mikä suolassa nopeuttaa korroosiota. Hypoteeseja on useita: natriumkloridi reagoi suoraan raudan kanssa, suola lisää veden sähkönjohtavuutta, kloridi heikentää suojaavaa oksidikerrosta, happi on välttämätön katodiselle reaktiolle, tai useampi on totta yhtä aikaa. Kokeissa verrataan puhdasta vettä, natriumkloridiliuosta, toista suolaa samalla johtavuudella ja hapetonta suolaliuosta.",
  2),
K("Miksi kokeessa muutetaan vain yhtä muuttujaa kerrallaan?",
  "Jotta vaihtoehtoiset selitykset voidaan erottaa toisistaan ja havaittu ero voidaan lukea juuri sen muuttujan tiliin.",
  "Kontrollit ratkaisevat kokeen todistusvoiman. Puhdas vesi on vertailukohta, natriumkloridiliuos testaa suolan vaikutuksen, toinen suola samalla johtavuudella erottaa, onko kyse johtavuudesta vai kloridista, ja hapeton suolaliuos kertoo, tarvitaanko happea. Jos kahta muuttujaa vaihdettaisiin yhtä aikaa, havaittua eroa ei voisi liittää kumpaankaan. Näin sama havainto voidaan sovittaa yhteen selitykseen muiden sijasta.",
  2),
K("Mikä on raudan korroosion kemiallinen malli?",
  "Kytketty hapettumis–pelkistymisprosessi: rauta hapettuu anodilla, happi pelkistyy katodilla.",
  "Anodinen reaktio on Fe → Fe<sup>2+</sup> + 2 e<sup>−</sup>, ja katodinen reaktio neutraalissa, hapellisessa vedessä O<sub>2</sub> + 2 H<sub>2</sub>O + 4 e<sup>−</sup> → 4 OH<sup>−</sup>. Ruostuminen ei siis ole vain raudan reagointia veden kanssa vaan sähkökemiaa, jossa elektronit siirtyvät raudasta hapelle. Suola nopeuttaa ionien kuljetusta liuoksessa, ja kloridi voi lisäksi häiritä suojaavia pintakerroksia.",
  2, L(['korroosio', 'korroosion', 'korroosiota', 'korroosiossa', 'korroosiosta', 'korroosioon', 'ruostuminen', 'ruostumisen', 'ruostumista'])),
]),
# ── 2.1 Kemian historiaa lyhyesti ──────────────────────────────────────────────────────
dict(LEHTI='Luento 2.1 - Kemian historiaa lyhyesti', NRO=21, KUVAT={}, KORTIT=[
K("Miten kemiaa hyödynnettiin esihistoriallisella ajalla?",
  "Metallien valmistus malmeista, lasi, pigmentit ja ensimmäiset synteettiset väri- ja kosmetiikka-aineet.",
  "Egyptiläiset ja mesopotamialaiset oppivat tuottamaan metallia malmeista: kuparia käytettiin noin 4000 eaa. ja pronssia alettiin valmistaa noin 3000 eaa. Lasin valmistus kehittyi suuremmassa mittakaavassa noin 1350 eaa. Varhaisimmat kalliomaalaukset tehtiin luonnon mineraalipigmenteillä, ja egyptiläiset loivat kemiallisilla reaktioilla ensimmäisiä synteettisiä väriaineita, kuten lyijykarbonaatista tehtyä punamultaa, sekä kosmeettisia aineita.",
  1),
K("Mikä oli Empedokleen neljän elementin oppi?",
  "Kaikki aine koostuu maasta, ilmasta, vedestä ja tulesta.",
  "Empedokles esitti noin 450 eaa., että kaikki koostuu neljästä perusaineesta: maasta, ilmasta, vedestä ja tulesta, ja aineiden ominaisuudet syntyvät niiden sekoitussuhteista. Aristoteles omaksui opin eikä hyväksynyt kilpailevaa atomiteoriaa, ja hänen arvovaltansa vuoksi näkemys hallitsi käsityksiä aineesta lähes 2000 vuotta, kunnes Boyle kyseenalaisti sen kokeellisesti 1600-luvulla.",
  1),
K("Mikä oli Demokritoksen atomiteoria?",
  "Aine koostuu jakamattomista osasista, atomeista.",
  "Demokritos esitti antiikin Kreikassa filosofisen atomiteorian: aine koostuu pienimmistä jakamattomista osasista, joita hän kutsui nimellä atomos, jakamaton. Teoria perustui päättelyyn, ei kokeisiin, ja Aristoteles hylkäsi sen neljän elementin opin hyväksi. Ajatus heräsi uudelleen vasta, kun Dalton palautti atomiteorian kemian keskiöön 1800-luvun alussa kokeellisten lakien selittäjänä.",
  2),
K("Mitä alkemia oli ja mitä se jätti perinnöksi kemialle?",
  "Noin 2000 vuoden pyrkimys muuntaa metalleja kullaksi. Perintönä kokeellisuus, laboratoriotekniikat ja uudet aineet.",
  "Kreikkalaisia seurasi alkemian aikakausi, jota harjoitettiin Aleksandriassa, arabimaissa, Euroopassa ja Kiinassa. Alkemistit pyrkivät muuntamaan halvempia metalleja kullaksi, mikä osoittautui mahdottomaksi. Työn sivutuotteena he kehittivät laboratoriotekniikoita ja välineitä sekä löysivät uusia aineita: alkoholitislaus ja vahvat hapot, kuten typpihappo, keksittiin alkemian tutkimuksissa. Kemialle jäivät kokeellisuus ja uudet yhdisteet, jotka loivat pohjan tieteen synnylle.",
  2, L('alkemia', ['alkemisti', 'alkemistin', 'alkemistit', 'alkemistien'])),
K("Miten alkemia muuttui tieteeksi 1500- ja 1600-luvuilla?",
  "Metallurgiasta tuli systemaattista (Agricola) ja kemia valjastettiin lääkkeisiin (Paracelsus, iatrokemia).",
  "Saksalainen Georgius Agricola kuvasi metallien jalostusta teoksessaan De re metallica vuonna 1556, ja metallurgiasta kehittyi systemaattinen tutkimusala. Samoihin aikoihin Paracelsus edusti iatrokemiaa, jossa kemia valjastettiin lääkkeiden valmistukseen: hän korosti kokeellisuutta ja paransi hoitoja kemiallisilla keinoilla. Kokeellisten menetelmien ja hyötynäkökulman vahvistuminen loi perustan modernin kemian synnylle.",
  1),
K("Miksi Robert Boylea pidetään ensimmäisenä kemistinä?",
  "Hän teki ensimmäiset tarkat kvantitatiiviset kokeet, kyseenalaisti neljän elementin opin ja määritteli alkuaineen.",
  "Irlantilainen Robert Boyle (1627–1691) suoritti ensimmäiset tarkasti kvantitatiiviset kemialliset kokeet ja kyseenalaisti perinteisen neljän elementin opin. Hän määritteli alkuaineen aineeksi, jota ei voida hajottaa yksinkertaisempiin osiin. Uusi alkuainekäsitys ja kokeellinen lähestymistapa erottivat kemian mystiikasta ja nostivat sen tieteelliselle pohjalle, minkä vuoksi häntä pidetään ensimmäisenä modernina kemistinä.",
  2),
K("Mitä Antoine Lavoisier osoitti ja muotoili?",
  "Palaminen on yhtymistä happeen, massa säilyy reaktioissa, ensimmäinen alkuaineluettelo ja uusi nimistö.",
  "Lavoisier (1743–1794) käynnisti kemian vallankumouksen, ja häntä pidetään nykyaikaisen kemian isänä. Hän osoitti kokeellisesti, että palaminen on aineen yhtymistä happeen, ja kumosi flogistonteorian, jonka mukaan palavasta aineesta poistuu flogiston-ainetta. Hän muotoili massan säilymisen lain, julkaisi ensimmäisen systemaattisen alkuaineiden luettelon ja uudisti kemian nimistöä tehden kemiasta kvantitatiivisen tieteen.",
  3),
K("Mikä on massan säilymisen laki?",
  "Aineen kokonaismassa säilyy muuttumattomana kemiallisessa reaktiossa.",
  "Lavoisier'n muotoilema laki sanoo, että kemiallisessa reaktiossa lähtöaineiden kokonaismassa on sama kuin tuotteiden kokonaismassa. Atomit eivät synny eivätkä häviä vaan järjestäytyvät uudelleen, mikä oli Daltonin atomiteorian selitys laille. Laki tekee reaktioyhtälöiden tasapainottamisesta ja stoikiometrisistä laskuista mahdollisia, ja se edellyttää, että myös kaasumaiset tuotteet otetaan huomioon punnitessa.",
  3, L(['massan säilymisen laki', 'massan säilymisen lain', 'massan säilymisen lakia', 'massan säilyminen', 'massan säilymisen'])),
K("Mikä on vakiosuhteiden laki?",
  "Tietyssä yhdisteessä alkuaineiden massasuhteet ovat aina samat.",
  "Joseph Proust havaitsi, että tietyssä yhdisteessä alkuaineiden massasuhteet ovat aina samat riippumatta siitä, mistä yhdiste on peräisin tai miten se on valmistettu. Esimerkiksi kuparikarbonaatissa kuparin, hapen ja hiilen massasuhde on aina 5,3 : 4 : 1. Laki tuki ajatusta atomien olemassaolosta ja vakioisista yhdisteiden kaavoista, ja Daltonin atomiteoria selitti sen.",
  3, L(['vakiosuhteiden laki', 'vakiosuhteiden lain', 'vakiosuhteiden lakia', 'vakiosuhteiden laissa'])),
K("Mikä oli Daltonin atomiteoria?",
  "Jokainen alkuaine koostuu identtisistä atomeista, jotka yhtyvät yhdisteiksi ja järjestäytyvät reaktioissa uudelleen häviämättä.",
  "John Dalton esitti vuonna 1808, että jokainen alkuaine koostuu identtisistä atomeista, jotka eroavat jonkin perustavanlaatuisen ominaisuuden puolesta muiden alkuaineiden atomeista. Eri alkuaineiden atomit voivat liittyä toisiinsa muodostaen yhdisteitä, mutta kemiallisissa reaktioissa atomit ainoastaan järjestäytyvät uudelleen eivätkä häviä. Teoria selitti Lavoisier'n ja Proustin lait ja vakiinnutti atomikäsitteen, vaikka kokeellinen todistusaineisto atomeista vahvistui vasta myöhemmin.",
  3),
K("Mitä Gay-Lussac havaitsi kaasujen reaktioista?",
  "Kaasut reagoivat yksinkertaisissa tilavuussuhteissa: 2 osaa vetyä ja 1 osa happea antavat 2 osaa vesihöyryä.",
  "",
  2),
K("Mikä on Avogadron laki?",
  "Yhtä suuret tilavuudet eri kaasuja sisältävät samassa lämpötilassa ja paineessa yhtä monta hiukkasta.",
  "Amedeo Avogadro esitti vuonna 1811 hypoteesin, että yhtä suuret kaasutilavuudet sisältävät yhtä monta hiukkasta. Yhdessä Gay-Lussacin tilavuussuhteiden kanssa tästä voitiin päätellä, että kaasumaiset alkuaineet esiintyvät kaksiatomisina molekyyleinä, kuten O<sub>2</sub> ja H<sub>2</sub>, ja saatiin oikeat molekyylikaavat monille yhdisteille. Veden kaavaksi tuli H<sub>2</sub>O, kun sen oli aiemmin luultu olevan HO. Laki loi perustan atomimassojen ja yhdistekaavojen selvittämiselle.",
  3, L(['Avogadron laki', 'Avogadron lain', 'Avogadron lakia', 'Avogadron hypoteesi', 'Avogadron hypoteesin'])),
K("Miten atomimassat saatiin yhtenäisiksi 1800-luvulla?",
  "Berzelius mittasi suhteellisia atomipainoja ja loi alkuainemerkit, Cannizzaro laski massat Avogadron lain avulla 1860.",
  "Jöns Jakob Berzelius mittasi monien alkuaineiden suhteellisia atomipainoja 1810-luvulla ja otti käyttöön nykyisenkaltaiset kirjainlyhenteet alkuaineille. Määritys oli haastavaa, koska yhteisiä standardeja tai selkeää käsitteistöä ei ollut. Vuonna 1860 Stanislao Cannizzaro esitteli vakuuttavan tavan laskea atomimassoja Avogadron lain pohjalta, ja kansainväliset kemistit omaksuivat yhtenäiset atomipainot. Pian sen jälkeen Mendelejev pystyi järjestämään alkuaineet jaksolliseen järjestelmään.",
  1),
K("Mitä Mendelejev teki vuonna 1869?",
  "Järjesti tunnetut alkuaineet jaksolliseen järjestelmään atomipainojen ja ominaisuuksien mukaan.",
  "Dmitri Mendelejev järjesti alkuaineet atomipainon mukaan riveihin niin, että samankaltaiset ominaisuudet toistuivat jaksollisesti samoissa sarakkeissa. Järjestelmä havainnollisti alkuaineiden keskinäiset riippuvuudet ja jätti aukkoja vielä tuntemattomille alkuaineille, joiden ominaisuudet hän ennusti oikein, kuten galliumin ja germaniumin. Nykyinen jaksollinen järjestelmä pohjautuu Mendelejevin ja Lothar Meyerin luokitteluun, mutta järjestysperusteena on järjestysluku.",
  2),
K("Miten J. J. Thomson löysi elektronin ja millainen oli hänen atomimallinsa?",
  "Katodisädekokeilla 1897. Elektroni on kevyt negatiivinen hiukkanen, upotettuna positiiviseen massaan kuin rusinat pullassa.",
  "Thomson osoitti vuonna 1897 katodisädekokeilla, että säteet koostuvat negatiivisesti varatuista, erittäin kevyistä hiukkasista, elektroneista. Hän mittasi elektronin massan ja varauksen suhteen, mikä paljasti massan olevan vain murto-osa atomista. Hänen atomimallissaan negatiiviset elektronit on upotettu tasaisesti positiiviseen, yhtenäiseen atomimassaan, eikä atomissa ole erillistä ydintä. Rutherfordin kultakalvokoe kumosi mallin 1911.",
  2),
K("Mitä Millikan mittasi öljypisarakokeella?",
  "Elektronin alkeisvarauksen, noin 1,602 × 10<sup>−19</sup> C, ja siitä elektronin massan.",
  "Robert Millikan mittasi vuonna 1909 öljypisarakokeella elektronin alkeisvarauksen ensimmäistä kertaa tarkasti: varattujen öljypisaroiden varaukset olivat aina saman perusyksikön monikertoja, joten sähkövaraus on kvantittunut. Yhdistämällä varaus Thomsonin mittaamaan massan ja varauksen suhteeseen voitiin laskea elektronin massa, noin 9,11 × 10<sup>−31</sup> kg. Millikanin työ täydensi Thomsonin löydön osoittamalla, kuinka pieniä elektronin varaus ja massa ovat.",
  2),
K("Mitä Rutherford päätteli kultakalvokokeesta?",
  "Atomissa on pieni, tiheä ja positiivinen ydin, ja suurin osa atomista on tyhjää tilaa.",
  "Ernest Rutherford havaitsi vuonna 1911, että ohueen kultakalvoon ammutuista alfahiukkasista pieni osa siroutui hyvin jyrkästi takaisin, mikä oli vastoin Thomsonin mallia. Hän päätteli, että atomissa täytyy olla erittäin pieni, tiheä ja positiivinen keskus, atomiydin, joka aiheuttaa voimakkaat sironnat. Elektronit ovat etäällä ytimestä, joten suurin osa atomista on tyhjää. Ydinmalli selitti, miksi massa ja positiivinen varaus ovat keskittyneet atomin keskelle.",
  3),
]),
# ── 2.2 Yksinkertaisten yhdisteiden nimeaminen ─────────────────────────────────────────
dict(LEHTI='Luento 2.2 - Yksinkertaisten yhdisteiden nimeäminen', NRO=22, KUVAT={}, KORTIT=[
K("Miksi yhdisteillä on systemaattinen nimi?",
  "Miljoonat yhdisteet vaativat nimen, joka yksilöi yhdisteen ja paljastaa sen koostumuksen yksiselitteisesti.",
  "Tunnettuja yhdisteitä on miljoonia ja määrä kasvaa jatkuvasti, joten sekaannusten välttämiseksi on kehitetty nimeämisjärjestelmä, joka antaa jokaiselle yhdisteelle yksilöivän nimen. Joillakin yhdisteillä on vakiintunut triviaalinimi, kuten vesi ja ammoniakki. Systemaattinen nimi paljastaa koostumuksen: veden nimi divetyoksidi kertoo kaavan H<sub>2</sub>O, kaksi vetyä ja yksi happi. Epäorgaanisten yhdisteiden ryhmät ovat binaariset ioniyhdisteet, moniatomisten ionien yhdisteet, binaariset kovalenttiyhdisteet ja hapot.",
  2),
K("Mikä on triviaalinimi?",
  "Yhdisteen vakiintunut arkinimi, joka ei kerro koostumusta, kuten vesi tai ammoniakki.",
  "",
  2, L('triviaalinimi')),
K("Mikä on molekyyli?",
  "Pysyvä atomien yhdelmä, jossa atomit jakavat elektroneja kovalenttisin sidoksin.",
  "Kun atomit jakavat elektroneja, niiden välille syntyy kovalenttinen sidos, ja syntyvää pysyvää atomien yhdelmää kutsutaan molekyyliksi. Molekyyli on pienin yhdisteen osanen, jolla on yhdisteen ominaisuudet: vesimolekyyli koostuu kahdesta vedystä ja yhdestä hapesta. Myös alkuaineet voivat esiintyä molekyyleinä, kuten happi O<sub>2</sub>. Ioniyhdisteet eivät muodosta molekyylejä vaan ionikiteitä, joissa ionit ovat säännöllisessä hilassa.",
  3, L('molekyyli')),
K("Mikä on ioniyhdiste?",
  "Yhdiste, jossa kationit ja anionit ovat sitoutuneet toisiinsa ionisidoksin.",
  "Kun atomi luovuttaa elektroneja ja toinen vastaanottaa ne, syntyy ionisidos ja pysyvää yhdistelmää kutsutaan ioniyhdisteeksi. Tyypillisesti metalli luovuttaa elektronit ja muodostaa kationin, epämetalli vastaanottaa ne ja muodostaa anionin. Ioniyhdiste ei koostu erillisistä molekyyleistä vaan ionikiteestä, jossa vastakkaismerkkiset ionit vuorottelevat, ja kaava kertoo ionien pienimmän suhteen, kuten NaCl tai CaCl<sub>2</sub>.",
  3, L('ioniyhdiste', ['ionikide', 'ionikiteen', 'ionikidettä', 'ionikiteessä', 'ionikiteet'])),
K("Mikä on ioni?",
  "Sähköisesti varautunut atomi tai atomiryhmä, joka on luovuttanut tai vastaanottanut elektroneja.",
  "Ioni syntyy, kun atomi tai atomiryhmä luovuttaa tai vastaanottaa elektroneja, jolloin protonien ja elektronien määrät eivät enää ole yhtä suuret. Positiivinen ioni on kationi, negatiivinen anioni. Yksiatomiset ionit, kuten Na<sup>+</sup> ja Cl<sup>−</sup>, muodostavat ioniyhdisteitä, ja moniatomiset ionit, kuten sulfaatti SO<sub>4</sub><sup>2−</sup>, ovat kovalenttisesti sitoutuneita ryhmiä, joilla on kokonaisvaraus. Ionien vetovoima on ionisidoksen perusta.",
  3, L('ioni')),
K("Mikä on kationi?",
  "Positiivinen ioni, joka on luovuttanut elektroneja. Tyypillisesti metalli.",
  "Kationi syntyy, kun atomi luovuttaa yhden tai useamman elektronin, jolloin protoneja jää enemmän kuin elektroneja ja ionin varaus on positiivinen. Metallit muodostavat kationeja helposti: natrium luovuttaa yhden elektronin ja muodostaa Na<sup>+</sup>-ionin, kalsium kaksi ja muodostaa Ca<sup>2+</sup>-ionin. Kationi nimetään alkuaineen nimellä, natrium-ioni, ja se kirjoitetaan kaavassa ja nimessä ensin. Moniatominen kationi on esimerkiksi ammonium.",
  3, L('kationi')),
K("Mikä on anioni?",
  "Negatiivinen ioni, joka on vastaanottanut elektroneja. Tyypillisesti epämetalli.",
  "Anioni syntyy, kun atomi vastaanottaa elektroneja, jolloin elektroneja on enemmän kuin protoneja ja varaus on negatiivinen. Epämetallit muodostavat anioneja: kloori vastaanottaa yhden elektronin ja muodostaa kloridin Cl<sup>−</sup>, happi kaksi ja muodostaa oksidin O<sup>2−</sup>. Yksiatominen anioni nimetään alkuaineen nimen kantaosasta päätteellä -idi. Moniatomiset anionit, kuten sulfaatti ja nitraatti, ovat happea sisältäviä oksoanioneja.",
  3, L('anioni')),
K("Mikä on binaarinen ioniyhdiste?",
  "Kahden alkuaineen ioniyhdiste: metallin kationi ja epämetallin anioni, kuten NaCl tai MgO.",
  "Binaarinen ioniyhdiste koostuu kahdesta alkuaineesta: metallin muodostamasta positiivisesta ionista eli kationista ja epämetallin muodostamasta negatiivisesta ionista eli anionista. Esimerkkejä ovat natriumkloridi NaCl, kalsiumsulfidi CaS, kalsiumkloridi CaCl<sub>2</sub>, litiumnitridi Li<sub>3</sub>N ja magnesiumoksidi MgO. Ionien lukumäärät kaavassa ovat sellaiset, että yhdisteen kokonaisvaraus on nolla.",
  3, L(['binaarinen ioniyhdiste', 'binaarisen ioniyhdisteen', 'binaarista ioniyhdistettä', 'binaariset ioniyhdisteet', 'binaaristen ioniyhdisteiden', 'binaarisia ioniyhdisteitä'])),
K("Miten binaarinen ioniyhdiste nimetään?",
  "Kationi alkuaineen nimellä ensin, anioni kantaosasta päätteellä -idi: NaCl on natriumkloridi.",
  "Kationi nimetään alkuaineen nimellä, esimerkiksi Na<sup>+</sup> natrium-ioni ja Ca<sup>2+</sup> kalsium-ioni. Anioni nimetään alkuaineen nimen kantaosasta ja päätteestä -idi: Cl<sup>−</sup> kloridi, O<sup>2−</sup> oksidi, N<sup>3−</sup> nitridi. Kationi kirjoitetaan ensin sekä kaavassa että nimessä, joten NaCl on natriumkloridi ja CaS kalsiumsulfidi. Ionien lukumäärä ilmaistaan kaavassa alaindeksillä ja nimessä tarvittaessa etuliitteellä.",
  3),
K("Mitkä ovat lukumäärän kreikkalaiset etuliitteet?",
  "Mono 1, di 2, tri 3, tetra 4, penta 5, heksa 6, hepta 7, okta 8, nona 9, deka 10.",
  "Ionien tai atomien lukumäärä ilmoitetaan tarvittaessa kreikan lukusanoihin perustuvilla etuliitteillä: mono-, di-, tri-, tetra-, penta-, heksa-, hepta-, okta-, nona- ja deka-. Harvemmin tarvitaan hendeka- (11) ja dodeka- (12), ja murto-osille hemi- (½) ja seskvi- (3/2). Etuliite liitetään suoraan alkuaineen nimeen ilman yhdysviivaa, ja sen loppuvokaalin voi jättää pois kielenasun selkiyttämiseksi: tetraoksidi on myös tetroksidi.",
  3),
K("Milloin lukumäärän etuliite jätetään pois?",
  "Yksiselitteisissä tapauksissa, erityisesti mono-: Li<sub>3</sub>N on litiumnitridi ilman tri-etuliitettä.",
  "Etuliitteet voidaan jättää pois, kun ionien varaukset määräävät kaavan yksiselitteisesti. Litiumnitridi riittää nimeksi, koska Li<sup>+</sup> ja N<sup>3−</sup> yhdistyvät vain suhteessa 3 : 1, ja mono- jätetään lähes aina pois. Etuliitteitä tarvitaan, kun samat alkuaineet muodostavat useita yhdisteitä, kuten typen oksidit, tai kun metallilla on useita mahdollisia varauksia, jolloin vaihtoehtona on roomalainen numero.",
  2),
K("Miten nimetään metallin yhdiste, kun metallilla on useita hapetuslukuja?",
  "Kationin varaus merkitään roomalaisella numerolla sulkeissa: FeCl<sub>2</sub> on rauta(II)kloridi, FeCl<sub>3</sub> rauta(III)kloridi.",
  "Jos metalliatomi voi esiintyä ioneissa eri hapetusluvuilla, kationin varaus merkitään nimen perään roomalaisella numerolla sulkeissa. FeCl<sub>2</sub> on rauta(II)kloridi, jossa rauta on Fe<sup>2+</sup>, ja FeCl<sub>3</sub> rauta(III)kloridi, jossa rauta on Fe<sup>3+</sup>. Vastaavasti Cu<sub>2</sub>O on kupari(I)oksidi ja CuO kupari(II)oksidi. Numero on välttämätön, koska pelkkä rautakloridi ei kertoisi, kumpi yhdiste on kyseessä.",
  3),
K("Mitkä ovat epämetallien anioninimien kantaosat?",
  "Karb- (karbidi), nitr- (nitridi), fosf- (fosfidi), oks- (oksidi), sulf- (sulfidi), hydr- (hydridi).",
  "Monien alkuaineiden anioninimi muodostetaan hieman muuntuneesta kantaosasta. Hiilen anioni C<sup>4−</sup> on karbidi, typen N<sup>3−</sup> nitridi, fosforin P<sup>3−</sup> fosfidi, hapen O<sup>2−</sup> oksidi, rikin S<sup>2−</sup> sulfidi, jolle käytetään tietyissä yhdisteissä myös tio-etuliitettä, ja vedyn H<sup>−</sup> hydridi. Halogeenien anionit ovat fluoridi, kloridi, bromidi ja jodidi.",
  2),
K("Mikä on moniatominen ioni?",
  "Useammasta atomista koostuva ryhmä, jolla on kokonaisvaraus, kuten hydroksidi OH<sup>−</sup> tai ammonium NH<sub>4</sub><sup>+</sup>.",
  "Ioniyhdisteessä ionina voi olla useammasta kovalenttisesti sitoutuneesta atomista koostuva ryhmä, joka kantaa kokonaisvarausta. Monilla yleisillä moniatomisilla ioneilla on vakiintunut nimi: OH<sup>−</sup> hydroksidi-ioni, CN<sup>−</sup> syanidi-ioni ja NH<sub>4</sub><sup>+</sup> ammonium-ioni. Tärkein ryhmä ovat oksoanionit, joissa epämetalli on sitoutunut happeen, kuten sulfaatti ja nitraatti. Moniatominen ioni pysyy koossa yhdisteen liuetessa ja reagoidessa.",
  3, L(['moniatominen ioni', 'moniatomisen ionin', 'moniatomista ionia', 'moniatomiset ionit', 'moniatomisten ionien', 'moniatomisia ioneja'])),
K("Mikä on oksoanioni?",
  "Epämetallin ja hapen muodostama moniatominen anioni, jonka nimi päättyy -aatti tai -iitti.",
  "Epämetallit muodostavat hapen kanssa tärkeitä moniatomisia anioneja, oksoanioneja eli happianioneja. Niiden nimet päättyvät tavallisesti -aatti: SO<sub>4</sub><sup>2−</sup> on sulfaatti-ioni ja NO<sub>3</sub><sup>−</sup> nitraatti-ioni. Pääte liitetään anionin keskusatomin nimen runkoon, joten Na<sub>2</sub>SO<sub>4</sub>:ssä keskusatomi on rikki ja yhdiste natriumsulfaatti. Muita yleisiä oksoanioneja ovat karbonaatti CO<sub>3</sub><sup>2−</sup> ja fosfaatti PO<sub>4</sub><sup>3−</sup>. Kutsutaan myös: happianioni.",
  3, L('oksoanioni', 'happianioni')),
K("Miten saman alkuaineen useat oksoanionit nimetään?",
  "Vähemmän happea -iitti, enemmän -aatti. Laajassa sarjassa hypo- vähiten ja per- eniten happea: hypokloriitti, kloriitti, kloraatti, perkloraatti.",
  "Jos samalla alkuaineella on kaksi oksoanionia, vähemmän happea sisältävä saa päätteen -iitti ja happirikkaampi -aatti: sulfiitti SO<sub>3</sub><sup>2−</sup> ja sulfaatti SO<sub>4</sub><sup>2−</sup>. Laajemmissa sarjoissa käytetään lisäksi etuliitteitä: vähiten happea sisältävä saa hypo- ja eniten sisältävä per-. Kloorin neljä oksoanionia ovat hypokloriitti ClO<sup>−</sup>, kloriitti ClO<sub>2</sub><sup>−</sup>, kloraatti ClO<sub>3</sub><sup>−</sup> ja perkloraatti ClO<sub>4</sub><sup>−</sup>.",
  3),
K("Miten natriumsulfaatti nimetään täysin systemaattisesti?",
  "Dinatriumtetraoksidosulfaatti: anionin hapet käsitellään keskusatomin ligandeina päätteellä -ido.",
  "IUPACin systemaattisessa nimistössä moniatomisen anionin atomit käsitellään keskusatomin ligandeina. Anionin happi saa nimen oksido ja lukumäärää osoittavan etuliitteen, joten sulfaatti-ioni on tetraoksidosulfaatti, neljä happea liittyneenä rikkiin, ja Na<sub>2</sub>SO<sub>4</sub> on dinatriumtetraoksidosulfaatti. Vastaavasti NaNO<sub>3</sub> on natriumtrioksidonitraatti, Na<sub>3</sub>PO<sub>4</sub> trinatriumtetraoksidofosfaatti ja LiAlH<sub>4</sub> litiumtetrahydridoaluminaatti, triviaalinimeltään litiumalumiinihydridi. Arkikäytössä triviaalinimet riittävät.",
  1),
K("Miten kidevedelliset yhdisteet nimetään?",
  "Kidevesi kaavaan pisteellä, nimeen hydraatti etuliitteineen: CuSO<sub>4</sub> · 5 H<sub>2</sub>O on kuparisulfaattipentahydraatti.",
  "Ionikiteeseen liittynyt vesi ilmoitetaan kaavassa pisteellä erotettuna, ja nimeen lisätään sana hydraatti, jota edeltää kreikkalainen etuliite veden määrälle. Kuparisulfaattipentahydraatti CuSO<sub>4</sub> · 5 H<sub>2</sub>O sisältää viisi vesimolekyyliä kaavayksikköä kohti ja natriumsulfaattidekahydraatti Na<sub>2</sub>SO<sub>4</sub> · 10 H<sub>2</sub>O kymmenen. Kidevesi voidaan poistaa kuumentamalla, jolloin jäljelle jää vedetön suola.",
  2, L('hydraatti', ['kidevesi', 'kideveden', 'kidevettä', 'kidevedellinen', 'kidevedellisen'])),
K("Miten moniatomiset kationit nimetään?",
  "Päätteellä -ium: NH<sub>4</sub><sup>+</sup> on ammonium-ioni ja H<sub>3</sub>O<sup>+</sup> oksonium-ioni eli hydronium.",
  "",
  2, L('ammonium-ioni')),
K("Mikä on binaarinen kovalenttiyhdiste ja miten se nimetään?",
  "Kahden epämetallin molekyyliyhdiste. Ensimmäinen alkuaine sellaisenaan, toinen päätteellä -idi, lukumäärät etuliitteillä: NO<sub>2</sub> typpidioksidi.",
  "Binaariset kovalenttiyhdisteet muodostuvat kahdesta epämetallista eivätkä muodosta ionikiteitä, mutta ne nimetään samankaltaisin säännöin: kaavassa ensin mainittu alkuaine nimetään sellaisenaan ja saa etuliitteen vain, jos atomeja on useampi, jälkimmäinen saa päätteen -idi ja tarvittaessa etuliitteen. Typen oksidit ovat dityppioksidi N<sub>2</sub>O, typpioksidi NO, dityppitrioksidi N<sub>2</sub>O<sub>3</sub>, typpidioksidi NO<sub>2</sub>, dityppitetroksidi N<sub>2</sub>O<sub>4</sub> ja dityppipentoksidi N<sub>2</sub>O<sub>5</sub>.",
  3, L(['binaarinen kovalenttiyhdiste', 'binaarisen kovalenttiyhdisteen', 'binaarista kovalenttiyhdistettä', 'binaariset kovalenttiyhdisteet', 'kovalenttiyhdiste', 'kovalenttiyhdisteen', 'kovalenttiyhdistettä', 'kovalenttiyhdisteet', 'molekyyliyhdiste', 'molekyyliyhdisteen', 'molekyyliyhdistettä', 'molekyyliyhdisteet'])),
K("Mikä on happo?",
  "Yhdiste, jossa yksi tai useampi vetyioni on sitoutunut anioniin ja joka vedessä luovuttaa vetyioneja.",
  "Happo voidaan määritellä yhdisteeksi, jossa yksi tai useampi vetyioni H<sup>+</sup> on sitoutunut anioniin. Arrheniuksen klassisen määritelmän mukaan happo tuottaa vedessä vetyioneja eli muodostaa oksoniumioneja liuetessaan: HA + H<sub>2</sub>O → A<sup>−</sup> + H<sub>3</sub>O<sup>+</sup>, lyhyemmin HA → A<sup>−</sup> + H<sup>+</sup>. Hapon nimi johdetaan sen anionista, ja nimeämisessä erotetaan hapettomat hapot ja oksohapot.",
  3, L(['happo', 'hapon', 'happoa', 'hapossa', 'haposta', 'happoon', 'hapoksi', 'hapot', 'happojen', 'happoja', 'hapoissa', 'hapoista', 'hapoilla'])),
K("Miten hapettomat hapot nimetään?",
  "Vety + anionin nimi päätteellä -idi: HCl on vetykloridi, H<sub>2</sub>S divetysulfidi.",
  "Kun hapon anionissa ei ole happea, nimi muodostetaan sanasta vety ja anionin -idi-päätteisestä nimestä. HCl on vetykloridi, HBr vetybromidi, HCN vetysyanidi ja H<sub>2</sub>S divetysulfidi tai vetysulfidi. Vesiliuoksesta käytetään usein triviaalinimeä: vetykloridin vesiliuos on suolahappo. Systemaattinen nimi kertoo kaavan suoraan, koska anionin varaus määrää vetyjen määrän.",
  2),
K("Miten oksohapot nimetään?",
  "Anionin -aatti muuttuu -happo ja -iitti muuttuu -hapoke: sulfaatti → rikkihappo, sulfiitti → rikkihapoke.",
  "Kun happi on mukana anionissa, hapon nimi perustuu anionin päätteeseen. Pääte -aatti antaa hapolle päätteen -happo: sulfaatti SO<sub>4</sub><sup>2−</sup> → rikkihappo H<sub>2</sub>SO<sub>4</sub>, nitraatti → typpihappo, fosfaatti → fosforihappo. Pääte -iitti antaa päätteen -hapoke: sulfiitti → rikkihapoke H<sub>2</sub>SO<sub>3</sub>. Anionin hypo- ja per-etuliitteet säilyvät: hypokloriitti → hypokloorihapoke HClO ja perkloraatti → perkloorihappo HClO<sub>4</sub>.",
  3, L(['oksohappo', 'oksohapon', 'oksohappoa', 'oksohapot', 'oksohappojen', 'oksohappoja', 'hapoke', 'hapokkeen', 'hapoketta', 'hapokkeet'])),
K("Miten nimestä päästään kaavaan: vanadiini(V)fluoridi, dihappidifluoridi, galliumoksidi ja mangaanidioksidi?",
  "VF<sub>5</sub>, O<sub>2</sub>F<sub>2</sub>, Ga<sub>2</sub>O<sub>3</sub> ja MnO<sub>2</sub>.",
  "Vanadiini(V)fluoridissa vanadiinin varaus on +5 ja fluoridin −1, joten kaava on VF<sub>5</sub>. Dihappidifluoridissa etuliitteet kertovat suoraan kaksi happea ja kaksi fluoria, O<sub>2</sub>F<sub>2</sub>. Galliumoksidissa gallium muodostaa Ga<sup>3+</sup>-ionin ja oksidi on O<sup>2−</sup>, joten neutraali kaava on Ga<sub>2</sub>O<sub>3</sub>. Mangaanidioksidissa etuliite di- kertoo kaksi happea, MnO<sub>2</sub>, jossa mangaanin hapetusluku on +4.",
  1),
]),
# ── 3.1 Atomin rakenne ja jaksollinen jarjestelma ──────────────────────────────────────
dict(LEHTI='Luento 3.1 - Atomin rakenne ja jaksollinen järjestelmä', NRO=31, KUVAT={
    'kemia_atomin_rakenne.png': (PDF31, 1, 'kuva'), 'kemia_jaksollinen.png': (PDF31, 3, 'kuva')}, KORTIT=[
K("Millainen on atomin yksinkertainen malli?",
  "Pieni ydin, noin 10<sup>−13</sup> cm, ja elektronipilvi, jonka halkaisija on noin 10<sup>−8</sup> cm.",
  "Yksinkertaisen mallin mukaan atomi koostuu pienestä ytimestä ja sitä ympäröivästä elektronipilvestä. Ytimen halkaisija on noin 10<sup>−13</sup> cm ja koko atomin noin 10<sup>−8</sup> cm, joten ydin on satatuhatta kertaa atomia pienempi ja atomi on lähes kokonaan tyhjää tilaa. Ydin koostuu positiivisista protoneista ja varauksettomista neutroneista, joita yhdessä kutsutaan nukleoneiksi, ja nukleonit rakentuvat kvarkeista. Kuvassa on rakenne atomista kvarkkiin.",
  3, L(['atomi', 'atomin', 'atomia', 'atomissa', 'atomista', 'atomiin', 'atomiksi', 'atomit', 'atomien', 'atomeja', 'atomeissa', 'atomeista', 'atomeihin']), 'kemia_atomin_rakenne.png'),
K("Mikä on atomiydin?",
  "Atomin pieni, tiheä ja positiivinen keskus, joka koostuu protoneista ja neutroneista.",
  "Atomiydin sisältää lähes koko atomin massan mutta vain noin sadastuhannesosan sen halkaisijasta. Se koostuu protoneista, joilla on positiivinen yksikkövaraus, ja neutroneista, jotka ovat varauksettomia. Protonien määrä eli järjestysluku määrää alkuaineen, ja protonien ja neutronien yhteismäärä on massaluku. Ytimen positiivinen varaus pitää elektronit atomissa, ja Rutherford päätteli ytimen olemassaolon kultakalvokokeesta.",
  3, L(['atomiydin', 'atomiytimen', 'atomiydintä', 'atomiytimessä', 'atomiytimestä', 'atomiytimeen', 'atomiytimet', 'atomiytimien', 'atomiytimiä', 'ydin', 'ytimen', 'ydintä', 'ytimessä', 'ytimestä', 'ytimeen'])),
K("Mikä on nukleoni?",
  "Yhteisnimitys ytimen rakenneosille, protoneille ja neutroneille.",
  "",
  2, L('nukleoni')),
K("Mikä on kvarkki?",
  "Alkeishiukkanen, josta protonit ja neutronit rakentuvat ja jota pidetään nykyisin jakamattomana.",
  "",
  1, L('kvarkki')),
K("Mikä on elektroni?",
  "Negatiivisesti varautunut, erittäin kevyt hiukkanen, joka muodostaa atomin ytimen ympärillä olevan elektronipilven.",
  "Elektronin varaus on −1 alkeisvarausta ja massa 9,11 × 10<sup>−31</sup> kg, vain noin 1/1800 protonin massasta. Elektronit sijaitsevat ytimen ympärillä orbitaaleilla, ja niiden määrä ja järjestäytyminen määräävät atomin kemialliset ominaisuudet: uloimmat valenssielektronit muodostavat sidokset. Thomson löysi elektronin katodisädekokeilla 1897 ja Millikan mittasi sen varauksen 1909.",
  3, L('elektroni')),
K("Mikä on protoni?",
  "Ytimen positiivinen hiukkanen, massaltaan 1,67 × 10<sup>−27</sup> kg. Protonien määrä määrää alkuaineen.",
  "Protonilla on positiivinen yksikkövaraus, +1 alkeisvarausta, ja massa 1,67 × 10<sup>−27</sup> kg, noin 1800 kertaa elektronin massa. Protonien lukumäärä ytimessä on järjestysluku, joka määrää alkuaineen: yksi protoni on vety, kuusi hiili. Neutraalissa atomissa protoneja ja elektroneja on yhtä paljon. Vetyatomin ydin on paljas protoni, jota kemiassa kutsutaan vetyioniksi H<sup>+</sup>.",
  3, L('protoni')),
K("Mikä on neutroni?",
  "Ytimen varaukseton hiukkanen, massaltaan lähes protonin suuruinen, 1,67 × 10<sup>−27</sup> kg.",
  "Neutronilla ei ole sähkövarausta, ja sen massa on lähes sama kuin protonin. Neutronit sitovat ytimen koossa ja tasapainottavat protonien keskinäistä hylkintää. Saman alkuaineen atomeilla voi olla eri määrä neutroneja, jolloin ne ovat toistensa isotooppeja: vedyn ytimessä neutroneja ei ole, deuteriumissa on yksi. Neutronien määrä ei vaikuta alkuaineen kemiallisiin ominaisuuksiin, koska ne riippuvat elektroneista.",
  3, L('neutroni')),
K("Mitkä ovat elektronin, protonin ja neutronin massat ja varaukset?",
  "Elektroni −1 ja 9,11 × 10<sup>−31</sup> kg. Protoni +1, neutroni 0, molemmat 1,67 × 10<sup>−27</sup> kg.",
  "",
  2),
K("Mikä on alkeisvaraus?",
  "Pienin vapaana esiintyvä sähkövaraus, 1,60 × 10<sup>−19</sup> C. Elektronin ja protonin varauksen suuruus.",
  "",
  2, L('alkeisvaraus', 'yksikkövaraus')),
K("Mistä atomin kemialliset ominaisuudet riippuvat?",
  "Elektronien määrästä ja järjestäytymisestä.",
  "",
  3),
K("Mikä on massaluku?",
  "Ytimen protonien ja neutronien yhteismäärä. Merkitään alkuaineen symbolin vasempaan yläkulmaan.",
  "Massaluku A on ytimen nukleonien eli protonien ja neutronien lukumäärä. Atomi merkitään niin, että massaluku kirjoitetaan alkuaineen symbolin vasempaan yläkulmaan ja järjestysluku vasempaan alakulmaan, esimerkiksi hiili-12 muodossa <sup>12</sup><sub>6</sub>C. Massaluku on kokonaisluku ja likimain atomin massa atomimassayksikköinä, kun taas jaksollisen järjestelmän atomimassa on isotooppien painotettu keskiarvo.",
  3, L('massaluku')),
K("Mikä on järjestysluku?",
  "Ytimen protonien lukumäärä, joka määrää alkuaineen ja sen paikan jaksollisessa järjestelmässä.",
  "Järjestysluku Z on protonien määrä ytimessä ja neutraalissa atomissa myös elektronien määrä. Se määrää, mikä alkuaine on kyseessä: jokaisella alkuaineella on oma järjestyslukunsa, vedyllä 1, hiilellä 6 ja hapella 8. Jaksollinen järjestelmä on järjestetty järjestysluvun mukaan, ja se merkitään alkuaineen symbolin vasempaan alakulmaan. Kutsutaan myös: atominumero, protoniluku.",
  3, L('järjestysluku', ['atominumero', 'atominumeron', 'atominumeroa', 'protoniluku', 'protoniluvun'])),
K("Mikä on isotooppi?",
  "Saman alkuaineen atomi, jolla on eri määrä neutroneja ja siksi eri massaluku.",
  "Isotoopit ovat saman alkuaineen atomeja, joilla on sama määrä protoneja mutta eri määrä neutroneja, joten ne eroavat toisistaan massaluvultaan. Esimerkiksi hiili-12 ja hiili-14 ovat hiilen isotooppeja. Kemialliset ominaisuudet ovat samat, koska ne riippuvat elektroneista. Useimmat luonnossa esiintyvät alkuaineet ovat isotooppiseoksia, minkä vuoksi jaksollisen järjestelmän atomimassat ovat painotettuja keskiarvoja eivätkä kokonaislukuja.",
  3, L('isotooppi', ['isotooppiseos', 'isotooppiseoksen', 'isotooppiseoksia'])),
K("Mihin alkuaineiden jaksollinen järjestelmä perustuu?",
  "Mendelejevin ja Meyerin luokitteluun. Alkuaineet ryhmitellään järjestysluvun ja elektronirakenteen mukaan jaksoihin ja ryhmiin.",
  "Nykyinen jaksollinen järjestelmä pohjautuu venäläisen Dmitri Mendelejevin ja saksalaisen Lothar Meyerin luokitteluun. Se ryhmittelee alkuaineet järjestysluvun eli atominumeron ja elektronirakenteen perusteella: vaakarivit ovat jaksoja, joissa pääkvanttiluku kasvaa, ja pystysarakkeet ryhmiä, joiden alkuaineilla on samanlainen valenssielektronirakenne ja siksi samankaltaiset ominaisuudet. Kuvassa järjestelmä IUPACin ryhmänumeroin 1–18, lantanoidit ja aktinoidit erikseen.",
  3, L(['jaksollinen järjestelmä', 'jaksollisen järjestelmän', 'jaksollista järjestelmää', 'jaksollisessa järjestelmässä', 'jaksollisesta järjestelmästä', 'jaksolliseen järjestelmään']), 'kemia_jaksollinen.png'),
K("Mikä on jakso jaksollisessa järjestelmässä?",
  "Taulukon vaakarivi. Saman jakson alkuaineilla on sama määrä elektronikuoria.",
  "",
  3, L('jakso')),
K("Mikä on ryhmä jaksollisessa järjestelmässä?",
  "Taulukon pystysarake. Saman ryhmän alkuaineilla on samanlainen valenssielektronirakenne ja samankaltaiset ominaisuudet.",
  "Ryhmät ovat jaksollisen järjestelmän pystysarakkeita, IUPACin suosituksessa numeroituina 1–18. Saman ryhmän alkuaineilla on yhtä monta valenssielektronia samantyyppisillä orbitaaleilla, joten ne muodostavat samanlaisia ioneja ja yhdisteitä: ryhmän 1 alkalimetallit muodostavat +1-ioneja ja ryhmän 17 halogeenit −1-ioneja. Ryhmien nimeämiskäytäntöjä on kolme: eurooppalainen roomalaisin numeroin ja kirjaimin, amerikkalainen ja IUPACin numerot 1–18.",
  3, L(['ryhmä', 'ryhmän', 'ryhmää', 'ryhmässä', 'ryhmästä', 'ryhmään', 'ryhmät', 'ryhmien', 'ryhmiä', 'ryhmissä', 'pääryhmä', 'pääryhmän', 'pääryhmät', 'pääryhmien'])),
K("Miten metallit ja epämetallit eroavat ioninmuodostuksessa?",
  "Metallit luovuttavat elektroneja ja muodostavat kationeja, epämetallit vastaanottavat ja muodostavat anioneja.",
  "Valtaosa alkuaineista on metalleja, jotka pyrkivät luovuttamaan uloimmat elektroninsa ja muodostamaan positiivisia ioneja eli kationeja. Epämetallit puolestaan vastaanottavat helposti elektroneja täydentääkseen uloimman kuorensa ja muodostavat negatiivisia ioneja eli anioneja. Metallit ovat jaksollisen järjestelmän vasemmassa ja keskiosassa, epämetallit oikeassa yläkulmassa, ja niiden välissä on puolimetalleja. Ero selittää, miksi ioniyhdisteet muodostuvat metallin ja epämetallin välille.",
  3, L(['metalli', 'metallin', 'metallia', 'metallissa', 'metallista', 'metalliin', 'metallit', 'metallien', 'metalleja', 'metalleissa', 'epämetalli', 'epämetallin', 'epämetallia', 'epämetallit', 'epämetallien', 'epämetalleja'])),
K("Mitkä ovat jaksollisen järjestelmän ryhmien kolme nimeämiskäytäntöä?",
  "Eurooppalainen roomalaisin numeroin ja kirjaimin, amerikkalainen omine kirjaimineen ja IUPACin numerot 1–18.",
  "",
  1),
]),
# ── 3.2 Kvanttimekaaninen atomimalli ───────────────────────────────────────────────────
dict(LEHTI='Luento 3.2 - Kvanttimekaaninen atomimalli', NRO=32, KUVAT={
    'kemia_spektri.png': (PDF32, 3, 'kuva'), 'kemia_emissiospektri.png': (PDF32, 7, 'kuva'), 'kemia_bohr.png': (PDF32, 9, 'kuva'),
    'kemia_1s_tiheys.png': (PDF32, 12, 'kuva'), 'kemia_kvanttiluvut.png': (PDF32, 15, 'kuva'), 'kemia_s_orbitaalit.png': (PDF32, 16, 'kuva'),
    'kemia_d_orbitaalit.png': (PDF32, 17, 'kuva'), 'kemia_tunkeutuminen.png': (PDF32, 21, 'kuva'), 'kemia_konfiguraatiot.png': (PDF32, 24, 'kuva'),
    'kemia_tayttymisjarjestys.png': (PDF32, 26, 'kuva')}, KORTIT=[
K("Mitä on sähkömagneettinen säteily?",
  "Avaruudessa valon nopeudella etenevää aaltoliikettä, joka siirtää energiaa: valo, radioaallot, mikroaallot, röntgensäteet.",
  "Energia siirtyy avaruudessa sähkömagneettisena säteilynä. Auringon valo, mikroaallot, röntgensäteet ja radioaallot ovat kaikki sähkömagneettista säteilyä: niille on yhteistä samantyyppinen aaltoliikkeen muoto ja sama nopeus, valon nopeus. Lajit eroavat vain aallonpituudeltaan ja taajuudeltaan. Kuvassa on säteilyn luokittelu gammasäteilystä pitkiin radioaaltoihin ja näkyvän valon kapea alue 400–700 nm.",
  3, L(['sähkömagneettinen säteily', 'sähkömagneettisen säteilyn', 'sähkömagneettista säteilyä', 'sähkömagneettisessa säteilyssä', 'sähkömagneettinen spektri', 'sähkömagneettisen spektrin']), 'kemia_spektri.png'),
K("Mitkä suureet kuvaavat aaltoliikettä?",
  "Aallonpituus, taajuus ja nopeus.",
  "Aallonpituus λ on kahden perättäisen huipun tai laakson välinen etäisyys, ja sen yksikkö on metri. Taajuus ν on aaltojen eli syklien lukumäärä sekunnissa annetussa avaruuden pisteessä, yksikkönä hertsi eli 1/s. Nopeus kertoo, kuinka nopeasti aallon huippu etenee, ja sähkömagneettiselle säteilylle se on valon nopeus c. Kolmea suuretta sitoo yhtälö λν = c: taajuus kasvaa, kun aallonpituus pienenee.",
  3, L('aallonpituus', 'taajuus')),
K("Mikä yhtälö sitoo aallonpituuden ja taajuuden?",
  "λν = c: aallonpituus kertaa taajuus on valon nopeus, noin 2,9979 × 10<sup>8</sup> m/s.",
  "Sähkömagneettiselle säteilylle pätee λν = c, jossa λ on aallonpituus metreinä, ν taajuus hertseinä ja c valon nopeus, noin 2,9979 × 10<sup>8</sup> m/s. Koska nopeus on vakio, säteilyn taajuus kasvaa aallonpituuden pienentyessä: sinisellä valolla on lyhyempi aallonpituus ja suurempi taajuus kuin punaisella. Yhtälöllä lasketaan taajuus tunnetusta aallonpituudesta, esimerkiksi 450 nm:n valolle 6,66 × 10<sup>14</sup> Hz.",
  3),
K("Mikä on Planckin kvanttihypoteesi?",
  "Systeemi voi vastaanottaa tai luovuttaa energiaa vain paketteina hν, joten ΔE = nhν ja energia on kvantittunut.",
  "Max Planck esitti vuonna 1901, että systeemi voi vastaanottaa tai luovuttaa energiaa vain tietyn suuruisina paketteina, kokonaislukukerrannaisina muodossa hν, jossa h on Planckin vakio 6,626 × 10<sup>−34</sup> Js ja ν säteilyn taajuus. Energianmuutos on siis ΔE = nhν, jossa n on luonnollinen luku. Tästä seuraa, että energia on kvantittunutta: sillä on hiukkasluonne, eikä se esiinny mielivaltaisina määrinä.",
  3, L(['Planckin kvanttihypoteesi', 'Planckin kvanttihypoteesin', 'kvanttihypoteesi', 'kvanttihypoteesin'])),
K("Mikä on Planckin vakio?",
  "Luonnonvakio h = 6,626 × 10<sup>−34</sup> Js, joka sitoo energiakvantin suuruuden säteilyn taajuuteen: E = hν.",
  "",
  2, L(['Planckin vakio', 'Planckin vakion', 'Planckin vakiota', 'Planckin vakiolla'])),
K("Mitä tarkoittaa, että energia on kvantittunut?",
  "Energia esiintyy vain erillisinä yksikköinä eli kvantteina, ei mielivaltaisina määrinä.",
  "Kvantittuneisuus tarkoittaa, että suure voi saada vain tiettyjä erillisiä arvoja. Säteilyn energia tulee kvantteina, joiden suuruus on hν, ja atomin elektroni voi olla vain tietyillä energiatasoilla, ei niiden välissä. Siksi vedyn emissiospektri koostuu erillisistä viivoista jatkuvan spektrin sijasta. Myös sähkövaraus on kvantittunut alkeisvarauksen monikerroiksi, minkä Millikan osoitti. Kutsutaan myös: kvantti, energiakvantti.",
  3, L('kvantti', ['kvantittunut', 'kvantittuneen', 'kvantittunutta', 'kvantittuminen', 'kvantittumisen', 'energiakvantti', 'energiakvantin', 'energiakvantteja'])),
K("Mikä on fotoni?",
  "Sähkömagneettisen säteilyn hiukkanen eli energiakvantti, jonka energia on E = hν = hc/λ.",
  "Einsteinin mukaan sähkömagneettinen säteily on kvanttimuodossa: se koostuu hiukkasista, fotoneista. Fotonin energia on E = hν = hc/λ, joten lyhytaaltoisella säteilyllä, kuten röntgensäteillä, on suurempi energia kuin pitkäaaltoisella. Suhteellisuusteorian E = mc<sup>2</sup> yhdistää energian ja massan. Fotonilla on sekä aalto- että hiukkasluonne. Esimerkiksi kuparikloridin ilotulitteessa emittoiman 450 nm:n sinisen valon fotonin energia on 4,41 × 10<sup>−19</sup> J.",
  3, L('fotoni')),
K("Kuinka paljon energiaa sininen 450 nm:n valo emittoi fotonia kohti?",
  "Noin 4,41 × 10<sup>−19</sup> J, kun ν = c/λ ja E = hν.",
  "Ilotulitusten sininen väri saadaan kuumentamalla kupari(I)kloridia 1200 °C:ssa, jolloin se emittoi 450 nm:n valoa. Ensin lasketaan taajuus ν = c/λ = 2,998 × 10<sup>8</sup> m/s jaettuna 450 × 10<sup>−9</sup> m, noin 6,662 × 10<sup>14</sup> Hz. Sitten energia E = hν = 6,626 × 10<sup>−34</sup> Js kertaa 6,662 × 10<sup>14</sup> Hz, noin 4,41 × 10<sup>−19</sup> J fotonia kohti.",
  2),
K("Mitä aalto-hiukkasdualismi tarkoittaa?",
  "Sähkömagneettisella säteilyllä ja aineella on sekä aalto- että hiukkasluonne.",
  "Valo käyttäytyy aaltona, kun se taittuu ja interferoi, mutta fotoneina, kun se irrottaa elektroneja metallista. De Broglien mukaan myös ainehiukkasilla on aaltoluonne, ja niiden aallonpituus on λ = h/mv. Suurilla kappaleilla, kuten tennispallolla, aallonpituus on liian pieni havaittavaksi ja hiukkasluonne vallitsee. Fotonilla aaltoluonne on vallitseva, ja välikokoisilla hiukkasilla, kuten elektronilla, on kumpaakin ominaisuutta. Kaikella materialla on molemmat luonteet.",
  3, L('aalto-hiukkasdualismi', ['dualismi', 'dualismin', 'dualismia'])),
K("Mikä on de Broglien periaate?",
  "Myös ainehiukkasilla on aaltoluonne, ja niiden aallonpituus on λ = h/mv.",
  "Ranskalainen Louis de Broglie esitti, että jos valolla on hiukkasluonne, ainehiukkasilla on vastaavasti aaltoliikeluonne. Hiukkasen aallonpituus on Planckin vakio jaettuna liikemäärällä, λ = h/mv, jossa m on massa ja v nopeus. Elektronin pieni massa antaa sille atomin mittakaavassa merkittävän aallonpituuden, mikä on kvanttimekaanisen atomimallin lähtökohta: ytimeen sitoutunut elektroni on seisova aalto.",
  2, L(['de Broglien periaate', 'de Broglien periaatteen', 'de Broglien periaatetta', 'de Broglien aallonpituus', 'de Broglien aallonpituuden'])),
K("Miten vedyn emissiospektri syntyy ja mitä se kertoo?",
  "Virittyneet vetyatomit säteilevät vain tiettyjä aallonpituuksia, joten elektronin energia on kvantittunut.",
  "Kun vetykaasun läpi johdetaan sähköpurkaus, osa H–H-sidoksista katkeaa ja syntyy korkeaenergisiä eli virittyneitä vetyatomeja. Luovuttaessaan energiansa ne säteilevät valoa, ja muodostuu vedyn emissiospektri, joka koostuu vain muutamasta viivasta. Jokainen viiva vastaa tiettyä aallonpituutta, joten vetyatomin elektronille ovat sallittuja vain tietyt energiatasot: elektronin energia on kvantittunut, ja tasojen väliset siirtymät tuottavat vain tiettyjä aallonpituuksia.",
  3, L(['emissiospektri', 'emissiospektrin', 'emissiospektriä', 'emissiospektrissä', 'viivaspektri', 'viivaspektrin']), 'kemia_emissiospektri.png'),
K("Miten energiatasojen välinen energianmuutos lasketaan emittoituneesta valosta?",
  "ΔE = hν = hc/λ, jossa λ on emittoituneen valon aallonpituus ja ν sen taajuus.",
  "",
  2),
K("Mikä on Bohrin atomimalli ja miksi se hylättiin?",
  "Elektroni kiertää ydintä vain tietyillä sallituilla ympyräradoilla. Selitti vedyn spektrin mutta ei muita atomeja.",
  "Niels Bohr esitti vuonna 1913 vetyatomin kvanttimallin, jossa elektroni kiertää ydintä vain tietyillä sallituilla, ympyränmuotoisilla kiertoradoilla ja voi olla vain määrätyissä, toisistaan erottuvissa energiatiloissa. Malli selitti hyvin vedyn viivaspektrin, mutta se ei toiminut monimutkaisemmille atomeille. Nykykäsityksen mukaan elektronit eivät kierrä ydintä ympyräradalla, vaan niitä kuvataan kvanttimekaanisesti seisovina aaltoina ja todennäköisyysjakaumina.",
  3, L(['Bohrin atomimalli', 'Bohrin atomimallin', 'Bohrin atomimallia', 'Bohrin malli', 'Bohrin mallin', 'Bohrin mallia']), 'kemia_bohr.png'),
K("Mikä on kvanttimekaaninen atomimalli?",
  "Heisenbergin, de Broglien ja Schrödingerin malli, jossa ytimeen sitoutunut elektroni on seisova aalto tietyillä alueilla.",
  "Kvanttimekaanisen atomimallin kehittivät Heisenberg, de Broglie ja Schrödinger, ja sen idea perustuu aaltoliikkeeseen. Mallin mukaan ytimeen sitoutunut elektroni vastaa seisovaa aaltoliikettä, joka on mahdollinen vain tietyillä atomin ympärillä olevilla alueilla, kuten kitaran kieli värähtelee vain kokonaisina puoliaallonpituuksina. Schrödingerin aaltoyhtälön ratkaisut ovat orbitaaleja, joista kukin vastaa tiettyä energiaa, ja elektronin paikkaa kuvaa todennäköisyysjakauma.",
  3, L(['kvanttimekaaninen atomimalli', 'kvanttimekaanisen atomimallin', 'kvanttimekaanista atomimallia', 'kvanttimekaniikka', 'kvanttimekaniikan', 'kvanttimekaniikkaa', 'kvanttimekaniikassa'])),
K("Mikä on Schrödingerin yhtälö ja aaltofunktio?",
  "Aaltoyhtälö, joka kuvaa elektronin aaltoluonnetta. Sen ratkaisu on aaltofunktio ψ, joka määrittelee kvanttimekaanisen tilan.",
  "Schrödinger kehitti aaltoyhtälön kuvaamaan vetyatomin elektronia. Yhtälö kuvaa hiukkasen aaltoluonnetta ja mittausten todennäköisyyspohjaista luonnetta, ja sen ratkaisu on aaltofunktio ψ(x, y, z), joka määrittelee systeemin kvanttimekaanisen tilan. Aaltofunktion neliö ψ<sup>2</sup> on todennäköisyystiheys: todennäköisyys löytää elektroni pisteestä. Vain ne ratkaisut ovat fysikaalisesti mielekkäitä, joissa yhtälön vakiot saavat kokonaislukuarvoja, ja nämä ratkaisut ovat orbitaaleja.",
  2, L('aaltofunktio', ['Schrödingerin yhtälö', 'Schrödingerin yhtälön', 'Schrödingerin yhtälöä', 'aaltoyhtälö', 'aaltoyhtälön', 'aaltoyhtälöä'])),
K("Mikä on orbitaali?",
  "Schrödingerin yhtälön ratkaisu, joka kuvaa aluetta, jossa elektroni todennäköisimmin on, ja vastaa tiettyä energiaa.",
  "Orbitaalit ovat aaltoyhtälön fysikaalisesti mielekkäitä ratkaisuja, joista kukin vastaa tiettyä kokonaisenergiaa. Elektronin tarkkaa sijaintia orbitaalilla ei voi tietää, vaan orbitaali on todennäköisyysjakauma. Sen koko määritellään sopimuksen mukaan alueeksi, jossa elektroni on 90 %:n todennäköisyydellä, ja sitä havainnollistetaan kolmiulotteisella pilvellä. Vetyatomin 1s-orbitaali on pallomainen ja sen säde noin 140 pikometriä. Orbitaali voi sisältää enintään kaksi elektronia.",
  3, L('orbitaali', 'atomiorbitaali')),
K("Mikä on Heisenbergin epätarkkuusperiaate?",
  "Hiukkasen paikkaa ja liikemäärää ei voi määrittää samanaikaisesti tarkasti.",
  "Heisenbergin epätarkkuusperiaate rajoittaa tarkkuutta, jolla hiukkasen paikka ja liike voidaan samanaikaisesti määrittää: mitä tarkemmin toinen tunnetaan, sitä epätarkempi toinen on. Siksi elektronin tarkkaa sijaintia orbitaalilla ei voida tietää, vaan käytetään todennäköisyysjakaumaa, joka kuvaa, missä elektroni todennäköisimmin on. Kysymykseen, missä elektroni atomissa on, ei ole tarkkaa vastausta, vaan vastaus on tilastollinen ja liittyy aaltofunktion arvoon.",
  3, L(['Heisenbergin epätarkkuusperiaate', 'Heisenbergin epätarkkuusperiaatteen', 'Heisenbergin epätarkkuusperiaatetta', 'epätarkkuusperiaate', 'epätarkkuusperiaatteen', 'epätarkkuusperiaatetta', 'epätarkkuusperiaatteessa'])),
K("Mitä aaltofunktion neliö kuvaa?",
  "Todennäköisyystiheyttä eli todennäköisyyttä löytää elektroni tietystä pisteestä.",
  "Termi ψ<sup>2</sup> on suhteellinen todennäköisyystiheys: se kertoo, kuinka todennäköisesti elektroni on koordinaattipisteessä x, y, z. Vedyn 1s-orbitaalilla tiheys on suurin ytimen luona ja pienenee tasaisesti etäisyyden kasvaessa, kuten kuvan pilvi ja käyrä näyttävät. Kun tiheys kerrotaan pallonkuoren pinta-alalla, saadaan säteittäinen jakauma, jonka huippu vedyllä on noin 53 pikometrin etäisyydellä, Bohrin säteen kohdalla.",
  2, L(['todennäköisyystiheys', 'todennäköisyystiheyden', 'todennäköisyystiheyttä', 'todennäköisyysjakauma', 'todennäköisyysjakauman', 'todennäköisyysjakaumaa']), 'kemia_1s_tiheys.png'),
K("Mistä kvanttiluvut tulevat?",
  "Schrödingerin yhtälön reunaehdoista: vain ratkaisut, joissa separoimisvakiot ovat kokonaislukuja, ovat mielekkäitä.",
  "Kaikki Schrödingerin aaltoyhtälön ratkaisut eivät ole fysikaalisesti mielekkäitä. Hyväksytään vain ne, joissa yhtälön matemaattiset separoimisvakiot saavat kokonaislukuarvoja, mikä vastaa reunaehtojen täyttymistä: aallon on sovittava atomiin kuten seisovan aallon kieleen. Mielekkäitä ratkaisuja sanotaan orbitaaleiksi, ja niihin johtaneista vakioista käytetään nimeä kvanttiluvut. Kutakin orbitaalia kuvaa kolme kvanttilukua n, l ja m<sub>l</sub>, ja elektronia lisäksi spinkvanttiluku.",
  1, L('kvanttiluku')),
K("Mikä on pääkvanttiluku n?",
  "Kokonaisluku 1, 2, 3, …, joka määrää orbitaalin energian ja koon.",
  "Pääkvanttiluku n voi saada arvot 1, 2, 3 ja niin edelleen, ja se määrää orbitaalin energian ja koon: mitä suurempi n, sitä kauempana ytimestä elektroni keskimäärin on ja sitä korkeampi sen energia. Vetyatomilla orbitaalin energia riippuu vain n:stä. Saman n:n orbitaalit muodostavat elektronikuoren, ja jaksollisen järjestelmän jakson numero on uloimman kuoren n. Kuvassa on kvanttilukujen yhdistelmät neljälle ensimmäiselle kuorelle.",
  3, L('pääkvanttiluku', ['elektronikuori', 'elektronikuoren', 'elektronikuorta', 'elektronikuoret', 'elektronikuorien', 'elektronikuoria']), 'kemia_kvanttiluvut.png'),
K("Mikä on sivukvanttiluku l?",
  "Kokonaisluku 0 … n−1, joka määrää orbitaalin muodon. Arvoja merkitään kirjaimilla s, p, d, f.",
  "Sivukvanttiluku l voi saada arvot 0, 1, 2 ja niin edelleen aina n−1:een asti, ja se määrää orbitaalin muodon ja elektronin impulssimomentin. Historiallisista syistä kokonaislukujen sijasta käytetään kirjaimia s, p, d, f, g ja niin edelleen aakkosjärjestyksessä. Elektronin kvanttiluvuille n ja l käytetään yhteismerkintää nl: 2p tarkoittaa n = 2 ja l = 1, 3d tarkoittaa n = 3 ja l = 2. Kutsutaan myös: orbitaalikvanttiluku.",
  3, L('sivukvanttiluku', 'orbitaalikvanttiluku')),
K("Mikä on magneettinen kvanttiluku m<sub>l</sub>?",
  "Kokonaisluku välillä −l … +l, joka määrää orbitaalin suunnan avaruudessa.",
  "Magneettinen kvanttiluku m<sub>l</sub> voi saada arvot −l, −(l−1), …, −1, 0, +1, …, l−1, l, eli 2l + 1 eri arvoa. Se ilmentää elektronin käyttäytymistä magneetti- tai sähkökentässä ja määrää orbitaalin suunnan: p-orbitaaleja on kolme, d-orbitaaleja viisi ja f-orbitaaleja seitsemän, kukin eri suuntaan. Ilman ulkoista kenttää saman l:n orbitaalit ovat energialtaan samanarvoisia.",
  3, L(['magneettinen kvanttiluku', 'magneettisen kvanttiluvun', 'magneettista kvanttilukua', 'magneettinen kvanttiluku m'])),
K("Mikä on spinkvanttiluku m<sub>s</sub>?",
  "Elektronin sisäistä pyörimismäärää vastaava kvanttiluku, arvoltaan +½ tai −½.",
  "Spin on alkeishiukkasten ominaisuus, jonka lähin klassinen analogia on sisäinen pyörimismäärä, mutta spiniä ei voi täysin kuvata klassisilla malleilla. Spinkvanttiluku m<sub>s</sub> voi saada arvot +½ ja −½, ja sitä kuvataan usein ylös- ja alaspäin osoittavilla nuolilla. Spin tekee elektronista pienen magneetin. Orbitaalin kaksi elektronia ovat vastakkaisspinisiä, mikä on Paulin kieltosäännön seuraus.",
  3, L('spinkvanttiluku', ['spin', 'spinin', 'spiniä', 'spinit', 'spinien'])),
K("Mikä on Paulin kieltosääntö?",
  "Atomissa ei ole kahta elektronia, joilla kaikki neljä kvanttilukua ovat samat. Orbitaalilla on enintään kaksi vastakkaisspinistä elektronia.",
  "Paulin kieltosäännön mukaan missään atomissa ei ole kahta elektronia, joilla kaikki neljä kvanttilukua n, l, m<sub>l</sub> ja m<sub>s</sub> ovat samat. Koska orbitaalin määräävät kolme ensimmäistä kvanttilukua ja spinillä on vain kaksi arvoa, jokainen orbitaali voi sisältää enintään kaksi elektronia, joiden spinien on oltava vastakkaismerkkiset. Sääntö määrää kuorten kapasiteetin, 2, 8, 18 ja 32 elektronia, ja siten jaksollisen järjestelmän rakenteen.",
  3, L(['Paulin kieltosääntö', 'Paulin kieltosäännön', 'Paulin kieltosääntöä', 'Paulin kieltosäännössä', 'kieltosääntö', 'kieltosäännön', 'kieltosääntöä'])),
K("Millaisia ovat s-, p-, d- ja f-orbitaalit?",
  "s pallomainen, p kaksilehtinen kolmeen suuntaan, d viisi nelilehtistä, f seitsemän monimutkaisempaa.",
  "s-orbitaalit ovat pallomaisia, ja 2s ja 3s ovat 1s:ää suurempia ja sisältävät solmupintoja, joilla todennäköisyys on nolla. p-orbitaaleja on kolme, kukin kaksilehtinen käsipaino oman akselinsa suuntaan. d-orbitaaleja on viisi, useimmat nelilehtisiä, ja f-orbitaaleja seitsemän vielä monimutkaisempaa. Kuvassa ovat vedyn 1s-, 2s- ja 3s-orbitaalien todennäköisyystiheys, leikkaus ja 90 %:n alue. Kaikilla saman n:n orbitaaleilla on vedyssä sama energia.",
  2, '', 'kemia_s_orbitaalit.png'),
K("Millaisia ovat 3d-orbitaalit?",
  "Viisi orbitaalia: neljä nelilehtistä eri tasoissa ja yksi käsipaino renkaalla z-akselin suuntaan.",
  "",
  2, '', 'kemia_d_orbitaalit.png'),
K("Mitä tarkoittaa, että orbitaalit ovat degeneroituneita?",
  "Ne ovat energeettisesti samanarvoisia.",
  "Vetyatomilla orbitaalin energia riippuu vain pääkvanttiluvusta n, joten kaikki saman n:n orbitaalit, esimerkiksi 2s ja kolme 2p-orbitaalia, ovat samalla energiatasolla eli degeneroituneita. Monielektronisilla atomeilla degeneraatio purkautuu osittain: energia riippuu myös l:stä, joten 2s on alempana kuin 2p, mutta kolme 2p-orbitaalia pysyvät keskenään samanarvoisina. Hundin sääntö koskee juuri degeneroituneiden orbitaalien täyttämistä.",
  2, L(['degeneroitunut', 'degeneroituneen', 'degeneroitunutta', 'degeneroituneet', 'degeneroituneiden', 'degeneraatio', 'degeneraation', 'degeneraatiota'])),
K("Mitä ovat perustila ja virittynyt tila?",
  "Perustilassa elektronit ovat alimmilla mahdollisilla energiatasoilla. Virittyneessä tilassa atomi on absorboinut energiaa ja elektroni on korkeammalla tasolla.",
  "Perustilassa vetyatomin elektroni on 1s-orbitaalilla, alimmalla mahdollisella energiatasolla. Kun atomi absorboi energiaa, esimerkiksi valoa tai sähköpurkauksen, elektroni voi siirtyä korkeammalle tasolle, ja atomi on virittyneessä tilassa. Virittynyt atomi palaa perustilaan luovuttamalla energian fotonina, jonka aallonpituus vastaa tasojen energiaeroa, mikä synnyttää emissiospektrin viivat. Viritystila kestää tyypillisesti vain nanosekunteja.",
  3, L(['perustila', 'perustilan', 'perustilaa', 'perustilassa', 'perustilasta', 'perustilaan', 'virittynyt tila', 'virittyneen tilan', 'virittynyttä tilaa', 'virittyneessä tilassa', 'virittyneeseen tilaan', 'viritystila', 'viritystilan', 'viritystilaa'])),
K("Miten monielektronisen atomin orbitaalienergiat eroavat vedystä?",
  "Energia riippuu sekä n:stä että l:stä: E<sub>ns</sub> < E<sub>np</sub> < E<sub>nd</sub> < E<sub>nf</sub>.",
  "Schrödingerin yhtälöä voidaan soveltaa monielektronisiin atomeihin yksinkertaistuksin, kuten keskimääräiskentällä, ja päädytään vedyn kaltaisiin orbitaaleihin. Niiden energia riippuu kuitenkin kvanttiluvuista n ja l eikä yksin n:stä kuten vedyllä: saman kuoren orbitaalit järjestyvät E<sub>ns</sub> < E<sub>np</sub> < E<sub>nd</sub> < E<sub>nf</sub>. Ero selittyy ydinvarauksen ja keskimääräisen elektronitiheyden yhteisvaikutuksella, sillä sisemmät elektronit varjostavat ydintä ja s-elektronit tunkeutuvat lähemmäs ydintä.",
  2),
K("Mikä on tunkeutumisvaikutus?",
  "Korkeaenergisen orbitaalin elektronilla voi olla huomattava todennäköisyys olla lähellä ydintä.",
  "Tunkeutumisvaikutus tarkoittaa, että myös korkeaenergisten orbitaalien elektroneilla voi olla huomattava todennäköisyys esiintyä lähellä atomiydintä. Kuvassa natriumin 3s-elektronin säteittäisessä jakaumassa on pieniä huippuja ydinelektronien alueella, kun taas 3d-elektroni pysyy kauempana. Lähellä ydintä elektroni tuntee suuremman ydinvarauksen, joten tunkeutuva orbitaali on matalaenergisempi: siksi 4s täyttyy ennen 3d:tä ja s-orbitaalit ovat p-orbitaaleja alempana.",
  2, L('tunkeutumisvaikutus', ['tunkeutuminen', 'tunkeutumisen']), 'kemia_tunkeutuminen.png'),
K("Mikä on Aufbau-periaate?",
  "Alkuaineet rakentuvat lisäämällä ytimeen protoni ja orbitaaleille elektroni kerrallaan alimmalle vapaalle energiatasolle.",
  "Aufbau-periaatteen eli rakentumisperiaatteen mukaan alkuaineet voidaan ajatella rakentuneen siten, että lisättäessä protoneja atomiytimeen lisätään vastaavasti elektroneja atomiorbitaaleille. Elektronit pyrkivät sijoittumaan niin, että atomin energia on mahdollisimman alhainen, joten orbitaalit täyttyvät energiajärjestyksessä alhaalta ylös Paulin kieltosääntöä ja Hundin sääntöä noudattaen. Näin saadaan jokaisen alkuaineen elektronikonfiguraatio ja samalla jaksollisen järjestelmän rakenne. Kutsutaan myös: rakentumisperiaate.",
  3, L(['Aufbau-periaate', 'Aufbau-periaatteen', 'Aufbau-periaatetta', 'rakentumisperiaate', 'rakentumisperiaatteen', 'rakentumisperiaatetta'])),
K("Mikä on elektronikonfiguraatio ja miten se merkitään?",
  "Elektronien jakauma orbitaaleille. Merkintä nl<sup>x</sup>: 2p<sup>3</sup> on kolme elektronia 2p-orbitaaleilla.",
  "Elektronikonfiguraatio kertoo, miten atomin elektronit jakautuvat orbitaaleille. Miehitys esitetään pää- ja sivukvanttiluvun yhteismerkinnän yläindeksillä: 2p<sup>3</sup> tarkoittaa kolmea elektronia 2p-orbitaaleilla ja 3d<sup>8</sup> kahdeksaa elektronia 3d-orbitaaleilla. Typen konfiguraatio on 1s<sup>2</sup>2s<sup>2</sup>2p<sup>3</sup> ja natriumin 1s<sup>2</sup>2s<sup>2</sup>2p<sup>6</sup>3s<sup>1</sup>, lyhyemmin [Ne]3s<sup>1</sup>. Kuvassa ovat kahden ensimmäisen jakson uloimmat konfiguraatiot.",
  3, L('elektronikonfiguraatio', ['elektronirakenne', 'elektronirakenteen', 'elektronirakennetta', 'elektronimiehitys', 'elektronimiehityksen']), 'kemia_konfiguraatiot.png'),
K("Mikä on Hundin sääntö?",
  "Elektronit asettuvat degeneroituneille orbitaaleille yksitellen samansuuntaisin spinein ennen pariutumista.",
  "Hundin säännön mukaan elektronit pyrkivät asettumaan energeettisesti samanarvoisille eli degeneroituneille orbitaaleille samansuuntaisin spinein niin pitkälle kuin mahdollista, ja vasta sitten ne alkavat pariutua. Sääntö koskee p-, d- ja f-orbitaaleja: typen kolme 2p-elektronia ovat kukin omalla orbitaalillaan samalla spinillä. Syynä on, että samalla orbitaalilla olevat elektronit hylkivät toisiaan, joten erillään ne ovat matalammalla energialla.",
  3, L(['Hundin sääntö', 'Hundin säännön', 'Hundin sääntöä', 'Hundin säännössä'])),
K("Mikä on valenssielektroni?",
  "Atomin suurimmalla pääkvanttiluvulla oleva elektroni, joka osallistuu sidosten muodostukseen.",
  "Alkuaineen suurimmalla pääkvanttiluvulla olevia elektroneja sanotaan valenssielektroneiksi: typellä ne ovat 2s<sup>2</sup>2p<sup>3</sup> eli viisi ja natriumilla 3s<sup>1</sup> eli yksi. Valenssielektronit ovat keskeisessä asemassa sidosta muodostettaessa, koska ne ovat uloimpana ja heikoimmin sidottuja. Sisemmät elektronit ovat ydinelektroneja, jotka eivät osallistu reaktioihin. Saman ryhmän alkuaineilla on yhtä monta valenssielektronia, mikä selittää niiden samankaltaisuuden.",
  3, L('valenssielektroni', 'ydinelektroni')),
K("Missä järjestyksessä orbitaalit täyttyvät?",
  "(n+1)s ennen nd:tä. Siirtymämetalleissa d-orbitaalit, lantanoideissa 4f ja aktinoideissa 5f täyttyvät.",
  "Orbitaalit täyttyvät energiajärjestyksessä, joka näkyy jaksollisen järjestelmän muodossa. (n+1)s-orbitaalit täyttyvät ennen nd-orbitaaleja: 4s ennen 3d:tä tunkeutumisvaikutuksen vuoksi. Ryhmien 1 ja 2 alkuaineissa täyttyvät s-orbitaalit, ryhmissä 13–18 p-orbitaalit, siirtymäalkuaineissa d-orbitaalit, lantanoideissa eli alkuaineissa 57–71 4f-orbitaalit ja aktinoideissa eli alkuaineissa 89–103 5f-orbitaalit. Kuvan taulukko näyttää, mikä orbitaali kussakin lohkossa täyttyy.",
  3, '', 'kemia_tayttymisjarjestys.png'),
K("Mitkä ovat rikin ja kadmiumin elektronikonfiguraatiot?",
  "Rikki [Ne]3s<sup>2</sup>3p<sup>4</sup>, kadmium [Kr]5s<sup>2</sup>4d<sup>10</sup>.",
  "Rikillä on 16 elektronia: 1s<sup>2</sup>2s<sup>2</sup>2p<sup>6</sup>3s<sup>2</sup>3p<sup>4</sup>, lyhyesti neonin rungon jälkeen [Ne]3s<sup>2</sup>3p<sup>4</sup>. Valenssielektroneja on kuusi, joten rikki ottaa mielellään kaksi elektronia ja muodostaa sulfidin S<sup>2−</sup>. Kadmiumilla on 48 elektronia: kryptonin rungon jälkeen täyttyvät 5s ja 4d, joten konfiguraatio on [Kr]5s<sup>2</sup>4d<sup>10</sup>. Täysi d-kuori tekee siitä sinkin kaltaisen metallin.",
  2),
K("Mikä on siirtymäalkuaine?",
  "Jaksollisen järjestelmän keskiosan metalli, jonka d-orbitaalit täyttyvät.",
  "Siirtymäalkuaineet eli siirtymämetallit ovat ryhmien 3–12 alkuaineita, joissa Aufbau-periaatteen mukaan täyttyvät d-orbitaalit: neljännessä jaksossa 3d skandiumista sinkkiin. Osittain täyttyneet d-orbitaalit antavat niille useita hapetuslukuja, kuten rauta(II) ja rauta(III), värillisiä yhdisteitä ja kyvyn toimia katalyytteinä ja entsyymien metallikeskuksina, kuten rauta hemissä ja sinkki monissa entsyymeissä. Kutsutaan myös: siirtymämetalli.",
  2, L('siirtymäalkuaine', ['siirtymämetalli', 'siirtymämetallin', 'siirtymämetallia', 'siirtymämetallit', 'siirtymämetallien', 'siirtymämetalleja'])),
K("Mitä ovat lantanoidit ja aktinoidit?",
  "Alkuaineet 57–71, joissa 4f-orbitaalit täyttyvät, ja alkuaineet 89–103, joissa 5f-orbitaalit täyttyvät.",
  "",
  1, L('lantanoidi', 'aktinoidi')),
]),
]
