# -*- coding: utf-8 -*-
"""Kemian peruskurssi I: sanaston toinen kierros (omistaja 12.9.2026: 'tee jokaikisesta sanasta!'). Kalvojen loput termit:
ionit ja hapot nimeamiskalvoilta, historian nimet joilla ei ole omaa korttia, 3.2:n fysiikan sanat. Liitetaan kemia_sanasto.py:n
listojen jatkoksi (indeksit 0..4 = luvut 1, 2.1, 2.2, 3.1, 3.2)."""
from biotek_taivutus import L
from pakka_rakenna import K

def N(*forms):
    return list(forms)

L1 = [
K("Mikä on teräs?",
  "Raudan ja hiilen seos, hiiltä alle 2 %. Ruostuu kuten rauta, ellei kromi tee siitä ruostumatonta.",
  "",
  1, L(N('teräs', 'teräksen', 'terästä', 'teräksessä', 'teräkset', 'teräksiä', 'ruostumaton teräs', 'ruostumattoman teräksen', 'rauta', 'raudan', 'rautaa', 'raudassa', 'rautaan'))),
K("Mikä on kloridi-ioni?",
  "Kloorin anioni Cl<sup>−</sup>. Suolavedessä kloridi lisää johtavuutta ja rikkoo raudan suojaavan oksidikerroksen.",
  "",
  2, L('kloridi', ['kloridi-ioni', 'kloridi-ionin', 'kloridi-ionit', 'kloridi-ioneja', 'NaCl', 'NaCl:n', 'NaCl-liuos', 'NaCl-liuoksen', 'ruokasuola', 'ruokasuolan', 'ruokasuolaa'])),
K("Mikä on oksidikerros?",
  "Metallin pinnalle hapettumisessa syntyvä ohut oksidikalvo. Alumiinilla tiivis ja suojaava, raudalla huokoinen ruoste, joka ei suojaa.",
  "",
  1, L(N('oksidikerros', 'oksidikerrosta', 'oksidikerroksen', 'oksidikerrokseen', 'oksidikerroksessa', 'oksidikalvo', 'oksidikalvon', 'oksidikalvoa', 'pintakerros', 'pintakerroksen', 'pintakerrosta', 'pintakerrokset', 'pintakerroksia', 'ruoste', 'ruosteen', 'ruostetta', 'ruostua', 'ruostuu'))),
K("Mitä toistaminen tarkoittaa tieteellisessä menetelmässä?",
  "Kokeen tekemistä uudelleen samoin ehdoin, jotta sattuman vaikutus paljastuu ja tulos osoittautuu luotettavaksi. Kutsutaan myös: toistettavuus.",
  "",
  2, L(N('toistaminen', 'toistamisen', 'toistamista', 'toistaa', 'toistetaan', 'toistettu', 'toisto', 'toiston', 'toistoa', 'toistot', 'toistojen', 'toistoja', 'toistokoe', 'toistokokeen', 'toistokokeet', 'rinnakkaismääritys', 'rinnakkaismäärityksen', 'rinnakkaismääritykset', 'rinnakkaisnäyte', 'rinnakkaisnäytteen', 'rinnakkaisnäytteet'))),
K("Mikä on data?",
  "Kokeessa kerätyt mittaustulokset, joita analysoimalla ennusteita testataan. Kutsutaan myös: aineisto, mittaustieto.",
  "",
  1, L(N('data', 'datan', 'dataa', 'datassa', 'datasta', 'aineisto', 'aineiston', 'aineistoa', 'aineistossa', 'aineistot', 'aineistoja', 'mittaustulos', 'mittaustuloksen', 'mittaustulosta', 'mittaustulokset', 'mittaustulosten', 'mittaustuloksia', 'tiedonkeruu', 'tiedonkeruun', 'tiedonkeruuta', 'mittaus', 'mittauksen', 'mittausta', 'mittaukset', 'mittausten', 'mittauksia', 'mitata', 'mitataan', 'mitattu', 'mitattava', 'mitattavaa'))),
K("Mikä on havainto?",
  "Aistein tai laittein todettu tosiasia, josta tieteellinen menetelmä alkaa: ilmiö herättää kysymyksen ja hypoteesin.",
  "",
  2, L('havainto', ['havaita', 'havaitaan', 'havaittu', 'havaittava', 'havaittavaa', 'havaittaviin', 'havainnoida', 'havainnointi', 'havainnoinnin', 'ilmiö', 'ilmiön', 'ilmiötä', 'ilmiössä', 'ilmiöt', 'ilmiöiden', 'ilmiöitä', 'ilmiöistä'])),
K("Mikä on malli kemiassa?",
  "Yksinkertaistettu kuva todellisuudesta, joka selittää havainnot ja ennustaa uusia, kuten atomimalli tai korroosion sähkökemiallinen malli.",
  "",
  2, L(N('malli', 'mallin', 'mallia', 'mallissa', 'mallista', 'malliin', 'mallit', 'mallien', 'malleja', 'malleissa', 'mallilla', 'malleilla', 'mallintaminen', 'mallintamisen', 'kemiallinen malli', 'kemiallisen mallin', 'kemiallista mallia'))),
K("Mikä on ongelmanratkaisu kemiassa?",
  "Järjestelmällinen eteneminen: rajaa ongelma, tunnista muuttujat, muodosta hypoteesi, ennusta, testaa ja tarkenna mallia.",
  "",
  1, L('ongelmanratkaisu', ['ongelma', 'ongelman', 'ongelmaa', 'ongelmassa', 'ongelmat', 'ongelmien', 'ongelmia', 'ratkaisu', 'ratkaisun', 'ratkaisua', 'ratkaisut', 'ratkaista', 'ratkaistaan', 'iteratiivinen', 'iteratiivisen', 'iteratiivista', 'iteratiivisesti', 'yrityksen ja erehdyksen', 'yritys ja erehdys'])),
K("Mikä on johtopäätös?",
  "Tuloksista tehty päätelmä: tukevatko havainnot ennustetta vai onko hypoteesia muutettava.",
  "",
  1, L(N('johtopäätös', 'johtopäätöksen', 'johtopäätöstä', 'johtopäätökset', 'johtopäätösten', 'johtopäätöksiä', 'päätelmä', 'päätelmän', 'päätelmää', 'päätelmät', 'päätelmien', 'päätelmiä', 'päätellä', 'päätellään', 'pääteltiin', 'päätteli'))),
]

L21 = [
K("Mitä sironta tarkoittaa?",
  "Hiukkasen tai säteen suunnan muutos sen kohdatessa esteen. Rutherfordin kokeessa alfahiukkaset sirosivat kultakalvon ytimistä.",
  "",
  2, L('sironta', ['sirota', 'siroaa', 'siroavat', 'sirosi', 'sirosivat', 'siroutua', 'siroutui', 'siroutuivat', 'sironnut', 'sironneet', 'sironnat', 'siroaminen', 'siroamisen', 'kultakalvokoe', 'kultakalvokokeen', 'kultakalvokokeessa', 'kultakalvokokeesta', 'kultakalvo', 'kultakalvon', 'kultakalvoon'])),
K("Mikä on vesihöyry?",
  "Vesi kaasuna. Gay-Lussac havaitsi, että kaksi tilavuutta vetyä ja yksi happea antavat kaksi tilavuutta vesihöyryä.",
  "",
  1, L('vesihöyry', ['vesihöyryn', 'vesihöyryä', 'vesihöyrynä', 'höyry', 'höyryn', 'höyryä', 'höyrynä', 'höyrystyä', 'höyrystyy', 'höyrystyminen', 'höyrystymisen', 'haihtua', 'haihtuu', 'haihtuminen', 'haihtumisen'])),
K("Mikä on massasuhde?",
  "Alkuaineiden massojen suhde yhdisteessä. Proust osoitti sen vakioksi: vedessä happea ja vetyä on aina suhteessa 8:1.",
  "",
  2, L(N('massasuhde', 'massasuhteen', 'massasuhdetta', 'massasuhteet', 'massasuhteiden', 'massasuhteita', 'kokonaismassa', 'kokonaismassan', 'kokonaismassaa', 'massa', 'massan', 'massaa', 'massassa', 'massat', 'massojen', 'massoja', 'massalla'))),
K("Mikä on varaus-massa-suhde?",
  "Hiukkasen sähkövarauksen ja massan osamäärä e/m, jonka Thomson mittasi elektronille katodisäteistä 1897.",
  "",
  2, L(N('varaus-massa-suhde', 'varaus-massa-suhteen', 'varaus-massa-suhdetta', 'varaus/massa-suhde', 'varaus/massa-suhteen', 'e/m', 'e/m-suhde', 'e/m-suhteen', 'varaus-suhde', 'varaus-suhteen', 'ominaisvaraus', 'ominaisvarauksen'))),
K("Mitä olivat muinaiset väriaineet?",
  "Väriaine, jota muinaiset ihmiset saivat mineraaleista (punamulta, okra) ja valmistivat kemiallisesti (lyijyvalkoinen lyijykarbonaatista).",
  "",
  1, L(N('punamulta', 'punamullan', 'punamultaa', 'okra', 'okran', 'okraa', 'lyijyvalkoinen', 'lyijyvalkoisen', 'lyijyvalkoista', 'lyijykarbonaatti', 'lyijykarbonaatin', 'lyijykarbonaatista', 'kalliomaalaus', 'kalliomaalauksen', 'kalliomaalaukset', 'kalliomaalausten', 'kalliomaalauksia', 'kosmetiikka muinaisuudessa'))),
K("Mikä on lasi?",
  "Piidioksidista sulattamalla tehty amorfinen kiinteä aine, jota valmistettiin jo Mesopotamiassa ja Egyptissä 3000-luvulla eaa.",
  "",
  1, L(N('lasi', 'lasin', 'lasia', 'lasissa', 'lasista', 'lasiin', 'lasit', 'lasien', 'laseja', 'lasinvalmistus', 'lasinvalmistuksen', 'piidioksidi', 'piidioksidin', 'piidioksidia', 'amorfinen', 'amorfisen', 'amorfista', 'amorfiset'))),
K("Mikä on kupari?",
  "Alkuaine Cu, ensimmäinen malmista pelkistetty metalli (n. 5000 eaa.). Tinan kanssa pronssia, kuparikarbonaatti oli Proustin koeaine.",
  "",
  2, L('kupari', ['Cu', 'kupari-ioni', 'kupari-ionin', 'kupari-ionit', 'kuparikarbonaatti', 'kuparikarbonaatin', 'kuparikarbonaattia', 'kupari(II)', 'kupari(I)', 'kupari(II)sulfaatti', 'kupari(II)sulfaatin', 'kuparisulfaatti', 'kuparisulfaatin', 'kuparisulfaattia', 'CuSO4', 'kupari(I)kloridi', 'kupari(I)kloridin', 'kuparikloridi', 'kuparikloridin', 'kuparikloridia', 'CuCl'])),
K("Kuka oli Aristoteles?",
  "Antiikin filosofi, joka hylkäsi Demokritoksen atomiopin ja kannatti Empedokleen neljää elementtiä. Hänen näkemyksensä hallitsi 2000 vuotta.",
  "",
  1, L(N('Aristoteles', 'Aristoteleen', 'Aristotelesta', 'Aristoteleen näkemys', 'neljä elementtiä', 'neljän elementin', 'neljän elementin oppi', 'neljän elementin opin', 'elementti', 'elementin', 'elementtiä', 'elementit', 'elementtien', 'elementtejä', 'maa, ilma, vesi ja tuli'))),
K("Kuka oli Jöns Jakob Berzelius?",
  "Ruotsalainen kemisti, joka määritti 1800-luvun alussa alkuaineiden suhteelliset atomipainot ja otti käyttöön kirjainlyhenteet (H, O, Fe).",
  "",
  2, L(N('Berzelius', 'Berzeliuksen', 'Berzeliusta', 'Jöns Jakob Berzelius', 'Jöns Jakob Berzeliuksen', 'alkuainemerkki', 'alkuainemerkin', 'alkuainemerkkiä', 'alkuainemerkit', 'alkuainemerkkien', 'alkuainemerkkejä', 'kirjainlyhenne', 'kirjainlyhenteen', 'kirjainlyhenteet', 'kemiallinen merkki', 'kemiallisen merkin', 'kemialliset merkit', 'symboli', 'symbolin', 'symbolia', 'symbolit', 'symbolien', 'symboleja'))),
K("Kuka oli Stanislao Cannizzaro?",
  "Italialainen kemisti, joka esitti 1860 Karlsruhen kongressissa Avogadron lakiin nojaavan yhtenäisen atomimassojen määrityksen, jonka kemistit omaksuivat.",
  "",
  1, L(N('Cannizzaro', 'Cannizzaron', 'Cannizzaroa', 'Stanislao Cannizzaro', 'Karlsruhen kongressi', 'Karlsruhen kongressin', 'Karlsruhen kongressissa'))),
K("Kuka oli Georgius Agricola?",
  "Saksalainen 1500-luvun oppinut, jonka teos De re metallica kuvasi kaivostoiminnan ja metallien jalostuksen järjestelmällisesti.",
  "",
  1, L(N('Agricola', 'Agricolan', 'Agricolaa', 'Georgius Agricola', 'Georgius Agricolan', 'De re metallica', 'kaivostoiminta', 'kaivostoiminnan', 'kaivostoimintaa', 'metallien jalostus', 'metallien jalostuksen'))),
K("Kuka oli Joseph Proust?",
  "Ranskalainen kemisti, joka osoitti 1799 kuparikarbonaatilla vakiosuhteiden lain: yhdisteen alkuaineiden massasuhde on aina sama.",
  "",
  1, L(N('Proust', 'Proustin', 'Proustia', 'Joseph Proust', 'Joseph Proustin'))),
K("Mikä on kaasu?",
  "Aineen olomuoto, jossa hiukkaset liikkuvat vapaasti ja täyttävät astian. Gay-Lussacin ja Avogadron kaasulait johtivat oikeisiin kaavoihin.",
  "",
  2, L(N('kaasumainen', 'kaasumaisen', 'kaasumaista', 'kaasumaiset', 'kaasumaisia', 'kaasumaisten', 'kaasulaki', 'kaasulain', 'kaasulakia', 'kaasulait', 'kaasulakien', 'kaasufaasi', 'kaasufaasin', 'kaasufaasissa', 'kaasujen', 'kaasuja', 'kaasuissa', 'kaksiatominen', 'kaksiatomisen', 'kaksiatomiset', 'kaksiatomisia', 'kaksiatomisina', 'kaksiatominen molekyyli', 'kaksiatomisen molekyylin', 'kaksiatomiset molekyylit'))),
K("Mikä on typpihappo?",
  "Vahva happo HNO<sub>3</sub>, jonka alkemistit tunsivat. Nykyään valmistetaan Ostwaldin menetelmällä ammoniakista. Anioni on nitraatti.",
  "",
  2, L('typpihappo', ['HNO3', 'HNO<sub>3</sub>', 'typpihapoke', 'typpihapokkeen', 'typpihapoketta', 'HNO2', 'vahva happo alkemiassa'])),
K("Mitä tyhjä tila atomissa tarkoittaa?",
  "Rutherfordin päätelmä: atomi on lähes kokonaan tyhjää, koska useimmat alfahiukkaset läpäisivät kultakalvon suoraan.",
  "",
  1, L(N('tyhjä tila', 'tyhjän tilan', 'tyhjää tilaa', 'tyhjässä tilassa', 'tyhjyys', 'tyhjyyden', 'tyhjyyttä', 'tiheä ydin', 'tiheän ytimen', 'tiheää ydintä', 'tiheä', 'tiheän', 'tiheää'))),
]

L22 = [
K("Mikä on ammoniakki?",
  "Typen ja vedyn yhdiste NH<sub>3</sub>, heikko emäs. Triviaalinimi on vakiintunut systemaattisen (typpitrihydridi) sijasta.",
  "",
  2, L('ammoniakki', ['NH3', 'NH<sub>3</sub>', 'ammoniumioni', 'ammoniumionin', 'ammoniumionia', 'ammonium', 'ammoniumin', 'NH4+', 'NH<sub>4</sub><sup>+</sup>'])),
K("Mikä on karbonaatti?",
  "Hiilihapon anioni CO<sub>3</sub><sup>2−</sup>. Kalsiumkarbonaatti on kalkkikiveä, natriumkarbonaatti soodaa. Vetykarbonaatti on bikarbonaatti.",
  "",
  2, L('karbonaatti', ['karbonaatti-ioni', 'karbonaatti-ionin', 'karbonaattiioni', 'CO3', 'kalsiumkarbonaatti', 'kalsiumkarbonaatin', 'kalsiumkarbonaattia', 'CaCO3', 'natriumkarbonaatti', 'natriumkarbonaatin', 'sooda', 'soodan', 'soodaa', 'kalkkikivi', 'kalkkikiven', 'kalkkikiveä'])),
K("Mikä on sulfaatti?",
  "Rikkihapon anioni SO<sub>4</sub><sup>2−</sup>, systemaattisesti tetraoksidosulfaatti. Natriumsulfaatti Na<sub>2</sub>SO<sub>4</sub> on dinatriumtetraoksidosulfaatti.",
  "",
  2, L('sulfaatti', ['sulfaatti-ioni', 'sulfaatti-ionin', 'sulfaatti-ionia', 'SO4', 'SO<sub>4</sub>', 'natriumsulfaatti', 'natriumsulfaatin', 'natriumsulfaattia', 'tetraoksidosulfaatti', 'tetraoksidosulfaatin', 'tetraoksido-sulfaatti', 'dinatriumtetraoksidosulfaatti', 'dinatriumtetraoksidosulfaatin', 'sulfiitti', 'sulfiitin', 'sulfiittia', 'sulfiitti-ioni', 'sulfiitti-ionin', 'SO3', 'rikkihapoke', 'rikkihapokkeen', 'rikkihapoketta', 'H2SO3'])),
K("Mikä on nitraatti nimeämisessä?",
  "Typpihapon anioni NO<sub>3</sub><sup>−</sup>, systemaattisesti trioksidonitraatti. Nitriitti NO<sub>2</sub><sup>−</sup> on happiköyhempi, typpihapokkeen anioni.",
  "",
  1, L(N('nitriitti', 'nitriitin', 'nitriittiä', 'nitriitti-ioni', 'nitriitti-ionin', 'NO2-', 'natriumnitraatti', 'natriumnitraatin', 'natriumnitraattia', 'natriumtrioksidonitraatti', 'trioksidonitraatti', 'trioksidonitraatin', 'NO3'))),
K("Mikä on fosfaatti nimeämisessä?",
  "Fosforihapon anioni PO<sub>4</sub><sup>3−</sup>, systemaattisesti tetraoksidofosfaatti. Natriumfosfaatti on trinatriumtetraoksidofosfaatti.",
  "",
  1, L(N('natriumfosfaatti', 'natriumfosfaatin', 'natriumfosfaattia', 'trinatriumtetraoksidofosfaatti', 'tetraoksidofosfaatti', 'tetraoksidofosfaatin', 'PO4', 'PO<sub>4</sub>', 'Na3PO4', 'fosfidi', 'fosfidin', 'fosfidia', 'fosfidi-ioni', 'tetrasulfidofosfaatti', 'trinatriumtetrasulfidofosfaatti', 'heksakloridofosfaatti', 'natriumheksakloridofosfaatti'))),
K("Mitkä ovat kloorin oksoanionit?",
  "Hypokloriitti, kloriitti, kloraatti ja perkloraatti: yksi, kaksi, kolme ja neljä happea kloorin ympärillä.",
  "Kun sama keskusatomi muodostaa useita oksoanioneja, happirikkaampi saa päätteen -aatti ja happiköyhempi -iitti. Kloorilla sarja on neljän mittainen, joten sitä laajennetaan etuliitteillä: hypo- tarkoittaa vielä vähemmän happea kuin -iitti ja per- vielä enemmän kuin -aatti. Näin hypokloriitissa on yksi happi, kloriitissa kaksi, kloraatissa kolme ja perkloraatissa neljä. Kloorin hapetusluku kasvaa samalla yhdestä seitsemään. Bromilla ja jodilla on vastaavat sarjat.",
  2, L(N('hypokloriitti', 'hypokloriitin', 'hypokloriittia', 'hypokloriitti-ioni', 'kloriitti', 'kloriitin', 'kloriittia', 'kloriitti-ioni', 'kloraatti', 'kloraatin', 'kloraattia', 'kloraatti-ioni', 'perkloraatti', 'perkloraatin', 'perkloraattia', 'perkloraatti-ioni', 'hypo', 'hypo-', 'per', 'per-', 'hypo-etuliite', 'per-etuliite', 'ClO', 'ClO2', 'ClO3', 'ClO4'))),
K("Mitkä ovat kloorin oksohapot?",
  "Hypokloorihapoke HClO, kloorihapoke HClO<sub>2</sub>, kloorihappo HClO<sub>3</sub> ja perkloorihappo HClO<sub>4</sub>.",
  "",
  2, L(N('hypokloorihapoke', 'hypokloorihapokkeen', 'hypokloorihapoketta', 'kloorihapoke', 'kloorihapokkeen', 'kloorihappo', 'kloorihapon', 'kloorihappoa', 'perkloorihappo', 'perkloorihapon', 'perkloorihappoa', 'HClO', 'HClO2', 'HClO3', 'HClO4', '-hapoke', '-happo'))),
K("Mikä on syanidi?",
  "Moniatominen anioni CN<sup>−</sup>, jonka -idi-pääte on poikkeus: yleensä -idi on yksiatominen. HCN on sinihappo.",
  "",
  1, L('syanidi', ['syanidi-ioni', 'syanidi-ionin', 'syanidi-ionia', 'CN-', 'vetysyanidi', 'vetysyanidin', 'vetysyanidia', 'HCN', 'sinihappo', 'sinihapon', 'sinihappoa'])),
K("Mikä on fluoridi?",
  "Fluorin anioni F<sup>−</sup>. Vanadiini(V)fluoridi VF<sub>5</sub> on esimerkki nimestä, jossa roomalainen hapetusluku määrää kaavan.",
  "",
  1, L('fluoridi', ['fluoridi-ioni', 'fluoridi-ionin', 'vanadiini(V)fluoridi', 'vanadiini(V)fluoridin', 'vanadiinifluoridi', 'vanadiini', 'vanadiinin', 'VF5', 'dihappidifluoridi', 'dihappidifluoridin', 'O2F2', 'galliumoksidi', 'galliumoksidin', 'Ga2O3', 'mangaanidioksidi', 'mangaanidioksidin', 'MnO2'])),
K("Mikä on karbidi?",
  "Hiilen anioni yhdisteessä metallin kanssa, kuten kalsiumkarbidi CaC<sub>2</sub>. Kantaosa karb- tulee latinan carbo.",
  "",
  1, L('karbidi', ['karbidi-ioni', 'kalsiumkarbidi', 'kalsiumkarbidin', 'karb', 'karb-', 'kantaosa karb'])),
K("Mikä on nitridi?",
  "Typen anioni N<sup>3−</sup> metallin kanssa, kuten litiumnitridi Li<sub>3</sub>N eli trilitiumnitridi. Kantaosa nitr-.",
  "",
  1, L('nitridi', ['nitridi-ioni', 'litiumnitridi', 'litiumnitridin', 'trilitiumnitridi', 'trilitiumnitridin', 'Li3N', 'nitr', 'nitr-', 'kantaosa nitr'])),
K("Mitkä ovat typen oksidit?",
  "Kovalenttisia yhdisteitä, joiden nimissä lukusanaetuliitteet erottavat sarjan jäsenet: dityppioksidi, typpimonoksidi, typpidioksidi, dityppipentoksidi.",
  "Typpi ja happi muodostavat kokonaisen sarjan oksideja, ja juuri siksi nimeen tarvitaan lukumäärän etuliitteet. Dityppioksidi eli dityppimonoksidi N<sub>2</sub>O on ilokaasu, typpimonoksidi NO viestimolekyyli, typpidioksidi NO<sub>2</sub> ruskea myrkyllinen kaasu, dityppitetroksidi N<sub>2</sub>O<sub>4</sub> sen dimeeri ja dityppipentoksidi N<sub>2</sub>O<sub>5</sub> typpihapon anhydridi. Mono jää pois ensimmäisen alkuaineen edestä, ja loppuvokaali voi kadota (tetroksidi, pentoksidi).",
  2, L(N('typpioksidi', 'typpioksidin', 'typpioksidia', 'typpioksidit', 'typpioksidien', 'typpioksideja', 'typen oksidit', 'typen oksidien', 'dityppioksidi', 'dityppioksidin', 'dityppimonoksidi', 'dityppimonoksidin', 'N2O', 'ilokaasu', 'ilokaasun', 'typpimonoksidi', 'typpimonoksidin', 'NO', 'dityppitrioksidi', 'dityppitrioksidin', 'N2O3', 'typpidioksidi', 'typpidioksidin', 'NO2', 'dityppitetroksidi', 'dityppitetroksidin', 'dityppitetraoksidi', 'dityppitetraoksidin', 'N2O4', 'dityppipentoksidi', 'dityppipentoksidin', 'dityppipentaoksidi', 'dityppipentaoksidin', 'N2O5'))),
K("Mikä on rikkihappo nimeämisessä?",
  "H<sub>2</sub>SO<sub>4</sub>, sulfaatin oksohappo. Rikkihapoke H<sub>2</sub>SO<sub>3</sub> vastaa happiköyhempää sulfiittia.",
  "",
  1, L(N('H2SO4', 'H<sub>2</sub>SO<sub>4</sub>', 'rikkihappoon', 'rikkihapossa'))),
K("Mikä on vetykloridi?",
  "Kaasu HCl, vesiliuoksena suolahappo. Hapettomat hapot nimetään vety + anioni: vetybromidi, vetysulfidi.",
  "",
  2, L('vetykloridi', ['HCl', 'vetybromidi', 'vetybromidin', 'vetybromidia', 'HBr', 'bromidi', 'bromidin', 'bromidia', 'bromidi-ioni', 'vetysulfidi', 'vetysulfidin', 'vetysulfidia', 'divetysulfidi', 'divetysulfidin', 'H2S', 'rikkivety', 'rikkivedyn', 'rikkivetyä', 'vetyjodidi', 'vetyjodidin', 'jodidi', 'jodidin', 'jodidi-ioni', 'hapeton happo', 'hapettoman hapon', 'hapettomat hapot', 'hapettomia happoja', 'hapettomien happojen'])),
K("Mikä on divetyoksidi?",
  "Veden systemaattinen nimi H<sub>2</sub>O:lle. Käytännössä vakiintunut nimi vesi säilyy, kuten ammoniakki.",
  "",
  1, L('divetyoksidi', ['H2O', 'H<sub>2</sub>O', 'vakiintunut nimi', 'vakiintuneen nimen', 'vakiintuneet nimet', 'arkikielen nimi', 'arkikielen nimen', 'arkinimi', 'arkinimen'])),
K("Mikä on hydraatti?",
  "Kidevedellinen yhdiste: kuparisulfaattipentahydraatti CuSO<sub>4</sub>·5H<sub>2</sub>O sisältää viisi vettä kaavayksikköä kohti. Nimessä kreikkalainen lukusana.",
  "",
  2, L(N('pentahydraatti', 'pentahydraatin', 'pentahydraattia', 'dekahydraatti', 'dekahydraatin', 'dekahydraattia', 'heksahydraatti', 'heksahydraatin', 'dihydraatti', 'dihydraatin', 'monohydraatti', 'monohydraatin', 'kuparisulfaattipentahydraatti', 'kuparisulfaattipentahydraatin', 'CuSO4·5H2O'))),
K("Mitkä ovat kreikkalaiset lukusanaetuliitteet?",
  "Lukumäärän etuliitteet mono, di, tri, tetra, penta, heksa, hepta, okta, nona, deka, hendeka ja dodeka.",
  "Binaaristen kovalenttiyhdisteiden nimissä atomien lukumäärä ilmaistaan kreikan lukusanoista johdetuilla etuliitteillä: mono yksi, di kaksi, tri kolme, tetra neljä, penta viisi, heksa kuusi, hepta seitsemän, okta kahdeksan, nona yhdeksän, deka kymmenen, hendeka yksitoista ja dodeka kaksitoista. Murto-osille on hemi puolikas ja seskvi puolitoista. Etuliite jätetään pois, kun nimi on muutenkin yksiselitteinen. Ioniyhdisteissä etuliitteitä ei käytetä.",
  2, L(N('mono', 'mono-', 'di', 'di-', 'tri', 'tri-', 'tetra', 'tetra-', 'penta', 'penta-', 'heksa', 'heksa-', 'hepta', 'hepta-', 'okta', 'okta-', 'nona', 'nona-', 'deka', 'deka-', 'hendeka', 'hendeka-', 'dodeka', 'dodeka-', 'seskvi', 'seskvi-', 'hemi-', 'lukusanaetuliite', 'lukusanaetuliitteen', 'lukusanaetuliitteet', 'lukusanaetuliitteitä', 'lukumäärän etuliite', 'lukumäärän etuliitteen', 'lukumäärän etuliitteet', 'kreikkalainen lukusana', 'kreikkalaisen lukusanan', 'kreikkalaiset lukusanat', 'kreikan lukusanat', 'kreikan lukusanoihin'))),
K("Mikä on roomalainen numero hapetusluvun merkintänä?",
  "Sulkeissa nimen perässä oleva luku, kuten rauta(III)kloridi, kertoo metallin hapetusluvun, kun metallilla on useita mahdollisia.",
  "",
  2, L(N('roomalainen numero', 'roomalaisen numeron', 'roomalaista numeroa', 'roomalaiset numerot', 'roomalaisin numeroin', 'roomalaisella numerolla', 'rauta(III)kloridi', 'rauta(III)kloridin', 'rauta(II)kloridi', 'rauta(II)kloridin', 'FeCl3', 'FeCl2', 'rauta(III)', 'rauta(II)', 'Stock-järjestelmä', 'Stock-järjestelmän', 'Stockin järjestelmä', 'Stockin järjestelmän'))),
K("Mikä on oksido-ligandi?",
  "Täysin systemaattisessa nimessä happiatomi keskusatomin ympärillä: sulfaatti on tetraoksidosulfaatti, jossa neljä oksidoa on liittynyt rikkiin.",
  "",
  1, L(N('oksido', 'oksido-', 'oksidoligandi', 'oksidoligandin', 'oksidoligandit', 'oksido-ligandi', 'oksido-ligandin', 'täysin systemaattinen nimi', 'täysin systemaattisen nimen', 'täysin systemaattiset nimet', 'additiivinen nimi', 'additiivisen nimen', 'additiivinen nimeäminen', 'additiivisen nimeämisen'))),
K("Mikä on litiumalumiinihydridi?",
  "LiAlH<sub>4</sub>, systemaattisesti litiumtetrahydridoaluminaatti. Voimakas pelkistin, jossa neljä hydridoligandia on liittynyt alumiiniin.",
  "",
  1, L('litiumalumiinihydridi', ['litiumalumiinihydridin', 'litiumalumiinihydridiä', 'litiumtetrahydridoaluminaatti', 'litiumtetrahydridoaluminaatin', 'LiAlH4', 'tetrahydridoaluminaatti', 'tetrahydridoaluminaatin', 'hydrido', 'hydrido-', 'hydridoligandi', 'hydridoligandin', 'litiumhydridi', 'litiumhydridin', 'LiH'])),
K("Mikä on magnesiumoksidi?",
  "MgO, binaarinen ioniyhdiste magnesium- ja oksidi-ioneista. Nimessä ei lukusanaetuliitteitä, koska ionien varaukset määräävät suhteen.",
  "",
  1, L('magnesiumoksidi', ['MgO', 'kalsiumkloridi', 'kalsiumkloridin', 'kalsiumkloridia', 'CaCl2', 'kalsiumsulfidi', 'kalsiumsulfidin', 'kalsiumsulfidia', 'CaS', 'kalsium-ioni', 'kalsium-ionin', 'kalsiumioni', 'natriumioni', 'natriumionin', 'natriumionit', 'natrium-ioni', 'natrium-ionin', 'magnesiumioni', 'magnesiumionin', 'magnesium-ioni'])),
K("Mikä on yhdysviiva yhdisteen nimessä?",
  "Väliviiva, jota käytetään lukusanaetuliitteen ja nimen välissä selkeyden vuoksi, kuten tetraoksido-sulfaatti, tai ioninimissä kuten sulfaatti-ioni.",
  "",
  1, L(N('yhdysviiva', 'yhdysviivan', 'yhdysviivaa', 'yhdysviivat', 'väliviiva', 'väliviivan', 'väliviivaa', 'loppuvokaali', 'loppuvokaalin', 'loppuvokaalia', 'kielenasu', 'kielenasun', 'kielenasua', 'tetraoksidi', 'tetroksidi', 'tetroksidin', 'pentoksidi', 'pentoksidin', 'pentaoksidi'))),
K("Mikä on Arrheniuksen happo?",
  "Klassinen määritelmä: happo on aine, joka vedessä luovuttaa protonin ja lisää oksoniumioneja, emäs lisää hydroksidi-ioneja.",
  "",
  2, L(N('Arrhenius', 'Arrheniuksen', 'Arrheniusta', 'Arrheniuksen happo', 'Arrheniuksen hapon', 'Arrheniuksen emäs', 'Arrheniuksen emäksen', 'Arrheniuksen määritelmä', 'Arrheniuksen määritelmän', 'klassinen happomääritelmä', 'klassisen happomääritelmän', 'Svante Arrhenius'))),
K("Mitä miljoonat yhdisteet tarkoittavat nimeämisen kannalta?",
  "Tunnettuja yhdisteitä on yli sata miljoonaa, joten jokaiselle tarvitaan yksilöivä, yksiselitteinen nimi sekaannusten välttämiseksi.",
  "",
  1, L(N('yksilöivä nimi', 'yksilöivän nimen', 'yksilöivä', 'yksilöivän', 'yksiselitteinen', 'yksiselitteisen', 'yksiselitteistä', 'yksiselitteiset', 'yksiselitteisesti', 'yksiselitteisissä', 'sekaannus', 'sekaannuksen', 'sekaannusta', 'sekaannukset', 'sekaannusten', 'sekaannuksia'))),
]

L31 = [
K("Kuka oli Lothar Meyer?",
  "Saksalainen kemisti, joka laati Mendelejevin kanssa samoihin aikoihin (1864–1870) jaksollisen taulukon atomitilavuuksien perusteella.",
  "",
  1, L(N('Lothar Meyer', 'Lothar Meyerin', 'Meyer', 'Meyerin', 'Meyeriä', 'Meyerin taulukko', 'Meyerin taulukon'))),
K("Mikä on kompromissijärjestelmä ryhmien nimeämisessä?",
  "IUPACin nykyinen käytäntö: ryhmät numeroidaan 1–18 vasemmalta oikealle vanhojen eurooppalaisten (IA…VIIIB) ja amerikkalaisten kirjainmerkintöjen sijasta.",
  "",
  2, L('kompromissijärjestelmä', ['kompromissijärjestelmän', 'kompromissijärjestelmää', 'IUPAC-järjestelmä', 'IUPAC-järjestelmän', 'IUPACin järjestelmä', 'IUPACin järjestelmän', 'eurooppalainen järjestelmä', 'eurooppalaisen järjestelmän', 'eurooppalaisessa järjestelmässä', 'eurooppalainen', 'eurooppalaisen', 'eurooppalaisessa', 'amerikkalainen järjestelmä', 'amerikkalaisen järjestelmän', 'amerikkalaisessa järjestelmässä', 'amerikkalainen', 'amerikkalaisen', 'amerikkalaisessa', 'nimeämiskäytäntö', 'nimeämiskäytännön', 'nimeämiskäytäntöä', 'nimeämiskäytännöt', 'IIIA', 'IIIB', 'ryhmänumero', 'ryhmänumeron', 'ryhmänumerot', 'ryhmien numerointi', 'ryhmien numeroinnin'])),
K("Mikä on jaksollinen taulukko?",
  "Alkuaineiden taulukko järjestysluvun mukaan: vaakarivit ovat jaksoja, pystysarakkeet ryhmiä. Kutsutaan myös: alkuaineiden taulukko.",
  "",
  2, L(N('jaksollinen taulukko', 'jaksollisen taulukon', 'jaksollista taulukkoa', 'jaksollisessa taulukossa', 'taulukko', 'taulukon', 'taulukkoa', 'taulukossa', 'taulukosta', 'taulukot', 'alkuaineiden taulukko', 'alkuaineiden taulukon', 'vaakarivi', 'vaakarivin', 'vaakariviä', 'vaakarivit', 'vaakarivien', 'vaakarivejä', 'pystysarake', 'pystysarakkeen', 'pystysaraketta', 'pystysarakkeet', 'pystysarakkeiden', 'pystysarakkeita'))),
K("Mikä on atomin halkaisija?",
  "Noin 10<sup>−10</sup> m eli 0,1 nm, ydin vain 10<sup>−15</sup> m. Elektronipilvi määrää koon.",
  "",
  2, L(N('atomin halkaisija', 'atomin halkaisijan', 'atomin koko', 'atomin koon', 'atomin kokoa', 'atomisäde', 'atomisäteen', 'atomisädettä', 'atomisäteet', 'atomisäteiden', 'ytimen halkaisija', 'ytimen halkaisijan', 'ytimen koko', 'ytimen koon'))),
K("Mikä on luokittelu kemiassa?",
  "Aineiden ryhmittely ominaisuuksien mukaan, kuten alkuaineiden luokittelu jaksoihin ja ryhmiin tai metalleihin ja epämetalleihin.",
  "",
  1, L('luokittelu', ['luokitella', 'luokitellaan', 'luokiteltu', 'luokittelun', 'luokittelua', 'luokitteluun', 'ryhmittely', 'ryhmittelyn', 'ryhmittelyä', 'ryhmitellä', 'ryhmittelee', 'taksonomia', 'taksonomian', 'taksonomiaa', 'taksonomiassa', 'järjestäytyminen', 'järjestäytymisen', 'järjestäytymisestä'])),
K("Mikä on nuklidimerkintä?",
  "Alkuaineen merkitsemistapa <sup>A</sup><sub>Z</sub>X: massaluku A ylhäällä, järjestysluku Z alhaalla, kuten <sup>12</sup><sub>6</sub>C.",
  "",
  1, L(N('merkitsemistapa', 'merkitsemistavan', 'merkitsemistapaa', 'yhteisnimitys', 'yhteisnimityksen', 'yhteisnimitystä', 'nuklidimerkintä', 'nuklidimerkinnän', 'nuklidimerkintää', 'nuklidi', 'nuklidin', 'nuklidia', 'nuklidit', 'nuklidien'))),
]

L32 = [
K("Mikä on aaltoliike?",
  "Häiriön eteneminen väliaineessa tai kentässä ilman aineen siirtymistä. Sähkömagneettinen säteily on sähkö- ja magneettikentän aaltoliikettä.",
  "",
  2, L(N('aaltoliike', 'aaltoliikkeen', 'aaltoliikettä', 'aaltoliikkeessä', 'aaltoliikkeeseen', 'aalto', 'aallon', 'aaltoa', 'aallossa', 'aallot', 'aaltojen', 'aaltoja', 'aalloissa', 'aaltomuoto', 'aaltomuodon', 'huippu', 'huipun', 'huippua', 'huiput', 'laakso', 'laakson', 'laaksoa', 'laaksot', 'sykli', 'syklin', 'sykliä', 'syklit', 'syklien', 'syklejä', 'värähtely', 'värähtelyn', 'värähtelyä', 'värähdys', 'värähdyksen', 'värähdystä', 'värähdykset'))),
K("Mikä on ilotulitusten väri?",
  "Metallisuolojen liekissä virittyneet atomit emittoivat aineelle ominaisia aallonpituuksia: kupari sinistä, natrium keltaista, strontium punaista.",
  "",
  1, L(N('ilotulitus', 'ilotulituksen', 'ilotulitusta', 'ilotulitukset', 'ilotulitusten', 'ilotulituksia', 'liekkikoe', 'liekkikokeen', 'liekkikoetta', 'liekki', 'liekin', 'liekkiä', 'liekissä', 'liekkiväri', 'liekkivärin', 'liekkivärit', 'sininen liekki', 'sinisen liekin', 'sininen valo', 'sinisen valon', 'sinistä valoa', 'sininen', 'sinisen', 'sinistä'))),
K("Mikä on joule?",
  "Energian SI-yksikkö J. Sinisen 450 nm:n valon fotoni kantaa 4,4·10<sup>−19</sup> J.",
  "",
  2, L(N('joule', 'joulen', 'joulea', 'joulet', 'joulen murto-osa', 'kJ', 'kilojoule', 'kilojoulen', 'kilojoulea', 'kJ/mol', 'energiayksikkö', 'energiayksikön', 'elektronivoltti', 'elektronivoltin', 'elektronivolttia', 'eV'))),
K("Mikä on koordinaatti aaltofunktiossa?",
  "Avaruuden pisteen sijainti (x, y, z tai r, θ, φ), jossa aaltofunktion arvo lasketaan.",
  "",
  1, L(N('koordinaatti', 'koordinaatin', 'koordinaattia', 'koordinaatit', 'koordinaattien', 'koordinaatteja', 'koordinaattipiste', 'koordinaattipisteen', 'koordinaattipisteessä', 'avaruus', 'avaruuden', 'avaruutta', 'avaruudessa', 'avaruuteen', 'paikka', 'paikan', 'paikkaa', 'paikassa', 'sijainti', 'sijainnin', 'sijaintia', 'sijaintiin', 'sijaitsee', 'pallokoordinaatit', 'pallokoordinaattien', 'pallokoordinaatisto', 'pallokoordinaatiston'))),
K("Mikä on monielektroninen atomi?",
  "Atomi, jossa on useampi elektroni. Elektronien hylkintä rikkoo vedyn degeneraation: 2s on alempana kuin 2p.",
  "",
  2, L(N('monielektroninen atomi', 'monielektronisen atomin', 'monielektronista atomia', 'monielektroniset atomit', 'monielektronisten atomien', 'monielektronisia atomeja', 'monielektronisilla atomeilla', 'monielektroninen', 'monielektronisen', 'monielektronista', 'monielektroniset', 'monielektronisia', 'monielektronisiin', 'yksielektroninen', 'yksielektronisen', 'yksielektroniset', 'vedynkaltainen', 'vedynkaltaisen', 'vedynkaltaiset', 'elektronien hylkintä', 'elektronien hylkinnän', 'elektronien välinen hylkintä', 'ydinvaraus', 'ydinvarauksen', 'ydinvarausta', 'efektiivinen ydinvaraus', 'efektiivisen ydinvarauksen', 'efektiivistä ydinvarausta', 'varjostus', 'varjostuksen', 'varjostusta', 'varjostaa', 'varjostavat'))),
K("Mitä pallomainen tarkoittaa orbitaalista?",
  "s-orbitaalin muoto: todennäköisyys riippuu vain etäisyydestä ytimestä, ei suunnasta. Sisäkkäiset pallopinnat kuvaavat todennäköisyyden jakaumaa säteen funktiona.",
  "",
  2, L(N('pallomainen', 'pallomaisen', 'pallomaista', 'pallomaiset', 'pallomaisia', 'pallosymmetrinen', 'pallosymmetrisen', 'pallosymmetriset', 'pallopinta', 'pallopinnan', 'pallopintaa', 'pallopinnat', 'pallopintojen', 'pallopintoja', 'pallopintoihin', 'pallopinnoilta', 'pallokuori', 'pallokuoren', 'pallokuorta', 'pallokuoret', 'säde', 'säteen', 'sädettä', 'säteet', 'säteiden', 'etäisyys ytimestä', 'etäisyyden ytimestä', 'radiaalinen', 'radiaalisen', 'radiaalinen todennäköisyys', 'radiaalisen todennäköisyyden', 'radiaalijakauma', 'radiaalijakauman'))),
K("Mikä on sähköpurkaus?",
  "Sähkövirran kulku kaasun läpi, joka virittää atomit. Vetykaasun purkausputki säteilee vedyn viivaspektrin.",
  "",
  1, L('sähköpurkaus', ['sähköpurkauksen', 'sähköpurkausta', 'purkausputki', 'purkausputken', 'purkausputkea', 'kaasupurkaus', 'kaasupurkauksen', 'kaasupurkausta', 'vetykaasu', 'vetykaasun', 'vetykaasua', 'vetykaasussa', 'vetylamppu', 'vetylampun'])),
K("Mikä on tennispallo de Broglien esimerkkinä?",
  "Makroskooppisen kappaleen aallonpituus λ = h/mv on niin pieni (10<sup>−34</sup> m), ettei aaltoluonne näy.",
  "",
  1, L(N('tennispallo', 'tennispallon', 'tennispalloa', 'makroskooppinen', 'makroskooppisen', 'makroskooppista', 'makroskooppiset', 'makroskooppisia', 'makroskooppinen kappale', 'makroskooppisen kappaleen', 'makroskooppiset kappaleet', 'suuri kappale', 'suuren kappaleen', 'suuret kappaleet', 'suurilla kappaleilla', 'kappale', 'kappaleen', 'kappaletta', 'kappaleet', 'kappaleiden', 'kappaleita', 'kappaleilla', 'mikroskooppinen', 'mikroskooppisen', 'mikroskooppiset', 'mikroskooppisia'))),
K("Mitä tilastollinen tarkoittaa kvanttimekaniikassa?",
  "Kvanttimekaniikka ei kerro elektronin tarkkaa paikkaa vaan todennäköisyyden löytää se kustakin pisteestä: |ψ|² on tilastollinen jakauma.",
  "",
  2, L(N('tilastollinen jakauma', 'tilastollisen jakauman', 'todennäköisyyspohjainen', 'todennäköisyyspohjaisen', 'todennäköisyyspohjaista', 'todennäköisyys', 'todennäköisyyden', 'todennäköisyyttä', 'todennäköisyydellä', 'todennäköisyydet', 'todennäköisyyksien', 'todennäköisin', 'todennäköisimmin', 'todennäköisimmän', 'todennäköisimmillä'))),
K("Mikä on yläindeksi konfiguraatiomerkinnässä?",
  "Orbitaalimerkinnän oikean yläkulman luku, joka kertoo elektronien määrän: 2p<sup>6</sup> tarkoittaa kuutta elektronia 2p-orbitaaleilla.",
  "",
  2, L(N('yläindeksi', 'yläindeksin', 'yläindeksiä', 'yläindeksit', 'yläindeksillä', 'yhteismerkintä', 'yhteismerkinnän', 'yhteismerkintää', 'orbitaalimerkintä', 'orbitaalimerkinnän', 'orbitaalimerkintää', 'konfiguraatiomerkintä', 'konfiguraatiomerkinnän', 'konfiguraatiomerkintää', 'nlx-merkintä', 'nlx-merkinnän', '1s2', '1s²', '2p6', '2p⁶', '3d10'))),
K("Mikä on separointivakio?",
  "Vakio, joka syntyy, kun Schrödingerin yhtälö jaetaan säde- ja kulmaosiin. Reunaehdot tekevät niistä kvanttiluvut.",
  "",
  1, L(N('separointivakio', 'separointivakion', 'separointivakiot', 'separointivakioiden', 'separoimisvakio', 'separoimisvakion', 'separoimisvakiot', 'separoimisvakioista', 'muuttujien separointi', 'muuttujien separoinnin', 'separointi', 'separoinnin', 'separoida', 'separoidaan'))),
K("Mikä on sekunti taajuuden yksikössä?",
  "Ajan SI-yksikkö s. Taajuus on värähdyksiä sekunnissa (1/s = Hz), valonnopeus metrejä sekunnissa.",
  "",
  1, L(N('sekunti', 'sekunnin', 'sekuntia', 'sekunnit', 'sekuntien', 'sekunteja', 'sekunnissa', '1/s', 'aikayksikkö', 'aikayksikön', 'aikayksikköä', 'metriä sekunnissa', 'm/s', 'valonnopeus', 'valonnopeuden', 'valonnopeutta', 'valon nopeus', 'valon nopeuden'))),
K("Mikä on vakio fysiikan kaavoissa?",
  "Muuttumaton luku, kuten Planckin vakio h = 6,626·10<sup>−34</sup> Js tai valonnopeus c. Yhdistää suureet kaavoissa.",
  "",
  1, L(N('vakio', 'vakion', 'vakiota', 'vakiot', 'vakioiden', 'vakioita', 'vakiona', 'vakioista', 'luonnonvakio', 'luonnonvakion', 'luonnonvakiot', 'luonnonvakioiden', 'luonnonvakioita', 'kaava', 'kaavan', 'kaavaa', 'kaavassa', 'kaavat', 'kaavojen', 'kaavoja', 'kaavana', 'yhtälö', 'yhtälön', 'yhtälöä', 'yhtälössä', 'yhtälöllä', 'yhtälöt', 'yhtälöiden', 'yhtälöitä'))),
K("Mikä on funktio matematiikassa?",
  "Sääntö, joka liittää muuttujan arvoon yhden arvon. Aaltofunktio ψ(x, y, z) on paikan funktio.",
  "",
  1, L(N('funktio', 'funktion', 'funktiota', 'funktiot', 'funktioiden', 'funktioita', 'funktiona', 'matemaattinen funktio', 'matemaattisen funktion', 'matemaattinen', 'matemaattisen', 'matemaattista', 'matemaattiset', 'matemaattisia', 'matemaattisesti', 'neliö', 'neliön', 'neliötä', 'neliöön', 'psi', 'ψ', 'ψ²', '|ψ|²', 'psii'))),
K("Mitä klassinen mekaniikka tarkoittaa?",
  "Newtonin fysiikka, jossa kappaleella on tarkka paikka ja nopeus. Ei päde atomeihin: elektroni on seisova aalto.",
  "",
  2, L(N('klassinen mekaniikka', 'klassisen mekaniikan', 'klassista mekaniikkaa', 'klassinen fysiikka', 'klassisen fysiikan', 'klassista fysiikkaa', 'klassinen', 'klassisen', 'klassista', 'klassiset', 'klassisia', 'klassisilla', 'klassisesti', 'Newtonin mekaniikka', 'Newtonin mekaniikan', 'mekaniikka', 'mekaniikan', 'mekaniikkaa', 'kvanttimekaaninen', 'kvanttimekaanisen', 'kvanttimekaanista', 'kvanttimekaaniset'))),
K("Mikä on systeemi fysiikassa?",
  "Tarkasteltava kokonaisuus, kuten atomi ja sen elektronit. Planckin mukaan systeemi vastaanottaa ja luovuttaa energiaa vain kvantteina.",
  "",
  1, L('systeemi', ['järjestelmä', 'järjestelmän', 'järjestelmää', 'järjestelmässä', 'järjestelmät', 'järjestelmien', 'järjestelmiä', 'kokonaisenergia', 'kokonaisenergian', 'kokonaisenergiaa', 'systeemin tila', 'systeemin tilan', 'tila', 'tilan', 'tilaa', 'tilassa', 'tilat', 'tilojen', 'tiloja'])),
K("Mikä on ympyrärata Bohrin mallissa?",
  "Bohrin oletus, että elektroni kiertää ydintä vain tietyillä sallituilla ympyränmuotoisilla radoilla. Kvanttimekaniikka korvasi radat orbitaaleilla.",
  "",
  2, L(N('ympyrärata', 'ympyräradan', 'ympyrärataa', 'ympyräradat', 'ympyräratojen', 'ympyräratoja', 'ympyränmuotoinen', 'ympyränmuotoisen', 'ympyränmuotoista', 'ympyränmuotoiset', 'ympyränmuotoisia', 'ympyränmuotoisella', 'ympyränmuotoisilla', 'kiertorata', 'kiertoradan', 'kiertorataa', 'kiertoradat', 'kiertoratojen', 'kiertoratoja', 'kiertoradalla', 'kiertoradoilla', 'rata', 'radan', 'rataa', 'radalla', 'radat', 'ratojen', 'ratoja', 'radoilla', 'sallittu rata', 'sallitun radan', 'sallitut radat', 'sallituilla radoilla', 'kiertää', 'kiertävät', 'kiertäminen'))),
K("Mikä on kadmiumin elektronikonfiguraatio esimerkkinä?",
  "[Kr] 4d<sup>10</sup> 5s<sup>2</sup>: kryptonin täydet kuoret ja niiden päälle 5s ja 4d täyteen.",
  "",
  1, L(N('kadmium', 'kadmiumin', 'kadmiumia', 'kadmiumille', 'Cd', 'krypton', 'kryptonin', 'Kr', '[Kr]', 'neon', 'neonin', 'Ne', '[Ne]', 'jalokaasuydin', 'jalokaasuytimen', 'jalokaasuydintä', 'jalokaasumerkintä', 'jalokaasumerkinnän', 'lyhennetty konfiguraatio', 'lyhennetyn konfiguraation'))),
K("Mikä on sisemmän kuoren elektroni?",
  "Täysien sisäkuorten elektroni, joka ei osallistu sidoksiin mutta varjostaa ydinvarausta. Kutsutaan myös: sisäelektroni.",
  "",
  2, L(N('sisäelektroni', 'sisäelektronin', 'sisäelektronia', 'sisäelektronit', 'sisäelektronien', 'sisäelektroneja', 'sisempi kuori', 'sisemmän kuoren', 'sisempää kuorta', 'sisemmät kuoret', 'sisemmällä kuorella', 'sisemmällä', 'ulompi kuori', 'ulomman kuoren', 'ulompaa kuorta', 'ulommat kuoret', 'ulommalla kuorella', 'uloin kuori', 'uloimman kuoren', 'uloimmalla kuorella', 'kuori', 'kuoren', 'kuorta', 'kuoressa', 'kuoret', 'kuorten', 'kuoria', 'kuorilla'))),
K("Mikä on täyttymisjärjestys?",
  "Orbitaalien energiajärjestys, jossa elektronit sijoittuvat: 1s 2s 2p 3s 3p 4s 3d 4p 5s 4d 5p.",
  "Aufbau-periaatteen mukaan elektronit täyttävät orbitaalit energiajärjestyksessä alimmasta alkaen. Monielektronisessa atomissa järjestys ei seuraa pelkkää pääkvanttilukua, vaan 4s täyttyy ennen 3d:tä ja 5s ennen 4d:tä, koska s-orbitaali tunkeutuu lähemmäs ydintä. Koko sarja on 1s 2s 2p 3s 3p 4s 3d 4p 5s 4d 5p 6s 4f 5d 6p. Muistisääntönä toimii diagonaalikaavio, jonka nuolet kulkevat vinottain. Poikkeuksia on kromilla ja kuparilla.",
  2, L(N('täyttymisjärjestys', 'täyttymisjärjestyksen', 'täyttymisjärjestystä', 'täyttymisjärjestyksessä', 'täyttyminen', 'täyttymisen', 'täyttymistä', 'täyttyä', 'täyttyy', 'täyttyvät', 'täyttyvä', 'täyttyvän', 'diagonaalikaavio', 'diagonaalikaavion', 'diagonaalikaaviota', 'diagonaalisääntö', 'diagonaalisäännön', 'Madelungin sääntö', 'Madelungin säännön', 'energiajärjestys', 'energiajärjestyksen', 'energiajärjestystä', 'energiajärjestyksessä', 'orbitaalienergia', 'orbitaalienergian', 'orbitaalienergiat', 'orbitaalienergioiden'))),
]

LUENNOT = [L1, L21, L22, L31, L32]

# kolmas kierros: sanasto3.py
import sanasto3
L1 += sanasto3.KEMIA_L1
L21 += sanasto3.KEMIA_L21
L22 += sanasto3.KEMIA_L22
L31 += sanasto3.KEMIA_L31
L32 += sanasto3.KEMIA_L32

# massakierros (omistaja 13.9.2026): sanasto_massa/<avain>.txt
import sanasto_massa
L1 += sanasto_massa.kortit("kemia_1")
L21 += sanasto_massa.kortit("kemia_21")
L22 += sanasto_massa.kortit("kemia_22")
L31 += sanasto_massa.kortit("kemia_31")
L32 += sanasto_massa.kortit("kemia_32")
