# -*- coding: utf-8 -*-
"""Kemian peruskurssi I: sanaston taydennys lukuihin 1, 2.1, 2.2, 3.1 ja 3.2 (termit, joita kalvoilla kaytetaan mutta joilla
ei ollut maaritelmakorttia). Numerot jatkuvat kunkin luvun 101:sta. Rakentaa tyokalut/kemia_kortit.py."""
from biotek_taivutus import L
from pakka_rakenna import K

SADE = ['säde', 'säteen', 'sädettä', 'säteessä', 'säteestä', 'säteeseen', 'säteet', 'säteiden', 'säteitä', 'säteissä']

LUENNOT = [
dict(LEHTI='Luento 1 - Johdanto', TIEDOSTO='Luento 1 - Sanasto (lisays)', NRO=1, ALKU=100, KUVAT={}, KORTIT=[
K("Mitä sähkökemia on?",
  "Kemian ala, joka tutkii sähkön ja kemiallisten reaktioiden yhteyttä: elektronien siirtoa hapettumis-pelkistymisreaktioissa.",
  "Sähkökemiassa hapettuminen ja pelkistyminen tapahtuvat eri paikoissa, ja elektronit kulkevat niiden välillä johdinta pitkin. Paristossa reaktio tuottaa sähkövirtaa, elektrolyysissä virta pakottaa reaktion käyntiin. Raudan ruostuminen on sähkökemiallinen ilmiö: rauta hapettuu anodilla, happi pelkistyy katodilla ja suolavesi johtaa ionit niiden välillä. Sähkökemia on paristojen, polttokennojen, korroosionsuojauksen ja metallien pinnoituksen perusta.",
  2, L('sähkökemia', ['sähkökemiallinen', 'sähkökemiallisen', 'sähkökemiallista', 'sähkökemialliset', 'sähkökemiallisia', 'sähkökemiallisesti'])),
K("Mikä on anodi?",
  "Elektrodi, jolla hapettuminen tapahtuu. Raudan ruostuessa rauta luovuttaa elektroneja anodisessa reaktiossa.",
  "",
  2, L('anodi', ['anodinen', 'anodisen', 'anodista', 'anodiset', 'anodisessa', 'anodisella', 'anodiselle', 'anodireaktio', 'anodireaktion'])),
K("Mikä on katodi?",
  "Elektrodi, jolla pelkistyminen tapahtuu. Raudan ruostuessa happi ottaa elektronit vastaan katodisessa reaktiossa.",
  "",
  2, L('katodi', ['katodinen', 'katodisen', 'katodista', 'katodiset', 'katodisessa', 'katodisella', 'katodiselle', 'katodireaktio', 'katodireaktion'])),
K("Mikä on kontrolli kokeessa?",
  "Vertailukoe, jossa tutkittavaa muuttujaa ei muuteta, jotta sen vaikutus voidaan erottaa muista tekijöistä.",
  "",
  2, L('kontrolli', ['kontrollikoe', 'kontrollikokeen', 'kontrollikoetta', 'vertailukoe', 'vertailukokeen', 'vertailukoetta', 'vertailukohta', 'vertailukohdan', 'vertailukohtaa'])),
K("Mikä on muuttuja kokeessa?",
  "Tekijä, joka voi vaihdella ja vaikuttaa tulokseen, kuten lämpötila tai suolapitoisuus. Kokeessa muutetaan yhtä kerrallaan.",
  "",
  2, L('muuttuja')),
K("Mikä on koesuunnitelma?",
  "Etukäteen laadittu kuvaus siitä, mitä muuttujia muutetaan, mitä pidetään vakiona, mitä mitataan ja mihin verrataan.",
  "",
  1, L('koesuunnitelma')),
K("Mitä synteesi tarkoittaa kemiassa?",
  "Yhdisteen valmistamista yksinkertaisemmista aineista kemiallisilla reaktioilla.",
  "",
  2, L('synteesi', ['syntetisoida', 'syntetisoidaan', 'syntetisoitu', 'syntetisoitava', 'synteettinen', 'synteettisen', 'synteettistä', 'synteettiset', 'synteettisiä', 'synteettisesti'])),
K("Mitä analyysi tarkoittaa kemiassa?",
  "Aineen koostumuksen tai rakenteen selvittämistä mittaamalla: mitä ainetta näytteessä on ja kuinka paljon.",
  "",
  2, L('analyysi', ['analysoida', 'analysoidaan', 'analysoitu', 'analyyttinen', 'analyyttisen', 'analyyttistä', 'analyyttiset'])),
K("Mikä on ennuste tieteellisessä menetelmässä?",
  "Hypoteesista johdettu väite siitä, mitä kokeessa pitäisi tapahtua, jos hypoteesi on tosi.",
  "",
  2, L('ennuste', ['ennustaa', 'ennustetaan', 'ennustettu', 'ennustemalli', 'ennustemallin', 'ennustemallia'])),
]),
dict(LEHTI='Luento 2.1 - Kemian historiaa lyhyesti', TIEDOSTO='Luento 2.1 - Sanasto (lisays)', NRO=21, ALKU=100, KUVAT={}, KORTIT=[
K("Mikä oli flogistonteoria?",
  "1700-luvun käsitys, että palava aine luovuttaa flogiston-nimistä ainetta. Lavoisier kumosi sen osoittamalla palamisen olevan yhtymistä happeen.",
  "Flogistonteorian mukaan kaikki palava sisälsi flogistonia, joka vapautui palaessa ja jätti jäljelle tuhkan. Teoria selitti palamisen ja metallien kalkkiutumisen, mutta ei sitä, miksi metalli painaa palettuaan enemmän. Lavoisier punnitsi reaktiot tarkasti suljetuissa astioissa ja osoitti 1770-luvulla, että palamisessa aine yhtyy ilman happeen ja massa säilyy. Flogistonin hylkääminen oli kemian vallankumouksen alku.",
  1, L('flogistonteoria', ['flogiston', 'flogistonin', 'flogistonia'])),
K("Mikä on atomiteoria?",
  "Käsitys, että aine koostuu atomeista. Demokritoksen filosofinen ajatus sai kokeellisen perustan Daltonin teoriasta 1803.",
  "",
  2, L('atomiteoria', ['atomikäsite', 'atomikäsitteen', 'atomikäsitettä', 'atomikäsitys', 'atomikäsityksen', 'atomikäsitystä'])),
K("Mikä on alfahiukkanen?",
  "Heliumin ydin: kaksi protonia ja kaksi neutronia. Radioaktiivisen hajoamisen tuote, jolla Rutherford pommitti kultakalvoa.",
  "Alfahiukkanen on heliumatomin ydin ilman elektroneja, varaukseltaan +2 ja massaltaan noin neljä atomimassayksikköä. Raskaat ytimet, kuten radium ja uraani, lähettävät alfahiukkasia hajotessaan. Ne ovat raskaita ja pysähtyvät paperiarkkiin, mutta juuri massansa vuoksi Rutherfordin kokeessa niiden jyrkkä siroaminen kultakalvosta paljasti, että atomin massa on keskittynyt pieneen positiiviseen ytimeen. Kutsutaan myös: alfasäteily.",
  1, L('alfahiukkanen', ['alfasäteily', 'alfasäteilyn', 'alfasäteilyä'])),
K("Mikä on atomimassa?",
  "Atomin massa atomimassayksikköinä. Alkuaineen atomimassa on sen isotooppien painotettu keskiarvo.",
  "Atomimassa ilmoitetaan atomimassayksikköinä, joista yksi on kahdestoistaosa hiili-12-atomin massasta. Alkuaineen taulukoitu atomimassa on luonnossa esiintyvien isotooppien painotettu keskiarvo, siksi kloorin arvo on 35,45. Berzelius määritti 1800-luvun alussa suhteellisia atomipainoja ja Cannizzaro yhtenäisti ne 1860 Avogadron periaatteella. Atomimassat ovat moolimassan ja stoikiometrian perusta. Kutsutaan myös: atomipaino, suhteellinen atomimassa.",
  3, L('atomimassa', 'atomipaino', ['atomimassayksikkö', 'atomimassayksikön', 'atomimassayksikköä', 'atomimassayksiköinä', 'atomimassayksiköissä'])),
K("Mikä on katodisäde?",
  "Tyhjiöputkessa negatiiviselta elektrodilta lähtevä hiukkassuihku. Thomson osoitti sen koostuvan elektroneista.",
  "",
  1, L(['katodi' + s for s in SADE] + ['katodisädekoe', 'katodisädekokeen', 'katodisädekokeilla', 'katodisädeputki', 'katodisädeputken'])),
K("Mitä iatrokemia oli?",
  "Paracelsuksen 1500-luvun suuntaus, joka valjasti kemian lääkkeiden valmistukseen ja lääketieteen hoitoihin.",
  "",
  1, L('iatrokemia')),
K("Mikä on mineraali?",
  "Luonnossa esiintyvä kiteinen epäorgaaninen aine, jolla on määrätty koostumus, kuten kvartsi tai kalsiitti.",
  "",
  1, L('mineraali', ['mineraalipigmentti', 'mineraalipigmentin', 'mineraalipigmentit', 'mineraalipigmenteillä'])),
K("Mikä on malmi?",
  "Kivilaji, josta metalli kannattaa erottaa. Kuparia tuotettiin malmeista jo muinaisessa Mesopotamiassa.",
  "",
  1, L('malmi')),
K("Mikä on pronssi?",
  "Kuparin ja tinan seos, ensimmäinen laajasti käytetty metalliseos ja pronssikauden nimen antaja.",
  "",
  1, L('pronssi')),
K("Mikä on Rutherfordin ydinmalli?",
  "Atomimalli, jossa massa ja positiivinen varaus ovat pienessä ytimessä ja elektronit kiertävät sitä pääosin tyhjässä tilassa.",
  "",
  2, L(['ydinmalli', 'ydinmallin', 'ydinmallia', 'ydinmallissa', 'Rutherfordin ydinmalli', 'Rutherfordin ydinmallin', 'Rutherfordin ydinmallia'])),
]),
dict(LEHTI='Luento 2.2 - Yksinkertaisten yhdisteiden nimeäminen', TIEDOSTO='Luento 2.2 - Sanasto (lisays)', NRO=22, ALKU=100, KUVAT={}, KORTIT=[
K("Mikä on keskusatomi?",
  "Moniatomisen ionin tai molekyylin atomi, johon muut atomit eli ligandit ovat sitoutuneet, kuten sulfaatti-ionin rikki.",
  "",
  2, L('keskusatomi')),
K("Mikä on IUPAC?",
  "Kansainvälinen kemian liitto, joka vahvistaa yhdisteiden systemaattiset nimeämissäännöt ja alkuaineiden nimet.",
  "",
  1, L(['IUPAC', 'IUPACin', 'IUPAC:n', 'IUPAC:in', 'IUPAC-nimi', 'IUPAC-nimen', 'IUPAC-nimistö', 'IUPAC-nimistön'])),
K("Mikä on alaindeksi kemiallisessa kaavassa?",
  "Alkuainemerkin oikealle alapuolelle kirjoitettu luku, joka kertoo atomien lukumäärän, kuten H<sub>2</sub>O:n 2.",
  "",
  2, L('alaindeksi')),
K("Mikä on etuliite yhdisteen nimessä?",
  "Nimen alkuun liitettävä osa, kuten lukumäärän mono, di ja tri tai happimäärän hypo ja per.",
  "",
  2, L('etuliite')),
K("Mikä on pääte yhdisteen nimessä?",
  "Nimen loppuosa, joka kertoo ionin lajin: -idi yksiatomiselle anionille, -aatti ja -iitti oksoanioneille.",
  "",
  2, L('pääte', ['loppuosa', 'loppuosan', 'loppuosaa', 'kantaosa', 'kantaosan', 'kantaosaa', 'kantaosat', 'kantaosasta'])),
K("Mikä on nimeämisjärjestelmä?",
  "Sovittu sääntöjen kokonaisuus, jolla jokaiselle yhdisteelle saadaan yksiselitteinen nimi, kuten IUPAC-nimistö.",
  "",
  1, L('nimeämisjärjestelmä', ['nimistö', 'nimistön', 'nimistöä', 'nimeämissääntö', 'nimeämissäännön', 'nimeämissäännöt', 'nimeämissääntöjen'])),
K("Mikä on yksiatominen ioni?",
  "Yhdestä atomista muodostunut ioni, kuten Na<sup>+</sup> tai Cl<sup>−</sup>. Vastakohta on moniatominen ioni.",
  "",
  2, L(['yksiatominen ioni', 'yksiatomisen ionin', 'yksiatomista ionia', 'yksiatomiset ionit', 'yksiatomisten ionien', 'yksiatomisia ioneja', 'yksiatominen', 'yksiatomisen', 'yksiatomista', 'yksiatomiset'])),
K("Mikä on hydridi?",
  "Vedyn yhdiste metallin kanssa, jossa vety on anionina H<sup>−</sup>, kuten litiumhydridi.",
  "",
  1, L('hydridi')),
K("Mikä on oksidi?",
  "Hapen yhdiste toisen alkuaineen kanssa, jossa happi on hapetusluvulla −II, kuten magnesiumoksidi tai typpidioksidi.",
  "",
  2, L('oksidi')),
K("Mikä on sulfidi?",
  "Rikin yhdiste, jossa rikki on anionina S<sup>2−</sup>, kuten kalsiumsulfidi tai divetysulfidi.",
  "",
  1, L('sulfidi')),
]),
dict(LEHTI='Luento 3.1 - Atomin rakenne ja jaksollinen järjestelmä', TIEDOSTO='Luento 3.1 - Sanasto (lisays)', NRO=31, ALKU=100, KUVAT={}, KORTIT=[
K("Mikä on alkeishiukkanen?",
  "Hiukkanen, jolla ei ole sisäistä rakennetta, kuten elektroni ja kvarkit. Protoni ja neutroni eivät ole alkeishiukkasia.",
  "",
  2, L('alkeishiukkanen')),
K("Mikä on partikkeli?",
  "Yleisnimitys pienelle hiukkaselle, kuten atomille, ionille, molekyylille tai alkeishiukkaselle.",
  "",
  1, L('partikkeli', ['hiukkanen', 'hiukkasen', 'hiukkasta', 'hiukkasessa', 'hiukkaseen', 'hiukkaset', 'hiukkasten', 'hiukkasia', 'hiukkasissa'])),
K("Mikä on nukleonien yhteisnimitys?",
  "Nukleoni on protonin ja neutronin yhteisnimitys eli atomiytimen rakenneosa. Ytimen nukleonien määrä on massaluku.",
  "",
  1),
K("Mitä tarkoittaa varaukseton?",
  "Sähkövaraukseltaan nolla, kuten neutroni tai atomi, jolla on yhtä monta protonia ja elektronia.",
  "",
  1, L(['varaukseton', 'varauksettoman', 'varauksetonta', 'varauksettomat', 'varauksettomia'])),
K("Mikä on pystysarake ja vaakarivi jaksollisessa järjestelmässä?",
  "Pystysarake on ryhmä: sama määrä valenssielektroneja. Vaakarivi on jakso, jonka aikana uloin kuori täyttyy.",
  "",
  2),
]),
dict(LEHTI='Luento 3.2 - Kvanttimekaaninen atomimalli', TIEDOSTO='Luento 3.2 - Sanasto (lisays)', NRO=32, ALKU=100, KUVAT={}, KORTIT=[
K("Mikä on energiataso?",
  "Atomin sallittu energian arvo, jolla elektroni voi olla. Elektroni siirtyy tasolta toiselle absorboimalla tai emittoimalla fotonin.",
  "Kvantittumisen vuoksi atomin elektronilla voi olla vain tiettyjä energioita, energiatasoja, joita pääkvanttiluku numeroi. Alin taso on perustila, ylemmät virittyneitä tiloja. Kun elektroni putoaa ylemmältä tasolta alemmalle, ero vapautuu fotonina, jonka energia on tasojen erotus, ja tästä syntyvät alkuaineiden viivaspektrit. Bohr laski vedyn energiatasot ympyräradoista, kvanttimekaniikka Schrödingerin yhtälöstä. Kutsutaan myös: energiatila.",
  3, L('energiataso', ['energiatila', 'energiatilan', 'energiatilaa', 'energiatilat', 'energiatilojen', 'energiatiloja', 'energiatilassa'])),
K("Mikä on seisova aalto?",
  "Aalto, joka ei etene vaan värähtelee paikallaan, kuten kitaran kieli. Sen pituuteen mahtuu kokonaisluku puoliaallonpituuksia.",
  "Kun aalto heijastuu kiinteistä päistä edestakaisin, vain sellaiset aallonpituudet säilyvät, joilla kielen pituuteen mahtuu kokonaisluku puoliaallonpituuksia, muut sammuttavat itsensä. Solmukohdat pysyvät paikallaan ja niiden välit värähtelevät. De Broglie ajatteli elektronin aaltona, jonka on mahduttava radalleen kokonaisina aallonpituuksina, mikä selitti Bohrin sallitut radat. Schrödingerin yhtälö tekee saman kolmessa ulottuvuudessa: orbitaalit ovat elektronin seisovia aaltoja.",
  2, L(['seisova aalto', 'seisovan aallon', 'seisovaa aaltoa', 'seisovat aallot', 'seisovia aaltoja', 'seisova aaltoliike', 'seisovan aaltoliikkeen', 'seisovaa aaltoliikettä', 'seisova', 'seisovaa', 'puoliaallonpituus', 'puoliaallonpituuden', 'puoliaallonpituutta', 'puoliaallonpituuksia'])),
K("Mikä on spektri?",
  "Säteilyn jakauma aallonpituuden tai energian mukaan. Kuumennettu kaasu emittoi viivaspektrin, kiinteä aine jatkuvan spektrin.",
  "Spektri saadaan hajottamalla valo prismalla tai hilalla aallonpituuksiinsa. Auringon ja hehkulampun spektri on jatkuva sateenkaari, mutta viritetty kaasu säteilee vain tiettyjä aallonpituuksia, jotka näkyvät erillisinä viivoina. Kullakin alkuaineella on oma viivastonsa, joten spektristä tunnistetaan aineet tähdistäkin. Vedyn viivat vastaavat energiatasojen eroja, mikä johti Bohrin malliin. Absorptiospektrissä samat aallonpituudet puuttuvat läpi kulkeneesta valosta. Kutsutaan myös: viivaspektri.",
  2, L('spektri', ['absorptiospektri', 'absorptiospektrin', 'absorptiospektriä', 'spektriviiva', 'spektriviivan', 'spektriviivat', 'spektriviivoja'])),
K("Mikä on hertsi?",
  "Taajuuden yksikkö: yksi värähdys sekunnissa, 1 Hz = 1/s.",
  "",
  2, L('hertsi', ['Hz', 'Hz:n'])),
K("Mitä emissio tarkoittaa?",
  "Säteilyn lähettämistä: virittynyt atomi palaa alemmalle energiatasolle ja emittoi fotonin.",
  "",
  2, L('emissio', ['emittoida', 'emittoi', 'emittoituu', 'emittoituva', 'emittoituvan', 'emittoitunut', 'emittoituneen', 'emittoitua', 'emittoituvat'])),
K("Mitä absorptio tarkoittaa säteilystä puhuttaessa?",
  "Säteilyn imeytymistä aineeseen: atomi ottaa fotonin energian ja siirtyy ylemmälle energiatasolle.",
  "",
  2, L('absorptio', ['absorboida', 'absorboi', 'absorboituu', 'absorboituva', 'absorboitunut', 'absorboitua', 'absorboituvat'])),
K("Mitä ovat sähkömagneettisen säteilyn lajit?",
  "Aallonpituuden mukaan: radioaallot, mikroaallot, infrapuna, näkyvä valo, ultravioletti, röntgensäteily ja gammasäteily. Lyhyempi aallonpituus on suurempi energia.",
  "",
  2, L(['radioaalto', 'radioaallon', 'radioaaltoa', 'radioaallot', 'radioaaltojen', 'radioaaltoja', 'mikroaalto', 'mikroaallon', 'mikroaaltoa', 'mikroaallot', 'mikroaaltojen', 'mikroaaltoja', 'infrapuna', 'infrapunan', 'infrapunaa', 'infrapunasäteily', 'infrapunasäteilyn', 'ultravioletti', 'ultravioletin', 'ultraviolettia', 'ultraviolettisäteily', 'ultraviolettisäteilyn', 'UV-säteily', 'UV-säteilyn', 'gammasäteily', 'gammasäteilyn', 'gammasäteilyä'] + ['röntgen' + s for s in ('säteily', 'säteilyn', 'säteilyä', 'säteilyssä')] + ['röntgen' + s for s in SADE])),
K("Mikä on impulssimomentti?",
  "Pyörimisliikkeen liikemäärä. Elektronin rataimpulssimomentin suuruuden määrää sivukvanttiluku l ja suunnan magneettinen kvanttiluku.",
  "",
  1, L('impulssimomentti', ['pyörimismäärä', 'pyörimismäärän', 'pyörimismäärää', 'liikemäärämomentti', 'liikemäärämomentin'])),
K("Mikä on reunaehto Schrödingerin yhtälössä?",
  "Vaatimus, jonka aaltofunktion on täytettävä ollakseen fysikaalisesti mielekäs: jatkuva, yksikäsitteinen ja häviävä äärettömyydessä. Reunaehdoista seuraavat kvanttiluvut.",
  "",
  1, L('reunaehto')),
K("Mikä on todennäköisyyspilvi?",
  "Kuva siitä, missä elektroni todennäköisimmin on: aaltofunktion neliön tiheys avaruudessa. Orbitaali on sen rajattu alue.",
  "",
  2, L(['todennäköisyyspilvi', 'todennäköisyyspilven', 'todennäköisyyspilveä', 'todennäköisyyspilvessä', 'todennäköisyyspilvet', 'todennäköisyyspilviä', 'elektronipilvi', 'elektronipilven', 'elektronipilveä', 'elektronipilvessä', 'elektronipilvet', 'elektronipilviä'])),
K("Mikä on keskimääräiskenttä?",
  "Yksinkertaistus monielektroniselle atomille: kukin elektroni liikkuu ytimen ja muiden elektronien keskimääräisessä kentässä.",
  "",
  1, L('keskimääräiskenttä', ['self-consistent field', 'SCF', 'keskimääräiskenttämenetelmä', 'keskimääräiskenttämenetelmän'])),
K("Mikä on Einsteinin massa-energia-yhtälö?",
  "E = mc<sup>2</sup>: energia ja massa vastaavat toisiaan. Planckin yhtälön kanssa se antaa fotonille liikemäärän.",
  "",
  1, L(['suhteellisuusteoria', 'suhteellisuusteorian', 'suhteellisuusteoriaa', 'suhteellisuusteoriassa', 'massa-energia-yhtälö', 'massa-energia-yhtälön', 'E = mc²', 'E=mc²'])),
K("Mikä on hiukkas-aaltoluonne?",
  "Aineen ja säteilyn kaksoisluonne: valo käyttäytyy sekä aaltona että fotoneina ja elektroni sekä hiukkasena että aaltona.",
  "",
  2, L(['hiukkasluonne', 'hiukkasluonteen', 'hiukkasluonnetta', 'aaltoluonne', 'aaltoluonteen', 'aaltoluonnetta', 'aaltoliikeluonne', 'aaltoliikeluonteen', 'aaltoliikeluonnetta', 'kaksoisluonne', 'kaksoisluonteen', 'kaksoisluonnetta'])),
]),
]
