# -*- coding: utf-8 -*-
"""Sanaston kolmas kierros (omistaja 12.9.2026: 'aivan jokaisesta'): kalvojen viimeiset termit, jotka jaivat toisen kierroksen
ehdokaslistoihin. Listat liitetaan sanasto2-moduulien jatkoksi."""
from biotek_taivutus import L
from pakka_rakenna import K

def N(*forms):
    return list(forms)

SOLU_L1 = [
K("Mikä on alkusolu?",
  "Ensimmäinen solu, josta kaikki elämä polveutuu: kalvon rajaama, itseään kopioiva järjestelmä noin 4 miljardia vuotta sitten.",
  "",
  2, L('alkusolu', ['alkumaapallo', 'alkumaapallon', 'alkumaapalloa', 'alkumaapallolla', 'protosolu', 'protosolun', 'protosolut', 'elämän synty', 'elämän synnyn', 'elämän syntyä', 'elämän syntyyn'])),
K("Mikä on eliökunta?",
  "Kaikki elävät olennot: bakteerit, arkeonit ja eukaryootit. Virukset eivät ole soluja eivätkä kuulu eliökuntaan.",
  "",
  2, L('eliökunta', ['eliöihin', 'elollinen', 'elollisen', 'elolliset', 'elollisia', 'eloton', 'elottoman', 'elotonta', 'elottomat', 'elottomia', 'elottomiin', 'ei-solullinen', 'ei-solullisen', 'ei-solulliset', 'ei-solullisia'])),
K("Mikä on kätisyys molekyylissä?",
  "Kiraalisen molekyylin ominaisuus erota peilikuvastaan kuin oikea ja vasen käsi. Latinaksi dexter ja sinister.",
  "",
  2, L('kätisyys', ['kätisyyden', 'kätisyyttä', 'oikeakätinen molekyyli', 'vasenkätinen molekyyli', 'dexter', 'sinister', 'laevus', 'rectus', 'peilikuva', 'peilikuvan', 'peilikuvaa', 'peilikuvat', 'peilikuvien', 'peilikuvia'])),
K("Mikä on siirtomolekyyli?",
  "Molekyyli, joka kuljettaa jotakin paikasta toiseen: hemoglobiini happea, ATP energiaa, siirtäjä-RNA aminohappoja, NADH elektroneja.",
  "",
  2, L('siirtomolekyyli', ['siirtomolekyylejä', 'kuljetusmolekyyli', 'kuljetusmolekyylin', 'kuljetusmolekyylit', 'kuljetusmolekyylejä', 'kantajamolekyyli', 'kantajamolekyylin', 'kantajamolekyylit'])),
K("Mikä on perusyksikkö biologiassa?",
  "Solu on elämän perusyksikkö: pienin kokonaisuus, jolla on kaikki elämän tunnusmerkit. Monomeeri on polymeerin perusyksikkö.",
  "",
  1, L('perusyksikkö', ['perusyksikön', 'perusyksikköä', 'perusyksiköt', 'rakenneyksikkö', 'rakenneyksikön', 'rakenneyksikköä', 'rakenneyksiköt', 'rakenneyksiköiden', 'rakenneosa', 'rakenneosan', 'rakenneosaa', 'rakenneosat', 'rakenneosien', 'rakenneosia', 'rakenneosista'])),
K("Mikä on Nitella?",
  "Näkinpartaislevä, jonka jättimäisissä soluissa solulimavirtaus näkyy mikroskoopilla. Klassinen tukirangan ja liikkeen malli.",
  "",
  1, L(N('Nitella', 'Nitellan', 'Nitella-levä', 'Nitella-levän', 'näkinparta', 'näkinparran', 'näkinpartaislevä', 'näkinpartaislevän', 'solulimavirtaus', 'solulimavirtauksen', 'solulimavirtausta'))),
K("Mikä on yksikerroksinen soluviljelmä?",
  "Solut kasvatettuina yhtenä kerroksena alustan pinnalla. Tavallinen tapa kasvattaa eläinsoluja laboratoriossa. Kutsutaan myös: monolayer.",
  "",
  1, L(N('yksikerroksinen', 'yksikerroksisen', 'yksikerroksista', 'yksikerroksiset', 'monolayer', 'monolayers', 'soluviljelmä', 'soluviljelmän', 'soluviljelmää', 'soluviljelmät', 'soluviljelmien', 'soluviljelmiä', 'soluviljelmissä', 'soluviljely', 'soluviljelyn', 'soluviljelyä', 'soluviljelyssä'))),
K("Mitä evolutiivinen tarkoittaa?",
  "Evoluutioon liittyvä: evolutiivisesti vanha rakenne, kuten ribosomi, on säilynyt kaikissa eliöissä yhteisestä esivanhemmasta.",
  "",
  1, L(N('evolutiivinen', 'evolutiivisen', 'evolutiivista', 'evolutiiviset', 'evolutiivisia', 'evolutiivisesti', 'evoluutiobiologia', 'evoluutiobiologian', 'evoluutiobiologiaa', 'konservoitunut', 'konservoituneen', 'konservoitunutta', 'konservoituneet', 'konservoituneita', 'säilynyt rakenne', 'säilyneen rakenteen'))),
K("Mikä on senttimetri solujen mittakaavassa?",
  "10<sup>−2</sup> m. Suurimmat solut, kuten linnunmunan keltuainen tai Nitellan solut, ovat senttimetrien kokoisia, tavalliset mikrometrien.",
  "",
  1, L('senttimetri', ['cm', 'millimetri', 'millimetrin', 'millimetriä', 'millimetrit', 'mm', 'mittakaava solubiologiassa', 'kokoluokka solubiologiassa'])),
K("Mikä on ravinnonhankintatapa?",
  "Tapa, jolla eliö hankkii energiansa ja hiilensä: valosta tai kemiasta, epäorgaanisesta tai orgaanisesta lähteestä.",
  "",
  2, L('ravinnonhankintatapa', ['ravinnonhankintatavat', 'ravinnonhankintatapoja', 'ravinnonhankinta', 'ravinnonhankinnan', 'ravinnonhankintaa', 'ravinto', 'ravinnon', 'ravintoa', 'ravinnossa', 'ravintona', 'ruoka', 'ruoan', 'ruokaa', 'ruuan', 'ravinnosta'])),
K("Mikä on geelimäinen?",
  "Hyytelömäinen, sitkeä ja muotonsa säilyttävä olomuoto. Solulima on tiheä ja geelimäinen, ei laimea liuos.",
  "",
  1, L(N('geelimäinen', 'geelimäisen', 'geelimäistä', 'geelimäiset', 'hyytelömäinen', 'hyytelömäisen', 'hyytelömäistä', 'ruuhkainen', 'ruuhkaisen', 'ruuhkaista', 'ahdas', 'ahtaan', 'ahdasta', 'makromolekulaarinen ruuhka', 'makromolekulaarisen ruuhkan'))),
]

SOLU_L2 = [
K("Mikä on protonipumppu?",
  "Kalvoproteiini, joka siirtää protoneja kalvon läpi energialla ja luo pH-eron, kuten mahalaukun happopumppu ja mitokondrion hengitysketju.",
  "",
  2, L('protonipumppu', ['protonipumpun', 'protonipumppua', 'protonipumput', 'protonipumppujen', 'pumppaus', 'pumppauksen', 'pumppausta', 'pumpata', 'pumpataan', 'happopumppu', 'happopumpun'])),
K("Mikä on vetysidoksen suuntavaikutus?",
  "Vetysidos on vahvin, kun luovuttaja, vety ja vastaanottaja ovat suoralla linjalla. Suuntautuneisuus antaa vedelle rakenteen.",
  "",
  2, L(N('suuntavaikutus', 'suuntavaikutuksen', 'suuntavaikutusta', 'suuntautuneisuus', 'suuntautuneisuuden', 'suuntautuneisuutta', 'suuntautunut', 'suuntautuneen', 'suuntautuneet', 'suora linja', 'suoralla linjalla', 'suorassa linjassa', 'lineaarinen vetysidos', 'lineaarisen vetysidoksen'))),
K("Mitä liikkuvuus tarkoittaa ioneista?",
  "Ionin nopeus sähkökentässä liuoksessa. Protonin liikkuvuus on poikkeuksellisen suuri, koska se hyppii vetysidoksia pitkin.",
  "",
  1, L('liikkuvuus', ['liikkuvuuden', 'liikkuvuutta', 'ionin liikkuvuus', 'ionin liikkuvuuden', 'liikkua', 'liikkuu', 'liikkuvat', 'liikkuva', 'liikkuvan'])),
K("Miksi happo kirvelee silmissä?",
  "Silmän pinnan hermopäätteet aistivat pH:n muutoksen ja kudos ärtyy. Elimistön nesteiden pH on tarkasti säädelty.",
  "",
  1, L(N('kirvellä', 'kirvelee', 'kirvele', 'kirvely', 'kirvelyn', 'ärsytys', 'ärsytyksen', 'ärsytystä', 'ärsyttää', 'ärsyttävä', 'silmä', 'silmän', 'silmää', 'silmät', 'silmien', 'silmissä'))),
K("Mikä on rakennemuutos proteiinissa?",
  "Proteiinin muodon muuttuminen sitoutumisen, pH:n tai fosforylaation vuoksi. Kutsutaan myös: konformaatiomuutos.",
  "",
  2, L(N('rakennemuutos', 'rakennemuutoksen', 'rakennemuutosta', 'rakennemuutokset', 'rakennemuutoksia', 'konformaatiomuutos', 'konformaatiomuutoksen', 'konformaatiomuutosta', 'konformaatiomuutokset', 'konformaatiomuutoksia'))),
K("Mikä on yhteenliittyminen molekyyleistä?",
  "Molekyylien kokoontuminen suuremmaksi rakenteeksi heikoilla vuorovaikutuksilla, kuten lipidit kalvoksi tai alayksiköt proteiiniksi. Kutsutaan myös: assosiaatio.",
  "",
  2, L(N('yhteenliittyminen', 'yhteenliittymisen', 'yhteenliittymistä', 'yhteenliittymä', 'yhteenliittymän', 'assosiaatio', 'assosiaation', 'assosiaatiota', 'assosioitua', 'assosioituu', 'assosioituvat', 'kokoontua', 'kokoontuu', 'kokoontuvat', 'kokoontuminen', 'kokoontumisen', 'assemble', 'itsejärjestäytyminen', 'itsejärjestäytymisen', 'itsejärjestäytyä', 'itsejärjestäytyy'))),
K("Mikä on ihmiselimistö kemiallisena ympäristönä?",
  "Vesipohjainen järjestelmä, jonka pH, lämpötila ja suolapitoisuus pysyvät kapeissa rajoissa: veri pH 7,4, 37 °C.",
  "",
  2, L(N('ihmiselimistö', 'ihmiselimistön', 'ihmiselimistöä', 'ihmiselimistössä', 'elimistö', 'elimistön', 'elimistöä', 'elimistössä', 'elimistöstä', 'elimistöön', 'elimistölle', 'elimistöt', 'keho', 'kehon', 'kehoa', 'kehossa', 'ruumis', 'ruumiin', 'ruumista', 'ruumiissa'))),
]

SOLU_L3 = [
K("Mikä on sijoituspaikka proteiinille?",
  "Solun osa, johon proteiini ohjataan valmistuttuaan: tuma, mitokondrio, kalvosto, lysosomi tai solun ulkopuoli. Kutsutaan myös: kohdeosoite.",
  "",
  1, L('sijoituspaikka', ['sijoituspaikan', 'sijoituspaikkaa', 'kohdeosoite', 'kohdeosoitteen', 'kohdeosoitetta', 'kohdeosoitteet', 'osoitesekvenssi', 'osoitesekvenssin', 'osoitesekvenssiä', 'osoitesekvenssit', 'valmistuspaikka', 'valmistuspaikan', 'valmistuspaikkaa', 'tapahtumispaikka', 'tapahtumispaikan', 'tapahtumispaikkaa'])),
K("Mikä on dynaaminen rakenne solussa?",
  "Jatkuvasti purkautuva ja uudelleen rakentuva rakenne, kuten mikrotubulukset ja aktiinisäikeet. Mahdollistaa muodon muutokset ja liikkeen.",
  "",
  2, L(N('dynaaminen', 'dynaamisen', 'dynaamista', 'dynaamiset', 'dynaamisia', 'dynaamisesti', 'dynaamisessa', 'dynaaminen epävakaus', 'dynaamisen epävakauden', 'dynaaminen rakenne', 'dynaamisen rakenteen', 'purkautua', 'purkautuu', 'purkautuvat', 'uudelleenrakentua', 'uudelleenrakentuu'))),
K("Mikä on interaktio solubiologiassa?",
  "Kahden molekyylin tai rakenteen vuorovaikutus, kuten proteiinin sitoutuminen toiseen. Kutsutaan myös: vuorovaikutus.",
  "",
  1, L('interaktio', ['proteiini-proteiini-vuorovaikutus', 'proteiini-proteiini-vuorovaikutuksen', 'proteiini-proteiini-vuorovaikutukset', 'proteiinien vuorovaikutus', 'proteiinien vuorovaikutukset', 'vuorovaikutus', 'vuorovaikutuksen', 'vuorovaikutusta', 'vuorovaikutukset', 'vuorovaikutusten', 'vuorovaikutuksia', 'vuorovaikutuksilla', 'vuorovaikuttaa', 'vuorovaikuttavat', 'vuorovaikutuksessa'])),
K("Mitä lajityypillinen tarkoittaa?",
  "Lajille ominainen ja vakio, kuten kromosomiluku: ihmisellä 46, hedelmäkärpäsellä 8, koiralla 78.",
  "",
  1, L(N('lajityypillinen', 'lajityypillisen', 'lajityypillistä', 'lajityypilliset', 'lajityypillisiä', 'lajityypillisesti', 'kromosomiluku', 'kromosomiluvun', 'kromosomilukua', 'laji', 'lajin', 'lajia', 'lajit', 'lajien', 'lajeja', 'lajille', 'lajilla'))),
K("Mikä on kalvoston kuljetus?",
  "Proteiinien ja lipidien siirto kalvorakkuloissa kalvostosta Golgiin ja sieltä määränpäähän. Kutsutaan myös: rakkulakuljetus, vesikkelikuljetus.",
  "",
  2, L(N('rakkulakuljetus', 'rakkulakuljetuksen', 'rakkulakuljetusta', 'vesikkelikuljetus', 'vesikkelikuljetuksen', 'vesikkelikuljetusta', 'kalvokuljetus', 'kalvokuljetuksen', 'kalvokuljetusta', 'kuljetus', 'kuljetuksen', 'kuljetusta', 'kuljetuksessa', 'kuljettaa', 'kuljetetaan', 'kuljetettu', 'kulkeutua', 'kulkeutuu', 'kulkeutuvat', 'eritystie', 'eritystien', 'eritystietä', 'sekretorinen reitti', 'sekretorisen reitin'))),
K("Mikä on lähtöaine solun reaktiossa?",
  "Aine, josta reaktio alkaa ja joka muuttuu tuotteeksi. Entsyymin lähtöaine on substraatti. Kutsutaan myös: reaktantti.",
  "",
  2, L(N('lähtöaine', 'lähtöaineen', 'lähtöainetta', 'lähtöaineessa', 'lähtöaineesta', 'lähtöaineena', 'lähtöaineet', 'lähtöaineiden', 'lähtöaineita', 'lähtöaineista', 'lähtöaineina', 'reaktantti', 'reaktantin', 'reaktanttia', 'reaktantit', 'reaktanttien', 'reaktantteja', 'tuote', 'tuotteen', 'tuotetta', 'tuotteena', 'tuotteet', 'tuotteiden', 'tuotteita', 'tuotteina', 'reaktiotuote', 'reaktiotuotteen', 'reaktiotuotteet', 'lopputuote', 'lopputuotteen', 'lopputuotetta', 'lopputuotteet'))),
K("Mitä vapautus tarkoittaa solubiologiassa?",
  "Aineen päästäminen irti tai ulos: energian vapautus hajotuksessa, hermovälittäjäaineen vapautus rakkulasta, hapen vapautus fotosynteesissä.",
  "",
  1, L('vapautus', ['vapauttaa', 'vapauttaen', 'vapautetaan', 'vapautettu', 'vapauttaminen', 'vapauttamisen', 'vapautua', 'vapautuu', 'vapautuvat', 'vapautuminen', 'vapautumisen', 'vapautunut', 'vapautuneen'])),
K("Mikä on solun jakautumiskoneisto?",
  "Mitoosin rakenteet: sentrosomit, sukkularihmasto ja kuroutumisrengas, jotka jakavat kromosomit ja soluliman. Kutsutaan myös: mitoosikoneisto.",
  "",
  2, L(N('jakautumiskoneisto', 'jakautumiskoneiston', 'jakautumiskoneistoa', 'mitoosikoneisto', 'mitoosikoneiston', 'sukkularihmasto', 'sukkularihmaston', 'sukkularihmastoa', 'sukkula', 'sukkulan', 'sukkulaa', 'kuroutumisrengas', 'kuroutumisrenkaan', 'kuroutumisrengasta', 'supistusrengas', 'supistusrenkaan', 'sentrosomi', 'sentrosomin', 'sentrosomia', 'sentrosomit', 'sentrosomien', 'cytokinesis'))),
]

SOLU_L4a = [
K("Mikä on leikkaa ja liimaa -mekanismi RNA:ssa?",
  "Silmukoinnin kuvaus: intronit leikataan pois ja eksonit liimataan yhteen ennen kuin lähetti-RNA lähtee tumasta.",
  "",
  1, L(N('leikkaa ja liimaa', 'leikkaa-liimaa', 'leikkaaliimaa', 'leikata', 'leikataan', 'leikattu', 'liimata', 'liimataan', 'liimattu', 'liittää', 'liitetään', 'liittäminen', 'liittämisen', 'liittämiseen'))),
K("Mikä on polytymiini?",
  "Pelkistä tymiineistä koostuva DNA-jakso. Vastinjuosteessa poly-A. Bakteerin terminaattorin U-jakso on transkriboitu polytymiinistä... tarkemmin A-jaksosta.",
  "",
  1, L('polytymiini', ['polytymiinin', 'polytymiiniä', 'poly-T', 'poly(T)', 'T-jakso', 'T-jakson', 'U-jakso', 'U-jakson', 'TTTTT', 'ttttt'])),
K("Mikä on transkriptiokoneisto?",
  "RNA-polymeraasi ja sen apuproteiinit (sigmatekijä bakteerilla, transkriptiotekijät eukaryootilla), jotka yhdessä lukevat geenin. Kutsutaan myös: koneisto.",
  "",
  2, L('transkriptiokoneisto', ['transkriptiokoneiston', 'transkriptiokoneistoa', 'koneisto', 'koneiston', 'koneistoa', 'koneistot', 'koneistojen', 'koneistoja', 'translaatiokoneisto', 'translaatiokoneiston', 'translaatiokoneistoa', 'replikaatiokoneisto', 'replikaatiokoneiston', 'solun koneisto', 'solun koneiston'])),
K("Mitä jännite tarkoittaa DNA:ssa?",
  "Kaksoiskierteen kiertymisestä syntyvä mekaaninen rasitus. Ylikiertyminen ja alikiertyminen (superkierteisyys) säätelevät luettavuutta.",
  "",
  2, L(N('jännite', 'jännitteen', 'jännitettä', 'jännitteessä', 'kierrejännite', 'kierrejännitteen', 'kierrejännitettä', 'superkierteisyys', 'superkierteisyyden', 'superkierteisyyttä', 'superkierre', 'superkierteen', 'superkierrettä', 'superkierteet', 'ylikiertyminen', 'ylikiertymisen', 'ylikiertynyt', 'alikiertyminen', 'alikiertymisen', 'alikiertynyt', 'gyraasi', 'gyraasin'))),
K("Mitä kallistuneet emäkset tarkoittavat?",
  "A-DNA:ssa emäsparit ovat kallistuneet kierteen akseliin nähden, B-DNA:ssa lähes kohtisuorassa. Ero näkyy uurteiden muodossa.",
  "",
  1, L(N('kallistunut', 'kallistuneen', 'kallistunutta', 'kallistuneet', 'kallistuneita', 'kallistuma', 'kallistuman', 'kallistumaa', 'kallistuskulma', 'kallistuskulman', 'kierteen akseli', 'kierteen akselin', 'akseli', 'akselin', 'akselia', 'akselit'))),
K("Mikä on heittomerkki nukleotidin hiilten numeroinnissa?",
  "Sokerin hiilet merkitään heittomerkillä (1'–5'), jotta ne erottuvat emäksen atomeista: 5'-fosfaatti, 3'-hydroksyyli, 2'-deoksi. Luetaan pilkku.",
  "",
  2, L(N('heittomerkki', 'heittomerkin', 'heittomerkkiä', 'heittomerkillä', 'pilkku', 'pilkun', 'pilkkua', 'pilkulla', 'prime', 'fiveprime', "1'", "2'", "3'", "4'", "5'", "1'-hiili", "2'-hiili", "2'-hiilen", "4'-hiili", "sokerin hiilet", "sokerin hiilten", "sokerin hiilien"))),
K("Mikä on tuottonopeus polymeraasilla?",
  "Nukleotidien liittämisnopeus: bakteerin RNA-polymeraasi 40–80 nukleotidia sekunnissa, DNA-polymeraasi jopa 1000. Kutsutaan myös: synteesinopeus.",
  "",
  1, L('tuottonopeus', ['tuottonopeuden', 'tuottonopeutta', 'synteesinopeus', 'synteesinopeuden', 'synteesinopeutta', 'polymerointinopeus', 'polymerointinopeuden', 'nukleotidia sekunnissa', 'nukleotidiä sekunnissa', 'prosessiivisuus', 'prosessiivisuuden', 'prosessiivisuutta'])),
K("Mitä fysiologinen tarkoittaa?",
  "Elimistön normaaleja oloja vastaava: pH 7,4, lämpötila 37 °C, suola 0,15 mol/ℓ. Fysiologia on elintoimintojen tiede.",
  "",
  2, L(N('fysiologinen', 'fysiologisen', 'fysiologista', 'fysiologiset', 'fysiologisia', 'fysiologisesti', 'fysiologisissa', 'fysiologisissa oloissa', 'fysiologisissa olosuhteissa', 'fysiologia', 'fysiologian', 'fysiologiaa', 'fysiologiassa', 'elintoiminto', 'elintoiminnon', 'elintoiminnot', 'elintoimintojen', 'elintoimintoja'))),
K("Mikä on ei-koodaava DNA?",
  "Genomin osa, joka ei koodaa proteiinia: intronit, säätelyalueet, toistojaksot ja RNA-geenit. Ihmisen genomista noin 98 %.",
  "",
  2, L(N('ei-koodaava', 'ei-koodaavan', 'ei-koodaavaa', 'ei-koodaavat', 'ei-koodaavia', 'ei-koodaavien', 'ei-koodaava DNA', 'ei-koodaavan DNA:n', 'ei-koodaavaa DNA:ta', 'ei-koodaava RNA', 'ei-koodaavan RNA:n', 'ei-koodaavat RNA:t', 'koodaava', 'koodaavan', 'koodaavaa', 'koodaavat', 'koodaavia', 'koodaavien', 'koodaavassa', 'koodata', 'koodaa', 'koodaama', 'koodaaman', 'koodaamaa', 'koodaamat', 'koodaamien', 'koodattu', 'koodatun', 'koodattuina', 'proteiinia koodaava', 'proteiinia koodaavan', 'proteiinia koodaavat', 'toistojakso', 'toistojakson', 'toistojaksoa', 'toistojaksot', 'toistojaksojen', 'toistojaksoja'))),
K("Mikä on DNA-rengas?",
  "Rengasmainen DNA-molekyyli ilman vapaita päitä: bakteerin kromosomi, plasmidit, mitokondrion DNA ja monet virusgenomit. Kutsutaan myös: rengas-DNA.",
  "",
  2, L(N('DNA-rengas', 'DNA-renkaan', 'DNA-rengasta', 'DNA-renkaat', 'DNA-renkaiden', 'DNA-renkaita', 'rengasmainen DNA', 'rengasmaisen DNA:n', 'rengasmaista DNA:ta', 'rengasmaiset DNA-molekyylit', 'rengasmaisia DNA-molekyylejä', 'rengaskromosomi', 'rengaskromosomin', 'suljettu rengas', 'suljetun renkaan', 'suljettu rengas-DNA', 'lineaarinen DNA', 'lineaarisen DNA:n', 'lineaarista DNA:ta', 'lineaariset DNA-molekyylit', 'lineaarisia DNA-molekyylejä'))),
]

BIOTEK_L1 = [
K("Mitä validointi tarkoittaa?",
  "Kokeellinen osoitus, että menetelmä tai tuote toimii tarkoitukseensa luotettavasti: tarkkuus, herkkyys, toistettavuus. Vaaditaan ennen käyttöönottoa.",
  "",
  2, L('validointi', ['validoida', 'validoidaan', 'validoitu', 'validoidun', 'validoituja', 'validaatio', 'validaation', 'validaatiota', 'käyttöönotto', 'käyttöönoton', 'käyttöönottoa', 'käyttöön'])),
K("Mitä kesyttäminen on biotekniikan historiassa?",
  "Villien eläinten ja kasvien ottaminen ihmisen hoitoon ja jalostukseen 10 000 vuotta sitten. Kutsutaan myös: domestikaatio.",
  "",
  2, L(N('kesyttäminen', 'kesyttämisen', 'kesyttämistä', 'kesyttää', 'kesytetty', 'kesytettiin', 'kesytys', 'kesytyksen', 'domestikaatio', 'domestikaation', 'domestikaatiota', 'domestikoida', 'domestikoitu', 'villi', 'villin', 'villiä', 'villit', 'villien', 'villejä', 'villilaji', 'villilajin', 'villilajit', 'villimuoto', 'villimuodon', 'villimuodot'))),
K("Mikä on entsyymipatentti?",
  "Takaminen 1894 saama patentti homeen amylaasille, ensimmäinen mikrobientsyymin patentti ja modernin entsyymiteollisuuden alku.",
  "",
  1, L('entsyymipatentti', ['entsyymipatentin', 'entsyymipatenttia', 'Takamine', 'Takaminen', 'Jokichi Takamine', 'takadiastaasi', 'takadiastaasin', 'entsyymiteollisuus', 'entsyymiteollisuuden', 'entsyymiteollisuutta'])),
K("Mikä on siirtymävaihe biotekniikan historiassa?",
  "Perinteisen käymisteollisuuden ja 1970-luvun geenitekniikan välinen vaihe: antibiootit, entsyymit ja kasvatustekniikka ilman geenimuokkausta.",
  "",
  1, L(N('siirtymävaihe', 'siirtymävaiheen', 'siirtymävaihetta', 'siirtymävaiheessa', 'siirtymävälivaihe', 'siirtymävälivaiheen', 'välivaihe', 'välivaiheen', 'välivaihetta', 'perinteinen biotekniikka', 'perinteisen biotekniikan', 'perinteistä biotekniikkaa', 'klassinen biotekniikka', 'klassisen biotekniikan'))),
K("Mikä on kilpajuoksu biotekniikan yhteydessä?",
  "Kilpailu ensimmäisyydestä: ihmisen genomin sekvensointi (julkinen hanke vastaan Celera 2000) ja CRISPR-patentit (Berkeley vastaan Broad).",
  "",
  1, L(N('kilpajuoksu', 'kilpajuoksun', 'kilpajuoksua', 'kilpailu', 'kilpailun', 'kilpailua', 'kilpailussa', 'kilpailla', 'kilpailevat', 'Celera', 'Celeran', 'ihmisen genomihanke', 'ihmisen genomihankkeen', 'Human Genome Project', 'genomihanke', 'genomihankkeen', 'genomihanketta'))),
K("Mikä on mahdollistaja teknologiana?",
  "Tekniikka, joka avaa monia sovelluksia kerralla: PCR, sekvensointi, CRISPR ja tekoäly. Kutsutaan myös: mahdollistava teknologia.",
  "",
  1, L('mahdollistaja', ['mahdollistajan', 'mahdollistajat', 'mahdollistava teknologia', 'mahdollistavan teknologian', 'mahdollistavat teknologiat', 'avainteknologia', 'avainteknologian', 'avainteknologiat', 'läpimurto', 'läpimurron', 'läpimurtoa', 'läpimurrot', 'läpimurtojen', 'vallankumous', 'vallankumouksen', 'vallankumousta', 'bioteknologinen vallankumous', 'bioteknologisen vallankumouksen'])),
K("Mikä on jaottelu biotekniikan alueisiin?",
  "Värikoodit: punainen lääketiede, vihreä maatalous, valkoinen teollisuus, sininen meri, keltainen elintarvikkeet, harmaa ympäristö.",
  "",
  2, L(N('jaottelu', 'jaottelun', 'jaottelua', 'jaotella', 'jaotellaan', 'jaoteltu', 'biotekniikan värit', 'biotekniikan värien', 'värikoodi', 'värikoodin', 'värikoodit', 'sininen biotekniikka', 'sinisen biotekniikan', 'sinistä biotekniikkaa', 'keltainen biotekniikka', 'keltaisen biotekniikan', 'meribiotekniikka', 'meribiotekniikan', 'jako', 'jaon', 'jakoa', 'osa-alue', 'osa-alueen', 'osa-alueet', 'osa-alueiden', 'osa-alueita', 'osa-alueilla'))),
K("Mikä on hansikas laboratoriossa?",
  "Suojakäsine, joka suojaa sekä työntekijää kemikaaleilta ja mikrobeilta että näytettä kontaminaatiolta. Aseptisen työn perusväline.",
  "",
  1, L(N('hansikas', 'hansikkaan', 'hansikasta', 'hansikkaat', 'hansikkaiden', 'hansikkaita', 'suojakäsine', 'suojakäsineen', 'suojakäsinettä', 'suojakäsineet', 'suojakäsineitä', 'suojavaruste', 'suojavarusteen', 'suojavarusteet', 'suojavarusteita', 'laboratorioturvallisuus', 'laboratorioturvallisuuden', 'aseptinen', 'aseptisen', 'aseptista', 'aseptiset', 'aseptisesti', 'aseptiikka', 'aseptiikan', 'aseptiikkaa'))),
K("Mikä on tieteenala?",
  "Tutkimuksen erikoistunut haara, kuten biokemia tai genetiikka. Biotekniikka on poikkitieteellinen: biologia, kemia, tekniikka ja tietojenkäsittely.",
  "",
  1, L('tieteenala', ['tieteenalan', 'tieteenalaa', 'tieteenalat', 'tieteenalojen', 'tieteenaloja', 'tieteenalana', 'tiede', 'tieteen', 'tiedettä', 'tieteessä', 'tieteet', 'tieteiden', 'tieteitä', 'tieteissä', 'luonnontiede', 'luonnontieteen', 'luonnontieteet', 'luonnontieteiden', 'luonnontieteitä', 'luonnontieteistä', 'poikkitieteellinen', 'poikkitieteellisen', 'poikkitieteellistä', 'poikkitieteelliset', 'monitieteinen', 'monitieteisen', 'monitieteiset'])),
]

BIOTEK_L2 = [
K("Mikä on alkupopulaatio ohjatussa evoluutiossa?",
  "Satunnaismutaatioilla tehty geenikirjasto, josta parhaat variantit valitaan seulomalla ja kierros toistetaan. Kutsutaan myös: varianttikirjasto.",
  "",
  1, L('alkupopulaatio', ['alkupopulaation', 'alkupopulaatiota', 'varianttikirjasto', 'varianttikirjaston', 'varianttikirjastoa', 'geenikirjasto', 'geenikirjaston', 'geenikirjastoa', 'kirjasto', 'kirjaston', 'kirjastoa', 'kirjastot', 'kirjastoista', 'variantti', 'variantin', 'varianttia', 'variantit', 'varianttien', 'variantteja', 'variants'])),
K("Mikä on happokäsittely?",
  "Proteiinin tai raaka-aineen käsittely happamassa: virusten inaktivointi lääkevalmistuksessa tai tärkkelyksen hajotus. Kutsutaan myös: hapotus.",
  "",
  1, L('happokäsittely', ['happokäsittelyn', 'happokäsittelyä', 'hapotus', 'hapotuksen', 'hapotusta', 'hapottaa', 'hapotetaan', 'happamoittaa', 'happamoitetaan', 'happamoittaminen', 'happamoittamisen', 'happamoittamiseen'])),
K("Mikä on hajuyhdiste?",
  "Haihtuva molekyyli, joka aistitaan hajuna, kuten rikkiyhdisteet ja amiinit mikrobikasvatuksessa tai esterit hedelmien aromissa.",
  "",
  1, L('hajuyhdiste', ['hajuyhdisteen', 'hajuyhdistettä', 'hajuyhdisteet', 'hajuyhdisteiden', 'hajuyhdisteitä', 'hajuyhdisteistä', 'aromi', 'aromin', 'aromia', 'aromit', 'aromien', 'aromiaine', 'aromiaineen', 'aromiaineet', 'aromiaineita', 'pahanhajuinen', 'pahanhajuisen', 'pahanhajuisia', 'haju', 'hajun', 'hajua', 'hajut', 'hajujen'])),
K("Mikä on lähtöilma ja poistoilma fermentorissa?",
  "Sisään syötettävä ilma steriilisuodatetaan, ja poistoilma suodatetaan ja hajunpoistetaan, ettei mikrobeja pääse ympäristöön.",
  "",
  1, L(N('lähtöilma', 'lähtöilman', 'lähtöilmaa', 'poistoilma', 'poistoilman', 'poistoilmaa', 'tuloilma', 'tuloilman', 'tuloilmaa', 'ilmansuodatin', 'ilmansuodattimen', 'ilmansuodattimet', 'poistovesi', 'poistoveden', 'poistovettä', 'jätevesien käsittely', 'jätevesien käsittelyn'))),
K("Mitä törmäily tarkoittaa reaktiossa?",
  "Molekyylien satunnaiset yhteentörmäykset, joista reaktio syntyy. Sekoitus lisää entsyymin ja substraatin kohtaamisia kasvatuksessa.",
  "",
  1, L('törmäily', ['törmäilyn', 'törmäilyä', 'törmäys', 'törmäyksen', 'törmäystä', 'törmäykset', 'törmäysten', 'törmäyksiä', 'törmätä', 'törmää', 'törmäävät', 'yhteentörmäys', 'yhteentörmäyksen', 'yhteentörmäykset', 'kohtaaminen', 'kohtaamisen', 'kohtaamisia'])),
K("Mikä on kemikaali?",
  "Teollisesti valmistettu tai käytetty kemiallinen aine. Biotekniikka korvaa kemikaaleja entsyymeillä ja tuottaa kemikaaleja mikrobeilla.",
  "",
  2, L('kemikaali', ['peruskemikaali', 'peruskemikaalin', 'peruskemikaalit', 'peruskemikaaleja', 'hienokemikaali', 'hienokemikaalin', 'hienokemikaalit', 'hienokemikaaleja', 'kemianteollisuus', 'kemianteollisuuden', 'kemianteollisuutta', 'kemianteollisuudessa', 'kemiallinen prosessi', 'kemiallisen prosessin', 'kemialliset prosessit', 'kemiallinen menetelmä', 'kemiallisen menetelmän', 'kemialliset menetelmät', 'kemiallisia menetelmiä'])),
K("Mikä on rajapinta bioprosessissa?",
  "Kahden faasin kohtaamispinta: ilmakuplan ja nesteen rajapinta, jonka läpi happi liukenee, tai solun ja kantajan rajapinta.",
  "",
  1, L('rajapinta', ['rajapinnan', 'rajapintaa', 'rajapinnat', 'rajapintojen', 'rajapintoja', 'faasiraja', 'faasirajan', 'faasirajat', 'hapensiirto', 'hapensiirron', 'hapensiirtoa', 'hapen liukeneminen', 'hapen liukenemisen', 'liuennut happi', 'liuenneen hapen', 'liuennutta happea'])),
K("Mikä on nisäkässolusysteemi?",
  "Proteiinituotto nisäkässoluissa, kuten CHO tai HEK293: kallis ja hidas mutta tekee ihmisen kaltaiset muokkaukset.",
  "",
  2, L('nisäkässolusysteemi', ['nisäkässolusysteemin', 'nisäkässolusysteemiä', 'nisäkässolutuotto', 'nisäkässolutuoton', 'nisäkässolutuottoa', 'HEK293', 'HEK293-solu', 'HEK293-solut', 'HEK-solu', 'HEK-solut', 'tuottosysteemi', 'tuottosysteemin', 'tuottosysteemiä', 'tuottosysteemit', 'tuottosysteemien', 'tuottosysteemejä', 'tuottojärjestelmä', 'tuottojärjestelmän', 'tuottojärjestelmät', 'ekspressiosysteemi', 'ekspressiosysteemin', 'ekspressiosysteemit'])),
K("Mitä automaattinen tarkoittaa bioprosessissa?",
  "Tietokoneen ohjaama: anturit mittaavat ja säätimet lisäävät happoa, emästä ja ravinnetta ilman ihmistä. Kutsutaan myös: prosessinohjaus.",
  "",
  1, L(N('automaattinen', 'automaattisen', 'automaattista', 'automaattiset', 'automaattisia', 'automaattisesti', 'automaatio', 'automaation', 'automaatiota', 'automatisoida', 'automatisoitu', 'prosessinohjaus', 'prosessinohjauksen', 'prosessinohjausta', 'säädin', 'säätimen', 'säädintä', 'säätimet', 'säätö', 'säädön', 'säätöä', 'säätää', 'säädetään', 'säädetty', 'säädeltävä', 'säädettävä', 'säädettävän', 'säädeltävän', 'parametri', 'parametrin', 'parametria', 'parametrit', 'parametrien', 'parametreja'))),
K("Mikä on globulaarinen proteiini?",
  "Pallomaiseksi laskostunut, vesiliukoinen proteiini, kuten entsyymit ja vasta-aineet. Vastakohta: säiemäinen eli fibrillaarinen, kuten kollageeni.",
  "",
  2, L(N('globulaarinen', 'globulaarisen', 'globulaarista', 'globulaariset', 'globulaarisia', 'globulaarinen proteiini', 'globulaarisen proteiinin', 'globulaariset proteiinit', 'globular', 'pallomainen proteiini', 'pallomaisen proteiinin', 'pallomaiset proteiinit', 'fibrillaarinen', 'fibrillaarisen', 'fibrillaariset', 'fibrillaarinen proteiini', 'fibrillaarisen proteiinin', 'fibrillaariset proteiinit', 'säiemäinen proteiini', 'säiemäisen proteiinin', 'säiemäiset proteiinit', 'säiemäinen', 'säiemäisen', 'säiemäiset'))),
K("Mikä on polyyppi?",
  "Limakalvon pinnasta kohoava kasvain, kuten suolen polyyppi, joka voi kehittyä syöväksi. Seulonnalla löydetään ja poistetaan ajoissa.",
  "",
  1, L('polyyppi', ['polyypin', 'polyyppiä', 'polyypit', 'polyyppien', 'polyyppejä', 'suolipolyyppi', 'suolipolyypin', 'suolipolyypit', 'adenooma', 'adenooman', 'adenoomat'])),
K("Mikä on soluvälitteinen immuniteetti?",
  "T-solujen toteuttama puolustus, joka tappaa virusinfektoituneet ja syöpäsolut suoraan. Vasta-aineet edustavat humoraalista immuniteettia.",
  "",
  2, L(N('soluvälitteinen', 'soluvälitteisen', 'soluvälitteistä', 'soluvälitteiset', 'soluvälitteinen immuniteetti', 'soluvälitteisen immuniteetin', 'soluvälitteistä immuniteettia', 'soluvälitteinen immuunivaste', 'soluvälitteisen immuunivasteen', 'humoraalinen', 'humoraalisen', 'humoraalista', 'humoraalinen immuniteetti', 'humoraalisen immuniteetin', 'humoraalista immuniteettia', 'vasta-ainevälitteinen', 'vasta-ainevälitteisen', 'vasta-ainevälitteinen immuniteetti', 'infektoitunut', 'infektoituneen', 'infektoitunutta', 'infektoituneet', 'infektoituneita', 'infektoituneisiin'))),
K("Mikä on pintamolekyyli?",
  "Solun pinnan molekyyli, jonka vasta-aine tunnistaa: reseptori, kalvoproteiini tai sokerirakenne. Kutsutaan myös: pinta-antigeeni.",
  "",
  2, L('pintamolekyyli', ['pintamolekyylin', 'pintamolekyyliä', 'pintamolekyylit', 'pintamolekyylien', 'pintamolekyylejä', 'pinta-antigeeni', 'pinta-antigeenin', 'pinta-antigeeniä', 'pinta-antigeenit', 'pintarakenne', 'pintarakenteen', 'pintarakennetta', 'pintarakenteet', 'pintarakenteita', 'solun pinta', 'solun pinnan', 'solun pintaa', 'solun pinnalla', 'pintaproteiini', 'pintaproteiinin', 'pintaproteiinit', 'pintaproteiineja', 'CD-molekyyli', 'CD-molekyylin', 'CD-molekyylit', 'CD20', 'CD38', 'CD3'])),
K("Mitä ei-patogeeninen tarkoittaa?",
  "Tautia aiheuttamaton. Tuotto-organismit ja rokotevektorit valitaan ei-patogeenisista kannoista, kuten E. coli K-12.",
  "",
  2, L(N('ei-patogeeninen', 'ei-patogeenisen', 'ei-patogeenistä', 'ei-patogeeniset', 'ei-patogeenisia', 'ei-patogeenisistä', 'apatogeeninen', 'apatogeenisen', 'apatogeeniset', 'K-12', 'E. coli K-12', 'GRAS', 'GRAS-status', 'GRAS-statuksen', 'turvallinen kanta', 'turvallisen kannan', 'turvalliset kannat', 'lisääntymiskyvytön virus', 'lisääntymiskyvyttömän viruksen', 'lisääntymiskyvyttömiä viruksia'))),
K("Mikä on proteolyysikestävyys?",
  "Proteiinin kyky vastustaa proteaasien hajotusta. Parannetaan muokkaamalla katkaisukohdat pois, mikä pidentää lääkkeen ja entsyymin elinikää.",
  "",
  1, L('proteolyysikestävyys', ['proteolyysikestävyyden', 'proteolyysikestävyyttä', 'proteaasikestävyys', 'proteaasikestävyyden', 'proteaasikestävä', 'proteaasikestävän', 'proteaasikestävät', 'katkaisukohta', 'katkaisukohdan', 'katkaisukohtaa', 'katkaisukohdat', 'katkaisukohtien', 'katkaisukohtia', 'elinikä veressä', 'eliniän veressä', 'puoliintumisaika', 'puoliintumisajan', 'puoliintumisaikaa'])),
K("Mikä on kertakäyttöinen bioreaktori?",
  "Muovipussista tehty steriili reaktori, joka hävitetään käytön jälkeen. Säästää pesun ja steriloinnin. Kutsutaan myös: single-use.",
  "",
  2, L(N('kertakäyttöinen', 'kertakäyttöisen', 'kertakäyttöistä', 'kertakäyttöiset', 'kertakäyttöisiä', 'kertakäyttöinen bioreaktori', 'kertakäyttöisen bioreaktorin', 'kertakäyttöiset bioreaktorit', 'kertakäyttöreaktori', 'kertakäyttöreaktorin', 'kertakäyttöreaktorit', 'single-use', 'single-use-reaktori', 'pussireaktori', 'pussireaktorin', 'pussireaktorit', 'uudelleenkäyttö', 'uudelleenkäytön', 'uudelleenkäyttöä', 'uudelleenkäytettävä', 'uudelleenkäytettävän', 'uudelleenkäytettävät'))),
K("Mikä on sivuvaikutus?",
  "Lääkkeen ei-toivottu vaikutus, kuten immuunireaktio proteiinilääkettä vastaan tai infektioalttius immuunivastetta hillittäessä. Kutsutaan myös: haittavaikutus.",
  "",
  2, L('sivuvaikutus', ['haittavaikutus', 'haittavaikutuksen', 'haittavaikutusta', 'haittavaikutukset', 'haittavaikutusten', 'haittavaikutuksia', 'sivuvaikutuksia', 'sivuvaikutusten', 'haitta', 'haitan', 'haittaa', 'haitat', 'haittojen', 'haittoja', 'haittapuoli', 'haittapuolen', 'haittapuolta', 'haittapuolet', 'haittapuolia', 'etu', 'edun', 'etua', 'edut', 'etujen', 'etuja', 'hyöty', 'hyödyn', 'hyötyä', 'hyödyt', 'hyötyjen', 'hyötyjä'])),
K("Mikä on syöpävarianttidiagnostiikka?",
  "Kasvaimen mutaatioiden tunnistus sekvensoimalla, jotta täsmälääke valitaan HER2- tai EGFR-mutaation mukaan. Kutsutaan myös: yksilöllistetty syövänhoito.",
  "",
  2, L('syöpävarianttidiagnostiikka', ['syöpävarianttidiagnostiikan', 'syöpävarianttidiagnostiikkaa', 'syöpädiagnostiikka', 'syöpädiagnostiikan', 'syöpädiagnostiikkaa', 'syöpädiagnostiikassa', 'yksilöllistetty lääketiede', 'yksilöllistetyn lääketieteen', 'yksilöllistettyä lääketiedettä', 'täsmälääketiede', 'täsmälääketieteen', 'täsmälääketiedettä', 'personoitu lääketiede', 'personoidun lääketieteen', 'precision medicine', 'kasvaimen sekvensointi', 'kasvaimen sekvensoinnin', 'EGFR', 'EGFR:n', 'EGFR-mutaatio', 'EGFR-mutaation'])),
K("Mitä ääriolot tarkoittavat entsyymeistä?",
  "Korkea lämpötila, äärimmäinen pH tai suolapitoisuus, joissa tavalliset entsyymit denaturoituvat. Ekstremofiilien entsyymit kestävät ne.",
  "",
  2, L(N('ääriolot', 'ääriolojen', 'äärioloja', 'äärioloissa', 'ääriolosuhteet', 'ääriolosuhteiden', 'ääriolosuhteita', 'ääriolosuhteissa', 'ekstremofiili', 'ekstremofiilin', 'ekstremofiiliä', 'ekstremofiilit', 'ekstremofiilien', 'ekstremofiilejä', 'ekstremotsyymi', 'ekstremotsyymin', 'ekstremotsyymit', 'termofiili', 'termofiilin', 'termofiilit', 'termofiilinen', 'termofiilisen', 'termofiiliset', 'kuumat lähteet', 'kuumien lähteiden', 'kuuma lähde', 'kuuman lähteen'))),
K("Mitä leivonta on entsyymien käyttökohteena?",
  "Leivän valmistus, jossa amylaasit vapauttavat hiivalle sokeria, ksylanaasit pehmentävät taikinaa ja lipaasit korvaavat emulgaattoreita.",
  "",
  1, L('leivonta', ['leivonnan', 'leivontaa', 'leivonnassa', 'leipoa', 'leivotaan', 'leipominen', 'leipomisen', 'taikina', 'taikinan', 'taikinaa', 'taikinassa', 'leipomo', 'leipomon', 'leipomot', 'leipomoteollisuus', 'leipomoteollisuuden', 'makeus', 'makeuden', 'makeutta', 'makeuttaa', 'makeutus', 'makeutuksen', 'makeutusaine', 'makeutusaineen', 'makeutusaineet'])),
]

BIOTEK_L3 = [
K("Mikä on määritysperiaate?",
  "Tapa, jolla määritys tuottaa signaalin: kilpaileva tai ei-kilpaileva, homogeeninen tai heterogeeninen, ja mikä leima ja mittaustekniikka.",
  "",
  2, L('määritysperiaate', ['määritysperiaatteen', 'määritysperiaatetta', 'määritysperiaatteet', 'määritysperiaatteita', 'määritysteknologia', 'määritysteknologian', 'määritysteknologiat', 'määritysteknologioita', 'määritysmenetelmä', 'määritysmenetelmän', 'määritysmenetelmät', 'määritysmenetelmiä', 'mittausperiaate', 'mittausperiaatteen', 'mittausperiaatteet', 'assay', 'assays', 'määritysmuoto', 'määritysmuodon', 'määritysmuodot', 'formaatti', 'formaatin', 'formaatit'])),
K("Mikä on laitteisto määrityksessä?",
  "Määrityksen tekevät laitteet: pipetointirobotti, levyinkubaattori, pesuri ja lukija, tai kaikki yhdessä analysaattorissa.",
  "",
  2, L('laitteisto', ['laitteiston', 'laitteistoa', 'laitteistot', 'laitteistojen', 'laitteistoja', 'analysaattori', 'analysaattorin', 'analysaattoria', 'analysaattorit', 'analysaattorien', 'analysaattoreita', 'analysaattorilla', 'lukija', 'lukijan', 'lukijaa', 'lukijat', 'levylukija', 'levylukijan', 'levylukijat', 'pipetointirobotti', 'pipetointirobotin', 'pipetointirobotit', 'laite', 'laitteen', 'laitetta', 'laitteessa', 'laitteesta', 'laitteeseen', 'laitteet', 'laitteiden', 'laitteita', 'laitteilla', 'laitteeksi', 'mittalaite', 'mittalaitteen', 'mittalaitetta', 'mittalaitteet', 'mittalaitteita'])),
K("Mikä on lukuarvo tuloksessa?",
  "Kvantitatiivisen määrityksen numeerinen tulos yksiköineen, kuten 4,2 mmol/ℓ, erotuksena kvalitatiivisesta positiivinen/negatiivinen-tuloksesta.",
  "",
  1, L('lukuarvo', ['lukuarvon', 'lukuarvoa', 'lukuarvot', 'lukuarvona', 'numeerinen tulos', 'numeerisen tuloksen', 'numeerinen', 'numeerisen', 'numeeriset', 'määrällinen', 'määrällisen', 'määrällistä', 'määrälliset', 'määrällisesti', 'laadullinen', 'laadullisen', 'laadullista', 'laadulliset', 'laadullisesti', 'tulos', 'tuloksen', 'tulosta', 'tulokset', 'tulosten', 'tuloksia', 'tuloksena', 'mmol/ℓ', 'mmol', 'µmol/ℓ', 'nmol/ℓ', 'pitoisuusyksikkö', 'pitoisuusyksikön'])),
K("Mikä on liuostilavuus määrityksessä?",
  "Reaktiossa käytettävä nestemäärä, mikrotiitterilevyllä 50–200 µℓ, mikrofluidiikassa nanolitroja. Pieni tilavuus säästää näytettä ja reagensseja.",
  "",
  1, L('liuostilavuus', ['liuostilavuuden', 'liuostilavuutta', 'liuostilavuudet', 'liuostilavuuksia', 'reaktiotilavuus', 'reaktiotilavuuden', 'reaktiotilavuutta', 'näytetilavuus', 'näytetilavuuden', 'näytetilavuutta', 'tilavuus', 'tilavuuden', 'tilavuutta', 'tilavuudet', 'tilavuuksien', 'tilavuuksia', 'mikrolitra', 'mikrolitran', 'mikrolitraa', 'mikrolitroja', 'µℓ', 'nanolitra', 'nanolitran', 'nanolitroja', 'millilitra', 'millilitran', 'millilitraa', 'mℓ', 'litra', 'litran', 'litraa', 'ℓ'])),
K("Mikä on kapasiteetti diagnostiikassa?",
  "Määritysten määrä, jonka laboratorio tai laite tekee aikayksikössä. Automaatio ja monianalyyttimääritykset nostavat sitä. Kutsutaan myös: läpäisykyky.",
  "",
  1, L('kapasiteetti', ['kapasiteetin', 'kapasiteettia', 'läpäisykyky', 'läpäisykyvyn', 'läpäisykykyä', 'throughput', 'high-throughput', 'suurikapasiteettinen', 'suurikapasiteettisen', 'suurikapasiteettiset', 'näytemäärä', 'näytemäärän', 'näytemäärää', 'näytemäärät'])),
K("Mikä on kaksipuoleinen vasta-ainepari?",
  "Sandwich-määrityksen kaksi vasta-ainetta, jotka sitoutuvat analyytin eri kohtiin: toinen pyydystää, toinen kantaa leiman. Kutsutaan myös: vasta-ainepari.",
  "",
  2, L(N('kaksipuoleinen', 'kaksipuoleisen', 'kaksipuoleista', 'kaksipuoleiset', 'vasta-ainepari', 'vasta-aineparin', 'vasta-aineparia', 'vasta-aineparit', 'vasta-aineparien', 'vasta-ainepareja', 'sitoutumiskohta', 'sitoutumiskohdan', 'sitoutumiskohtaa', 'sitoutumiskohdat', 'sitoutumiskohtien', 'sitoutumiskohtia', 'sitoutumispinta', 'sitoutumispinnan', 'sitoutumispintaa'))),
K("Mikä on lääkäri diagnostiikan käyttäjänä?",
  "Tulkitsee laboratoriotulokset oireiden ja tutkimusten rinnalla ja tekee hoitopäätöksen. Testi ei korvaa kliinistä arviota.",
  "",
  1, L(N('lääkäri', 'lääkärin', 'lääkäriä', 'lääkärit', 'lääkärien', 'lääkäreitä', 'lääkärille', 'hoitopäätös', 'hoitopäätöksen', 'hoitopäätöstä', 'hoitopäätökset', 'hoitopäätöksiä', 'hoitopäätöksistä', 'kliininen arvio', 'kliinisen arvion', 'kliinistä arviota', 'hoito', 'hoidon', 'hoitoa', 'hoidossa', 'hoitoon', 'hoidot', 'hoitojen', 'hoitoja', 'hoitomuoto', 'hoitomuodon', 'hoitomuodot', 'hoitomuotoja', 'hoitaa', 'hoidetaan', 'hoidettu'))),
K("Mikä on leimaamaton analyytti kilpailevassa määrityksessä?",
  "Näytteen oma analyytti, joka kilpailee leimatun analyytin kanssa vasta-aineesta: mitä enemmän sitä on, sitä pienempi signaali.",
  "",
  2, L(N('leimaamaton', 'leimaamattoman', 'leimaamatonta', 'leimaamattomat', 'leimaamattomia', 'leimaamaton analyytti', 'leimaamattoman analyytin', 'leimattu analyytti', 'leimatun analyytin', 'leimattua analyyttiä', 'leimattu antigeeni', 'leimatun antigeenin', 'leimattua antigeenia', 'leimata', 'leimataan', 'leimattu', 'leimatun', 'leimattua', 'leimattuja', 'leimatulla', 'leimaus', 'leimauksen', 'leimausta', 'käänteinen signaali', 'käänteisen signaalin', 'laskeva signaali', 'laskevan signaalin'))),
K("Mikä on glykosylaation mittaus diagnostiikassa?",
  "Sokeroituneen proteiinin osuus, kuten HbA1c: kertoo verensokerin kuukausien keskiarvon. Kutsutaan myös: glykaatio.",
  "",
  2, L(N('glykaatio', 'glykaation', 'glykaatiota', 'glykoitunut', 'glykoituneen', 'glykoitunutta', 'glykoituneet', 'glucosylation', 'sokeroitunut', 'sokeroituneen', 'sokeroitunutta', 'sokeroituneet', 'sokeroituminen', 'sokeroitumisen', 'verensokeri', 'verensokerin', 'verensokeria', 'verensokerimittari', 'verensokerimittarin', 'verensokerimittarit', 'glukoosimittari', 'glukoosimittarin', 'glukoosimittarit', 'glukoosimittareissa', 'diabetesdiagnostiikka', 'diabetesdiagnostiikan', 'diabetesdiagnostiikkaa'))),
K("Mitä tarttuva tauti tarkoittaa diagnostiikassa?",
  "Mikrobin aiheuttama, ihmisestä toiseen leviävä sairaus. Todetaan antigeeni-, vasta-aine- tai nukleiinihappotestillä. Kutsutaan myös: infektiotauti.",
  "",
  2, L(N('tarttuva tauti', 'tarttuvan taudin', 'tarttuvaa tautia', 'tarttuvat taudit', 'tarttuvien tautien', 'tarttuvia tauteja', 'tarttuva', 'tarttuvan', 'tarttuvat', 'tarttuvien', 'tarttuvia', 'infektiotauti', 'infektiotaudin', 'infektiotautia', 'infektiotaudit', 'infektiotautien', 'infektiotauteja', 'infektio', 'infektion', 'infektiota', 'infektiossa', 'infektiot', 'infektioiden', 'infektioita', 'infektiodiagnostiikka', 'infektiodiagnostiikan', 'infektiodiagnostiikkaa', 'tulehdustauti', 'tulehdustaudin', 'tulehdustaudit', 'epidemia', 'epidemian', 'epidemiaa', 'pandemia', 'pandemian', 'pandemiaa', 'pandemiassa'))),
]

KEMIA_L1 = [
K("Mikä on olosuhde kokeessa?",
  "Kokeen ulkoinen tekijä, kuten lämpötila, paine tai hapen läsnäolo, joka pidetään vakiona tai jota muutetaan hallitusti.",
  "",
  1, L('olosuhde', ['olosuhteen', 'olosuhdetta', 'olosuhteet', 'olosuhteiden', 'olosuhteita', 'olosuhteissa', 'olosuhteisiin', 'koeolosuhde', 'koeolosuhteen', 'koeolosuhteet', 'koeolosuhteissa', 'vakio-olosuhteet', 'vakio-olosuhteissa', 'olot', 'olojen', 'oloja', 'oloissa'])),
K("Mikä on selitys tieteellisessä menetelmässä?",
  "Havainnolle ehdotettu syy. Kilpailevat selitykset erotetaan kokeella, joka ennustaa eri tuloksen kummallekin. Kutsutaan myös: vaihtoehtoinen selitys.",
  "",
  1, L('selitys', ['selityksen', 'selitystä', 'selitykset', 'selitysten', 'selityksiä', 'selittää', 'selittävä', 'selittävät', 'selitetty', 'vaihtoehtoinen selitys', 'vaihtoehtoisen selityksen', 'vaihtoehtoiset selitykset', 'vaihtoehtoisia selityksiä', 'kilpaileva selitys', 'kilpailevan selityksen', 'kilpailevat selitykset', 'arvaus', 'arvauksen', 'arvausta', 'perusteltu arvaus', 'perustellun arvauksen'])),
K("Mikä on aineen koostumus?",
  "Mistä alkuaineista tai yhdisteistä aine muodostuu ja missä suhteessa. Kemia tutkii aineen koostumusta, rakennetta ja muutoksia.",
  "",
  2, L('koostumus', ['koostumuksen', 'koostumusta', 'koostumukset', 'koostumuksia', 'koostumukseen', 'koostumuksessa', 'koostua', 'koostuu', 'koostuvat', 'koostuva', 'koostuvan', 'kemiallinen koostumus', 'kemiallisen koostumuksen', 'kemiallista koostumusta', 'aineen rakenne', 'aineen rakenteen', 'aineen rakennetta', 'aineen ominaisuudet', 'aineen ominaisuuksien', 'aineen ominaisuuksia'])),
K("Mitä tieteellinen tarkoittaa?",
  "Tieteen menetelmin saatu ja tarkistettu: perustuu havaintoihin, kokeisiin, toistettavuuteen ja julkiseen arviointiin. Kutsutaan myös: järjestelmällinen.",
  "",
  1, L(N('tieteellinen', 'tieteellisen', 'tieteellistä', 'tieteelliset', 'tieteellisiä', 'tieteellisesti', 'tieteelliseksi', 'tieteelliselle', 'järjestelmällinen', 'järjestelmällisen', 'järjestelmällistä', 'järjestelmälliset', 'järjestelmällisesti', 'julkaista', 'julkaistaan', 'julkaistu', 'julkaisu', 'julkaisun', 'julkaisua', 'julkaisut', 'julkaisujen', 'julkaisuja', 'vertaisarviointi', 'vertaisarvioinnin', 'vertaisarvioitu', 'vertaisarvioidun'))),
]

KEMIA_L21 = [
K("Mikä on aikakausi kemian historiassa?",
  "Kehityksen jakso: esihistoriallinen käytännön kemia, antiikin filosofia, alkemia, 1600–1700-lukujen tieteellistyminen ja 1800-luvun atomiteoria.",
  "",
  1, L('aikakausi', ['aikakauden', 'aikakautta', 'aikakaudet', 'aikakausien', 'aikakausia', 'aikakaudella', 'esihistoriallinen', 'esihistoriallisen', 'esihistoriallista', 'esihistoriallisella', 'esihistoria', 'esihistorian', 'esihistoriaa', 'muinainen', 'muinaisen', 'muinaista', 'muinaiset', 'muinaisten', 'muinaisia', 'antiikki', 'antiikin', 'antiikkia', 'keskiaika', 'keskiajan', 'keskiaikaa', 'keskiajalla', 'uusi aika', 'uuden ajan', 'uudella ajalla', 'historia', 'historian', 'historiaa', 'historiassa', 'kemian historia', 'kemian historian', 'kemian historiaa', 'antiikki', 'antiikkia'])),
K("Mikä on kemisti?",
  "Kemian tutkija tai ammattilainen. Boyle oli ensimmäinen moderni kemisti: kvantitatiivisia kokeita ilman alkemian mystiikkaa.",
  "",
  1, L('kemisti', ['kemistinä', 'fyysikko', 'fyysikon', 'fyysikkoa', 'fyysikot', 'fyysikoiden', 'fyysikkojen', 'tutkija', 'tutkijan', 'tutkijaa', 'tutkijat', 'tutkijoiden', 'tutkijoita', 'tiedemies', 'tiedemiehen', 'tiedemiestä', 'tiedemiehet', 'tiedemiesten', 'tiedemiehiä', 'luonnonfilosofi', 'luonnonfilosofin', 'luonnonfilosofit', 'filosofi', 'filosofin', 'filosofia', 'filosofit', 'filosofinen', 'filosofisen', 'filosofista', 'filosofiset'])),
K("Mikä on perusosa aineessa?",
  "Aineen pienin rakenneosa, jota ei voi jakaa kemiallisesti: atomi (kreikan atomos, jakamaton).",
  "",
  1, L(N('perusosa', 'perusosan', 'perusosaa', 'perusosat', 'perusosien', 'perusosia', 'perusaine', 'perusaineen', 'perusainetta', 'perusaineet', 'perusaineiden', 'perusaineita', 'perusaineesta', 'jakamaton', 'jakamattoman', 'jakamatonta', 'jakamattomat', 'jakamattomia', 'jakamattomista', 'jakamattomana', 'atomos', 'osanen', 'osasen', 'osasta', 'osaset', 'osasten', 'osasia', 'osasista'))),
K("Mikä on todistusaineisto tieteessä?",
  "Kokeelliset tulokset, jotka tukevat teoriaa. Daltonin atomiteoria vakiintui, kun massan säilymisen ja vakiosuhteiden lait tukivat sitä.",
  "",
  1, L('todistusaineisto', ['todistusaineiston', 'todistusaineistoa', 'todiste', 'todisteen', 'todistetta', 'todisteet', 'todisteiden', 'todisteita', 'todistaa', 'todistettu', 'todistetusti', 'näyttö', 'näytön', 'näyttöä', 'vahvistaa', 'vahvistaa teorian', 'vahvistui', 'vahvistuminen', 'vahvistumisen', 'vakiinnuttaa', 'vakiinnutti', 'vakiintua', 'vakiintui', 'vakiintunut', 'vakiintuneen'])),
K("Mikä on yhdistymisreaktio?",
  "Reaktio, jossa kaksi ainetta yhtyy yhdeksi, kuten vety ja happi vedeksi. Gay-Lussac tutki kaasujen yhdistymisreaktioita tilavuuksina.",
  "",
  2, L('yhdistymisreaktio', ['yhdistymisreaktion', 'yhdistymisreaktiota', 'yhdistymisreaktiot', 'yhdistymisreaktioiden', 'yhdistymisreaktioita', 'yhtyä', 'yhtyy', 'yhtyvät', 'yhtyminen', 'yhtymisen', 'yhtymistä', 'yhdistyä', 'yhdistyy', 'yhdistyvät', 'yhdistyminen', 'yhdistymisen', 'synteesireaktio', 'synteesireaktion', 'synteesireaktiot', 'tilavuusosa', 'tilavuusosan', 'tilavuusosaa', 'tilavuusosat', 'tilavuusosien', 'tilavuusosia'])),
K("Mikä on kemiallinen kaava?",
  "Yhdisteen merkintä alkuainemerkeillä ja alaindekseillä, kuten H<sub>2</sub>O. Oikeat kaavat saatiin vasta Avogadron oivalluksen jälkeen.",
  "",
  2, L(N('kemiallinen kaava', 'kemiallisen kaavan', 'kemiallista kaavaa', 'kemialliset kaavat', 'kemiallisten kaavojen', 'kemiallisia kaavoja', 'yhdistekaava', 'yhdistekaavan', 'yhdistekaavaa', 'yhdistekaavat', 'yhdistekaavojen', 'yhdistekaavoja', 'molekyylikaava', 'molekyylikaavan', 'molekyylikaavaa', 'molekyylikaavat', 'empiirinen kaava', 'empiirisen kaavan', 'empiiristä kaavaa', 'rakennekaava', 'rakennekaavan', 'rakennekaavaa', 'rakennekaavat', 'kaavayksikkö', 'kaavayksikön', 'kaavayksikköä'))),
]

KEMIA_L22 = [
K("Mikä on happirikkaampi oksoanioni?",
  "Saman keskusatomin ioneista se, jossa on enemmän happea: sulfaatti on sulfiittia happirikkaampi ja saa päätteen -aatti.",
  "",
  1, L(N('happirikkaampi', 'happirikkaamman', 'happirikkaampaa', 'happirikkaammat', 'happirikas', 'happirikkaan', 'happirikasta', 'happiköyhempi', 'happiköyhemmän', 'happiköyhempää', 'happiköyhä', 'happiköyhän', 'happiköyhää', 'happimäärä', 'happimäärän', 'happimäärää', 'happiatomi', 'happiatomin', 'happiatomia', 'happiatomit', 'happiatomien', 'happiatomeja'))),
K("Mikä on ionikiteinen rakenne?",
  "Ioneista koostuva säännöllinen hila, jossa kationit ja anionit vuorottelevat, kuten NaCl. Ioniyhdisteillä ei ole molekyylejä.",
  "",
  2, L(N('ionikiteinen', 'ionikiteisen', 'ionikiteistä', 'ionikiteiset', 'ionikiteisiä', 'ionihila', 'ionihilan', 'ionihilaa', 'ionihilat', 'kidehila', 'kidehilan', 'kidehilaa', 'kidehilat', 'hila', 'hilan', 'hilaa', 'hilat', 'hilarakenne', 'hilarakenteen', 'hilarakennetta', 'kiderakenne', 'kiderakenteen', 'kiderakennetta', 'kiderakenteet'))),
]

KEMIA_L31 = [
K("Mikä on kirjain ryhmän merkinnässä?",
  "Vanhassa eurooppalaisessa käytännössä ryhmä merkittiin roomalaisella numerolla ja kirjaimella A tai B (IIIA, IIIB).",
  "",
  1, L(N('kirjain', 'kirjaimen', 'kirjainta', 'kirjaimet', 'kirjainten', 'kirjaimia', 'kirjaimin', 'A-ryhmä', 'A-ryhmän', 'A-ryhmät', 'B-ryhmä', 'B-ryhmän', 'B-ryhmät', 'sivuryhmä jaksollisessa järjestelmässä', 'sivuryhmät jaksollisessa järjestelmässä', 'numero', 'numeron', 'numeroa', 'numerot', 'numeroiden', 'numeroita', 'numeroin', 'numerointi', 'numeroinnin', 'numerointia', 'numeroida', 'numeroidaan', 'numeroitu'))),
K("Mitä valtaosa alkuaineista on?",
  "Metalleja: noin 80 % alkuaineista luovuttaa elektroneja ja muodostaa kationeja. Epämetallit ovat taulukon oikeassa yläkulmassa.",
  "",
  1, L(N('valtaosa', 'valtaosan', 'valtaosaa', 'enemmistö', 'enemmistön', 'enemmistöä', 'puolimetalli', 'puolimetallin', 'puolimetallia', 'puolimetallit', 'puolimetallien', 'puolimetalleja', 'metalloidi', 'metalloidin', 'metalloidit', 'metalloidien'))),
]

KEMIA_L32 = [
K("Mikä on kokonaisluku kvanttimekaniikassa?",
  "Luku ilman murto-osaa (…−1, 0, 1, 2…). Kvanttiluvut ovat kokonaislukuja, ja energia tulee vain kvantin kokonaislukukerrannaisina.",
  "",
  2, L('kokonaisluku', ['kokonaisluvun', 'kokonaislukua', 'kokonaisluvut', 'kokonaislukujen', 'kokonaislukuja', 'kokonaislukuarvo', 'kokonaislukuarvon', 'kokonaislukuarvot', 'kokonaislukuarvoja', 'kokonaislukukerrannainen', 'kokonaislukukerrannaisen', 'kokonaislukukerrannaiset', 'kokonaislukukerrannaisina', 'kerrannainen', 'kerrannaisen', 'kerrannaiset', 'kerrannaisina', 'monikerta', 'monikerran', 'monikertoina', 'puoliluku', 'puoliluvun', 'puolilukuja'])),
K("Mikä on aakkosjärjestys sivukvanttiluvun kirjaimissa?",
  "s, p, d ja f tulevat spektroskopian sanoista sharp, principal, diffuse, fundamental. Niiden jälkeen kirjaimet jatkuvat aakkosissa: g, h, i.",
  "",
  1, L(N('aakkosjärjestys', 'aakkosjärjestyksen', 'aakkosjärjestystä', 'aakkosjärjestyksessä', 'aakkoset', 'aakkosten', 'aakkosia', 'sharp', 'principal', 'diffuse', 'fundamental', 'orbitaalikirjain', 'orbitaalikirjaimen', 'orbitaalikirjaimet', 'orbitaalikirjainten', 'g-orbitaali', 'g-orbitaalin', 'g-orbitaalit', 'historiallinen syy', 'historiallisen syyn', 'historiallisista syistä'))),
K("Mikä on analogia opetuksessa?",
  "Tutun asian käyttö oudon selittämiseen: elektronin seisova aalto verrattuna kitaran kieleen tai kvantittuminen portaisiin luiskan sijasta.",
  "",
  1, L('analogia', ['analoginen', 'analogisen', 'analogista', 'analogiset', 'analogisia', 'analogisesti', 'vertaus', 'vertauksen', 'vertausta', 'vertaukset', 'vertauksia', 'vertauskuva', 'vertauskuvan', 'vertauskuvat', 'kitaran kieli', 'kitaran kielen', 'kitaran kieltä', 'kieli', 'kielen', 'kieltä', 'portaat', 'portaiden', 'portaita', 'porras', 'portaan', 'porrasta', 'luiska', 'luiskan', 'luiskaa'])),
K("Mikä on orbitaalin leikkaus?",
  "Kolmiulotteisen orbitaalin poikkileikkaus tasossa, jolla muoto ja solmutasot havainnollistetaan: p-orbitaalin kaksi lohkoa, d-orbitaalin neljä.",
  "",
  1, L(N('orbitaalin leikkaus', 'orbitaalin leikkauksen', 'poikkileikkaus', 'poikkileikkauksen', 'poikkileikkausta', 'poikkileikkaukset', 'poikkileikkauksia', 'lohko', 'lohkon', 'lohkoa', 'lohkot', 'lohkojen', 'lohkoja', 'solmutaso', 'solmutason', 'solmutasoa', 'solmutasot', 'solmutasojen', 'solmutasoja', 'solmu', 'solmun', 'solmua', 'solmut', 'solmujen', 'solmuja', 'solmukohta', 'solmukohdan', 'solmukohdat', 'solmukohtia', 'kuvio', 'kuvion', 'kuviota', 'kuviot', 'kuvioiden', 'kuvioita', 'kuvioilla', 'suuntautua avaruudessa', 'suunta', 'suunnan', 'suuntaa', 'suunnat', 'suuntien', 'suuntia'))),
K("Mikä on korkeaenerginen tila?",
  "Tila, jonka energia on perustilaa suurempi: virittynyt elektroni, korkeaenerginen fotoni (UV, röntgen) tai sähköpurkauksen virittämä atomi.",
  "",
  1, L(N('korkeaenerginen', 'korkeaenergisen', 'korkeaenergistä', 'korkeaenergiset', 'korkeaenergisiä', 'korkeaenergisten', 'korkeaenergisillä', 'suurienerginen', 'suurienergisen', 'suurienergiset', 'suurienergisiä', 'matalaenerginen', 'matalaenergisen', 'matalaenergiset', 'matalaenergisiä', 'pienienerginen', 'pienienergisen', 'pienienergiset', 'energiarikas', 'energiarikkaan', 'energiarikasta', 'energiarikkaat', 'energiarikkaita', 'energiaköyhä', 'energiaköyhän', 'energiaköyhät'))),
K("Mikä on välikokoinen hiukkanen aalto-hiukkasdualismissa?",
  "Atomien ja molekyylien kokoluokka, jossa aalto- ja hiukkasluonne näkyvät molemmat. Elektronit ovat aaltoja, tennispallot hiukkasia.",
  "",
  1, L(N('välikoko', 'välikoon', 'välikokoa', 'välikokoinen hiukkanen', 'välikokoisen hiukkasen', 'välikokoiset hiukkaset', 'atomien mittakaava', 'atomien mittakaavan', 'atomien mittakaavassa', 'ainehiukkanen', 'ainehiukkasen', 'ainehiukkasta', 'ainehiukkaset', 'ainehiukkasten', 'ainehiukkasia', 'ainehiukkasilla'))),
]
