# -*- coding: utf-8 -*-
"""Solu- ja biomolekyylit, Luento 3 - Eukaryoottisolujen rakenteen perusteet (3. Eukaryoottisolujen rakenteen
perusteet 2026.pdf). Rakentaa tyokalut/solu_kortit.py. Tuma, mitokondrio, kloroplasti, ribosomi, kromatiini, histoni,
soluelin ja solulima on maaritelty Luento 1:ssa - niihin linkitetaan, ei maaritella uudestaan."""
from biotek_taivutus import L
from pakka_rakenna import K

PDF = '3. Eukaryoottisolujen rakenteen perusteet 2026.pdf'
LEHTI = 'Luento 3 - Eukaryoottisolujen rakenteen perusteet'
NRO = 3
KUVAT = {
    'solu3_sentrifugointi.jpg': (PDF, 7, 'kuva'), 'solu3_golgi.jpg': (PDF, 14, 'kuva'), 'solu3_autofagia.jpg': (PDF, 18, 'kuva'),
    'solu3_mitokondrio.jpg': (PDF, 33, 'kuva'), 'solu3_kloroplasti.png': (PDF, 36, 'kuva'), 'solu3_tukiranka.jpg': (PDF, 40, 'kuva'),
    'solu3_kinesiini.png': (PDF, 44, 'kuva'), 'solu3_klatriini.jpg': (PDF, 55, 'kuva'),
}

KORTIT = [
# ── kalvo, kuljetus ja reseptorit ──────────────────────────────────────────────────────
K("Miksi solukalvossa tarvitaan kuljetusproteiineja?",
  "Solukalvo ei läpäise useimpia molekyylejä, joten niille on tehtävä aukko: kalvon läpäisevä proteiini.",
  "Solukalvon lipidikaksoiskerros päästää läpi vain pieniä poolittomia molekyylejä, kuten happea ja hiilidioksidia. Ioneille, sokereille ja aminohapoille on tehtävä aukko, ja aukot ovat erityisiä kalvon läpäiseviä proteiineja, jotka yleensä päästävät lävitseen vain yhtä tai harvaa molekyyliä. Tämä valikoivuus tekee kalvosta portin, joka määrää, mitä soluun tulee ja mitä sieltä lähtee. Solukalvossa on kuljetusproteiinien lisäksi reseptoriproteiineja.",
  3),
K("Mikä on kuljetusproteiini?",
  "Kalvon läpäisevä proteiini, joka päästää tietyn molekyylin kalvon läpi joko passiivisena kanavana tai aktiivisena pumppuna.",
  "Kuljetusproteiini on solukalvon proteiini, jonka kautta molekyyli pääsee lipidikerroksen läpi. Passiivinen kanava päästää molekyylit kulkemaan konsentraatiogradientin suuntaan, suuremmasta pitoisuudesta pienempään, ilman energiaa. Aktiivinen pumppu siirtää molekyylejä gradienttia vastaan ja käyttää siihen ulkoista energiaa, tavallisesti ATP:ta. Kumpikin on valikoiva: yksi proteiini kuljettaa yleensä vain yhtä tai harvaa molekyyliä.",
  3, L('kuljetusproteiini', ['kanava', 'kanavan', 'kanavaa', 'kanavat', 'kanavien', 'pumppu', 'pumpun', 'pumppua', 'pumput', 'pumppujen'])),
K("Mikä on reseptori?",
  "Proteiini, joka välittää informaatiota solukalvon yli, esimerkiksi ionikanavana tai entsyyminä.",
  "Reseptori on solukalvon proteiini, joka tunnistaa solun ulkopuolisen viestimolekyylin, kuten hormonin tai välittäjäaineen, ja välittää tiedon sen sitoutumisesta solun sisään. Osa reseptoreista on ionikanavia, jotka avautuvat viestin sitoutuessa, osa entsyymejä, jotka aktivoituvat ja käynnistävät signaaliketjun solulimassa. Reseptorin ansiosta solu reagoi ympäristöönsä ilman, että viestimolekyyli itse kulkee kalvon läpi.",
  3, L('reseptori', 'reseptoriproteiini')),
# ── organellit yleisesti ───────────────────────────────────────────────────────────────
K("Miten eukaryoottisolu eroaa prokaryootista kalvorakenteiltaan?",
  "Eukaryoottisolussa on lukuisia kalvon rajoittamia soluelimiä, prokaryooteilla niitä ei varsinaisesti ole.",
  "Eukaryoottisolu sisältää lukuisia kalvon rajoittamia soluelimiä: tuman, mitokondriot, endoplasmisen kalvoston, Golgin laitteen, lysosomit ja peroksisomit. Prokaryooteilla varsinaisia kalvon rajoittamia soluelimiä ei esiinny, joskin eräillä Asgard-arkeoneilla on solun ulkoisia ja sisäisiä kalvorakkuloita. Bakteereilla ja arkeoneilla on sen sijaan inkluusioita, kalvottomia tai yksinkertaisen kuoren rajaamia jyväsiä, jotka varastoivat aineita tai hoitavat erityistehtäviä.",
  3),
K("Mikä on inkluusio?",
  "Bakteerin tai arkeonin solunsisäinen jyvänen, joka varastoi aineita tai hoitaa erityistehtävää, kuten karboksisomi.",
  "Inkluusiot ovat prokaryoottien solun sisäisiä rakenteita, jotka korvaavat osittain eukaryoottien soluelimet. Ne varastoivat aineita, muun muassa rikkiä, nitraattia ja fosfaattia. Magnetosomit sisältävät magnetiittikiteitä, joiden avulla bakteeri orientoituu magneettikentässä. Karboksisomit ovat proteiinikuoren rajaamia inkluusioita, joihin hiilidioksidia sitova entsyymi on pakattu tehokasta hiilensidontaa varten, ja ne ovat yleisiä syanobakteereilla.",
  2, L('inkluusio', 'karboksisomi')),
K("Miten soluelimet erotellaan laboratoriossa?",
  "Sentrifugoimalla solumurskaa kasvavilla nopeuksilla, jolloin soluelimet laskeutuvat pelleteiksi painonsa mukaan.",
  "Kudos homogenoidaan ja sentrifugoidaan vaiheittain. Hitaalla nopeudella, 1000 g, pellettiin laskeutuvat ehjät solut, tumat, tukirangat ja solukalvot. Keskinopeudella, 20 000 g, saadaan mitokondriot, lysosomit ja peroksisomit, ja suurella nopeudella, 80 000 g, endoplasmisen kalvoston kappaleet ja pienet rakkulat. Ultrasentrifugoinnissa, 150 000 g, laskeutuvat ribosomit ja suuret makromolekyylit, ja liukoiset proteiinit jäävät vielä supernatanttiin. Kutsutaan myös: differentiaalisentrifugointi.",
  2, L(['differentiaalisentrifugointi', 'differentiaalisentrifugoinnin', 'differentiaalisentrifugointia', 'sentrifugointi', 'sentrifugoinnin', 'sentrifugointia', 'sentrifugoinnissa', 'sentrifugoimalla', 'supernatantti', 'supernatantin', 'supernatanttia', 'supernatantissa', 'pelletti', 'pelletin', 'pellettiä', 'pelletit']), 'solu3_sentrifugointi.jpg'),
# ── endoplasminen kalvosto ja Golgi ────────────────────────────────────────────────────
K("Mikä on endoplasminen kalvosto?",
  "Kalvoista koostuva soluelin, jossa valmistetaan solun pinnalle ja ulkopuolelle menevät proteiinit ja lipidit.",
  "Endoplasminen kalvosto on kalvoista koostuva soluelin, joka täyttää suuren osan eukaryoottisolusta, ja sen sisimmät kalvot ovat yhtäjatkuvia tumakotelon kanssa. Se on solun pinnalle ja ulkopuolelle tulevien proteiinien ja lipidien valmistuspaikka. Karkea kalvosto on ribosomien peittämä ja valmistaa erittyviä proteiineja, sileä kalvosto valmistaa lipidejä. Valmiit tuotteet kulkevat kalvorakkuloissa Golgin laitteeseen. Kutsutaan myös: endoplasmakalvosto, solulimakalvosto, ER.",
  3, L(['endoplasminen kalvosto', 'endoplasmisen kalvoston', 'endoplasmista kalvostoa', 'endoplasmisessa kalvostossa', 'endoplasmisesta kalvostosta', 'endoplasmiseen kalvostoon', 'endoplasmakalvosto', 'endoplasmakalvoston', 'endoplasmakalvostoa', 'endoplasmakalvostossa', 'endoplasmakalvostosta', 'endoplasmakalvostoon', 'solulimakalvosto', 'solulimakalvoston', 'solulimakalvostoa', 'solulimakalvostossa'])),
K("Mikä on karkea endoplasminen kalvosto?",
  "Ribosomien peittämä osa kalvostoa, jonka ribosomit valmistavat erittyviä proteiineja kalvoston sisäiseen tilaan.",
  "Karkean endoplasmisen kalvoston pinnalla on suuri määrä ribosomeja, jotka antavat sille elektronimikroskoopissa karkean ulkonäön. Ribosomit valmistavat kalvoproteiineja ja erittyviä proteiineja ja työntävät ne synteesin aikana kalvoston sisäiseen tilaan, jossa proteiinit laskostuvat ja saavat ensimmäiset sokeriryhmänsä. Sieltä ne kulkevat rakkuloissa Golgin laitteeseen. Solut, jotka erittävät paljon proteiinia, kuten haiman solut, ovat täynnä karkeaa kalvostoa.",
  3, L(['karkea endoplasminen kalvosto', 'karkean endoplasmisen kalvoston', 'karkeaa endoplasmista kalvostoa', 'karkeassa endoplasmisessa kalvostossa', 'karkea kalvosto', 'karkean kalvoston', 'karkeaa kalvostoa', 'karkeassa kalvostossa'])),
K("Mikä on sileä endoplasminen kalvosto?",
  "Ribosomiton osa kalvostoa, jossa valmistetaan lipidejä, muun muassa lisää solukalvoa.",
  "Sileä endoplasminen kalvosto on lipidien biosynteesipaikka. Siellä valmistetaan kalvojen fosfolipidit, joista syntyy lisää solukalvoa ja soluelinten kalvoja, sekä steroidit, kuten steroidihormonit. Pinnalla ei ole ribosomeja, joten se näyttää sileältä. Maksasoluissa sileä kalvosto myös muokkaa lääkeaineita ja myrkkyjä vesiliukoisemmiksi, ja lihassoluissa se varastoi kalsiumia, joka laukaisee supistuksen.",
  3, L(['sileä endoplasminen kalvosto', 'sileän endoplasmisen kalvoston', 'sileää endoplasmista kalvostoa', 'sileässä endoplasmisessa kalvostossa', 'sileä kalvosto', 'sileän kalvoston', 'sileää kalvostoa', 'sileässä kalvostossa'])),
K("Mikä on Golgin laite?",
  "Litistyneistä kalvo-onteloista koostuva soluelin, joka prosessoi, muokkaa ja lajittelee kalvostosta tulevat proteiinit.",
  "Golgin laite koostuu 4–11 litistyneestä kalvopussista eli cisternasta. Käsiteltävät proteiinit tuodaan endoplasmisesta kalvostosta kalvorakkuloissa, ja ne siirtyvät ontelosta toiseen samalla mekanismilla. Golgin laitteessa proteiineihin lisätään kemiallisia ryhmiä: hiilihydraatteja glykosylaatiossa, sulfaattiryhmiä tai lipidejä. Lopuksi proteiineja sisältävät rakkulat ohjataan lysosomeihin, solukalvolle tai ulos solusta. Nisäkässoluissa Golgin laitteita on useita, ja ne muodostavat nauhan. Kutsutaan myös: Golgin kompleksi.",
  3, L(['Golgin laite', 'Golgin laitteen', 'Golgin laitetta', 'Golgin laitteessa', 'Golgin laitteesta', 'Golgin laitteeseen', 'Golgin laitteet', 'Golgin laitteiden', 'Golgin laitteita', 'Golgin kompleksi', 'Golgin kompleksin', 'Golgin kompleksia', 'cisterna', 'cisternan', 'cisternaa', 'cisternat'])),
K("Mitkä ovat Golgin laitteen cis- ja trans-puoli?",
  "Cis-puoli kohti kalvostoa ottaa aineet vastaan, trans-puoli kohti solukalvoa vapauttaa ne.",
  "Golgin laite on suunnattu: cis-puoli on orientoitunut kohti endoplasmista kalvostoa ja tumaa, ja sinne saapuvat kalvostosta tulevat rakkulat. Proteiinit etenevät ontelosta toiseen kohti trans-puolta, joka on orientoitunut kohti solukalvoa eli solun pintaa. Trans-puolelta prosessoidut aineet vapautetaan rakkuloissa lysosomeihin, solukalvolle tai eritettäväksi. Kuvassa elektronimikroskooppikuva Golgin laitteesta, cis-puoli ylhäällä ja trans-puoli alhaalla.",
  2, L(['cis-puoli', 'cis-puolen', 'cis-puolta', 'cis-puolella', 'trans-puoli', 'trans-puolen', 'trans-puolta', 'trans-puolella']), 'solu3_golgi.jpg'),
K("Miten soluelimet järjestetään solun sisällä?",
  "Mikrotubulukset järjestävät soluelimet eläinsoluissa, kasveilla saman tekevät aktiinisäikeet.",
  "",
  1),
# ── lysosomit, vakuoli, peroksisomit ───────────────────────────────────────────────────
K("Mikä on lysosomi?",
  "Eläinsolun kalvorakkula, joka sisältää makromolekyylejä pilkkovia entsyymejä ja jonka pH on noin 5.",
  "Lysosomeja on vain eläinsoluissa. Ne sisältävät makromolekyylejä pilkkovia entsyymejä, ja niiden kalvo suojaa solua entsyymien vaikutukselta. Lysosomin pH on noin 5, selvästi alempi kuin soluliman noin 7, ja lysosomin entsyymit toimivat parhaiten juuri happamassa, joten solulimaan vuotanut entsyymi on lähes toimeton. Kun makromolekyyli on hajotettu monomeereikseen, ne pääsevät lysosomin kalvon läpi solun käyttöön. Lysosomi hoitaa autofagian ja fagosytoosin hajotusvaiheen.",
  3, L('lysosomi')),
K("Mitä autofagia tarkoittaa?",
  "Solun omien soluelinten, kuten kuluneiden mitokondrioiden, hajotusta lysosomissa.",
  "Autofagiassa solu hajottaa omia rakenteitaan. Kulunut soluelin, kuten mitokondrio, suljetaan endoplasmisesta kalvostosta peräisin olevan kalvon sisään autofagosomiksi, joka fuusioituu lysosomiin. Lysosomin entsyymit pilkkovat sisällön monomeereiksi, jotka solu käyttää uudelleen. Autofagia kierrättää rakennusaineita, poistaa vaurioituneita soluelimiä ja auttaa solua selviämään nälästä. Kuvassa vasemmalla autofagia, oikealla fagosytoosi.",
  2, L('autofagia', ['autofagosomi', 'autofagosomin', 'autofagosomia', 'autofagosomit']), 'solu3_autofagia.jpg'),
K("Mitä fagosytoosi tarkoittaa?",
  "Solusyöntiä: solu ottaa sisäänsä pieniä partikkeleja, kuten bakteereja, kalvorakkulaan ja hajottaa ne lysosomissa.",
  "Fagosytoosi on endosytoosin muoto, jossa solu ottaa sisäänsä pieniä partikkeleja, kuten bakteereja. Solukalvo kietoutuu partikkelin ympärille ja kuroutuu fagosomiksi, joka fuusioituu lysosomiin fagolysosomiksi, ja lysosomin entsyymit hajottavat sisällön. Esimerkiksi makrofagit, valkosolut, tuhoavat näin bakteereja. Fagosytoosi on myös yksisoluisten eliöiden, kuten ameebojen, tapa syödä. Kutsutaan myös: solusyönti.",
  3, L('fagosytoosi', ['solusyönti', 'solusyönnin', 'solusyöntiä', 'fagosomi', 'fagosomin', 'fagosomia', 'fagosomit', 'fagolysosomi', 'fagolysosomin'])),
K("Mikä on kasvisolun vakuoli?",
  "Suuri kalvorakkula, joka hajottaa aineita, varastoi pigmenttejä ja pitää kasvin pystyssä osmoottisella paineella.",
  "Kasvisolun vakuoli on lysosomin vastine: siellä tapahtuvat hajottavat reaktiot. Se on myös pigmenttien sijoituspaikka, ja kukkien värit syntyvät vakuolin väriaineista. Tärkein tehtävä on mekaaninen: vakuoli ottaa osmoottisesti vettä ja ylläpitää kasvisolun sisäistä painetta, joka painaa solukalvoa soluseinää vasten ja pitää kasvin pystyssä. Kuihtuminen on tämän paineen katoamista. Vakuoli voi täyttää yli 90 prosenttia kasvisolun tilavuudesta.",
  3, L('vakuoli')),
K("Mikä on peroksisomi?",
  "Soluelin, jossa vetyperoksidia tuottavat hajotusreaktiot tapahtuvat ja katalaasi hajottaa vetyperoksidin vedeksi ja hapeksi.",
  "Jotkut hajotusreaktiot, kuten pitkien rasvahappojen hapetus, tuottavat vetyperoksidia H<sub>2</sub>O<sub>2</sub>, joka olisi solussa erittäin vahingollinen hapetin. Siksi nämä reaktiot on eristetty peroksisomeihin, joissa katalaasi-entsyymi hajottaa vetyperoksidin heti hapeksi ja vedeksi. Kasveissa on peroksisomeja, jotka sisältävät glyoksylaattisyklin entsyymejä, ja niitä kutsutaan glyoksisomeiksi. Lysosomeja, peroksisomeja ja glyoksisomeja kutsutaan yhteisnimellä mikrobodit.",
  3, L('peroksisomi', 'glyoksisomi', ['katalaasi', 'katalaasin', 'katalaasia', 'katalaasientsyymi', 'mikrobodi', 'mikrobodin', 'mikrobodit', 'mikrobodeja', 'mikrobodeiksi'])),
# ── tuma ───────────────────────────────────────────────────────────────────────────────
K("Millainen on tuman rakenne?",
  "Kaksinkertaisen kalvon rajaama, endoplasmiseen kalvostoon yhteydessä oleva tila, jonka täyttää kromatiini ja jossa on tumajyvänen.",
  "Tumaa rajoittaa kaksinkertainen kalvo, tumakotelo, joka on yhteydessä endoplasmiseen kalvostoon ja jonka läpäisevät tumahuokoset. Kun solu ei ole jakautumassa, tuman täyttää DNA:sta ja proteiineista koostuva kromatiini. Tumassa on lisäksi tumajyvänen, jossa syntetisoidaan ribosomaalista RNA:ta ja kootaan ribosomien osat. Tuman sisällä tapahtuvat DNA:n replikaatio ja transkriptio, ja lähetti-RNA kulkee huokosten kautta solulimaan translaatioon.",
  3),
K("Mikä on tumajyvänen?",
  "Tuman alue, jossa syntetisoidaan ribosomaalista RNA:ta ja kootaan ribosomin alayksiköt.",
  "",
  3, L('tumajyvänen', ['tumajyväsen', 'tumajyvästä', 'tumajyväsessä', 'tumajyväset', 'nukleolus', 'nukleoluksen'])),
K("Mikä on tumahuokonen?",
  "Tumakotelon läpäisevä, proteiineista koostuva monimutkainen rakenne, jonka aukko on noin 90 nm.",
  "Tumakotelossa on tumahuokosia, joissa on proteiineista koostuva monimutkainen rakenne ja noin 90 nm halkaisijainen aukko. Huokosen kautta lähetti-RNA ja ribosomin osat kulkevat tumasta solulimaan ja tumaan menevät proteiinit, kuten histonit ja polymeraasit, solulimasta tumaan. Pienet molekyylit diffundoituvat vapaasti, mutta suurten kuljetus on valikoivaa ja vaatii tunnistussignaalin. Kutsutaan myös: tumahuokoskompleksi.",
  2, L('tumahuokonen', ['tumahuokosen', 'tumahuokosta', 'tumahuokosessa', 'tumahuokoset', 'tumahuokosten', 'tumahuokosia', 'tumahuokoskompleksi', 'tumahuokoskompleksin'])),
K("Mitä mitoosissa tapahtuu?",
  "Kahdentunut DNA pakkautuu kromosomeiksi, tumakotelo hajoaa ja tumasukkula vetää sisarkromatidit solun eri päihin.",
  "Mitoosi on tuman jakautuminen, joka edeltää solun jakautumista eli sytokineesiä. Ennen mitoosia solun DNA on kahdentunut. Mitoosin alkaessa se pakkaantuu tiiviiksi kromosomeiksi, joissa on kaksi identtistä kromatidia, ja tumakotelo hajoaa. Sisarkromatidit erkanevat toisistaan tumasukkulan mikrotubulusten vetäminä ja kulkeutuvat solun eri päihin, minkä jälkeen kummankin ympärille muodostuu uusi tumakotelo. Tuloksena on kaksi tumaa, joissa on sama perimä.",
  3, L('mitoosi', ['sytokineesi', 'sytokineesin', 'sytokineesiä', 'sytokineesissä', 'tumasukkula', 'tumasukkulan', 'tumasukkulaa', 'sisarkromatidi', 'sisarkromatidin', 'sisarkromatidit', 'sisarkromatidien', 'kromatidi', 'kromatidin', 'kromatidia', 'kromatidit'])),
K("Miten DNA pakataan tumaan?",
  "Negatiivinen DNA kiertyy positiivisten histonien ympärille nukleosomeiksi, jotka järjestyvät kromatiinikuiduiksi.",
  "DNA on fosfaattiryhmiensä vuoksi negatiivisesti varautunut, ja se kiertyy positiivisesti varattujen histoniproteiinien ympärille noin suhteessa 1:1. Histoni-DNA-kompleksi organisoituu nukleosomeiksi, helminauhaksi, joka kiertyy edelleen kromatiinikuiduiksi ja mitoosissa tiiviiksi kromosomeiksi. Pakkaus on välttämätön: ihmissolussa on kaksi metriä DNA:ta, mutta kromosomien yhteenlaskettu pituus on vain noin 200 mikrometriä.",
  3, L('nukleosomi')),
K("Mitä tarkoittavat diploidi ja haploidi solu?",
  "Diploidissa solussa kutakin kromosomia on kaksi, haploidissa sukusolussa vain yksi.",
  "Kromosomien lukumäärä ja muoto on lajityypillinen ominaisuus: ihmisellä on 46 kromosomia, simpanssilla 48. Useimmissa soluissa kutakin kromosomia on kaksi kappaletta, toinen äidiltä ja toinen isältä, ja solu on diploidi. Sukusoluissa kutakin kromosomia on vain yksi, ja solu on haploidi. Hedelmöityksessä kaksi haploidia sukusolua yhdistyy diploidiksi tsygootiksi, ja haploidit sukusolut syntyvät meioosissa.",
  3, L(['diploidi', 'diploidin', 'diploidia', 'diploidissa', 'diploidit', 'diploidinen', 'haploidi', 'haploidin', 'haploidia', 'haploidissa', 'haploidit', 'haploidinen'])),
K("Montako kromosomia ihmisellä ja simpanssilla on?",
  "Ihmisellä 46, simpanssilla 48.",
  "",
  1),
# ── mitokondriot ja kloroplastit ───────────────────────────────────────────────────────
K("Millainen on mitokondrion rakenne?",
  "Kaksinkertainen kalvo: tasainen ulkokalvo ja poimuttunut sisäkalvo, jonka kristat ympäröivät proteiinirikasta matriksia.",
  "Mitokondrio on kaksinkertaisesta kalvosta muodostuva soluelin, muodoltaan vaihteleva ja halkaisijaltaan tyypillisesti noin mikrometrin. Ulkokalvo on tasainen, mutta sisäkalvo muodostaa kristoiksi kutsuttuja poimuja, jotka lisäävät sen pinta-alaa ja joissa hengitysketju ja ATP-syntaasi sijaitsevat. Kalvojen välissä on kalvojenvälinen tila. Sisäkalvon sisäpuolella oleva aines on matriksi, joka sisältää runsaasti proteiineja, aineenvaihdunnan välituotteita, mitokondrion oman DNA:n ja ribosomit.",
  3, L('krista', 'matriksi', ['ulkokalvo', 'ulkokalvon', 'ulkokalvoa', 'sisäkalvo', 'sisäkalvon', 'sisäkalvoa', 'sisäkalvossa', 'kalvojenvälinen tila', 'kalvojenvälisen tilan', 'kalvojenvälistä tilaa', 'kalvojenvälisessä tilassa']), 'solu3_mitokondrio.jpg'),
K("Mitä mitokondriot tekevät aerobisessa solussa?",
  "Hapettavat ravintoaineita hapen avulla ja tuottavat hiilidioksidia, vettä ja ATP:ta eli suurimman osan solun energiasta.",
  "Mitokondriot tuottavat suurimman osan aerobisen solun energiasta. Ne hapettavat ravintoaineita, kuten sokereiden ja rasvahappojen hajoamistuotteita, solulimasta diffundoituvan hapen avulla ja tuottavat hiilidioksidia, vettä ja ATP:ta. Sitruunahappokierto tapahtuu matriksissa, ja hengitysketju sisäkalvon kristoissa pumppaa protoneja kalvojenväliseen tilaan, mistä ATP-syntaasi ottaa energian ATP:n valmistukseen. Mitokondrio on endosymbioosissa soluun tulleen bakteerin jälkeläinen.",
  3),
K("Mitä kloroplastit tekevät?",
  "Ottavat talteen auringon energiaa ja tuottavat ATP:ta, pelkistyneitä hiiliyhdisteitä hiilidioksidista ja happea.",
  "Kasvit sisältävät mitokondrioiden ohella kloroplasteja, jotka muuttavat aurinkoenergiaa kemialliseksi energiaksi. Kloroplastit ottavat talteen auringon fotoneja ja tuottavat niiden energialla ATP:ta solun käyttöön, pelkistävät hiilidioksidia sokereiksi ja vapauttavat sivutuotteena happea. Kloroplastin vihreä väri tulee klorofyllistä, tärkeimmästä fotosynteettisestä pigmentistä, joka absorboi punaista ja sinistä valoa ja heijastaa vihreää.",
  3),
K("Millainen on kloroplastin rakenne?",
  "Kaksoiskalvo, jonka sisällä on strooma ja siinä tylakoidit eli yhteyttämiskalvosto, jonka sisällä on luumen.",
  "Kloroplastilla on mitokondrion tapaan kaksoiskalvo, jonka sisällä on stroomaksi kutsuttu tila. Stroomassa ovat hiilidioksidin sitomisen entsyymit, kloroplastin oma DNA ja ribosomit. Strooman sisällä ovat tylakoidit eli yhteyttämiskalvosto, litteät kalvopussit, joiden kalvoissa ovat klorofylliä sisältävät fotosysteemit ja joissa fotosynteesin valoreaktiot tapahtuvat. Tylakoidien sisällä on vielä luumen, johon valoreaktiot pumppaavat protoneja.",
  3, L('strooma', 'tylakoidi', ['yhteyttämiskalvosto', 'yhteyttämiskalvoston', 'yhteyttämiskalvostoa', 'yhteyttämiskalvostossa', 'luumen', 'luumenin', 'luumenia', 'luumenissa']), 'solu3_kloroplasti.png'),
K("Mikä on klorofylli?",
  "Kloroplastin tärkein fotosynteettinen pigmentti, joka antaa kasveille vihreän värin ja absorboi valon energian.",
  "Klorofylli a on kasvien ja kloroplastien vihreän värin lähde ja tärkein fotosynteettinen pigmentti. Sen rengasmainen porfyriinirakenne, jonka keskellä on magnesiumioni, absorboi punaista ja sinistä valoa ja heijastaa vihreää. Absorboitu fotonin energia virittää klorofyllin elektronin, ja viritysenergia siirtyy tylakoidikalvon fotosysteemeissä reaktiokeskukseen, jossa se käynnistää elektroninsiirtoketjun. Pitkä hiilivetyhäntä ankkuroi klorofyllin kalvoon.",
  3, L('klorofylli')),
# ── solulima ja tukiranka ─────────────────────────────────────────────────────────────
K("Millainen ympäristö solulima on?",
  "Ruuhkainen, järjestäytynyt ja dynaaminen liuos, jossa on runsaasti makromolekyylejä ja reaktioiden aineita.",
  "Solulima on ruuhkainen, järjestäytynyt ja dynaaminen. Siinä on runsaasti liuenneita aineita, makromolekyylejä sekä reaktioiden lähtöaineita ja tuotteita, niin tiheästi, että molekyylit törmäilevät jatkuvasti. Prokaryooteilla pelkkä lämpöliike riittää solun biokemialliseen toimintaan, koska matkat ovat lyhyitä. Eukaryoottisolu on paljon suurempi, joten kaikilla eukaryooteilla ja joillain arkeoneilla on lisäksi solun tukiranka, joka järjestää ja kuljettaa aineita.",
  2),
K("Mikä on solun tukiranka?",
  "Proteiinikuiduista koostuva sisäinen verkosto, joka tukee solun rakennetta ja järjestää ja liikuttaa aineita.",
  "Solun tukirangan tehtävä on tukea solun rakennetta sekä järjestää ja liikuttaa aineita paikkoihin, joissa niitä tarvitaan. Eukaryoottisolussa ja joillain arkeoneilla on useista erilaisista proteiinikuiduista koostuva sisäinen tukiverkosto. Kuituja on kolmea tyyppiä: mikrotubulukset, välikokoiset säikeet ja aktiinikuidut. Kukin koostuu samankaltaisista proteiinialayksiköistä, joista kasaantuu dynaamisesti tasapaksuja kuituja, jotka voivat purkautua ja rakentua uudelleen tarpeen mukaan. Kutsutaan myös: sytoskeleton.",
  3, L(['solun tukiranka', 'solun tukirangan', 'solun tukirankaa', 'solun tukirangassa', 'tukiranka', 'tukirangan', 'tukirankaa', 'tukirangassa', 'tukirangasta', 'tukirankaan', 'sytoskeleton', 'sytoskeletonin'])),
K("Mitkä ovat tukirangan kolme kuitutyyppiä ja niiden paksuudet?",
  "Mikrotubulukset 25 nm, välikokoiset säikeet 10 nm ja mikrofilamentit eli aktiinikuidut 5–9 nm.",
  "Mikrotubulukset ovat paksuimpia, 25 nm, tubuliinista koostuvia onttoja putkia, joita pitkin kinesiini ja dyneiini kuljettavat rahtia. Välikokoiset säikeet, 10 nm, ovat kestäviä köysiä, jotka tukevat solun muotoa. Mikrofilamentit eli aktiinikuidut, 5–9 nm, ovat ohuimpia ja mahdollistavat solun muodonmuutokset ja liikkeen. Kuvassa fluoresenssivärjätty solu: aktiini punaisena, mikrotubulukset vihreinä ja tuma sinisenä.",
  3, '', 'solu3_tukiranka.jpg'),
K("Mikä on mikrotubulus?",
  "Tubuliiniyksiköistä koostuva 25 nm paksu ontto putki, jota pitkin kinesiini ja dyneiini liikuttavat rahtia.",
  "Mikrotubulukset koostuvat tubuliiniyksiköistä, jotka liittyvät toisiinsa onttoja putkia muodostaen. Ne ovat tukirangan paksuimpia kuituja ja polaarisia: toinen pää on plus-pää, jossa kasvu on nopeaa, ja toinen miinus-pää. Mikrotubulukset toimivat kiskoina, joita pitkin moottoriproteiinit kinesiini ja dyneiini kuljettavat rakkuloita, soluelimiä ja RNA:ta. Ne muodostavat myös tumasukkulan, joka vetää kromosomit erilleen mitoosissa, sekä värekarvojen ja siimojen rungon.",
  3, L('mikrotubulus', 'tubuliini')),
K("Mitä kinesiini ja dyneiini tekevät?",
  "Kuljettavat rahtia ATP:n voimalla mikrotubuluksia pitkin: kinesiini kohti plus-päätä, dyneiini kohti miinus-päätä.",
  "Kinesiini ja dyneiini ovat moottoriproteiineja, jotka liikuttavat ATP:n voimalla mikrotubuluksia pitkin vesikkeleitä ja soluelimiä, proteiineja ja proteiinikomplekseja, RNA:ta ja muita mikrotubuluksia. Kinesiini liikkuu kohti mikrotubuluksen plus-päätä eli tyypillisesti solun reunoille, dyneiini kohti miinus-päätä eli solun keskustaan. Kummallakin on kaksi päädomeenia, jotka tarttuvat vuorotellen kiskoon kuin jalat, ja häntä, joka sitoo rahdin. Kuvassa dyneiini vasemmalla ja kinesiini oikealla.",
  3, L('kinesiini', 'dyneiini', ['moottoriproteiini', 'moottoriproteiinin', 'moottoriproteiinia', 'moottoriproteiinit', 'moottoriproteiinien']), 'solu3_kinesiini.png'),
K("Mitä ovat välikokoiset säikeet?",
  "10 nm paksut, rakenteeltaan vaihtelevat tukirangan kuidut, jotka lisäävät solun kestävyyttä ulkoisia voimia vastaan.",
  "Välikokoiset säikeet ovat rakenteeltaan ja toiminnaltaan hyvin vaihteleva ryhmä, jonka tehtävänä on tukea solun rakenteita ja lisätä solun kestävyyttä ulkoisia voimia vastaan. Ne ovat köysimäisiä ja kestävät venytystä paremmin kuin muut kuidut. Keratiinit muodostavat hiukset ja kynnet ja vahvistavat ihon epiteelisoluja. Vimentiini muodostaa solulimaan pysyviä säikeitä, jotka tukevat solun muotoa. Tumakotelon sisäpintaa tukevat laminit ovat myös välikokoisia säikeitä.",
  2, L(['välikokoiset säikeet', 'välikokoisten säikeiden', 'välikokoisia säikeitä', 'välikokoinen säie', 'välikokoisen säikeen', 'vimentiini', 'vimentiinin', 'vimentiiniä'])),
K("Mikä on mikrofilamentti?",
  "Aktiiniproteiinista kasaantuva 5–9 nm paksu tukirangan kuitu, jota pitkin myosiini liikuttaa kohteita.",
  "Mikrofilamentit eli aktiinikuidut kasaantuvat aktiini-nimisestä proteiinista, jota on myös lihassäikeissä. Ne ovat tukirangan ohuimpia kuituja ja keskittyvät solukalvon alle, jossa ne määräävät solun muodon ja mahdollistavat sen liikkeen ja jakautumisen kuroutumisen. Filamiini sitoo aktiinikuituja ristiin 90 asteen kulmassa verkoksi, ja fodriini sitoo niitä pitkittäin yhteen ja ankkuroi ne mikrotubuluksiin, solukalvoon ja tumakoteloon. Kutsutaan myös: aktiinikuitu, aktiinisäie.",
  3, L('mikrofilamentti', 'aktiini', ['aktiinikuitu', 'aktiinikuidun', 'aktiinikuitua', 'aktiinikuidut', 'aktiinikuitujen', 'aktiinikuituja', 'aktiinisäie', 'aktiinisäikeen', 'aktiinisäikeet', 'aktiinisäikeitä', 'filamiini', 'filamiinin', 'fodriini', 'fodriinin'])),
K("Mikä on myosiini?",
  "Moottoriproteiini, joka liikuttaa kohteita aktiinikuituja pitkin ja tuottaa lihassupistuksen.",
  "Myosiiniproteiinit mahdollistavat kohteiden, kuten soluelinten, liikuttamisen mikrofilamentteja pitkin ATP:n energialla, samaan tapaan kuin kinesiini mikrotubuluksia pitkin. Aktiinin ja myosiinin vuorovaikutus mahdollistaa myös lihasten toiminnan: lihassolussa myosiinipäät vetävät aktiinisäikeitä lomittain, jolloin lihas supistuu. Myosiineja on 18 proteiiniperhettä, jotka eroavat rakenteeltaan ja liikkeen suunnalta aktiinikuidun plus- tai miinus-päähän.",
  3, L('myosiini')),
# ── endosytoosi ja eksosytoosi ─────────────────────────────────────────────────────────
K("Mitä endosytoosi tarkoittaa?",
  "Materiaalin ottamista soluun solukalvosta kuroutuvan rakkulan, endosomin, sisällä ilman, että materiaali kulkee kalvon läpi.",
  "Endosytoosissa sisäänotettava materiaali päätyy solukalvosta kuroutuvan vesikkelin eli endosomin sisään. Materiaali ei kulje solukalvon läpi vaan jää kalvon rajaamaan rakkulaan, joka kuljetetaan solun sisään ja voidaan fuusioida toisen kalvorakkulan, kuten lysosomin, kanssa. Endosytoosi voi olla ei-spesifistä nesteen nielemistä tai spesifistä, reseptorivälitteistä, kuten klatriinimekanismi. Fagosytoosi on endosytoosia, jossa otetaan sisään partikkeleja.",
  3, L('endosytoosi', ['endosomi', 'endosomin', 'endosomia', 'endosomissa', 'endosomit'])),
K("Miten klatriinivälitteinen endosytoosi toimii?",
  "Klatriiniproteiinit kertyvät solukalvon sisäpinnalle, taivuttavat kalvon otettavan aineen ympärille ja rakkula kuroutuu irti.",
  "Reseptorit sitovat solun ulkopuolisen ligandin, ja klatriiniproteiinit kertyvät adaptoriproteiinien avulla solukalvon sisäpinnalle reseptorien kohdalle. Klatriini muodostaa verkkomaisen kuoren, joka deformoi solukalvon endosytoitavan materiaalin ympärille kuopaksi. Dynamiini kuroo klatriinin peittämän rakkulan irti kalvosta, ja se otetaan solun sisään, minkä jälkeen klatriinikuori puretaan. Mekanismi on spesifinen eli reseptorivälitteinen. Kuvassa vaiheet kaaviona ja elektronimikroskooppikuvina.",
  2, L('klatriini', ['klatriinivälitteinen endosytoosi', 'klatriinivälitteisen endosytoosin', 'klatriinivälitteistä endosytoosia', 'reseptorivälitteinen endosytoosi', 'reseptorivälitteisen endosytoosin', 'reseptorivälitteistä endosytoosia', 'dynamiini', 'dynamiinin']), 'solu3_klatriini.jpg'),
K("Mitä eksosytoosi tarkoittaa?",
  "Solun sisältä tulevan kalvorakkulan sulautumista solukalvoon, jolloin sen sisältö vapautuu solun ulkopuolelle.",
  "Eksosytoosissa solun sisältä tuleva kalvorakkula sulautuu solukalvon kanssa ja vapauttaa sisältönsä solun ulkopuolelle. Näin solu erittää suuria molekyylejä, proteiineja, hormoneja ja jäteaineita, ja rakkulan kalvon proteiinit päätyvät solukalvolle. Eksosytoosi voi olla jatkuvaa, kuten kalvon uusiutuminen, tai säädeltyä, kuten hermovälittäjäaineiden vapautus, jonka laukaisee kalsiumsignaali. Endosytoosi ja eksosytoosi pitävät yhdessä solukalvon pinta-alan vakiona.",
  3, L('eksosytoosi')),
]
