# -*- coding: utf-8 -*-
"""Solu- ja biomolekyylit, Luento 2 - Vesi: sanaston taydennys (numerot 2.201-). Rakentaa tyokalut/solu_kortit.py."""
from biotek_taivutus import L
from pakka_rakenna import K

LEHTI = 'Luento 2 - Vesi'
TIEDOSTO = 'Luento 2 - Sanasto (lisays)'
NRO = 2
ALKU = 200
KUVAT = {}

KORTIT = [
K("Mikä on emäs?",
  "Aine, joka vastaanottaa protonin tai luovuttaa vedessä hydroksidi-ioneja.",
  "Brønstedin määritelmän mukaan emäs on protonin vastaanottaja: ammoniakki sitoo protonin ammoniumioniksi ja karboksylaatti karboksyylihapoksi. Arrheniuksen vanhemman määritelmän mukaan emäs tuottaa veteen hydroksidi-ioneja, kuten natriumhydroksidi. Vahva emäs, kuten NaOH, on vedessä kokonaan ioneina, heikko emäs, kuten ammoniakki, vain osittain. Emäs nostaa liuoksen pH:ta ja neutraloi happoja. Kutsutaan myös: alkalinen aine.",
  3, L(['emäs', 'emäksen', 'emästä', 'emäksessä', 'emäksestä', 'emäkseen', 'emäkseksi', 'emäksellä', 'emäkset', 'emästen', 'emäksiä', 'emäksissä', 'emäksinen', 'emäksisen', 'emäksistä', 'emäksisessä', 'emäksiset', 'alkalinen', 'alkalisen', 'alkalista', 'alkalisessa', 'alkaliset'])),
K("Mikä on vahva happo?",
  "Happo, joka dissosioituu vedessä käytännössä kokonaan, kuten suolahappo tai rikkihappo.",
  "Vahva happo luovuttaa protoninsa vedelle täydellisesti: suolahappo HCl on vesiliuoksessa kokonaan oksoniumioneina ja kloridi-ioneina, eikä dissosioitumatonta happoa ole jäljellä. Siksi vahvan hapon liuoksen vetyionipitoisuus on sama kuin hapon pitoisuus ja pH lasketaan suoraan siitä. Vahvoja happoja ovat suolahappo, rikkihappo, typpihappo ja perkloorihappo. Heikko happo dissosioituu vain osittain ja asettuu tasapainoon.",
  3, L(['vahva happo', 'vahvan hapon', 'vahvaa happoa', 'vahvassa hapossa', 'vahvat hapot', 'vahvojen happojen', 'vahvoja happoja', 'suolahappo', 'suolahapon', 'suolahappoa', 'rikkihappo', 'rikkihapon', 'rikkihappoa'])),
K("Mitä neutralointi tarkoittaa?",
  "Hapon ja emäksen reaktiota, jossa vetyionit ja hydroksidi-ionit yhtyvät vedeksi ja syntyy suola.",
  "Neutraloinnissa happo ja emäs kumoavat toisensa: hapon vetyionit ja emäksen hydroksidi-ionit muodostavat vettä, ja jäljelle jäävät ionit muodostavat suolan. Suolahappo ja natriumhydroksidi tuottavat vettä ja natriumkloridia. Kun happo ja emäs on lisätty täsmälleen ekvivalentteina määrinä, liuos on neutraloitu, mihin titraus perustuu. Elimistössä puskurit neutraloivat aineenvaihdunnan happoja ennen kuin pH ehtii muuttua. Kutsutaan myös: neutralisaatio.",
  3, L('neutralointi', ['neutralisaatio', 'neutralisaation', 'neutralisaatiota', 'neutraloida', 'neutraloi', 'neutraloivat', 'neutraloituu', 'neutraloitu', 'neutraali', 'neutraalin', 'neutraalia', 'neutraalissa'])),
K("Mikä on suola?",
  "Ioniyhdiste, joka syntyy hapon ja emäksen neutraloinnissa, kuten natriumkloridi.",
  "Suola koostuu kationeista ja anioneista, jotka pysyvät kiteessä yhdessä ionisidoksin. Se syntyy, kun hapon protoni korvautuu metalli-ionilla tai muulla kationilla: natriumkloridi on suolahapon ja natriumhydroksidin suola, natriumfosfaatti fosforihapon. Vedessä suola liukenee ioneiksi, jotka vesimolekyylit ympäröivät hydraatiokuoreksi, ja liuos johtaa sähköä. Elimistön suolat, kuten natrium-, kalium- ja kloridi-ionit, ylläpitävät osmoottista tasapainoa ja hermoimpulsseja.",
  3, L('suola', ['natriumkloridi', 'natriumkloridin', 'natriumkloridia', 'suolaliuos', 'suolaliuoksen', 'suolaliuosta', 'suolaliuoksessa'])),
K("Mikä on konsentraatio?",
  "Liuenneen aineen määrä liuoksen tilavuutta kohti, tavallisesti mooleina litrassa.",
  "Konsentraatio eli pitoisuus kertoo, kuinka paljon ainetta on tietyssä tilavuudessa liuosta. Biokemiassa käytetään molaarisuutta, mol/ℓ eli M: yhden molaarinen liuos sisältää yhden moolin ainetta litrassa. Solun aineiden pitoisuudet ovat usein millimoolien tai mikromoolien luokkaa. Konsentraatio määrää reaktionopeuden, tasapainon aseman ja osmoottisen paineen, ja hakasulkeet, kuten [H<sup>+</sup>], tarkoittavat aineen konsentraatiota. Kutsutaan myös: pitoisuus, molaarisuus.",
  3, L('konsentraatio', 'pitoisuus', ['molaarisuus', 'molaarisuuden', 'molaarisuutta', 'molaarinen', 'molaarisen', 'molaarista'])),
K("Mikä on liuos?",
  "Homogeeninen seos, jossa liuennut aine on jakautunut molekyyleinä tai ioneina liuottimeen.",
  "Liuoksessa liuennut aine, kuten suola tai sokeri, on hajonnut yksittäisiksi molekyyleiksi tai ioneiksi liuottimeen, tavallisesti veteen, niin että seos on tasalaatuinen eikä hiukkasia erota. Vesiliuoksessa liuotin on vesi, ja solulima on monimutkainen vesiliuos. Aine liukenee, jos sen vuorovaikutukset liuottimen kanssa ovat riittävän vahvat: poolinen liukenee pooliseen, pooliton poolittomaan. Liukoisuus kertoo, paljonko ainetta liuotin enintään ottaa.",
  3, L(['liuos', 'liuoksen', 'liuosta', 'liuoksessa', 'liuoksesta', 'liuokseen', 'liuokseksi', 'liuokset', 'liuosten', 'liuoksia', 'liuoksissa', 'liuotin', 'liuottimen', 'liuotinta', 'liuottimessa', 'liuottimesta', 'liuottimeen', 'liuottimet', 'liuottimien', 'liuottimia', 'vesiliuos', 'vesiliuoksen', 'vesiliuosta', 'vesiliuoksessa', 'vesiliuoksesta', 'vesiliuokset', 'liuennut aine', 'liuenneen aineen', 'liuennutta ainetta', 'liukoisuus', 'liukoisuuden', 'liukoisuutta', 'vesiliukoinen', 'vesiliukoisen', 'vesiliukoista', 'vesiliukoisia', 'vesiliukoiset', 'vesiliukoisuus'])),
K("Mikä on olomuoto?",
  "Aineen tila kiinteänä, nesteenä tai kaasuna, jonka lämpötila ja paine määräävät.",
  "Kiinteässä olomuodossa hiukkaset ovat paikoillaan säännöllisessä järjestyksessä, nesteessä ne liikkuvat toistensa ohi mutta pysyvät koossa, ja kaasussa ne liikkuvat vapaasti. Olomuoto vaihtuu sulamis- ja kiehumispisteessä, kun lämpöliike voittaa hiukkasten väliset vetovoimat. Vesi on poikkeuksellinen: jää kelluu, koska vetysidosverkosto tekee kiinteästä muodosta nestettä harvemman. Kutsutaan myös: faasi.",
  2, L('olomuoto', ['faasi', 'faasin', 'faasia', 'faasissa', 'faasit', 'nestefaasi', 'nestefaasin', 'kiinteä olomuoto', 'kiinteän olomuodon', 'kaasu', 'kaasun', 'kaasua', 'kaasut', 'neste', 'nesteen', 'nestettä', 'nesteet'])),
K("Mikä on kiehumispiste?",
  "Lämpötila, jossa nesteen höyrynpaine on yhtä suuri kuin ulkoinen paine ja neste alkaa kiehua.",
  "Kiehumispisteessä nesteen molekyylit saavat riittävästi energiaa irrotakseen toisistaan kaikkialla nesteessä, ei vain pinnalta. Se riippuu molekyylien välisten voimien vahvuudesta: veden kiehumispiste 100 °C on molekyylin kokoon nähden hyvin korkea, koska vetysidokset pitävät molekyylit yhdessä. Rikkivety, jossa vetysidoksia ei ole, kiehuu −60 °C:ssa. Korkea kiehumispiste pitää veden nestemäisenä elämän lämpötiloissa.",
  2, L('kiehumispiste', ['höyrynpaine', 'höyrynpaineen', 'höyrynpainetta'])),
K("Mikä on sulamispiste?",
  "Lämpötila, jossa kiinteä aine muuttuu nesteeksi.",
  "",
  2, L('sulamispiste', ['jäätymispiste', 'jäätymispisteen', 'jäätymispistettä'])),
K("Mitä lämpöliike on?",
  "Molekyylien jatkuvaa satunnaista liikettä, jonka voimakkuus riippuu lämpötilasta.",
  "Kaikki molekyylit värähtelevät, pyörivät ja liikkuvat satunnaisesti, ja tämän liikkeen keskimääräinen energia on suoraan verrannollinen lämpötilaan. Lämpöliike sekoittaa liuokset diffuusiolla, rikkoo heikkoja sidoksia ja antaa törmääville molekyyleille energian reagoida. Se katkoo vetysidoksia vedessä, joten verkosto on jatkuvassa muutoksessa. Prokaryootin pienessä solussa lämpöliike riittää kuljettamaan aineet, eukaryootti tarvitsee lisäksi tukirangan. Kutsutaan myös: Brownin liike.",
  2, L('lämpöliike', ['Brownin liike', 'Brownin liikkeen', 'Brownin liikettä', 'diffuusio', 'diffuusion', 'diffuusiota', 'diffuusiossa', 'diffundoitua', 'diffundoituu', 'diffundoituvat'])),
K("Mikä on osittaisvaraus?",
  "Poolisen sidoksen atomille syntyvä osittainen sähkövaraus, jota merkitään δ+ tai δ−.",
  "Kun kaksi elektronegatiivisuudeltaan erilaista atomia jakaa elektroniparin, elektronit viettävät enemmän aikaa elektronegatiivisemman atomin luona. Se saa pienen negatiivisen osittaisvarauksen δ− ja toinen atomi positiivisen δ+. Vedessä hapella on δ− ja vedyillä δ+, mikä tekee molekyylistä dipolin ja mahdollistaa vetysidokset. Osittaisvaraukset ovat pienempiä kuin ionin kokonainen varaus, mutta ne ohjaavat molekyylien tunnistamista ja sitoutumista.",
  3, L('osittaisvaraus', ['sähkövaraus', 'sähkövarauksen', 'sähkövarausta', 'sähkövaraukset', 'varaus', 'varauksen', 'varausta', 'varaukset', 'varausten'])),
K("Mikä on histidiini?",
  "Aminohappo, jonka imidatsolisivuketjun pK<sub>a</sub> on lähellä 7, joten se toimii happo-emäskatalyyttinä.",
  "Histidiinin sivuketju on imidatsolirengas, jonka pK<sub>a</sub> on noin 6–7. Solun pH:ssa osa histidiineistä on protonoituneita ja osa ei, joten sivuketju voi sekä luovuttaa että vastaanottaa protonin. Siksi histidiini on entsyymien aktiivisten keskusten yleisin happo-emäskatalyytti ja hyvä metalli-ionien ligandi: hemoglobiinissa se sitoo hemin raudan, ja hemoglobiinin histidiinit puskuroivat veren pH:ta.",
  2, L('histidiini')),
K("Mikä on hemoglobiini?",
  "Punasolujen proteiini, joka sitoo happea hemiryhmiensä rautaan ja kuljettaa sen keuhkoista kudoksiin.",
  "Hemoglobiini koostuu neljästä alayksiköstä, joissa kussakin on hemi, rautaa sisältävä rengas, joka sitoo yhden happimolekyylin. Alayksiköt vaikuttavat toisiinsa: ensimmäisen hapen sitoutuminen helpottaa seuraavien sitoutumista, joten hemoglobiini ottaa hapen tehokkaasti keuhkoissa ja luovuttaa sen kudoksissa. Hiilidioksidi ja hapan pH heikentävät hapen sitoutumista, mikä ohjaa hapen sinne, missä sitä kulutetaan. Hemoglobiini toimii myös veren puskurina.",
  3, L('hemoglobiini', ['hemi', 'hemin', 'hemiä', 'hemiryhmä', 'hemiryhmän', 'hemiryhmää', 'hemiryhmät'])),
K("Mikä on sytokromi?",
  "Hemiä sisältävä proteiini, joka siirtää elektroneja hengitysketjussa ja fotosynteesissä.",
  "Sytokromit ovat hemiproteiineja, joiden rauta vaihtelee hapetuslukujen +2 ja +3 välillä ja siirtää siten yhden elektronin kerrallaan. Mitokondrion hengitysketjussa sytokromit b, c ja a kuljettavat elektronit hapelle, ja sytokromi c on pieni liukoinen elektroninkuljettaja. Kloroplastin sytokromi b<sub>6</sub>f kytkee fotosysteemit toisiinsa. Sytokromi P450 -entsyymit hapettavat maksassa lääkeaineita ja myrkkyjä.",
  2, L('sytokromi')),
K("Mikä on pepsiini?",
  "Mahalaukun proteaasi, joka toimii parhaiten pH:ssa noin 2.",
  "Pepsiini pilkkoo ruoan proteiineja mahalaukussa. Se erittyy inaktiivisena pepsinogeenina, jonka mahahappo aktivoi, ja sen pH-optimi noin 2 vastaa mahanesteen happamuutta: ohutsuolen emäksisemmässä ympäristössä se lakkaa toimimasta. Pepsiini on esimerkki siitä, että jokaisella entsyymillä on oma pH-optiminsa, jossa sen aktiivisen keskuksen ryhmät ovat oikeassa protonaatiotilassa, ja pH:n muutos pois optimista hidastaa reaktiota jyrkästi.",
  2, L('pepsiini', ['pH-optimi', 'pH-optimin', 'pH-optimia', 'pH-optimit', 'pH-optimissa'])),
K("Mikä on trypsiini?",
  "Haiman erittämä proteaasi, joka toimii ohutsuolessa pH:ssa noin 8 ja pilkkoo lysiinin ja arginiinin jälkeen.",
  "Trypsiini erittyy haimasta inaktiivisena trypsinogeenina ja aktivoituu ohutsuolessa. Sen pH-optimi on noin 8, ohutsuolen emäksinen ympäristö. Trypsiini katkaisee peptidisidoksen aina lysiinin tai arginiinin jälkeen, joten sitä käytetään laboratoriossa proteiinien pilkkomiseen tunnetun kokoisiksi peptideiksi ennen massaspektrometriaa ja solujen irrottamiseen kasvatusalustasta. Nahkateollisuus pehmentää sillä nahkaa, ja haiman tulehduksessa liian aikaisin aktivoitunut trypsiini vaurioittaa haimaa itseään.",
  2, L('trypsiini')),
K("Mikä on fosfataasi?",
  "Entsyymi, joka poistaa fosfaattiryhmän vesikatkaisulla.",
  "Fosfataasi katkaisee fosfaattiesterisidoksen ja irrottaa fosfaattiryhmän substraatistaan, kuten proteiinista tai sokerifosfaatista. Se on kinaasin vastavaikuttaja: kinaasi liittää fosfaatin ja fosfataasi poistaa sen, ja tämä pari säätelee monien entsyymien aktiivisuutta. Alkalinen fosfataasi toimii parhaiten emäksisessä pH:ssa noin 9–10, ja sen määrää veressä mitataan maksan ja luuston sairauksien diagnostiikassa.",
  2, L('fosfataasi', ['kinaasi', 'kinaasin', 'kinaasia', 'kinaasit', 'kinaasien', 'fosforylaatio', 'fosforylaation', 'fosforylaatiota', 'fosforyloida', 'fosforyloitu'])),
K("Mikä on proteaasi?",
  "Entsyymi, joka pilkkoo proteiineja katkaisemalla peptidisidoksia vesikatkaisulla.",
  "Proteaasit katkaisevat peptidisidoksen lisäämällä siihen veden. Ruoansulatuksen proteaasit, kuten pepsiini ja trypsiini, hajottavat ravinnon proteiinit aminohapoiksi. Solun sisällä proteaasit hajottavat vaurioituneet ja tarpeettomat proteiinit, aktivoivat esiasteita katkaisemalla niistä palan ja säätelevät signaaleja. Proteiinien puhdistuksessa solun omat proteaasit ovat uhka, joka torjutaan proteaasi-inhibiittoreilla ja kylmällä. Kutsutaan myös: peptidaasi.",
  3, L('proteaasi', ['peptidaasi', 'peptidaasin', 'peptidaasit', 'proteolyysi', 'proteolyysin', 'proteolyysiä', 'proteolyyttinen', 'proteolyyttisen'])),
]
