# -*- coding: utf-8 -*-
"""Solu- ja biomolekyylit: sanaston toinen kierros (omistaja 12.9.2026: 'paljon viela sanoja joilla ei ole maaritelmakorttia.
tee jokaikisesta sanasta!'). Kalvojen kaikki loput termit, myos esimerkkieliot, historian nimet ja arkisemmat kasitteet.
Listat liitetaan solu_L*_sanasto.py:n KORTIT-listojen jatkoksi, numerointi jatkuu. Ei tuoda sanastomoduuleja (kehatuonti)."""
from biotek_taivutus import L
from pakka_rakenna import K

def N(*forms):   # valmis taivutuslista sellaisenaan
    return list(forms)

L1 = [
K("Mikä on alfaproteobakteeri?",
  "Proteobakteerien ryhmä, johon mitokondrion esi-isä kuului. Rikettsiat ovat sen nykyisiä solunsisäisiä jäseniä.",
  "",
  2, L('alfaproteobakteeri', ['proteobakteeri', 'proteobakteerin', 'proteobakteeria', 'proteobakteerit', 'proteobakteerien', 'proteobakteereja', 'proteobakteereille', 'alfaproteobakteereille'])),
K("Mikä on arkkibakteeri?",
  "Arkeonin vanhempi nimi, kun arkeoneja pidettiin vielä bakteereina. Nykyään ne ovat oma domeeninsa.",
  "",
  1, L('arkkibakteeri')),
K("Mitä astrobiologia on?",
  "Elämän synnyn, esiintymisen ja edellytysten tutkimus maapallon ulkopuolella ja alkumaapallolla.",
  "",
  1, L('astrobiologia', ['astrobiology'])),
K("Mikä on estrogeeni?",
  "Naissukupuolihormoni, kolesterolista tehty steroidi. Esimerkki lipidistä, joka toimii viestimolekyylinä.",
  "",
  2, L('estrogeeni')),
K("Mikä on testosteroni?",
  "Miessukupuolihormoni, kolesterolista tehty steroidi. Esimerkki lipidistä, joka toimii viestimolekyylinä.",
  "",
  2, L('testosteroni')),
K("Mikä on fumaarihappo?",
  "Nelihiilinen dikarboksyylihappo, sitruunahappokierron välituote. Trans-isomeeri, jonka cis-muoto on maleiinihappo.",
  "",
  1, L('fumaarihappo', ['fumaraatti', 'fumaraatin', 'fumaraattia', 'maleiinihappo', 'maleiinihapon', 'maleiinihappoa'])),
K("Mikä on omenahappo?",
  "Nelihiilinen hydroksidikarboksyylihappo, sitruunahappokierron välituote ja omenan hapan maku. Kutsutaan myös: malaatti.",
  "",
  1, L('omenahappo', ['malaatti', 'malaatin', 'malaattia'])),
K("Mikä on etaani?",
  "Kahden hiilen alkaani C<sub>2</sub>H<sub>6</sub>, jonka hiili–hiili-yksöissidoksen ympäri molekyyli pääsee pyörimään vapaasti.",
  "",
  1, L('etaani')),
K("Mikä on hermosignaali?",
  "Hermosolun välittämä viesti: kalvoa pitkin kulkeva sähköinen impulssi ja soluvälissä hermovälittäjäaine.",
  "",
  2, L('hermosignaali', ['hermoimpulssi', 'hermoimpulssin', 'hermoimpulssia', 'hermoimpulssit'])),
K("Mikä on kemo-organoheterotrofi?",
  "Eliö, joka saa energiansa kemiallisista sidoksista, elektroninsa orgaanisista yhdisteistä ja hiilensä orgaanisesta aineesta. Ihminen on tällainen.",
  "Nimi kokoaa kolme ravinnonhankinnan ulottuvuutta. Kemotrofi ottaa energiansa kemiallisista reaktioista, ei valosta kuten fototrofi. Organotrofi käyttää elektronien lähteenä orgaanisia yhdisteitä, litotrofi epäorgaanisia kuten vetyä tai rautaa. Heterotrofi saa hiilensä valmiista orgaanisesta aineesta, autotrofi sitoo sen hiilidioksidista. Eläimet, sienet ja useimmat bakteerit ovat kemo-organoheterotrofeja, kasvit foto-litoautotrofeja. Kutsutaan myös: kemoheterotrofi.",
  2, L('kemo-organoheterotrofi', ['kemoheterotrofi', 'kemoheterotrofin', 'kemoheterotrofit'])),
K("Mikä on kompleksisuus biologiassa?",
  "Rakenteen ja toiminnan monimutkaisuus: elävä olento on hierarkkisesti järjestynyt molekyyleistä eliöön.",
  "",
  1, L('kompleksisuus', ['hierarkia', 'hierarkian', 'hierarkiaa', 'hierarkkinen', 'hierarkkisen', 'hierarkkista', 'hierarkkisesti'])),
K("Mikä on korkkisolu?",
  "Kuollut, korkkiseinäinen kasvisolu. Robert Hooke näki korkin solut mikroskoopilla 1665 ja antoi solulle nimen.",
  "",
  1, L('korkkisolu', ['Hooke', 'Hooken', 'Hookea', 'Robert Hooke', 'Robert Hooken'])),
K("Mikä on levä?",
  "Yhteyttävä, yksinkertainen vesieliö ilman juuria tai lehtiä. Yksisoluinen tai monisoluinen, kasveista erillinen ryhmä.",
  "",
  2, L(N('levä', 'levän', 'levää', 'levässä', 'levästä', 'levään', 'levät', 'levien', 'leviä', 'levissä', 'viherlevä', 'viherlevän', 'viherlevää', 'viherlevät', 'viherlevien', 'viherleviä'))),
K("Mikä on lineaarinen molekyyli?",
  "Suoraketjuinen, haarautumaton molekyyli, kuten lineaarinen polymeeri. Vastakohtia ovat haarautunut ja rengasmainen.",
  "",
  1, L(N('lineaarinen', 'lineaarisen', 'lineaarista', 'lineaariseksi', 'lineaariset', 'lineaarisia', 'lineaarisesti', 'haarautunut', 'haarautuneen', 'haarautunutta', 'haarautuneet', 'haarautuvat', 'rengasmainen', 'rengasmaisen', 'rengasmaista', 'rengasmaiset', 'rengasmaisia', 'renkaanmuotoinen', 'renkaanmuotoisia'))),
K("Mikä on maankuori?",
  "Maapallon uloin kiinteä kerros. Yleisimmät alkuaineet happi, pii ja alumiini, elämässä hiili, vety, happi, typpi.",
  "",
  1, L('maankuori', ['maankuoressa', 'maankuoren'])),
K("Mikä on nitraatti?",
  "Typen hapettunein muoto NO<sub>3</sub><sup>−</sup>, kasvien ja monien mikrobien typenlähde. Ihmiselle nitraatti on hyödytön.",
  "",
  2, L('nitraatti', ['nitraatti-ioni', 'nitraatti-ionin', 'nitraattiioni', 'nitraattiionin'])),
K("Mitä ovat Cahn–Ingold–Prelog-prioriteettisäännöt?",
  "Säännöt, joilla stereokeskuksen substituentit asetetaan tärkeysjärjestykseen atomiluvun mukaan, jotta konfiguraatio voidaan nimetä R:ksi tai S:ksi.",
  "",
  1, L(N('Cahn–Ingold–Prelog', 'Cahn-Ingold-Prelog-säännöt', 'Cahn–Ingold–Prelog-säännöt', 'Cahn-Ingold-Prelog-prioriteettisäännöt', 'prioriteettisäännöt', 'prioriteettisääntöjen', 'prioriteettisääntö', 'prioriteettisäännön', 'CIP-säännöt', 'CIP-sääntöjen', 'R/S-järjestelmä', 'R/S-järjestelmän'))),
K("Mikä on Fischer-projektio?",
  "Tapa piirtää kiraalinen molekyyli tasoon: vaakasidokset osoittavat katsojaa kohti, pystysidokset poispäin.",
  "",
  2, L(N('Fischer-projektio', 'Fischer-projektion', 'Fischer-projektiota', 'Fischer-projektiossa', 'Fischer-projektiot', 'Fischerin projektio', 'Fischerin projektion', 'projektio', 'projektion', 'projektiota', 'projektiossa', 'projektiot'))),
K("Mikä on stereokemia?",
  "Kemian osa, joka tutkii atomien kolmiulotteista järjestystä molekyylissä ja sen vaikutusta ominaisuuksiin.",
  "",
  2, L('stereokemia', ['stereokeskus', 'stereokeskuksen', 'stereokeskusta', 'stereokeskukset', 'stereokeskuksia', 'kolmiulotteinen', 'kolmiulotteisen', 'kolmiulotteista', 'kolmiulotteiset', 'kolmiulotteisia', 'kolmiulotteisesti', 'kolmiuloitteiseen', 'kolmiulotteiseen'])),
K("Mikä on plasma?",
  "Veren nestemäinen osa ilman soluja. Sisältää proteiinit ja hyytymistekijät. Seerumi on plasma ilman hyytymistekijöitä.",
  "",
  2, L(N('plasma', 'plasman', 'plasmaa', 'plasmassa', 'plasmasta', 'plasmaan', 'veriplasma', 'veriplasman', 'veriplasmaa', 'veriplasmassa'))),
K("Mikä on soluväliaine?",
  "Solujen väliin eritetty proteiinien ja polysakkaridien verkko, joka tukee kudosta, kuten kollageeni sidekudoksessa.",
  "",
  2, L('soluväliaine', ['soluväliaineen', 'soluväliainetta', 'soluväliaineessa', 'soluväliaineeseen', 'ekstrasellulaarinen matriksi', 'ekstrasellulaarisen matriksin', 'solunulkoinen matriksi', 'solunulkoisen matriksin'])),
K("Mitä terminen liike tarkoittaa?",
  "Lämmöstä johtuvaa molekyylien satunnaista liikettä. Kutsutaan myös: lämpöliike.",
  "",
  1, L(N('terminen', 'termisen', 'termistä', 'termiset', 'termisesti'))),
K("Mitä biologinen tiedonsiirto on?",
  "Perinnöllisen informaation kulku DNA:sta RNA:n kautta proteiiniin ja sukupolvelta toiselle.",
  "",
  2, L('tiedonsiirto', ['informaatio', 'informaation', 'informaatiota', 'informaatioon', 'informaatiossa', 'informationaalinen', 'informationaalisen', 'informationaaliset', 'informationaalisia'])),
K("Mikä on viestimolekyyli?",
  "Solujen väliseen tai sisäiseen viestintään erikoistunut molekyyli, kuten hormoni, hermovälittäjäaine tai kasvutekijä.",
  "",
  2, L('viestimolekyyli', ['viestintämolekyyli', 'viestintämolekyylin', 'viestintämolekyylit', 'viestintämolekyyleinä', 'signaalimolekyyli', 'signaalimolekyylin', 'signaalimolekyylit', 'signaalimolekyylejä'])),
K("Mikä on sitoutumismolekyyli?",
  "Molekyyli, jonka tehtävä on tarttua toiseen: vasta-aine antigeeniin, reseptori ligandiin, lektiini sokeriin.",
  "",
  1, L('sitoutumismolekyyli')),
K("Mikä on ravintovarastomolekyyli?",
  "Energian ja rakennusaineen varastoksi tehty molekyyli: tärkkelys ja glykogeeni sokerista, triglyseridit rasvasta.",
  "",
  2, L('ravintovarastomolekyyli', ['ravintovarasto', 'ravintovaraston', 'ravintovarastoa', 'ravintovarastona', 'varastomolekyyli', 'varastomolekyylin', 'varastomolekyylit'])),
K("Mikä on kaksinauhainen DNA?",
  "Kaksi vastakkaissuuntaista nukleotidiketjua, jotka emäsparit pitävät yhdessä kaksoiskierteenä. Kutsutaan myös: kaksijuosteinen.",
  "",
  2, L(N('kaksinauhainen', 'kaksinauhaisen', 'kaksinauhaista', 'kaksinauhaiseen', 'kaksinauhaiset', 'kaksijuosteinen', 'kaksijuosteisen', 'kaksijuosteista', 'kaksijuosteiset', 'yksinauhainen', 'yksinauhaisen', 'yksinauhaista', 'yksinauhaiset', 'yksijuosteinen', 'yksijuosteisen', 'yksijuosteista'))),
K("Mitä itsereplikoituminen tarkoittaa?",
  "Molekyylin tai järjestelmän kyky tehdä kopioita itsestään. Elämän tunnusmerkki, jonka DNA ja solu toteuttavat.",
  "",
  2, L(N('itsereplikoituminen', 'itsereplikoitumisen', 'itsereplikoitumista', 'itsereplikoitua', 'itsereplikoitumaan', 'itsereplikoituva', 'itsereplikoituvan', 'replikoitua', 'replikoituu', 'replikoituvat'))),
K("Mikä on esivanhempi evoluutiossa?",
  "Aikaisempi eliö, josta myöhemmät lajit polveutuvat. Kaikkien nykyisten solujen yhteinen esivanhempi on LUCA.",
  "",
  1, L(N('esivanhempi', 'esivanhemman', 'esivanhempaa', 'esivanhemmat', 'esivanhempien', 'esivanhempia', 'esivanhempina', 'esi-isä', 'esi-isän', 'esi-isää', 'esi-isät', 'esi-isien', 'esi-isiä', 'esi-isämme', 'kantamuoto', 'kantamuodon', 'kantamuotoa'))),
K("Mikä on eliösukupolvi?",
  "Yksi lisääntymiskierros vanhemmista jälkeläisiin. Evoluutio etenee sukupolvi sukupolvelta.",
  "",
  1, L('eliösukupolvi', ['sukupolvi', 'sukupolven', 'sukupolvea', 'sukupolvet', 'sukupolvien', 'sukupolvia', 'sukupolvelta', 'sukupolvelle'])),
K("Mitä solubiologia on?",
  "Solun rakenteen, toiminnan ja jakautumisen tutkimus. Biokemia ja molekyylibiologia selittävät solun molekyylitasolla.",
  "",
  1, L('solubiologia', ['molekyylibiologia', 'molekyylibiologian', 'molekyylibiologiaa', 'molekyylibiologiassa'])),
K("Mitä fysiikka on kemian ja biologian rinnalla?",
  "Aineen, energian ja voimien perustiede. Biologia palautuu kemiaan ja kemia fysiikkaan.",
  "",
  1, L('fysiikka', ['fysikaalinen', 'fysikaalisen', 'fysikaalista', 'fysikaaliset', 'fysikaalisia', 'fysikaalisesti', 'fysiokemiallinen', 'fysiokemiallisen', 'fysiokemialliset', 'fysiokemiallisia'])),
K("Mitä lääketiede on?",
  "Sairauksien syiden, ehkäisyn ja hoidon tiede. Biokemia on sen perusta: taudit ovat molekyylien häiriöitä.",
  "",
  1, L(N('lääketiede', 'lääketieteen', 'lääketiedettä', 'lääketieteessä', 'lääketieteeseen', 'lääketieteellinen', 'lääketieteellisen', 'lääketieteellistä', 'lääketieteelliset', 'lääketieteellisiä', 'lääketieteellisesti', 'medisiina', 'medisiinan'))),
K("Mikä on maksa?",
  "Suurin sisäelin, aineenvaihdunnan keskus: varastoi glykogeenia, valmistaa plasman proteiinit ja hajottaa myrkyt.",
  "",
  2, L(N('maksa', 'maksan', 'maksaa', 'maksassa', 'maksasta', 'maksaan', 'maksasolu', 'maksasolun', 'maksasolut', 'maksasolujen', 'maksasoluissa'))),
K("Mikä on suolisto?",
  "Ruoansulatuskanavan osa mahalaukusta peräsuoleen: ohutsuoli imeyttää ravinteet, paksusuolessa elää mikrobisto.",
  "",
  2, L('suolisto', ['ohutsuoli', 'ohutsuolen', 'ohutsuolta', 'ohutsuolessa', 'paksusuoli', 'paksusuolen', 'paksusuolta', 'paksusuolessa', 'suoli', 'suolen', 'suolta', 'suolessa', 'suolen limakalvo', 'suolen limakalvon'])),
K("Mitä katalysoiminen tarkoittaa?",
  "Reaktion nopeuttamista alentamalla aktivaatioenergiaa ilman, että katalysoija kuluu. Entsyymit katalysoivat solun reaktiot.",
  "",
  2, L(N('katalysoida', 'katalysoi', 'katalysoivat', 'katalysoitu', 'katalysoitua', 'katalysoima', 'katalysoiman', 'katalysoimat', 'katalysoimia', 'katalysoituu', 'katalysoituvat', 'katalyysi', 'katalyysin', 'katalyysiä', 'katalyysissä', 'katalyyttinen', 'katalyyttisen', 'katalyyttistä', 'katalyyttiset', 'katalyyttisesti'))),
K("Mitä epäjärjestys tarkoittaa termodynamiikassa?",
  "Hiukkasten ja energian satunnaista jakautumista, jonka mitta on entropia. Elävä solu ylläpitää järjestystä energian kustannuksella.",
  "",
  2, L(N('epäjärjestys', 'epäjärjestyksen', 'epäjärjestystä', 'epäjärjestykseen', 'järjestyneisyys', 'järjestyneisyyden', 'järjestyneisyyttä'))),
K("Mitä lisääntyminen on?",
  "Uusien yksilöiden tuottaminen: suvuton jakautumalla tai suvullinen sukusoluilla. Elämän tunnusmerkki.",
  "",
  2, L(N('lisääntyminen', 'lisääntymisen', 'lisääntymistä', 'lisääntymiseen', 'lisääntyä', 'lisääntyy', 'lisääntyvät', 'lisääntymiskyky', 'lisääntymiskyvyn', 'lisääntymiskykyä', 'lisääntymiskyvytön', 'lisääntymiskyvyttömän', 'lisääntymiskyvyttömiä', 'lisääntymiskyvytöntä', 'suvuton lisääntyminen', 'suvuttoman lisääntymisen', 'suvullinen lisääntyminen', 'suvullisen lisääntymisen'))),
K("Mikä on ekosysteemi?",
  "Alueen eliöt ja niiden eloton ympäristö vuorovaikutuksineen: energia virtaa ja aineet kiertävät sen läpi.",
  "",
  1, L('ekosysteemi')),
K("Mitä elintarviketekniikka on?",
  "Ruoan valmistuksen, säilyvyyden ja turvallisuuden tekniikka. Elintarvikebiotekniikka käyttää mikrobeja ja entsyymejä.",
  "",
  1, L('elintarviketekniikka', ['elintarviketeollisuus', 'elintarviketeollisuuden', 'elintarviketeollisuutta', 'elintarviketeollisuudessa', 'elintarvike', 'elintarvikkeen', 'elintarviketta', 'elintarvikkeet', 'elintarvikkeiden', 'elintarvikkeita', 'elintarvikkeissa', 'elintarvikkeisiin', 'elintarvikkeessa', 'elintarvikekemia', 'elintarvikekemian'])),
K("Mitä terveysteknologia on?",
  "Terveydenhuollon laitteet, diagnostiikka ja ohjelmistot. Suomen suurimpia korkean teknologian vientialoja.",
  "",
  1, L('terveysteknologia', ['terveydenhuolto', 'terveydenhuollon', 'terveydenhuoltoa', 'terveydenhuollossa', 'terveydenhuoltokulut', 'terveydenhuoltokuluista'])),
K("Mitä materiaalitekniikka on?",
  "Materiaalien rakenteen ja ominaisuuksien tekniikka. Biomateriaalit ja biomuovit ovat sen ja biotekniikan rajapinta.",
  "",
  1, L('materiaalitekniikka')),
K("Mikä on Chlamydomonas?",
  "Yksisoluinen, kaksisiimainen viherlevä, fotosynteesin ja siimojen malliorganismi.",
  "",
  1, L(N('Chlamydomonas', 'Chlamydomonaksen', 'Chlamydomonasta', 'Chlamydomonas reinhardtii'))),
K("Mikä on Homo sapiens?",
  "Nykyihmisen lajinimi Linnén kaksiosaisessa nimistössä: suku Homo, laji sapiens.",
  "",
  1, L(N('Homo sapiens', 'Homo sapiensin', 'Homo sapiensia', 'nykyihminen', 'nykyihmisen', 'nykyihmistä'))),
K("Mikä on Lehninger Principles of Biochemistry?",
  "Kurssin oppikirja, biokemian klassinen yleisteos, jonka Albert Lehninger julkaisi 1970 ja jota Nelson ja Cox jatkavat.",
  "",
  1, L(N('Lehninger', 'Lehningerin', 'Lehningeriä', 'Lehninger Principles of Biochemistry', 'Nelson ja Cox', 'Nelsonin ja Coxin'))),
K("Mitä yksisolutason tutkimus tarkoittaa?",
  "Menetelmät, jotka mittaavat yksittäisiä soluja kudoksen keskiarvon sijaan, kuten yksisolusekvensointi. Kutsutaan myös: single-cell.",
  "",
  1, L(N('single-cell', 'yksisolutaso', 'yksisolutason', 'yksisolutasolla', 'yksisolusekvensointi', 'yksisolusekvensoinnin', 'yksisolumenetelmä', 'yksisolumenetelmät', 'yksisolumenetelmien'))),
K("Mikä on organoidi?",
  "Kantasoluista laboratoriossa kasvatettu pieni, elimen rakennetta jäljittelevä solurykelmä, kuten suolisto- tai aivo-organoidi.",
  "",
  1, L('organoidi', ['organoids'])),
K("Mikä on epiteeli?",
  "Pintoja verhoava tiivis solukerros: iho, suolen sisäpinta ja rauhaset ovat epiteeliä. Kutsutaan myös: pintakudos.",
  "",
  2, L('epiteeli', ['epiteelisolu', 'epiteelisolun', 'epiteelisolut', 'epiteelisolujen', 'epiteelisoluja', 'pintakudos', 'pintakudoksen', 'pintakudosta', 'epithelial'])),
K("Mikä on kielimalli?",
  "Tekstiä ennustava tekoälymalli, kuten ChatGPT. Käyttökelpoinen opiskelun apuna, mutta sen väitteet on tarkistettava lähteistä.",
  "",
  1, L('kielimalli', ['suuri kielimalli', 'suuren kielimallin', 'ChatGPT', 'ChatGPT:n'])),
K("Mikä on fossiili?",
  "Muinaisen eliön kivettynyt jäänne tai jälki. Vanhimmat solufossiilit ovat noin 3,5 miljardin vuoden ikäisiä stromatoliitteja.",
  "",
  2, L('fossiili', ['fossiloitua', 'fossiloitunut', 'fossiloituneen', 'fossiloituneita', 'solufossiili', 'solufossiilin', 'solufossiilit', 'solufossiileja', 'mikrofossiili', 'mikrofossiilin', 'mikrofossiilit'])),
K("Mikä on Eoentophysalis belcherensis?",
  "Kanadan Belcher-saarilta löydetty noin 2 miljardin vuoden ikäinen syanobakteerifossiili, joka muistuttaa nykyisiä sukulaisiaan.",
  "",
  1, L(N('Eoentophysalis', 'Eoentophysalis belcherensis', 'Eoentophysaliksen', 'Belcher-saaret', 'Belcher-saarten', 'Belcher-saarilta'))),
K("Mikä on hiilivetyketju?",
  "Pelkistä hiili- ja vetyatomeista koostuva ketju, kuten rasvahapon häntä. Hydrofobinen ja energiarikas.",
  "",
  2, L('hiilivetyketju', ['hiilivetyhäntä', 'hiilivetyhännän', 'hiilivetyhäntää', 'hiilivetyhännät', 'hiilivetyketjuja'])),
K("Mikä on kalvorakenne?",
  "Lipidikaksoiskerroksesta ja proteiineista muodostuva rajapinta: solukalvo ja eukaryootin sisäkalvot.",
  "",
  2, L('kalvorakenne', ['kalvorakenteet', 'kalvorakenteita', 'kalvorakenteisia', 'kalvorakenteissa', 'kalvo', 'kalvon', 'kalvoa', 'kalvossa', 'kalvosta', 'kalvoon', 'kalvot', 'kalvojen', 'kalvoja', 'kalvoissa', 'kalvoista'])),
K("Mikä on nukkuminen aineenvaihdunnan kannalta?",
  "Lepotila, jossa energiankulutus laskee ja aivot puhdistavat aineenvaihduntatuotteita. Ei kuulu kurssin ydinsisältöön.",
  "",
  1),
K("Mitä tarkoittaa liukenematon?",
  "Aine, joka ei sekoitu veteen molekyylitasolla, kuten rasvat ja monet proteiinikuidut. Vastakohta: vesiliukoinen.",
  "",
  1, L(N('liukenematon', 'liukenemattoman', 'liukenematonta', 'liukenemattomat', 'liukenemattomia', 'liukenemattomien', 'veteen liukenematon', 'veteen liukenemattomia'))),
K("Mikä on aine kemian ja biologian kielessä?",
  "Kaikki, millä on massa ja tilavuus. Kemiallinen aine on alkuaine tai yhdiste.",
  "",
  1, L(N('aine', 'aineen', 'ainetta', 'aineessa', 'aineesta', 'aineeseen', 'aineet', 'aineiden', 'aineita', 'aineissa', 'aineisiin', 'aineiksi', 'kemiallinen aine', 'kemiallisen aineen', 'kemiallista ainetta', 'kemialliset aineet'))),
K("Mikä on jänne?",
  "Kollageenista koostuva sidekudosnauha, joka kiinnittää lihaksen luuhun. Kollageeni antaa sille vetolujuuden.",
  "",
  1, L(N('jänne', 'jänteen', 'jännettä', 'jänteessä', 'jänteet', 'jänteiden', 'jänteitä', 'jänteissä'))),
K("Mikä on rusto?",
  "Kimmoisa, verisuoneton tukikudos nivelpinnoilla, korvassa ja nenässä, kollageenin ja proteoglykaanien verkko.",
  "",
  1, L('rusto', ['rustot', 'rustoa', 'rustossa', 'rustokudos', 'rustokudoksen', 'rustokudosta'])),
K("Mikä on luu?",
  "Kova tukikudos, jossa kollageenisäikeiden lomassa on kalsiumfosfaattia. Luuydin tuottaa verisolut.",
  "",
  1, L(N('luu', 'luun', 'luuta', 'luussa', 'luusta', 'luuhun', 'luut', 'luiden', 'luita', 'luissa', 'luukudos', 'luukudoksen', 'luukudosta'))),
K("Mikä on kynsi?",
  "Keratiinista koostuva kova levy sormen päässä, samaa proteiinia kuin hiukset ja sarvet.",
  "",
  1, L(N('kynsi', 'kynnen', 'kynttä', 'kynnet', 'kynsien', 'kynsiä', 'kynsissä'))),
]

L2 = [
K("Mikä on aivorunko?",
  "Aivojen alin osa, joka säätelee hengitystä ja sykettä. Sen hengityskeskus tunnistaa veren hiilidioksidin ja pH:n.",
  "",
  1, L('aivorunko', ['hengityskeskus', 'hengityskeskuksen', 'hengityskeskusta'])),
K("Mikä on asetaatti-ioni?",
  "Etikkahapon anioni CH<sub>3</sub>COO<sup>−</sup>, joka syntyy kun etikkahappo luovuttaa protoninsa. Kutsutaan myös: asetaatti.",
  "",
  2, L('asetaatti', ['asetaatti-ioni', 'asetaatti-ionin', 'asetaatti-ionia', 'asetaatti-ionit', 'asetaattia'])),
K("Mikä on etikkahappo?",
  "Heikko karboksyylihappo CH<sub>3</sub>COOH, etikan happo, pK<sub>a</sub> 4,76. Asetaatin kanssa se muodostaa puskurin.",
  "",
  3, L('etikkahappo', ['etikka', 'etikan', 'etikkaa', 'etikkahappoliuos', 'etikkahappoliuoksen'])),
K("Mikä on fosforihappo?",
  "Kolmiprotoninen happo H<sub>3</sub>PO<sub>4</sub>. Toinen dissosiaatio (pK<sub>a</sub> 7,2) tekee fosfaatista solun puskurin.",
  "",
  2, L('fosforihappo', ['fosfaattipuskuri', 'fosfaattipuskurin', 'fosfaattipuskuria', 'natriumfosfaattipuskuri', 'natriumfosfaattipuskurin'])),
K("Mitä deprotonoituminen tarkoittaa?",
  "Protonin irtoamista molekyylistä, jolloin happo muuttuu konjugaattiemäksekseen. Vastakohta on protonoituminen.",
  "",
  2, L(N('deprotonoituminen', 'deprotonoitumisen', 'deprotonoitua', 'deprotonoituu', 'deprotonoituvat', 'deprotonoitunut', 'deprotonoituneen', 'deprotonoituna', 'deprotonoitu', 'protonoituminen', 'protonoitumisen', 'protonoitua', 'protonoituu', 'protonoituvat', 'protonoitunut', 'protonoituneen', 'protonoituna', 'protonoitu'))),
K("Mitä hengitys on?",
  "Hapen ottamista ja hiilidioksidin poistamista. Keuhkotuuletus säätää veren pH:ta bikarbonaattipuskurin kautta.",
  "",
  2, L(N('hengitys', 'hengityksen', 'hengitystä', 'hengityksessä', 'hengittää', 'hengittäminen', 'keuhkotuuletus', 'keuhkotuuletuksen', 'keuhkotuuletusta'))),
K("Mikä on hiilidioksidi?",
  "Kaasu CO<sub>2</sub>, soluhengityksen lopputuote ja fotosynteesin raaka-aine. Vedessä se muodostaa hiilihappoa.",
  "",
  3, L('hiilidioksidi')),
K("Mitä ionisoituminen tarkoittaa?",
  "Neutraalin molekyylin muuttumista ioneiksi, kuten hapon dissosioituessa vedessä protoniksi ja anioniksi.",
  "",
  2, L(N('ionisoituminen', 'ionisoitumisen', 'ionisoitumista', 'ionisoitua', 'ionisoituu', 'ionisoituvat', 'ionisoitunut', 'ionisoituneen', 'ionisoitu', 'ionisaatio', 'ionisaation', 'ionisaatiota'))),
K("Mikä on ketjureaktio?",
  "Reaktio, jonka tuote käynnistää seuraavan saman reaktion. Vedessä protoni hyppii vetysidosverkkoa pitkin ketjuna.",
  "",
  1, L('ketjureaktio')),
K("Mikä on kide?",
  "Kiinteä aine, jonka atomit tai molekyylit ovat säännöllisessä hilassa. Jää on veden kide.",
  "",
  2, L(N('kide', 'kiteen', 'kidettä', 'kiteessä', 'kiteeseen', 'kiteet', 'kiteiden', 'kiteitä', 'kiteiksi', 'kiteissä', 'kiteinen', 'kiteisen', 'kiteistä', 'kiteytyä', 'kiteytyy', 'kiteytyminen', 'kiteytymisen'))),
K("Mikä on kuoriproteiini?",
  "Viruksen kapsidin rakenneproteiini, joka pakkaa genomin. Kutsutaan myös: kapsidiproteiini.",
  "",
  1, L('kuoriproteiini', ['kapsidiproteiini', 'kapsidiproteiinin', 'kapsidiproteiinit'])),
K("Mitä liuennut tarkoittaa?",
  "Aine, jonka hiukkaset ovat sekoittuneet liuottimeen molekyylitasolla, kuten suola vedessä.",
  "",
  1, L(N('liuennut', 'liuenneen', 'liuennutta', 'liuenneena', 'liuenneet', 'liuenneiden', 'liuenneita', 'liueta', 'liukenee', 'liukenevat', 'liukeneminen', 'liukenemisen', 'liuottaa', 'liuottaminen'))),
K("Mikä on mahalaukku?",
  "Ruoansulatuskanavan pussi, jonka suolahappo laskee sisällön pH:n noin 2:een ja aktivoi pepsiinin.",
  "",
  2, L('mahalaukku', ['mahahappo', 'mahahapon', 'mahahappoa', 'mahaneste', 'mahanesteen', 'mahanestettä', 'maha', 'mahan', 'mahassa'])),
K("Mikä on mooli?",
  "Ainemäärän yksikkö: 6,022·10<sup>23</sup> hiukkasta. Veden pitoisuus vedessä on 55,5 mol/ℓ.",
  "",
  3, L('mooli', ['mol', 'mol/ℓ', 'ainemäärä', 'ainemäärän', 'ainemäärää', 'ainemäärät', 'Avogadron vakio', 'Avogadron vakion', 'Avogadron luku', 'Avogadron luvun'])),
K("Mikä on natriumhydroksidi?",
  "Vahva emäs NaOH, joka dissosioituu vedessä täysin natrium- ja hydroksidi-ioneiksi. Kutsutaan myös: lipeä.",
  "",
  2, L('natriumhydroksidi', ['NaOH', 'NaOH:n', 'NaOH:ta', 'lipeä', 'lipeän', 'lipeää'])),
K("Mikä on paine?",
  "Voima pinta-alaa kohti. Kaasun paine syntyy molekyylien törmäyksistä, osmoottinen paine vetää vettä kalvon läpi.",
  "",
  2, L(N('paine', 'paineen', 'painetta', 'paineessa', 'paineesta', 'paineeseen', 'paineet', 'paineiden', 'paineita'))),
K("Mikä on rasva?",
  "Glyserolin ja kolmen rasvahapon esteri, triglyseridi. Veteen liukenematon energiavarasto. Kutsutaan myös: triasyyliglyseroli.",
  "",
  3, L(N('rasva', 'rasvan', 'rasvaa', 'rasvassa', 'rasvasta', 'rasvaan', 'rasvat', 'rasvojen', 'rasvoja', 'rasvoissa', 'triglyseridi', 'triglyseridin', 'triglyseridiä', 'triglyseridit', 'triglyseridien', 'triglyseridejä', 'triasyyliglyseroli', 'triasyyliglyserolin', 'triasyyliglyserolit'))),
K("Mikä on reaktioyhtälö?",
  "Kemiallisen reaktion merkintä: lähtöaineet vasemmalla, tuotteet oikealla, kertoimet tasapainossa. Kutsutaan myös: reaktiokaava.",
  "",
  2, L(N('reaktioyhtälö', 'reaktioyhtälön', 'reaktioyhtälöä', 'reaktioyhtälössä', 'reaktioyhtälöt', 'reaktioyhtälöiden', 'reaktioyhtälöitä', 'reaktiokaava', 'reaktiokaavan', 'reaktiokaavaa', 'tasapainoyhtälö', 'tasapainoyhtälön', 'tasapainoyhtälöä'))),
K("Mikä on tasapainovakio?",
  "Tuotteiden ja lähtöaineiden pitoisuuksien suhde tasapainossa, K. Hapon dissosiaatiovakio K<sub>a</sub> on sen erikoistapaus.",
  "",
  2, L('tasapainovakio', ['tasapainovakiot'])),
K("Mikä on veri?",
  "Verisuonissa kiertävä neste: plasma ja siinä punasolut, valkosolut ja verihiutaleet. Sen pH pysyy 7,4:ssä.",
  "",
  3, L(N('veri', 'veren', 'verta', 'veressä', 'verestä', 'vereen', 'verinäyte', 'verinäytteen', 'verinäytettä', 'verinäytteestä', 'verisuoni', 'verisuonen', 'verisuonta', 'verisuonet', 'verisuonten', 'verisuonia', 'verisuonissa'))),
K("Mikä on vesimolekyyli?",
  "H<sub>2</sub>O: happi ja kaksi vetyä 104,5 asteen kulmassa. Taipunut ja polaarinen, siksi vetysidokset.",
  "",
  3, L('vesimolekyyli', ['vesimolekyyleihin', 'vesimolekyylille'])),
K("Mikä on vetyatomi?",
  "Pienin atomi: yksi protoni ja yksi elektroni. Vetysidoksessa sen elektroniköyhä ydin vetää puoleensa vapaata elektroniparia.",
  "",
  2, L('vetyatomi')),
K("Mikä on voima?",
  "Vuorovaikutus, joka vetää tai työntää hiukkasia. Molekyylien väliset voimat ovat sähköisiä: ioni-, dipoli- ja dispersiovoimia.",
  "",
  2, L(N('voima', 'voiman', 'voimaa', 'voimat', 'voimien', 'voimia', 'voimina', 'voimalla', 'vetovoima', 'vetovoiman', 'vetovoimaa', 'vetovoimaan', 'vetovoimat', 'hylkivä voima', 'hylkivän voiman'))),
K("Mikä on suolavesi?",
  "Vesiliuos, jossa on liuenneena natriumkloridia. Meressä noin 35 g/ℓ, ja ionit lisäävät sähkönjohtavuutta.",
  "",
  1, L('suolavesi', ['suolaveden', 'suolavettä', 'suolavedessä', 'merivesi', 'meriveden', 'merivettä', 'merivedessä'])),
K("Mikä on vesistö?",
  "Järvet, joet ja meret: veden ominaisuudet, kuten jään keveys, tekevät niistä elinkelpoisia talvellakin.",
  "",
  1, L(N('vesistö', 'vesistön', 'vesistöä', 'vesistössä', 'vesistöt', 'vesistöjen', 'vesistöjä', 'vesistöissä'))),
K("Mikä on ei-polaarinen molekyyli?",
  "Molekyyli, jonka varaus jakautuu tasaisesti, kuten hiilivedyt. Ei sekoitu veteen. Kutsutaan myös: pooliton.",
  "",
  2, L(N('ei-polaarinen', 'ei-polaarisen', 'ei-polaarista', 'ei-polaariset', 'ei-polaarisia', 'ei-polaarisessa', 'pooliton', 'poolittoman', 'poolitonta', 'poolittomat', 'poolittomia', 'poolittomien', 'poolittomissa', 'apolaarinen', 'apolaarisen', 'apolaariset'))),
K("Mikä on lämpötila?",
  "Hiukkasten keskimääräisen liike-energian mitta. Nostaa reaktionopeutta ja rikkoo vetysidoksia.",
  "",
  2, L(N('lämpötila', 'lämpötilan', 'lämpötilaa', 'lämpötilassa', 'lämpötilasta', 'lämpötilaan', 'lämpötilat', 'lämpötilojen', 'lämpötiloja', 'lämpötiloissa'))),
K("Mikä on kaksoissidos?",
  "Kahden atomin välinen sidos, jossa jaetaan kaksi elektroniparia, kuten C=O tai C=C. Jäykkä, ei pyöri.",
  "",
  2, L('kaksoissidos', ['kaksois', 'kolmoissidos', 'kolmoissidoksen', 'kolmoissidosta', 'kolmoissidokset', 'yksöissidos', 'yksöissidoksen', 'yksöissidosta', 'yksöissidokset'])),
K("Mikä on sähköinen johtavuus?",
  "Aineen kyky kuljettaa sähkövirtaa. Puhdas vesi johtaa huonosti, suolaliuos hyvin ionien vuoksi.",
  "",
  1, L(N('sähkönjohtavuus', 'sähkönjohtavuuden', 'sähkönjohtavuutta', 'johtavuus', 'johtavuuden', 'johtavuutta', 'sähköinen johtavuus', 'sähköisen johtavuuden'))),
]

L3 = [
K("Mitä ankkurointi tarkoittaa solussa?",
  "Proteiinin tai organellin kiinnittämistä paikoilleen, esimerkiksi tukirankaan tai kalvoon.",
  "",
  1, L(N('ankkuroida', 'ankkuroi', 'ankkuroitu', 'ankkuroituu', 'ankkuroituvat', 'ankkurointi', 'ankkuroinnin', 'ankkuroituna'))),
K("Mikä on aurinkoenergia?",
  "Auringon säteilyn energia, jonka fotosynteesi sitoo kemiallisiksi sidoksiksi. Lähes kaiken elämän energianlähde.",
  "",
  2, L('aurinkoenergia', ['auringonvalo', 'auringonvalon', 'auringonvaloa', 'auringonvalossa', 'aurinko', 'auringon', 'aurinkoa', 'valoenergia', 'valoenergian', 'valoenergiaa'])),
K("Mitä biosynteesi on?",
  "Solun oma valmistus: yksinkertaisista lähtöaineista rakennetaan entsyymien avulla monimutkaisia molekyylejä.",
  "",
  2, L('biosynteesi', ['biosynteesipaikka', 'biosynteesipaikan', 'biosynteesitie', 'biosynteesitien', 'biosynteesitiet', 'biosynteesiteissä', 'biosynteettinen', 'biosynteettisen'])),
K("Mitä deformoituminen tarkoittaa solussa?",
  "Muodon muuttumista voiman vaikutuksesta. Tukiranka ja kalvo antavat solun muotoutua ja liikkua.",
  "",
  1, L(N('deformoitua', 'deformoituu', 'deformoituvat', 'deformoida', 'deformoivat', 'deformaatio', 'deformaation', 'deformaatiota'))),
K("Mikä on erittyvä proteiini?",
  "Solusta ulos vietävä proteiini, joka syntetisoidaan karkeassa kalvostossa ja pakataan Golgissa rakkulaan.",
  "",
  2, L(N('erittyvä proteiini', 'erittyvän proteiinin', 'erittyviä proteiineja', 'erittyvät proteiinit', 'erittyvä', 'erittyvän', 'erittyviä', 'erittyy', 'erittyvät', 'erittää', 'eritys', 'erityksen', 'eritystä', 'eritetään', 'eritetty'))),
K("Mikä on filamentti?",
  "Proteiineista koottu säie. Tukirangan filamentteja ovat aktiinisäikeet, välikokoiset filamentit ja mikrotubulukset.",
  "",
  2, L('filamentti', ['filaments', 'säie', 'säikeen', 'säiettä', 'säikeessä', 'säikeet', 'säikeiden', 'säikeitä', 'säikeissä'])),
K("Mikä on välikokoinen filamentti?",
  "Noin 10 nm:n paksuinen, köysimäinen tukirangan säie, kuten keratiini ja tuman laminit. Kestää vetoa.",
  "",
  2, L(N('välikokoinen filamentti', 'välikokoisen filamentin', 'välikokoista filamenttia', 'välikokoiset filamentit', 'välikokoisten filamenttien', 'välikokoisia filamentteja', 'välikokoinen', 'välikokoiset', 'intermediate filament', 'intermediate filaments', 'intermediaarifilamentti', 'intermediaarifilamentit', 'lamiini', 'lamiinin', 'lamiinit', 'lamiineja'))),
K("Mikä on fosfaatti?",
  "Fosforihapon anioni PO<sub>4</sub><sup>3−</sup>. Nukleotidien, fosfolipidien ja ATP:n osa. Fosforylaatio liittää sen proteiiniin.",
  "",
  3, L('fosfaatti', ['fosfaatti-ioni', 'fosfaatti-ionin', 'fosfaatteja', 'fosfaateista'])),
K("Mikä on fraktio solufraktioinnissa?",
  "Sentrifugoinnissa eroteltu osa: tietyllä nopeudella pohjalle painuva pelletti tai päälle jäävä supernatantti.",
  "",
  2, L('fraktio', ['painofraktio', 'painofraktion', 'painofraktiot', 'painofraktioita', 'solufraktiointi', 'solufraktioinnin', 'fraktiointi', 'fraktioinnin', 'solupelletti', 'solupelletit', 'ultrasentrifugointi', 'ultrasentrifugoinnin', 'ultrasentrifugi', 'ultrasentrifugin'])),
K("Mitä fuusioituminen tarkoittaa kalvoista?",
  "Kahden kalvon sulautumista yhdeksi, kuten rakkulan liittyessä solukalvoon eksosytoosissa.",
  "",
  2, L(N('fuusioitua', 'fuusioituu', 'fuusioituvat', 'fuusioida', 'fuusioidaan', 'fuusioitunut', 'kalvofuusio', 'kalvofuusion', 'kalvofuusiota', 'sulautua', 'sulautuu', 'sulautuvat', 'sulautuminen', 'sulautumisen'))),
K("Mikä on glyoksylaattisykli?",
  "Kasvien ja mikrobien reitti, joka tekee rasvasta sokeria glyoksisomeissa. Eläimillä sitä ei ole.",
  "",
  1, L('glyoksylaattisykli', ['glyoksylaattikierto', 'glyoksylaattikierron', 'glyoksylaattikiertoa'])),
K("Mitä hajotus tarkoittaa aineenvaihdunnassa?",
  "Suurten molekyylien pilkkomista pienemmiksi energian vapauttamiseksi eli katabolia.",
  "",
  2, L(N('hajotus', 'hajotuksen', 'hajotusta', 'hajotuksessa', 'hajotusreaktio', 'hajotusreaktion', 'hajotusreaktiot', 'hajottaa', 'hajotetaan', 'hajotettu', 'hajotettava', 'hajottava', 'hajottavan', 'hajottavat', 'hajottavaa', 'hajottavien', 'hajoaa', 'hajoavat', 'hajoaminen', 'hajoamisen'))),
K("Mikä on halkaisija?",
  "Ympyrän tai pallon läpimitta. Solujen halkaisija on tyypillisesti 1–100 mikrometriä.",
  "",
  1, L('halkaisija', ['läpimitta', 'läpimitan', 'läpimittaa', 'halkaisijainen'])),
K("Mikä on kaksoiskalvo?",
  "Kaksi sisäkkäistä kalvoa. Tumaa, mitokondriota ja viherhiukkasta ympäröi kaksoiskalvo, muita organelleja yksi kalvo.",
  "",
  2, L('kaksoiskalvo', ['kaksinkertainen kalvo', 'kaksinkertaisen kalvon', 'kaksinkertaisesta kalvosta'])),
K("Mitä kuroutuminen tarkoittaa?",
  "Kalvon painumista ja irtoamista rakkulaksi, kuten endosytoosissa, tai solun jakautumista kahtia kuroutumalla.",
  "",
  2, L(N('kuroutua', 'kuroutuu', 'kuroutuvat', 'kuroutuva', 'kuroutuvan', 'kuroutuminen', 'kuroutumisen', 'kuroutumista', 'kuroutumalla'))),
K("Mitä lajittelu tarkoittaa Golgin laitteessa?",
  "Proteiinien ohjaamista oikeisiin osoitteisiin: lysosomiin, solukalvolle tai ulos. Osoitteena toimii sokeri- tai peptidimerkki.",
  "",
  2, L(N('lajittelu', 'lajittelun', 'lajittelua', 'lajitella', 'lajittelee', 'lajitellaan', 'proteiinien lajittelu', 'proteiinien lajittelun', 'kohdennus', 'kohdennuksen', 'kohdennusta'))),
K("Mikä on lihassäie?",
  "Lihassolu: pitkä, monitumainen solu täynnä aktiini- ja myosiinisäikeitä, jotka liukuvat toistensa lomaan supistuksessa.",
  "",
  2, L(N('lihassäie', 'lihassäikeen', 'lihassäiettä', 'lihassäikeet', 'lihassäikeiden', 'lihassäikeitä', 'lihassäikeissä', 'lihassolu', 'lihassolun', 'lihassolua', 'lihassolut', 'lihassolujen', 'lihassoluja', 'lihas', 'lihaksen', 'lihasta', 'lihakset', 'lihasten', 'lihaksia', 'lihaksissa', 'aktiini-myosiini'))),
K("Mikä on magneettikenttä?",
  "Magneetin tai sähkövirran ympärille syntyvä kenttä, joka vaikuttaa liikkuviin varauksiin. NMR ja magneettikuvaus perustuvat siihen.",
  "",
  1, L('magneettikenttä', ['magneettikentän', 'magneettikenttää', 'magneettikentässä', 'magneetti', 'magneetin', 'magneettia', 'magneettinen', 'magneettisen', 'magneettista', 'magneettiset', 'sähkökenttä', 'sähkökentän', 'sähkökenttää', 'sähkökentässä'])),
K("Mitä orientoituminen tarkoittaa solussa?",
  "Molekyylin tai rakenteen asettumista tiettyyn suuntaan, kuten kalvoproteiinin suunta kalvossa tai mikrotubulusten suuntaus.",
  "",
  1, L(N('orientoituminen', 'orientoitumisen', 'orientoitumista', 'orientoitua', 'orientoituu', 'orientoituvat', 'orientoitunut', 'orientoituneen', 'orientaatio', 'orientaation', 'orientaatiota', 'suuntautua', 'suuntautuu', 'suuntautuminen', 'suuntautumisen'))),
K("Mitä prosessointi tarkoittaa proteiineista?",
  "Proteiinin muokkausta synteesin jälkeen: leikkausta, sokerointia ja laskostusta kalvostossa ja Golgissa.",
  "",
  2, L(N('prosessointi', 'prosessoinnin', 'prosessointia', 'prosessoinnissa', 'prosessoida', 'prosessoi', 'prosessoidaan', 'prosessoitu', 'prosessoidun', 'prosessoituja', 'prosessoitujen'))),
K("Mikä on rikki biomolekyyleissä?",
  "Alkuaine S, jota on kysteiinissä ja metioniinissa. Kysteiinien rikkisillat lukitsevat proteiinin rakenteen.",
  "",
  2, L('rikki', ['rikin', 'rikkiä', 'rikkiin', 'rikkiatomi', 'rikkiatomin', 'rikkiatomit', 'rikkiyhdiste', 'rikkiyhdisteen', 'rikkiyhdisteet', 'rikkiyhdisteiden', 'rikkiyhdisteitä', 'rikkisilta', 'rikkisillan', 'rikkisiltaa', 'rikkisillat', 'rikkisiltojen', 'rikkisiltoja'])),
K("Mikä on sulfaattiryhmä?",
  "Rikkihapon ryhmä –OSO<sub>3</sub><sup>−</sup>, joka liitetään Golgissa proteoglykaanien sokereihin ja antaa niille negatiivisen varauksen.",
  "",
  1, L('sulfaattiryhmä', ['sulfatoida', 'sulfatoidaan', 'sulfatoitu', 'sulfaatio', 'sulfaation'])),
K("Mikä on tukiverkosto solussa?",
  "Tukirangan säikeiden verkko, joka antaa solulle muodon, kiinnittää organellit ja toimii kuljetusratana.",
  "",
  1, L('tukiverkosto', ['tukikuitu', 'tukikuidun', 'tukikuidut', 'tukikuiduista', 'tukikuituja'])),
K("Mikä on välituote?",
  "Reaktiosarjan keskellä syntyvä ja heti kuluva molekyyli, kuten sitruunahappokierron hapot. Kutsutaan myös: intermediaatti.",
  "",
  2, L(N('välituote', 'välituotteen', 'välituotetta', 'välituotteet', 'välituotteiden', 'välituotteita', 'välituotteina', 'intermediaatti', 'intermediaatin', 'intermediaattia', 'intermediaatit'))),
K("Mitä varastointi tarkoittaa solussa?",
  "Aineen tallettamista myöhempää käyttöä varten: glykogeeni ja rasva energiaa, vakuoli vettä, kalvorakkulat eritteitä.",
  "",
  1, L('varastointi', ['varastoida', 'varastoi', 'varastoidaan', 'varastoitu', 'varastoitua', 'varastoituu', 'varastoituvat', 'varastoaine', 'varastoaineen', 'varastoaineet', 'varastoaineita', 'varastoaineikseen'])),
K("Mikä on jäteaine solussa?",
  "Aineenvaihdunnan tarpeeton tai haitallinen tuote, kuten hiilidioksidi, urea tai vetyperoksidi, joka poistetaan tai hajotetaan.",
  "",
  1, L(N('jäteaine', 'jäteaineen', 'jäteainetta', 'jäteaineet', 'jäteaineiden', 'jäteaineita', 'aineenvaihduntatuote', 'aineenvaihduntatuotteen', 'aineenvaihduntatuotteet', 'aineenvaihduntatuotteiden', 'aineenvaihduntatuotteita', 'kuona-aine', 'kuona-aineen', 'kuona-aineet', 'kuona-aineita'))),
K("Mikä on kuitu solubiologiassa?",
  "Pitkä, ohut säiemäinen rakenne, kuten kollageenikuitu soluväliaineessa tai tukirangan säikeet.",
  "",
  1, L(N('kuitu', 'kuidun', 'kuitua', 'kuidut', 'kuitujen', 'kuituja', 'kuiduista', 'kollageenikuitu', 'kollageenikuidun', 'kollageenikuidut', 'kollageenikuituja'))),
]

L4a = [
K("Mikä on adenovirus?",
  "Kaksijuosteinen DNA-virus, joka aiheuttaa hengitystieinfektioita. Muokattuna yleinen geeniterapian ja rokotteiden vektori.",
  "",
  2, L('adenovirus', ['adenoviruksen', 'adenovirusta', 'adenovirukset', 'adenovirusvektori', 'adenovirusvektorin'])),
K("Mikä on lac-repressori?",
  "LacI-geenin proteiini, joka sitoutuu lac-operonin operaattoriin ja estää transkription, kunnes allolaktoosi irrottaa sen.",
  "",
  2, L(N('lac-repressori', 'lac-repressorin', 'lac-repressoria', 'lac-repressoriin', 'LacI', 'lacI', 'lacI-geeni', 'lacI-geenin', 'LacI-proteiini', 'LacI-proteiinin'))),
K("Mikä on cAMP?",
  "Syklinen AMP, ATP:stä tehty toisiolähetti. Bakteerissa ilmoittaa glukoosin puutteesta ja aktivoi lac-operonin CAP-proteiinin kautta.",
  "",
  2, L(N('cAMP', 'cAMP:n', 'cAMP:tä', 'syklinen AMP', 'syklisen AMP:n', 'cGMP', 'cGMP:n', 'syklinen GMP', 'syklinen nukleotidi', 'syklisen nukleotidin', 'sykliset nukleotidit', 'syklisiä nukleotideja', 'toisiolähetti', 'toisiolähetin', 'toisiolähettiä', 'toisiolähetit'))),
K("Mikä on guanosiinimonofosfaatti?",
  "Nukleotidi GMP: guaniini, riboosi ja yksi fosfaatti. RNA:n rakenneosa, syklisenä cGMP viestimolekyyli.",
  "",
  1, L('guanosiinimonofosfaatti', ['GMP', 'GMP:n', 'adenosiinimonofosfaatti', 'adenosiinimonofosfaatin', 'AMP', 'AMP:n', 'sytidiinimonofosfaatti', 'CMP', 'uridiinimonofosfaatti', 'UMP'])),
K("Mikä on heterorengas?",
  "Rengas, jossa on hiilen lisäksi muitakin atomeja, kuten typpeä. Nukleoemäkset ovat typpiheterorenkaita.",
  "",
  1, L(N('heterorengas', 'heterorenkaan', 'heterorengasta', 'heterorenkaassa', 'heterorenkaat', 'heterorenkaiden', 'heterorenkaita', 'heterosyklinen', 'heterosyklisen', 'heterosykliset', 'heterosyklisiä'))),
K("Mitä jaksollisuus tarkoittaa DNA:ssa?",
  "Rakenteen toistuminen säännöllisin välein: kaksoiskierteessä kierros toistuu 3,4 nm:n välein, mikä näkyi Franklinin röntgenkuvassa.",
  "",
  1, L('jaksollisuus', ['jaksollinen rakenne', 'jaksollisen rakenteen', 'toistuva rakenne', 'toistuvan rakenteen'])),
K("Mikä on konsensussekvenssi?",
  "Yleisin emäsjärjestys, kun monta saman tehtävän sekvenssiä rinnastetaan, kuten promoottorin TATAAT ja TTGACA.",
  "",
  2, L('konsensussekvenssi', ['konsensusalue', 'konsensusalueen', 'konsensusalueet', 'konsensusalueita', 'konsensus', 'konsensuksen', 'TATAAT', 'TTGACA', '-10-alue', '-35-alue', 'Pribnow-laatikko', 'Pribnow-laatikon'])),
K("Mikä on uurre DNA:ssa?",
  "Kaksoiskierteen pinnan ura, jossa emäkset ovat esillä. Iso uurre on proteiinien tavallinen tunnistuskohta, pieni uurre kapeampi.",
  "",
  2, L(N('uurre', 'uurteen', 'uurretta', 'uurteessa', 'uurteet', 'uurteiden', 'uurteita', 'iso uurre', 'ison uurteen', 'isoa uurretta', 'pieni uurre', 'pienen uurteen', 'pientä uurretta', 'suuri uurre', 'suuren uurteen', 'major groove', 'minor groove', 'ura', 'uran', 'uraa', 'urat', 'urien', 'uria', 'uriin'))),
K("Mikä on ohjaussekvenssi?",
  "DNA-jakso, joka ohjaa geenin lukemista: promoottori, operaattori, tehostaja tai terminaattori. Kutsutaan myös: säätelyalue.",
  "",
  2, L('ohjaussekvenssi', ['säätelyelementti', 'säätelyelementin', 'säätelyelementtiä', 'säätelyelementit', 'säätelyelementtien', 'säätelyelementtejä'])),
K("Mikä on perimäaines?",
  "Solun perinnöllinen materiaali, DNA, ja viruksilla joskus RNA. Kutsutaan myös: geneettinen materiaali.",
  "",
  2, L(N('perimäaines', 'perimäaineksen', 'perimäainesta', 'perimäaineksessa', 'perimäainekseen', 'geneettinen materiaali', 'geneettisen materiaalin', 'geneettistä materiaalia', 'perinnöllinen aines', 'perinnöllisen aineksen'))),
K("Mitä RNA-lajit ovat?",
  "Lähetti-RNA kantaa ohjeen, siirtäjä-RNA tuo aminohapon, ribosomi-RNA rakentaa ribosomin, lisäksi säätelevät pienet RNA:t.",
  "",
  2, L(N('RNA-laji', 'RNA-lajin', 'RNA-lajit', 'RNA-lajien', 'RNA-lajeja', 'RNA-lajeista', 'RNA-molekyyli', 'RNA-molekyylin', 'RNA-molekyyliä', 'RNA-molekyylit', 'RNA-molekyylien', 'RNA-molekyylejä', 'RNA-molekyyleillä', 'RNA-ketju', 'RNA-ketjun', 'RNA-ketjua', 'RNA-juoste', 'RNA-juosteen', 'RNA-juosteesta', 'RNA-juostetta'))),
K("Mitä steerinen este tarkoittaa?",
  "Atomien tilantarpeen aiheuttama este: suuret ryhmät eivät mahdu samaan paikkaan, mikä rajoittaa muotoa ja sitoutumista.",
  "",
  1, L(N('steerinen', 'steerisen', 'steeristä', 'steeriset', 'steerisesti', 'steerinen este', 'steerisen esteen', 'steeristä estettä'))),
K("Mikä on templaatti?",
  "Malli, jonka mukaan uusi juoste rakennetaan emäspariutumisella. Kutsutaan myös: mallijuoste.",
  "",
  2, L(N('templaatti', 'templaatin', 'templaattia', 'templaattina', 'templaatit', 'template'))),
K("Mitä transkriboiminen tarkoittaa?",
  "RNA-kopion tekemistä DNA:sta eli transkriptiota. Transkriboitu alue on se, josta RNA on luettu.",
  "",
  1, L(N('transkriboida', 'transkriboidaan', 'transkriboitu', 'transkriboidun', 'transkriboitua', 'transkriboituu', 'transkriboituvat', 'transkriboituva', 'transkriboivat', 'transkriboi'))),
K("Mitä transloiminen tarkoittaa?",
  "Proteiinin valmistamista lähetti-RNA:n ohjeen mukaan eli translaatiota.",
  "",
  1, L(N('transloida', 'transloidaan', 'transloitu', 'transloitua', 'transloituu', 'transloituvat', 'transloituva', 'transloi'))),
K("Mikä on vastinjuoste?",
  "Kaksoiskierteen toinen juoste, jonka emäkset ovat komplementaarisia ensimmäiselle. Kutsutaan myös: vastinnauha, komplementaarinen juoste.",
  "",
  2, L(N('vastinjuoste', 'vastinjuosteen', 'vastinjuostetta', 'vastinjuosteet', 'vastinjuosteiden', 'vastinjuosteita', 'vastinnauha', 'vastinnauhan', 'vastinnauhaa', 'vastinnauhat', 'komplementaarinen juoste', 'komplementaarisen juosteen', 'komplementaarista juostetta'))),
K("Mikä on virhefrekvenssi?",
  "Väärien nukleotidien osuus kopioinnissa. DNA-polymeraasilla oikoluvun kanssa noin 1/10<sup>9</sup>, RNA-polymeraasilla 1/10<sup>4</sup>.",
  "",
  2, L('virhefrekvenssi', ['virhetaajuus', 'virhetaajuuden', 'virhetaajuutta', 'virhetiheys', 'virhetiheyden', 'kopiointivirhe', 'kopiointivirheen', 'kopiointivirheet', 'kopiointivirheitä'])),
K("Mikä on virusgenomi?",
  "Viruksen perimä: DNA:ta tai RNA:ta, yksi- tai kaksijuosteista, lineaarista tai rengasmaista, muutamasta geenistä satoihin.",
  "",
  1, L('virusgenomi', ['virusgenomeissa', 'virusgenomin', 'virusgenomit'])),
K("Mikä on 5'-pää?",
  "Nukleotidiketjun pää, jossa sokerin 5'-hiilessä on vapaa fosfaatti. Vastapää on 3'-pää, ja synteesi etenee 5'→3'.",
  "",
  3, L(N("5'-pää", "5'-pään", "5'-päähän", "5'-päässä", "5'-päästä", "3'-pää", "3'-pään", "3'-päähän", "3'-päässä", "3'-päästä", "5'→3'", "5'-3'", "viisi-pilkku", "kolme-pilkku", "5’-pää", "3’-pää", "5'-hiili", "5'-hiilen", "3'-hiili", "3'-hiilen"))),
K("Mikä on Rosalind Franklin?",
  "Kemisti, jonka DNA-kuidun röntgendiffraktiokuva 51 paljasti kaksoiskierteen mitat Watsonille ja Crickille 1953. Kuoli 1958 ennen Nobelia.",
  "",
  2, L(N('Rosalind Franklin', 'Rosalind Franklinin', 'Franklin', 'Franklinin', 'Franklinia', 'Wilkins', 'Wilkinsin', 'Maurice Wilkins', 'Maurice Wilkinsin', 'Gosling', 'Goslingin', 'Raymond Gosling'))),
K("Keitä olivat Watson ja Crick?",
  "James Watson ja Francis Crick esittivät DNA:n kaksoiskierremallin 1953 Cambridgessa ja saivat Nobelin 1962 Wilkinsin kanssa.",
  "",
  2, L(N('Watson ja Crick', 'Watsonin ja Crickin', 'Watson', 'Watsonin', 'Watsonille', 'Crick', 'Crickin', 'James Watson', 'Francis Crick', 'Watson-Crick', 'Watson–Crick'))),
K("Mikä on röntgendiffraktio?",
  "Röntgensäteiden sironta kiteestä tai kuidusta säännölliseksi kuvioksi, josta rakenteen mitat lasketaan. Kutsutaan myös: röntgenkristallografia.",
  "",
  2, L(N('röntgendiffraktio', 'röntgendiffraktion', 'röntgendiffraktiota', 'röntgendiffraktiolla', 'röntgenkristallografia', 'röntgenkristallografian', 'röntgenkristallografiaa', 'röntgenkristallografialla', 'diffraktio', 'diffraktion', 'diffraktiota', 'diffraktiokuva', 'diffraktiokuvan', 'diffraktiokuvio', 'diffraktiokuvion', 'DNA-kuitu', 'DNA-kuidun'))),
K("Mikä on Nobelin palkinto?",
  "Alfred Nobelin säätiön vuosittain jakama tieteen huippupalkinto. Watson, Crick ja Wilkins saivat sen 1962, Sanger kahdesti.",
  "",
  1, L(N('Nobelin palkinto', 'Nobelin palkinnon', 'Nobelin palkintoa', 'Nobel-palkinto', 'Nobel-palkinnon', 'Nobel', 'Nobelin', 'Nobelit', 'nobelisti', 'nobelistin', 'nobelistit'))),
K("Mikä on SI-pituusyksikkö molekyylien mittakaavassa?",
  "Metrin murto-osat: nanometri 10<sup>−9</sup> m (DNA:n kierros 3,4 nm), mikrometri 10<sup>−6</sup> m (solu).",
  "",
  2, L(N('nanometri', 'nanometrin', 'nanometriä', 'nanometrissä', 'nanometrit', 'nanometrien', 'nm', 'pikometri', 'pikometrin', 'pikometriä', 'pm', 'mikrometri', 'mikrometrin', 'mikrometriä', 'mikrometrit', 'µm', 'metri', 'metrin', 'metriä', 'SI-yksikkö', 'SI-yksikön', 'SI-yksiköt', 'SI-pituusyksikkö', 'SI-pituusyksikön'))),
K("Mitä pinoutuminen tarkoittaa emäksistä?",
  "Emäsparien tasojen asettumista päällekkäin kaksoiskierteessä. Hydrofobiset pinoutumisvoimat vakauttavat kierteen enemmän kuin vetysidokset.",
  "",
  2, L(N('pinoutuminen', 'pinoutumisen', 'pinoutumista', 'pinoutumisesta', 'pinoutua', 'pinoutuu', 'pinoutuvat', 'pinoutumisvoima', 'pinoutumisvoiman', 'pinoutumisvoimat', 'pinoutumisvuorovaikutus', 'pinoutumisvuorovaikutuksen', 'stacking', 'base stacking'))),
K("Mikä on rakennusohje geenin merkityksessä?",
  "Geeniin tallennettu emäsjärjestys, joka määrää proteiinin aminohappojärjestyksen. Kutsutaan myös: ohje, koodi.",
  "",
  1, L(N('rakennusohje', 'rakennusohjeen', 'rakennusohjetta', 'rakennusohjeet', 'rakennusohjeiden', 'rakennusohjeita', 'ohje', 'ohjeen', 'ohjetta', 'ohjeet', 'ohjeiden', 'ohjeita'))),
K("Mikä on välittäjämolekyyli tiedonsiirrossa?",
  "Molekyyli, joka kantaa tiedon vaiheesta toiseen: lähetti-RNA DNA:lta ribosomille, siirtäjä-RNA kodonilta aminohapolle.",
  "",
  1, L(N('välittäjämolekyyli', 'välittäjämolekyylin', 'välittäjämolekyyliä', 'välittäjämolekyylit', 'välittäjämolekyylien', 'välittäjämolekyylejä'))),
K("Mikä on solunjakautuminen?",
  "Emosolun jakautuminen kahdeksi tytärsoluksi. Sitä ennen DNA kahdentuu replikaatiossa, jotta kumpikin saa täyden perimän.",
  "",
  2, L(N('solunjakautuminen', 'solunjakautumisen', 'solunjakautumista', 'solunjakautumisessa', 'solunjakautumiseen', 'solun jakautuminen', 'solun jakautumisen', 'solun jakautumista', 'jakautuminen', 'jakautumisen', 'jakautumista', 'jakautua', 'jakautuu', 'jakautuvat', 'jakautumassa', 'emosolu', 'emosolun', 'emosolua', 'tytärsolu', 'tytärsolun', 'tytärsolua', 'tytärsolut', 'tytärsolujen', 'tytärsoluja'))),
]

# kolmas kierros: sanasto3.py
import sanasto3
L1 += sanasto3.SOLU_L1
L2 += sanasto3.SOLU_L2
L3 += sanasto3.SOLU_L3
L4a += sanasto3.SOLU_L4a

# massakierros (omistaja 13.9.2026): sanasto_massa/<avain>.txt
import sanasto_massa
L1 += sanasto_massa.kortit("solu_L1")
L2 += sanasto_massa.kortit("solu_L2")
L3 += sanasto_massa.kortit("solu_L3")
L4a += sanasto_massa.kortit("solu_L4a")
