# -*- coding: utf-8 -*-
"""Solu- ja biomolekyylit, Luento 4a - Biologinen tiedonsiirto ja evoluutio (4a. Biologinen tiedonsiirto ja evoluutio.pdf):
keskusdogma, nukleiinihappojen rakenne, transkriptio, eukaryoottien RNA:n muokkaus. Rakentaa tyokalut/solu_kortit.py.
DNA, RNA, nukleotidi, nukleiinihappo, keskusdogma, transkriptio, translaatio, lahetti-RNA, komplementaarisuus ja
RNA-maailmahypoteesi on maaritelty Luento 1:ssa - niihin linkitetaan."""
from biotek_taivutus import L
from pakka_rakenna import K

PDF = '4a. Biologinen tiedonsiirto ja evoluutio.pdf'
LEHTI = 'Luento 4a - Biologinen tiedonsiirto ja evoluutio'
NRO = 4
KUVAT = {
    'solu4_nukleotidi.png': (PDF, 13, 'kuva'), 'solu4_polynukleotidi.png': (PDF, 24, 'kuva'), 'solu4_emasparit.jpg': (PDF, 35, 'kuva'),
    'solu4_abz.jpg': (PDF, 38, 'kuva'), 'solu4_transkriptio.png': (PDF, 44, 'kuva'), 'solu4_lac.png': (PDF, 50, 'kuva'),
    'solu4_saatelyelementit.png': (PDF, 53, 'sivu'), 'solu4_silmukointi.jpg': (PDF, 60, 'kuva'),
}

KORTIT = [
# ── keskusdogma ────────────────────────────────────────────────────────────────────────
K("Mihin solun toiminta perustuu?",
  "Genomiin tallentuneeseen informaatioon sekä sen kopiointiin ja siirtämiseen eri muodoissa.",
  "Solun toiminta perustuu sen genomiin tallentuneeseen informaatioon ja sen kopiointiin ja siirtämiseen eri muodoissa: DNA:sta DNA:ksi replikaatiossa, DNA:sta RNA:ksi transkriptiossa ja RNA:sta proteiiniksi translaatiossa. Nämä informationaaliset makromolekyylit kytkee toisiinsa molekyylibiologian keskusdogma, jonka Crick esitti vuonna 1956. DNA sisältää ohjeet kaikkiin solun mahdollisiin toimintoihin, ja transkriptiossa valitaan, mitä niistä kulloinkin ilmennetään.",
  3),
K("Mihin suuntaan informaatio kulkee keskusdogman mukaan?",
  "Vain yhteen suuntaan: DNA → RNA → proteiini. Proteiinista tieto ei koskaan palaa nukleiinihappoihin.",
  "Keskusdogman mukaan informaatio liikkuu DNA:sta RNA:han transkriptiossa ja RNA:sta proteiiniin translaatiossa, ei koskaan proteiinista takaisin nukleiinihappoihin. DNA kopioituu myös itsekseen replikaatiossa. Normaalisolussa RNA:sta ei tehdä DNA:ta eikä RNA:ta kopioida, mutta virukset rikkovat tätä: retrovirusten käänteinen transkriptaasi tekee RNA:sta DNA:ta ja RNA-virusten replikaasi kopioi RNA:ta. Proteiinista nukleiinihappoon tieto ei kulje koskaan.",
  3),
K("Mitä replikaatio on ja kuinka tarkkaa se on?",
  "DNA:n kopiointia kahdeksi kopioksi solunjakautumisessa. Virhefrekvenssi eukaryooteilla 10<sup>−9</sup>, prokaryooteilla 10<sup>−6</sup>.",
  "Replikaatiossa DNA:sta tuotetaan solunjakautumisen yhteydessä kaksi periaatteessa identtistä kopiota, jotta kumpikin tytärsolu saa koko perimän. Replikaatiota katalysoi DNA-polymeraasi apuproteiineineen, ja kaksoiskierteen rakenne tekee sen helpoksi: vastinjuosteet erotetaan ja kummallekin syntetisoidaan uusi vastinjuoste, mitä kutsutaan semikonservatiiviseksi malliksi. Virhefrekvenssi on eukaryooteilla noin 10<sup>−9</sup> ja prokaryooteilla 10<sup>−6</sup> nukleotidia kohti, ja harvat virheet ovat evoluution raaka-ainetta.",
  3, L('replikaatio', ['DNA-polymeraasi', 'DNA-polymeraasin', 'DNA-polymeraasia', 'semikonservatiivinen replikaatio', 'semikonservatiivisen replikaation', 'semikonservatiivinen', 'semikonservatiivisen'])),
K("Mitä käänteiskopiointi on?",
  "Retroviruksen käänteisen transkriptaasin tekemä DNA-kopio viruksen RNA-perimästä.",
  "Normaalisolussa informaatio ei kulje RNA:sta DNA:han. Retroviruksilla, kuten HIV:llä, perimäaines on RNA:ta, ja niiden käänteinen transkriptaasi tekee viruksen RNA:sta DNA-kopion, joka liitetään isäntäsolun genomiin. Sieltä isäntäsolun oma koneisto transkriboi ja transloi viruksen geenit. Käänteinen transkriptaasi on tärkeä molekyylibiologian työkalu, jolla lähetti-RNA:sta tehdään komplementaarista DNA:ta. Kutsutaan myös: käänteinen transkriptio.",
  2, L('käänteiskopiointi', ['käänteinen transkriptio', 'käänteisen transkription', 'käänteistä transkriptiota', 'käänteinen transkriptaasi', 'käänteisen transkriptaasin', 'käänteistä transkriptaasia', 'retrovirus', 'retroviruksen', 'retrovirusta', 'retovirukset', 'retrovirukset', 'retrovirusten', 'retoviruksia', 'retroviruksia'])),
K("Miten RNA-virus tulee toimeen ilman DNA:ta?",
  "Sen replikaasi kopioi RNA:ta suoraan, ja RNA-perimä voi sisältää suoraan proteiinien rakennusohjeet.",
  "Normaalisolussa RNA:ta ei kopioida, mutta viruksilla voi olla RNA-riippuvainen RNA-polymeraasi eli replikaasi, joka kopioi viruksen RNA-genomin. RNA-viruksen perimä voi suoraan sisältää rakennusohjeet sen proteiineille, jolloin isäntäsolun ribosomit transloivat sen sellaisenaan eikä DNA:ta tarvita lainkaan. Näin toimivat esimerkiksi koronavirukset ja influenssavirus. RNA-polymeraaseilta puuttuu korjauslukukyky, joten RNA-virukset mutatoituvat nopeasti.",
  2, L(['replikaasi', 'replikaasin', 'replikaasia', 'RNA-riippuvainen RNA-polymeraasi', 'RNA-riippuvaisen RNA-polymeraasin', 'RNA-virus', 'RNA-viruksen', 'RNA-virusta', 'RNA-virukset', 'RNA-virusten', 'RNA-viruksia'])),
K("Mikä on kodoni?",
  "Kolmen nukleotidin jakso lähetti-RNA:ssa, joka vastaa yhtä aminohappoa.",
  "Translaatiossa RNA:n nukleotidijärjestyksen mukaan tuotetaan proteiini niin, että aina kolmea nukleotidia eli kodonia vastaa yksi aminohappo. Neljästä nukleotidista saa 64 eri kolmikkoa, joista 61 koodaa 20 aminohappoa ja kolme on lopetuskodoneja. Aloituskodoni AUG koodaa metioniinia, prokaryooteilla formyylimetioniinia. Koska kodoneja on enemmän kuin aminohappoja, useimpia aminohappoja vastaa useampi kodoni, mitä sanotaan koodin degeneroituneisuudeksi.",
  3, L('kodoni', ['aloituskodoni', 'aloituskodonin', 'aloituskodonia', 'lopetuskodoni', 'lopetuskodonin', 'lopetuskodonia', 'lopetuskodonit', 'stop-kodoni', 'stop-kodonin'])),
K("Mikä toteuttaa translaation?",
  "Ribosomi, RNA:sta ja proteiineista koostuva molekulaarinen koneisto.",
  "Translaation toteuttaa ribosomi, RNA:sta ja proteiineista koostuva molekulaarinen koneisto, joka lukee lähetti-RNA:n kodoneja ja liittää siirtäjä-RNA:iden tuomat aminohapot ketjuksi. Ribosomi on valtava: eukaryootin ribosomin massa on noin 4,7 miljoonaa daltonia, kun tavallinen entsyymi, kuten lysotsyymi, painaa 16 000 daltonia. Ribosomin katalyyttinen ydin on ribosomaalista RNA:ta, ei proteiinia, mikä tukee RNA-maailmahypoteesia.",
  3),
# ── nukleiinihappojen rakenne ─────────────────────────────────────────────────────────
K("Millaisia polymeerejä nukleiinihapot ovat?",
  "Nukleotidien lineaarisia polymeerejä, jotka voivat esiintyä myös suljettuina renkaina.",
  "Nukleiinihapot, DNA ja RNA, ovat nukleotidien lineaarisia polymeerejä, joissa peräkkäiset nukleotidit on liitetty fosfodiesterisidoksin. Molemmat voivat esiintyä myös suljettuina renkaina: bakteerien genomit ja plasmidit ovat useimmiten rengasmaisia DNA-molekyylejä, ja jotkin geenit koodaavat rengasmaisia RNA-molekyylejä, joita ei transloida proteiineiksi. Eukaryoottien kromosomit ovat lineaarisia, mutta mitokondrioiden DNA on rengas.",
  2, L(['rengas-DNA', 'rengas-DNA:n', 'rengas-DNA:ta', 'circRNA', 'circRNA:n'])),
K("Mistä osista nukleotidi koostuu?",
  "Typpipitoisesta rengasrakenteisesta emäksestä, pentoosisokerista ja yhdestä tai useammasta fosfaattiryhmästä.",
  "Nukleotidissa on kolme osaa: typpipitoinen rengasrakenteinen emäs, joka on puriini tai pyrimidiini, viisihiilinen pentoosisokeri, riboosi tai deoksiriboosi, ja fosfaattiryhmä tai -ryhmiä. Emäs on kiinni sokerin 1'-hiilessä ja fosfaatti 5'-hiilessä. Emäksen ja sokerin hiilet numeroidaan erikseen, ja sokerin hiilet merkitään heittomerkillä, jota sanotaan pilkuksi: 5' on viisi-pilkku. Kuvassa ribonukleotidi, jossa 2'-hydroksyyli on korostettu.",
  3, '', 'solu4_nukleotidi.png'),
K("Mitä eroa on puriineilla ja pyrimidiineillä?",
  "Molemmat ovat aromaattisia typpipitoisia heterorenkaita. Pyrimidiineissä on yksi rengas, puriineissa kaksi.",
  "Nukleotidien emäkset ovat aromaattisia heterorenkaita, joissa on hiilten lisäksi typpeä. Pyrimidiineissä on yksi kuusirengas: sytosiini C, tymiini T, jota on vain DNA:ssa, ja urasiili U, jota on vain RNA:ssa. Puriineissa on kaksi yhteen liittynyttä rengasta: adeniini A ja guaniini G. Kaksoiskierteessä puriini pariutuu aina pyrimidiinin kanssa, joten emäsparien leveys on vakio ja kierre on tasapaksu.",
  3, L('puriini', 'pyrimidiini')),
K("Mitkä ovat DNA:n ja RNA:n emäkset?",
  "Molemmissa adeniini, guaniini ja sytosiini. DNA:ssa lisäksi tymiini, RNA:ssa sen tilalla urasiili.",
  "",
  3, L('adeniini', 'guaniini', 'sytosiini', 'tymiini', 'urasiili')),
K("Mitä eroa on nukleotidilla ja nukleosidilla?",
  "Nukleosidi on pelkkä emäs ja sokeri ilman fosfaattia. Nukleotidissa on lisäksi fosfaatti.",
  "Pelkän emäksen ja riboosin muodostama yhdiste on nukleosidi: adeniinia vastaa adenosiini, guaniinia guanosiini, sytosiinia sytidiini ja urasiilia uridiini. Nukleosidilla ei ole fosfaattiosaa. Kun sokerin 5'-hiileen liitetään yksi, kaksi tai kolme fosfaattia, syntyy nukleotidi, esimerkiksi adenosiinimonofosfaatti AMP, ADP ja ATP. Nukleiinihappojen rakenneosat ovat nukleotideja, ja nukleosidien johdannaisia käytetään myös lääkkeinä, kuten viruslääke asikloviiri.",
  3, L('nukleosidi', ['adenosiini', 'adenosiinin', 'adenosiinia', 'guanosiini', 'guanosiinin', 'guanosiinia'])),
K("Mitä eroa on ribonukleotidilla ja deoksiribonukleotidilla?",
  "RNA:n riboosissa on 2'-hydroksyyli, DNA:n deoksiriboosissa sen tilalla vety, mikä tekee DNA:sta stabiilimman.",
  "RNA on ribonukleiinihappo, jonka sokeri on riboosi. Riboosin 2'-hiilen hydroksyyliryhmä mahdollistaa vetysidokset muiden molekyylien kanssa ja RNA:n monimutkaiset rakenteet, mutta altistaa myös fosfodiesterisidoksen katkeamiselle. DNA on deoksiribonukleiinihappo, jonka deoksiriboosissa 2'-hiilessä on hydroksyylin sijaan vety, mikä tekee rakenteesta stabiilimman ja sopivamman perimän pitkäaikaiseen säilytykseen. Deoksinukleotidit merkitään d-etuliitteellä: dAMP, dTMP.",
  3, L('riboosi', 'deoksiriboosi', ['ribonukleotidi', 'ribonukleotidin', 'ribonukleotidia', 'ribonukleotidit', 'deoksiribonukleotidi', 'deoksiribonukleotidin', 'deoksiribonukleotidia', 'deoksiribonukleotidit'])),
K("Mitä tehtäviä nukleotideilla on nukleiinihappojen lisäksi?",
  "Energian kantajia (ATP, GTP), koentsyymien osia (NAD, FAD, CoA), säätelymolekyylejä (cAMP, cGMP) ja aktivoituja välituotteita.",
  "Nukleotidit ovat nukleiinihappojen rakenneosia, mutta niillä on monia muitakin tehtäviä. ATP ja GTP ovat yleiskäyttöisiä biosynteettisen energian kantajia. Useissa koentsyymeissä on adeniiniosa: NAD, FAD ja koentsyymi A. Sykliset nukleotidit cAMP ja cGMP ovat säätely- ja välittäjämolekyylejä solun signaloinnissa. Lisäksi useissa biosynteesiteissä on aktivoituja välituotteita, jotka ovat nukleotidijohdannaisia, kuten UDP-glukoosi glykogeenin synteesissä.",
  2),
K("Mikä on fosfodiesterisidos?",
  "Sidos, joka liittää peräkkäisten nukleotidien 5'- ja 3'-hiilet fosfaatin kautta nukleiinihapon rungoksi.",
  "Nukleiinihapoissa fosfodiesterisidos yhdistää peräkkäisten nukleotidien 5'- ja 3'-hiilet: yhden nukleotidin 5'-fosfaatti on sitoutunut edellisen nukleotidin sokerin 3'-hydroksyyliin. Näin syntyy sokeri-fosfaatti-runko, josta emäkset työntyvät sivulle. Ketjulla on suunta: toisessa päässä on vapaa 5'-fosfaatti ja toisessa vapaa 3'-hydroksyyli. Nukleotidijärjestys ilmoitetaan 5'-päästä 3'-päähän, ja yleensä emästen tunnuskirjaimet ACGT tai ACGU riittävät.",
  3, L('fosfodiesterisidos', ['polynukleotidi', 'polynukleotidin', 'polynukleotidia', 'polynukleotidit', 'polynukleotidiketju', 'polynukleotidiketjun', 'polynukleotidiketjua']), 'solu4_polynukleotidi.png'),
# ── DNA:n rakenteen selvittaminen ──────────────────────────────────────────────────────
K("Mitkä ovat Chargaffin säännöt?",
  "Emäskoostumus on lajille ominainen ja sama kaikissa kudoksissa, ja aina A = T ja G = C.",
  "Erwin Chargaff tutki eri DNA:iden emäskoostumuksia 1950-luvun alussa ja havaitsi neljä sääntöä. Eri lajien emäskoostumus on yleensä erilainen. Saman eliön eri kudoksissa emäskoostumus on samanlainen. Ikä, ravinto tai ympäristö ei vaikuta eliön DNA:n emäskoostumukseen. Kaikissa DNA-näytteissä adeniinin määrä on yhtä suuri kuin tymiinin, ja guaniinin sama kuin sytosiinin. Neljäs sääntö oli ratkaiseva vihje emäspariutumisesta Watsonille ja Crickille.",
  3, L(['Chargaffin säännöt', 'Chargaffin sääntöjen', 'Chargaffin sääntöjä', 'Chargaffin sääntö', 'Chargaffin säännön', 'Chargaffin sääntöä'])),
K("Mitä Franklin ja Wilkins osoittivat röntgensädediffraktiolla?",
  "DNA on kierteinen, ja rakenteessa on kaksi jaksollisuutta: 3,4 Å ja 34 Å.",
  "Rosalind Franklin ja Maurice Wilkins osoittivat röntgensädediffraktiolla, että DNA on rakenteeltaan kierteinen ja että siinä on kaksi jaksollisuutta, 3,4 Å ja 34 Å. Raymond Gosling otti Franklinin ryhmässä väitöskirjatutkijana kuuluisan kuvan 51 DNA-kuidun B-muodosta, ja Wilkins jakoi kuvan James Watsonille ilman lupaa. Watson ja Crick kehittivät kaksoiskierremallin pääosin Chargaffin, Franklinin ja Wilkinsin tulosten perusteella. Watson, Crick ja Wilkins saivat Nobelin 1962, Franklin oli kuollut 1958.",
  2, L(['röntgensädediffraktio', 'röntgensädediffraktion', 'röntgensädediffraktiota', 'röntgensädediffraktiolla', 'kuva 51', 'kuvan 51', 'photo 51'])),
K("Mikä on ångström?",
  "Molekyylirakenteiden tutkimuksessa käytetty pituusyksikkö, 0,1 nm eli 10<sup>−10</sup> m. Ei SI-yksikkö.",
  "Ångström, Å, on 0,1 nanometriä eli 10<sup>−10</sup> metriä. Se ei ole SI-yksikkö, mutta sitä käytetään yleisesti molekyylirakenteiden tutkimuksessa, koska atomien väliset etäisyydet ovat muutaman ångströmin luokkaa: tyypillinen hiili–hiili-sidos on 1,54 Å ja vetysidos noin 3 Å. DNA:n emäsparien väli on 3,4 Å ja kierteen nousu 34 Å. Yksikkö on nimetty ruotsalaisen fyysikon Anders Ångströmin mukaan.",
  2, L(['ångström', 'ångströmin', 'ångströmiä', 'ångströmit', 'ångströmejä', 'angström', 'angströmin'])),
K("Millainen on Watsonin ja Crickin DNA-malli?",
  "Kaksi vastakkaissuuntaista polynukleotidiketjua kiertyy toistensa ympäri, emäkset keskellä pareittain: A–T ja G–C.",
  "Watsonin ja Crickin mallissa kaksi vastakkaissuuntaista eli antiparalleelia polynukleotidiketjua kiertyy toistensa ympäri niin, että sokeri-fosfaatti-rungot ovat ulkona ja emäkset keskellä. Emäkset ovat aina pareittain: adeniini pariutuu tymiinin ja guaniini sytosiinin kanssa, mikä selittää Chargaffin neljännen säännön. Emästen pinoutumisesta päällekkäin seuraa 3,4 Å:n jaksollisuus, ja 34 Å vastaa kierteen nousua, joten yhdelle kierrokselle mahtuu 10 emäsparia.",
  3, L(['kaksoiskierre', 'kaksoiskierteen', 'kaksoiskierrettä', 'kaksoiskierteessä', 'kaksoiskierteestä', 'kaksoiskierteeseen', 'kaksoiskierteet', 'Watsonin ja Crickin malli', 'Watsonin ja Crickin mallin', 'Watsonin ja Crickin mallia', 'antiparalleeli', 'antiparalleelin', 'antiparalleelit', 'antiparalleelisuus', 'vastakkaissuuntainen', 'vastakkaissuuntaiset'])),
K("Mitkä ovat Watson–Crick-emäsparit ja montako vetysidosta niissä on?",
  "A–T kahdella vetysidoksella ja G–C kolmella.",
  "Spesifiset vetysidokset voivat muodostua vain oikeiden eli komplementaaristen emäsparien välille. Adeniinin ja tymiinin välissä on kaksi vetysidosta, guaniinin ja sytosiinin välissä kolme, joten GC-rikas DNA on tiiviimmin sidottu ja sulaa korkeammassa lämpötilassa. Kummassakin parissa puriini on pyrimidiinin vastapäätä, joten parien leveys on lähes sama, noin 11 Å, ja kierre pysyy tasapaksuna. Kuvassa emäsparit ja vetysidosten pituudet.",
  3, L(['emäspari', 'emäsparin', 'emäsparia', 'emäsparissa', 'emäsparit', 'emäsparien', 'emäspareja', 'emäspareissa', 'Watson-Crick-emäspari', 'Watson-Crick-emäsparit', 'emäspariutuminen', 'emäspariutumisen', 'emäspariutumista']), 'solu4_emasparit.jpg'),
K("Mitkä ovat DNA:n suuri ja pieni ura?",
  "Kaksi kierteistä uraa fosfodiesteriketjujen välissä. Uriin sitoutuvat proteiinit tunnistavat emäsjärjestyksen kierrettä avaamatta.",
  "Koska kaksi juostetta eivät ole tasan vastakkain kierteen akselin ympärillä, fosfodiesteriketjujen väliin jää kaksi eri levyistä kierteistä uraa, suuri ura ja pieni ura. Emäsparien reunat ovat näkyvissä urien pohjalla, ja suuressa urassa jokaisella emäsparilla on oma vetysidoskuvionsa. Siksi uriin sitoutuvat proteiinit, kuten E. colin lac-repressori, pystyvät tunnistamaan tietyn nukleoemäsjärjestyksen kaksoiskierrettä avaamatta. Kutsutaan myös: major groove, minor groove.",
  2, L(['suuri ura', 'suuren uran', 'suurta uraa', 'suuressa urassa', 'pieni ura', 'pienen uran', 'pientä uraa', 'pienessä urassa'])),
K("Mitä ovat DNA:n A-, B- ja Z-muodot?",
  "B on fysiologinen Watson–Crick-muoto, A kompaktimpi vedettömissä oloissa ja RNA:ssa, Z vasenkätinen säätelysekvensseissä.",
  "Watsonin ja Crickin malli tunnetaan DNA:n B-muotona, ja se vastaa parhaiten satunnaisen DNA:n rakennetta fysiologisissa olosuhteissa. A-muoto vallitsee vedettömissä olosuhteissa: siinä emäkset ovat kallistuneet kierteen akselin suhteen ja rakenne on kompaktimpi, ja RNA:n kaksoiskierteet ovat aina A-muotoa. Vasenkätinen Z-DNA esiintyy ilmeisesti luonnossa eräissä säätelysekvensseissä, ja vuorottelevat puriinit ja pyrimidiinit, erityisesti G ja C, suosivat sen syntymistä.",
  2, L(['B-DNA', 'B-DNA:n', 'B-DNA:ta', 'B-muoto', 'B-muodon', 'B-muotoa', 'A-DNA', 'A-DNA:n', 'A-muoto', 'A-muodon', 'A-muotoa', 'Z-DNA', 'Z-DNA:n', 'Z-DNA:ta', 'Z-muoto', 'Z-muodon']), 'solu4_abz.jpg'),
K("Millainen on RNA:n rakenne?",
  "Yksinauhainen, mutta komplementaariset jaksot pariutuvat A-muotoisiksi kaksoiskierteiksi, joista syntyy monimutkaisia kolmiulotteisia rakenteita.",
  "RNA on yksinauhaista, mutta emäsjärjestyksestä riippuen saman nauhan komplementaariset jaksot voivat liittyä yhteen ja muodostaa kaksoiskierteisiä jaksoja, hiusneulasilmukoita. Kaksoiskierteet ovat vain A-muotoa, koska riboosin 2'-hydroksyyli estää steerisesti B-muodon. Näiden yhdistelminä voi syntyä hyvin monimutkaisia kolmiulotteisia rakenteita, ja kuten proteiineilla, järjestys määrää rakenteen. Joillakin RNA-molekyyleillä on katalyyttisiä ominaisuuksia, ja niitä kutsutaan ribotsyymeiksi.",
  3, L(['hiusneulasilmukka', 'hiusneulasilmukan', 'hiusneulasilmukkaa', 'hiusneulasilmukat', 'hiusneularakenne', 'hiusneularakenteen'])),
K("Mikä on ribotsyymi?",
  "RNA-molekyyli, jolla on katalyyttisiä ominaisuuksia eli joka toimii entsyymin tavoin.",
  "Ribotsyymi on RNA-molekyyli, joka katalysoi kemiallista reaktiota kuten entsyymi. Sen kolmiulotteinen rakenne muodostaa aktiivisen keskuksen, jossa esimerkiksi RNA katkaistaan tai liitetään. Ribosomin peptidisidoksen muodostava keskus on ribotsyymi, ja silmukoinnin katalysoi RNA. Ribotsyymit tukevat RNA-maailmahypoteesia, jonka mukaan aivan ensimmäisillä eliöillä RNA toimi sekä geneettisenä materiaalina että entsyymeinä, ennen kuin DNA ja proteiinit ottivat tehtävät.",
  3, L('ribotsyymi')),
# ── transkriptio ───────────────────────────────────────────────────────────────────────
K("Mistä RNA-polymeraasi saa energian nukleotidin liittämiseen?",
  "Nukleotidit ovat trifosfaatteja, ja kaksi fosfaattia vapautuu liittämisen yhteydessä.",
  "RNA-polymeraasi syntetisoi RNA-polymeeriä solussa olevista vapaista nukleotideista, joiden on oltava trifosfaattimuodossa: ATP, GTP, CTP ja UTP. Kun nukleotidi liitetään ketjun 3'-päähän, sen kaksi ulointa fosfaattia vapautuvat liuokseen pyrofosfaattina, ja fosfoanhydridisidosten energia ajaa fosfodiesterisidoksen muodostumisen. Pyrofosfaatin vesikatkaisu kahdeksi fosfaatiksi tekee reaktiosta käytännössä palautumattoman, samaan tapaan kuin DNA:n replikaatiossa.",
  2, L(['RNA-polymeraasi', 'RNA-polymeraasin', 'RNA-polymeraasia', 'RNA-polymeraasissa', 'RNA-polymeraasit', 'RNA-polymeraasien'])),
K("Miten RNA-polymeraasi lukee DNA:ta?",
  "Se erottaa juosteet ja rakentaa mallijuosteelle komplementaarisen RNA:n 5'→3'-suuntaan lukien mallia 3'→5'.",
  "Polymeraasi sitoutuu DNA:han ja erottaa sen juosteet toisistaan transkriptiokuplaksi. Ketjuun tulevan nukleotidin pitää muodostaa Watson–Crick-pari mallijuosteen seuraavan nukleotidin kanssa, joten syntyvä RNA on komplementaarinen mallijuosteelle. RNA-synteesi on mahdollista vain 5'→3'-suunnassa, joten polymeraasi lukee mallijuostetta vastakkaisessa suunnassa 3'→5'. Edetessään polymeraasi kiertää DNA:ta, ja syntyvän jännitteen purkavat topoisomeraasit.",
  3, L(['mallijuoste', 'mallijuosteen', 'mallijuostetta', 'mallijuosteessa', 'transkriptiokupla', 'transkriptiokuplan', 'transkriptiokuplaa', 'topoisomeraasi', 'topoisomeraasin', 'topoisomeraasit']), 'solu4_transkriptio.png'),
K("Mikä on koodaava juoste?",
  "Mallijuosteen vastinjuoste, jonka sekvenssi on sama kuin RNA:n, paitsi että T:n tilalla on U.",
  "RNA-polymeraasi lukee mallijuostetta, mutta syntyvä RNA on sen komplementti ja siten identtinen mallijuosteen vastinjuosteen kanssa, paitsi että tymiinin tilalla on urasiili. Tätä vastinjuostetta kutsutaan koodaavaksi eli sense-juosteeksi, ja siksi DNA-sekvenssit kirjoitetaan yleensä koodaavan juosteen mukaan 5'→3'-suunnassa: geenin sekvenssi luetaan suoraan kuin lähetti-RNA. Eri geenien koodaava juoste voi olla kumpi tahansa DNA:n juosteista.",
  2, L(['koodaava juoste', 'koodaavan juosteen', 'koodaavaa juostetta', 'koodaavassa juosteessa', 'sense-juoste', 'sense-juosteen', 'antisense-juoste', 'antisense-juosteen'])),
K("Miten rifampisiini toimii?",
  "Tuberkuloosilääke, joka estää spesifisesti bakteerien RNA-polymeraasin.",
  "Transkriptio on soluille elintärkeä toiminto, ja monien antibioottien toiminta perustuu RNA-polymeraasin spesifiseen estämiseen. Rifampisiini sitoutuu bakteerin RNA-polymeraasiin ja tukkii kanavan, jota pitkin syntyvä RNA poistuu, joten transkriptio pysähtyy muutaman nukleotidin jälkeen. Eukaryoottien RNA-polymeraasit ovat rakenteeltaan erilaisia eivätkä sido rifampisiinia, mikä tekee lääkkeestä valikoivan bakteereja vastaan ilman vaikutusta potilaan omiin soluihin.",
  1, L('rifampisiini')),
K("Mikä on promoottori?",
  "DNA-sekvenssi, jonka RNA-polymeraasi tunnistaa ja jonka vierestä se aloittaa transkription.",
  "Koko DNA:ta ei transkriboida, vaan polymeraasi tunnistaa DNA:sta tietyn sekvenssin, promoottorin, ja aloittaa synteesin sen vierestä. E. colin promoottoreissa on kaksi konsensusaluetta, TTGACA ja TATAAT, noin 35 ja 10 emäsparia ennen aloituskohtaa, ja RNA-polymeraasi taivuttaa DNA:ta niin, että molemmat ovat kontaktissa tunnistuskohtiinsa. Geenien transkriptiota säätelevät promoottorin kohdalle tai viereen sitoutuvat proteiinit, jotka aktivoivat tai repressoivat geenejä solun tarpeiden mukaan.",
  3, L('promoottori')),
K("Mikä on terminaattori?",
  "DNA:n ohjaussekvenssi, jonka kohdalla transkriptio päättyy.",
  "Transkriptio jatkuu promoottorista, kunnes polymeraasi kohtaa toisen ohjaussekvenssin, terminaattorin. Prokaryooteilla terminaattorissa on koodaavassa juosteessa polytymiinijakso TTTTT, jota edeltää käänteinen toisto. Transkriboitu RNA muodostaa toistosta hiusneulasilmukan, joka johtaa polymeraasin irtoamiseen, tai erityinen Rho-proteiini avustaa terminaatiossa. Syntynyttä RNA-molekyyliä kutsutaan transkriptiksi. Eukaryooteilla transkription päättyminen kytkeytyy transkriptin 3'-pään leikkaukseen ja poly-A-hännän lisäykseen.",
  2, L('terminaattori', ['Rho-proteiini', 'Rho-proteiinin', 'Rho-tekijä', 'Rho-tekijän', 'terminaatio', 'terminaation', 'terminaatiota', 'terminaatiossa'])),
K("Mikä on transkripti?",
  "Transkriptiossa syntynyt RNA-molekyyli.",
  "",
  3, L('transkripti', ['primääritranskripti', 'primääritranskriptin', 'primääritranskriptiä', 'primääritranskriptissä', 'primääritranskriptistä'])),
K("Miten lac-operonia säädellään?",
  "LacI-repressori peittää promoottorin. Laktoosista syntyvä allolaktoosi inaktivoi repressorin, ja polymeraasi pääsee transkriboimaan.",
  "E. colin lac-operoni sisältää laktoosin käytön geenit yhden promoottorin takana. Sen transkriptiota säätelee lacI-geenin koodaama repressori LacI, joka sitoutuu operonin säätelyalueelle operaattoriin ja peittää promoottorin, jolloin RNA-polymeraasi ei pääse aloittamaan. Kun laktoosia on saatavilla, se muutetaan allolaktoosiksi, joka sitoutuu repressoriin ja inaktivoi sen. Repressori irtoaa, ja polymeraasi voi transkriboida operonin geenit. Näin geenit ilmennetään vain, kun laktoosia on.",
  2, L(['lac-operoni', 'lac-operonin', 'lac-operonia', 'lac-operonissa', 'operoni', 'operonin', 'operonia', 'operonissa', 'operonit', 'operonien', 'repressori', 'repressorin', 'repressoria', 'repressorit', 'repressorien', 'operaattori', 'operaattorin', 'operaattoria', 'operaattoriin', 'allolaktoosi', 'allolaktoosin', 'allolaktoosia']), 'solu4_lac.png'),
K("Mitä eroa on polykistronisella ja monokistronisella lähetti-RNA:lla?",
  "Polykistroninen koodaa useaa proteiinia, monokistroninen yhtä. Prokaryooteilla molempia, eukaryooteilla vain monokistronisia.",
  "Prokaryooteilla proteiinia koodaavan geenin transkripti on suoraan lähetti-RNA, ja yksi lähetti-RNA voi koodata useaa proteiinia, jolloin se on polykistroninen: operonin geenit transkriboidaan yhdeksi molekyyliksi, jossa on jokaiselle proteiinille oma aloitus- ja lopetuskodoni. Eukaryooteilla yksi transkripti koodaa yhtä proteiinia, ja lähetti-RNA on monokistroninen. Monokistronisia lähetti-RNA:ita esiintyy myös prokaryooteilla. Kistroni on proteiinia koodaava DNA:n osa.",
  2, L(['polykistroninen', 'polykistronisen', 'polykistronista', 'monokistroninen', 'monokistronisen', 'monokistronista', 'kistroni', 'kistronin', 'kistronia', 'sistroni', 'sistronin'])),
K("Mitkä ovat tyypillisen prokaryoottisen geenin säätelyelementit?",
  "Promoottori, ribosomin sitoutumiskohta, aloituskodoni ATG, lopetuskodoni ja terminaattori.",
  "Kuvassa prokaryoottisen geenin rakenne DNA:ssa, lähetti-RNA:ssa ja proteiinissa. Promoottori edeltää transkription aloituskohtaa. Transkriptiin kopioituvat ribosomin sitoutumiskohta AGGAG, aloituskodoni AUG, koodaava alue, lopetuskodoni UAG ja terminaattorin hiusneula. Ribosomi sitoutuu sitoutumiskohtaan ja aloittaa translaation aloituskodonista, joka prokaryooteilla koodaa formyylimetioniinia, ja lopettaa lopetuskodoniin. Terminaattori päättää transkription lopetuskodonin jälkeen.",
  3, L(['ribosomin sitoutumiskohta', 'ribosomin sitoutumiskohdan', 'ribosomin sitoutumiskohtaa', 'RBS', 'formyylimetioniini', 'formyylimetioniinin', 'formyylimetioniinia', 'fMet']), 'solu4_saatelyelementit.png'),
K("Mitkä ovat prokaryoottisen transkription vaiheet?",
  "Polymeraasin sitoutuminen, transkriptiokuplan muodostuminen, aloitus, elongaatio, sigma-yksikön vaihtuminen NusA:ksi ja päättyminen.",
  "Transkriptio etenee kuudessa vaiheessa. RNA-polymeraasi sitoutuu sigma-tekijänsä avulla promoottoriin. DNA:n juosteet erotetaan transkriptiokuplaksi. Transkriptio alkaa ensimmäisten nukleotidien liittämisellä. Elongaatiossa polymeraasi etenee pitkin DNA:ta ja pidentää RNA:ta. Sigma-yksikkö, jota tarvittiin vain promoottorin tunnistukseen, vaihtuu NusA-proteiiniksi. Lopulta polymeraasi kohtaa terminaattorin ja transkriptio päättyy, jolloin RNA ja polymeraasi irtoavat DNA:sta.",
  2, L(['sigma-tekijä', 'sigma-tekijän', 'sigma-tekijää', 'sigma-yksikkö', 'sigma-yksikön', 'elongaatio', 'elongaation', 'elongaatiota', 'elongaatiossa'])),
K("Mitkä ovat tärkeimmät RNA-lajit?",
  "Proteiineja koodaava lähetti-RNA, ribosomin rakenteellinen ribosomaalinen RNA ja aminohappoja tuova siirtäjä-RNA.",
  "Tärkeimmät RNA-lajit ovat lähetti-RNA, joka kantaa geenin ohjeen tumasta ribosomille, ribosomaalinen RNA, joka on ribosomin rakenteellinen ja katalyyttinen osa, ja siirtäjä-RNA, joka tuo aminohapot proteiinisynteesiin ja tunnistaa antikodonillaan lähetti-RNA:n kodonin. Ribosomaalista RNA:ta on solun RNA:sta ylivoimaisesti eniten. Lisäksi soluissa on pieniä säätely-RNA:ita, kuten mikro-RNA:t. Kutsutaan myös: mRNA, rRNA, tRNA.",
  3, L(['siirtäjä-RNA', 'siirtäjä-RNA:n', 'siirtäjä-RNA:ta', 'siirtäjä-RNA:ssa', 'siirtäjä-RNA:t', 'tRNA', 'tRNA:n', 'tRNA:ta', 'ribosomaalinen RNA', 'ribosomaalisen RNA:n', 'ribosomaalista RNA:ta', 'rRNA', 'rRNA:n', 'rRNA:ta'])),
# ── eukaryoottien RNA:n muokkaus ──────────────────────────────────────────────────────
K("Mitä ovat eksonit ja intronit?",
  "Eksonit ovat geenin koodaavia alueita, intronit niiden välissä olevia ei-koodaavia alueita, jotka poistetaan silmukoinnissa.",
  "Eukaryooteilla geenien koodaavien alueiden eli eksonien välissä on ei-koodaavia alueita, introneja. Molemmat transkriboidaan primääritranskriptiin, mutta intronit poistetaan silmukoinnissa ja eksonit liitetään yhteen lähetti-RNA:ksi. Eksonit vastaavat usein proteiinin toiminnallisia osia, domeeneja. Koska rekombinaatio osuu todennäköisimmin pitkään introniin, ehjät eksonit rekombinoituvat ja voivat yhdistyä uusiksi geeneiksi, mikä on evoluutiossa tuottanut uusia proteiineja.",
  3, L('eksoni', 'introni')),
K("Mitä silmukointi on?",
  "Intronien poisto primääritranskriptista ja eksonien liittäminen yhteen leikkaa-liimaa-periaatteella, jolloin syntyy lähetti-RNA.",
  "Silmukoinnissa useat RNA:ta prosessoivat entsyymit ja pienet RNA-molekyylit, jotka muodostavat silmukointikoneiston, leikkaavat intronit pois primääritranskriptista ja liimaavat eksonit yhteen. Katalyysin tekee RNA, joten silmukointikoneisto on ribotsyymi. Silmukointi tapahtuu tumassa ennen kuin lähetti-RNA viedään solulimaan. Sama geeni voidaan silmukoida eri tavoilla, jolloin yhdestä primääritranskriptista syntyy eri proteiineja, mitä kutsutaan vaihtoehtoiseksi silmukoinniksi. Kutsutaan myös: splicing.",
  3, L('silmukointi', ['vaihtoehtoinen silmukointi', 'vaihtoehtoisen silmukoinnin', 'vaihtoehtoista silmukointia', 'silmukointikoneisto', 'silmukointikoneiston', 'spliseosomi', 'spliseosomin'])),
K("Mitä muokkauksia eukaryoottien lähetti-RNA saa tumassa?",
  "5'-päähän huppurakenne, 3'-päähän poly-A-häntä, intronien silmukointi ja ylimääräisen RNA:n leikkaus.",
  "Eukaryooteilla primääritranskripti muokataan tumassa ennen solulimaan vientiä. Sen 5'-päähän lisätään erityinen huppurakenne, muokattu guaniininukleotidi, joka suojaa RNA:ta hajotukselta ja ohjaa ribosomin sitoutumista. Sen 3'-päästä leikataan ylimääräinen RNA pois ja tilalle lisätään poly-A-häntä, satoja adeniineja, joka lisää stabiilisuutta. Intronit poistetaan silmukoinnissa. Kuvassa ovalbumiinigeenin 7700 emäsparin transkriptista syntyy 1872 nukleotidin lähetti-RNA.",
  3, L(['huppurakenne', 'huppurakenteen', 'huppurakennetta', '5\'-huppu', '5\'-hupun', 'cap-rakenne', 'poly-A-häntä', 'poly-A-hännän', 'poly-A-häntää', 'polyadenylaatio', 'polyadenylaation', 'polyadenylaatiota', 'posttranskriptionaalinen muokkaus', 'posttranskriptionaalisen muokkauksen', 'posttranskriptionaalisia muokkauksia', 'posttranskriptionaaliset muokkaukset']), 'solu4_silmukointi.jpg'),
K("Missä replikaatio, transkriptio ja translaatio tapahtuvat eukaryoottisolussa?",
  "Replikaatio ja transkriptio tumassa, translaatio solulimassa.",
  "",
  3),
K("Miksi lähetti-RNA hajotetaan?",
  "Jotta proteiinin tuottonopeutta ja määrää voidaan säädellä. Transkription ja hajotuksen tasapaino määrää lähetti-RNA:n määrän.",
  "Lähetti-RNA:t hajotetaan jonkin ajan kuluttua nukleaasien toimesta, jotta proteiinin tuottonopeutta ja määrää solussa voidaan säädellä: pysyvä lähetti-RNA tuottaisi proteiinia loputtomiin, vaikka tarve olisi ohi. Transkription ja hajotuksen välinen tasapaino määrää, kuinka paljon lähetti-RNA:ta on solussa. Eukaryooteilla poly-A-hännän lyheneminen ja hupun poisto käynnistävät hajotuksen, ja eri lähetti-RNA:iden elinajat vaihtelevat minuuteista päiviin.",
  2, L(['nukleaasi', 'nukleaasin', 'nukleaasia', 'nukleaasit', 'nukleaasien'])),
]
