# -*- coding: utf-8 -*-
"""Solu- ja biomolekyylit, Luento 1 - sanaston taydennys (omistaja 12.9.2026: 'aivan joka ikinen sana pitaa maaritella').
Termikortit kalvojen sanoille, joilla ei ollut maaritelmakorttia. Numerot 1.301-, pakka sama kuin Luento 1:n.
Rakentaa tyokalut/solu_kortit.py."""
from biotek_taivutus import L
from pakka_rakenna import K

LEHTI = 'Luento 1 - Elämä, perusteet ja periaatteet'
TIEDOSTO = 'Luento 1 - Sanasto (lisays)'
NRO = 1
ALKU = 300
KUVAT = {}

KORTIT = [
K("Mitä biokemia on?",
  "Elämän kemiaa: tiede, joka tutkii eliöiden molekyylejä, niiden rakenteita ja reaktioita.",
  "Biokemia tutkii elämän perustan muodostavien molekyylien rakennetta ja toimintaa: proteiineja, nukleiinihappoja, hiilihydraatteja ja lipidejä sekä niiden reaktioita, kuten geenien säätelyä ja entsyymien katalyysiä. Se yhdistää kemian ja biologian ja on perustutkimusta, jonka tuloksia biotekniikka soveltaa. Biokemian keskeinen ajatus on, että elämän ilmiöt selittyvät molekyylien rakenteista ja vuorovaikutuksista ilman erillistä elämänvoimaa.",
  3, L('biokemia')),
K("Mikä on geeni?",
  "DNA:n jakso, joka sisältää ohjeen yhden RNA-molekyylin tai proteiinin valmistamiseen.",
  "Geeni on perimän toiminnallinen yksikkö: DNA:n jakso, jonka nukleoemäsjärjestys koodaa RNA-molekyylin ja useimmiten sen kautta proteiinin. Geeniin kuuluvat koodaavan alueen lisäksi säätelyalueet, kuten promoottori, jotka määräävät, milloin ja missä soluissa geeni ilmennetään. Ihmisellä on noin 20 000 proteiinia koodaavaa geeniä, ja ne muodostavat vain pari prosenttia genomista.",
  3, L('geeni')),
K("Mitä geenin ilmentyminen tarkoittaa?",
  "Geenin tiedon lukemista käyttöön: transkriptiota RNA:ksi ja translaatiota proteiiniksi.",
  "Geenin ilmentyminen eli ekspressio on prosessi, jossa geenin sisältämä tieto muutetaan toimivaksi tuotteeksi. Ensin geeni transkriboidaan RNA:ksi ja lähetti-RNA transloidaan proteiiniksi. Solu säätelee ilmentymistä tarpeen mukaan, joten saman genomin soluista tulee erilaisia: maksasolu ja hermosolu ilmentävät eri geenejä. Ilmentymisen säätely on solujen erilaistumisen ja ympäristöön reagoimisen perusta. Kutsutaan myös: ekspressio, geeniekspressio.",
  3, L(['geenin ilmentyminen', 'geenin ilmentymisen', 'geenin ilmentymistä', 'ilmentyminen', 'ilmentymisen', 'ilmentymistä', 'ilmennetään', 'ilmentää', 'ilmentävät', 'ekspressio', 'ekspression', 'ekspressiota', 'ekspressoidaan', 'geeniekspressio', 'geeniekspression'])),
K("Mikä on peptidisidos?",
  "Amidisidos, joka liittää aminohapon karboksyyliryhmän seuraavan aminohapon aminoryhmään.",
  "Peptidisidos syntyy kondensaatioreaktiossa, kun yhden aminohapon karboksyyliryhmä ja toisen aminoryhmä liittyvät yhteen ja vettä irtoaa. Sidos on amidisidos: tasomainen ja jäykkä, koska typen elektronipari delokalisoituu karbonyylille, eikä sen ympäri voi kiertää. Peptidisidokset liittävät aminohapot polypeptidiketjuksi, ja ketjun runko toistaa kuviota typpi, alfahiili, karbonyylihiili. Sidos katkeaa vesikatkaisulla proteaasien avulla.",
  3, L('peptidisidos')),
K("Mikä on polypeptidi?",
  "Peptidisidoksin liitetty aminohappoketju. Proteiini koostuu yhdestä tai useammasta polypeptidistä.",
  "Polypeptidi on lineaarinen ketju aminohappoja, jotka on liitetty toisiinsa peptidisidoksin. Ketjulla on suunta: toisessa päässä on vapaa aminoryhmä, N-pää, ja toisessa vapaa karboksyyliryhmä, C-pää. Lyhyitä ketjuja kutsutaan peptideiksi, ja proteiini on yksi tai useampi laskostunut polypeptidi. Aminohappojen järjestys polypeptidissä määrää sen laskostumisen ja siten proteiinin toiminnan.",
  3, L('polypeptidi', 'peptidi')),
K("Mikä on alfakierre?",
  "Proteiinin sekundaarirakenne, jossa polypeptidiketju kiertyy oikeakätiseksi spiraaliksi vetysidosten tukemana.",
  "Alfakierteessä polypeptidin runko kiertyy oikeakätiseksi ruuviksi, jossa jokaisen karbonyylin happi muodostaa vetysidoksen neljä aminohappoa myöhemmän amidivedyn kanssa. Kierroksella on 3,6 aminohappoa ja nousu 5,4 Å. Sivuketjut osoittavat ulospäin kierteestä. Alfakierre on beetalaskoksen ohella yleisin sekundaarirakenne, ja esimerkiksi keratiini ja monet kalvoproteiinien kalvonläpäisevät osat ovat alfakierteitä. Kutsutaan myös: alfaheliksi, α-kierre.",
  3, L('alfakierre', ['alfaheliksi', 'alfaheliksin', 'alfaheliksiä', 'alfaheliksit', 'α-kierre', 'α-kierteen', 'α-heliksi'])),
K("Mikä on aminohapon sivuketju?",
  "Aminohapon alfahiileen sitoutunut vaihteleva ryhmä, joka erottaa 20 aminohappoa toisistaan.",
  "Jokaisessa aminohapossa alfahiileen on sitoutunut aminoryhmä, karboksyyliryhmä, vety ja sivuketju, jota merkitään R. Sivuketju on ainoa osa, joka vaihtelee: glysiinillä se on vety, alaniinilla metyyli, kysteiinillä sulfhydryyli ja lysiinillä pitkä aminoryhmään päättyvä ketju. Sivuketjujen kemia, poolisuus, varaus ja koko, määrää proteiinin laskostumisen, vuorovaikutukset ja entsyymien katalyysin. Kutsutaan myös: R-ryhmä.",
  3, L('sivuketju', ['R-ryhmä', 'R-ryhmän', 'R-ryhmää', 'R-ryhmät'])),
K("Mikä on glysiini?",
  "Pienin aminohappo, jonka sivuketju on pelkkä vety.",
  "Glysiini on ainoa aminohappo, jolla ei ole kiraalista keskusta, koska sen alfahiileen on sitoutunut kaksi vetyä. Pienen sivuketjun ansiosta se mahtuu ahtaisiin kohtiin ja antaa polypeptidiketjulle joustavuutta, joten se on yleinen käänteissä ja kollageenin tiheässä kolmoiskierteessä, jossa joka kolmas aminohappo on glysiini. Se toimii myös hermoston välittäjäaineena.",
  2, L('glysiini')),
K("Mikä on hiiliketju?",
  "Toisiinsa sitoutuneiden hiiliatomien muodostama molekyylin runko.",
  "Hiili muodostaa neljä kovalenttista sidosta ja voi sitoutua toisiin hiiliin lähes rajattomasti, joten hiiliatomeista syntyy suoria, haarautuneita ja rengasmaisia ketjuja. Tämä hiiliketju eli hiilirunko on orgaanisten molekyylien selkäranka, johon funktionaaliset ryhmät kiinnittyvät. Rasvahapon häntä on suora hiiliketju, sokerit renkaita ja bentseeni aromaattinen rengas. Hiilen ketjuuntumiskyky on syy siihen, että elämä rakentuu hiilelle.",
  3, L('hiiliketju', 'hiilirunko')),
K("Mikä on hiilivety?",
  "Yhdiste, joka koostuu vain hiilestä ja vedystä.",
  "Hiilivedyt ovat yksinkertaisimpia orgaanisia yhdisteitä: hiiliketju, jonka kaikkiin vapaisiin sidoksiin on liittynyt vetyä, kuten metaani, etaani ja bentseeni. Ne ovat poolittomia ja vettä hylkiviä, koska hiilen ja vedyn elektronegatiivisuudet ovat lähes samat. Biomolekyyleissä hiilivetyosat, kuten rasvahappojen hännät ja aminohappojen alkyyliketjut, muodostavat hydrofobiset alueet, jotka kokoavat kalvot ja proteiinien sisukset.",
  2, L('hiilivety')),
K("Mikä on funktionaalinen ryhmä?",
  "Molekyylin osa, tietty atomiryhmä, joka määrää, miten molekyylin se kohta reagoi.",
  "Funktionaalinen ryhmä on hiilirunkoon kiinnittynyt atomiryhmä, kuten hydroksyyli, karbonyyli, karboksyyli, amino tai fosforyyli, jolla on aina samat kemialliset ominaisuudet molekyylistä riippumatta. Ryhmä määrää, millaisia sidoksia kyseinen kohta muodostaa ja miten se reagoi: karboksyyli on happo, amino emäs, hydroksyyli vetysidoksen muodostaja. Biomolekyylien kemia on pitkälti niiden funktionaalisten ryhmien kemiaa.",
  3, L(['funktionaalinen ryhmä', 'funktionaalisen ryhmän', 'funktionaalista ryhmää', 'funktionaalisessa ryhmässä', 'funktionaaliset ryhmät', 'funktionaalisten ryhmien', 'funktionaalisia ryhmiä'])),
K("Mikä on aromaattinen rengas?",
  "Tasomainen rengas, jonka p-elektronit jakautuvat koko renkaalle ja tekevät siitä erityisen vakaan.",
  "Aromaattisessa renkaassa, kuten bentseenissä, kuusi hiiltä muodostaa tasomaisen kuusikulmion, jonka p-elektronit eivät ole yksittäisissä kaksoissidoksissa vaan jakautuvat tasaisesti koko renkaalle. Delokalisaatio vakauttaa rakennetta ja antaa renkaalle taipumuksen pinoutua toisten renkaiden päälle. Aminohapoista fenyylialaniini, tyrosiini ja tryptofaani ovat aromaattisia, ja nukleoemäkset sekä klorofyllin rengas ovat aromaattisia heterorenkaita, joissa on myös typpeä.",
  2, L(['aromaattinen rengas', 'aromaattisen renkaan', 'aromaattista rengasta', 'aromaattiset renkaat', 'aromaattinen', 'aromaattisen', 'aromaattista', 'aromaattisia', 'aromaattisuus', 'aromaattisuuden'])),
K("Mikä on isomeeri?",
  "Yhdiste, jolla on sama molekyylikaava kuin toisella mutta eri rakenne.",
  "Isomeerit ovat molekyylejä, joissa on samat atomit samassa määrässä mutta eri tavalla järjestettyinä. Rakenneisomeereissä atomit on sidottu toisiinsa eri järjestyksessä, kuten glukoosi ja fruktoosi. Stereoisomeereissä sidokset ovat samat mutta atomien asento avaruudessa eroaa, kuten peilikuvaiset enantiomeerit ja cis- ja trans-muodot. Isomeerit voivat käyttäytyä biologisesti aivan eri tavoin, koska entsyymit tunnistavat molekyylin muodon. Kutsutaan myös: isomeria.",
  3, L('isomeeri', 'isomeria', ['rakenneisomeeri', 'rakenneisomeerin', 'rakenneisomeerit', 'rakenneisomeria'])),
K("Mikä on glukoosi?",
  "Kuusihiilinen aldehydisokeri, solujen tärkein energianlähde ja tärkkelyksen, glykogeenin ja selluloosan rakenneyksikkö.",
  "Glukoosi C<sub>6</sub>H<sub>12</sub>O<sub>6</sub> on monosakkaridi, jossa on kuusi hiiltä, aldehydiryhmä ja viisi hydroksyyliryhmää. Vesiliuoksessa se on lähes kokonaan rengasmuodossa, jossa aldehydi on muodostanut hemiasetaalin 5-hiilen hydroksyylin kanssa. Glukoosi on solujen tärkein polttoaine: glykolyysi ja soluhengitys hapettavat sen hiilidioksidiksi ja vedeksi. Varastomuotoja ovat tärkkelys ja glykogeeni, ja selluloosa on sen rakennepolymeeri. Kutsutaan myös: rypälesokeri.",
  3, L('glukoosi', ['rypälesokeri', 'rypälesokerin', 'rypälesokeria'])),
K("Mikä on monosakkaridi?",
  "Yksinkertainen sokeri, jota ei voi hajottaa pienemmiksi sokereiksi, kuten glukoosi tai fruktoosi.",
  "Monosakkaridi on hiilihydraattien rakenneyksikkö: aldehydi tai ketoni, jossa on lisäksi useita hydroksyyliryhmiä ja tavallisesti kolmesta seitsemään hiiltä. Kuusihiilisiä heksooseja ovat glukoosi, fruktoosi ja galaktoosi, viisihiilisiä pentooseja riboosi ja deoksiriboosi. Monosakkaridit liittyvät glykosidisidoksin disakkarideiksi ja polysakkarideiksi. Ne ovat vesiliukoisia ja makeita, ja glukoosi on solun tärkein energianlähde.",
  3, L('monosakkaridi', ['yksinkertainen sokeri', 'yksinkertaisen sokerin', 'yksinkertaisia sokereita', 'heksoosi', 'heksoosin', 'heksoosit'])),
K("Mikä on disakkaridi?",
  "Kahdesta monosakkaridista glykosidisidoksella liittynyt sokeri, kuten sakkaroosi tai laktoosi.",
  "Disakkaridi syntyy, kun kahden monosakkaridin hydroksyyliryhmät liittyvät kondensaatiossa glykosidisidokseksi ja vettä irtoaa. Sakkaroosi eli ruokosokeri on glukoosi ja fruktoosi, laktoosi eli maitosokeri glukoosi ja galaktoosi, maltoosi kaksi glukoosia. Disakkaridit pilkotaan ruoansulatuksessa entsyymeillä takaisin monosakkarideiksi: sakkaraasi pilkkoo sakkaroosin ja laktaasi laktoosin, ja laktaasin puute aikuisilla aiheuttaa laktoosi-intoleranssin.",
  3, L('disakkaridi', ['sakkaroosi', 'sakkaroosin', 'sakkaroosia', 'laktoosi', 'laktoosin', 'laktoosia', 'maltoosi', 'maltoosin'])),
K("Mikä on polysakkaridi?",
  "Monosakkarideista koostuva pitkä polymeeri, kuten tärkkelys, glykogeeni tai selluloosa.",
  "Polysakkaridi on satojen tai tuhansien monosakkaridien ketju, jonka yksiköt on liitetty glykosidisidoksin. Tärkkelys ja glykogeeni ovat glukoosin varastomuotoja kasveissa ja eläimissä, ja niiden haarautunut rakenne mahdollistaa nopean pilkkomisen. Selluloosa on glukoosin rakennepolymeeri, jonka toisenlainen sidos tekee siitä suoran ja lujan kuidun, jota ihmisen entsyymit eivät pilko. Kitiini ja peptidoglykaani ovat muita rakennepolysakkarideja.",
  3, L('polysakkaridi', ['glykogeeni', 'glykogeenin', 'glykogeenia', 'glykogeeniin'])),
K("Mikä on glykosidisidos?",
  "Sokeriyksiköt toisiinsa liittävä kovalenttinen sidos, joka syntyy kahden hydroksyylin kondensaatiossa.",
  "Glykosidisidos muodostuu, kun monosakkaridin anomeerisen hiilen hydroksyyli reagoi toisen molekyylin hydroksyylin kanssa ja vettä irtoaa. Sokerien välillä sidos liittää yksiköt di- ja polysakkarideiksi, ja sen suunta ratkaisee polymeerin muodon: tärkkelyksen alfa-sidokset antavat kierteisen, selluloosan beeta-sidokset suoran ketjun. Nukleotideissa glykosidisidos liittää emäksen sokeriin. Sidos katkeaa vesikatkaisulla.",
  3, L('glykosidisidos')),
K("Mikä on hemiasetaali?",
  "Rakenne, jossa aldehydin hiileen on liittynyt sekä hydroksyyli että eetterihappi. Sokerien rengasmuodon perusta.",
  "Hemiasetaali syntyy, kun alkoholin hydroksyyli liittyy aldehydin karbonyylihiileen, jolloin hiileen jää hydroksyyli ja eetterihappi. Sokereissa reaktio tapahtuu molekyylin sisällä: glukoosin aldehydi reagoi oman 5-hiilensä hydroksyylin kanssa, ja syntyy kuusijäseninen rengas. Rengasmuoto on vesiliuoksessa tasapainossa avoimen ketjun kanssa, ja renkaan uusi kiraalinen keskus tuottaa alfa- ja beetamuodot. Ketonisokerit muodostavat vastaavasti hemiketaaleja.",
  2, L('hemiasetaali')),
K("Mikä on glyseraldehydi?",
  "Kolmihiilinen aldehydisokeri, yksinkertaisin kiraalinen sokeri ja L/D-nimeämisen vertailukohta.",
  "Glyseraldehydi on pienin aldoosi: kolme hiiltä, aldehydiryhmä ja kaksi hydroksyyliä. Sen keskimmäinen hiili on kiraalinen, joten sitä on kaksi peilikuvamuotoa, D ja L. Kaikkien sokerien D- ja L-muodot nimetään vertaamalla niiden kauimmaista kiraalista hiiltä glyseraldehydiin. Glyseraldehydi-3-fosfaatti on glykolyysin ja fotosynteesin keskeinen välituote, jossa sokerin hajotus ja rakentaminen kohtaavat.",
  2, L('glyseraldehydi')),
K("Mikä on fosfolipidi?",
  "Kalvolipidi, jossa glyseroliin on liittynyt kaksi rasvahappoa ja fosfaattiryhmä. Muodostaa lipidikaksoiskerroksen.",
  "Fosfolipidissä glyserolin kahteen hydroksyyliin on esteröitynyt rasvahappo ja kolmanteen fosfaatti, johon on usein liittynyt koliini tai muu poolinen ryhmä. Molekyyli on amfipaattinen: fosfaattipää on hydrofiilinen ja rasvahappohännät hydrofobisia. Vedessä fosfolipidit järjestyvät itsestään kaksoiskerrokseksi, jossa hännät ovat sisällä ja päät vettä vasten. Tämä lipidikaksoiskerros on kaikkien solukalvojen perusrakenne.",
  3, L('fosfolipidi', ['lipidikaksoiskerros', 'lipidikaksoiskerroksen', 'lipidikaksoiskerrosta', 'lipidikaksoiskerroksessa', 'kaksoiskerros', 'kaksoiskerroksen', 'kaksoiskerrosta', 'kaksoiskerroksessa'])),
K("Mikä on epäorgaaninen yhdiste?",
  "Yhdiste, joka ei perustu hiilirunkoon, kuten vesi, suolat ja mineraalit.",
  "Epäorgaanisia yhdisteitä ovat vesi, hapot, emäkset, suolat ja metallien yhdisteet sekä yksinkertaiset hiilen yhdisteet, kuten hiilidioksidi ja karbonaatit. Eliöt tarvitsevat niitä: vesi on liuotin, fosfaatti ja ammonium ovat rakennusaineita, ja metalli-ionit, kuten magnesium, rauta ja sinkki, ovat entsyymien apuaineita. Elämän kemia alkaa epäorgaanisista lähtöaineista, joista autotrofit rakentavat orgaaniset yhdisteet.",
  2, L(['epäorgaaninen yhdiste', 'epäorgaanisen yhdisteen', 'epäorgaanista yhdistettä', 'epäorgaaniset yhdisteet', 'epäorgaanisten yhdisteiden', 'epäorgaanisia yhdisteitä', 'epäorgaaninen', 'epäorgaanisen', 'epäorgaanista', 'epäorgaanisia'])),
K("Mikä on orgaaninen yhdiste?",
  "Hiilirunkoon perustuva yhdiste, jossa hiileen on sitoutunut vetyä ja usein happea, typpeä, rikkiä tai fosforia.",
  "Orgaaniset yhdisteet ovat hiilen yhdisteitä, joissa hiiliketjuun on liittynyt vetyä ja funktionaalisia ryhmiä. Kaikki biomolekyylit, sokerit, lipidit, aminohapot ja nukleotidit, ovat orgaanisia, samoin muovit ja polttoaineet. Nimi on peräisin ajalta, jolloin uskottiin, että niitä syntyy vain elävissä olennoissa, kunnes Wöhler valmisti ureaa epäorgaanisista lähtöaineista 1828. Orgaaninen kemia on hiiliyhdisteiden kemiaa.",
  2, L(['orgaaninen yhdiste', 'orgaanisen yhdisteen', 'orgaanista yhdistettä', 'orgaaniset yhdisteet', 'orgaanisten yhdisteiden', 'orgaanisia yhdisteitä', 'orgaaninen', 'orgaanisen', 'orgaanista', 'orgaanisia', 'orgaaninen kemia', 'orgaanisen kemian'])),
K("Mitä hapettuminen tarkoittaa?",
  "Elektronien luovuttamista. Hiiliyhdisteissä usein vedyn menetystä tai hapen liittymistä.",
  "Hapettumisessa atomi tai molekyyli luovuttaa elektroneja, jolloin sen hapetusluku kasvaa. Orgaanisessa kemiassa hapettuminen näkyy hiilen sidosten muutoksena: alkoholi hapettuu aldehydiksi, aldehydi karboksyylihapoksi ja lopulta hiilidioksidiksi, kun vetyjä poistuu ja happea liittyy. Ravintoaineiden hapettuminen soluhengityksessä vapauttaa energian, joka varastoidaan ATP:hen. Hapettumista seuraa aina jonkin toisen aineen pelkistyminen. Kutsutaan myös: oksidaatio.",
  3, L('hapettuminen', ['hapettua', 'hapettuu', 'hapettuvat', 'hapetetaan', 'hapettaa', 'hapettamalla', 'hapetus', 'hapetuksen', 'hapetusta', 'oksidaatio', 'oksidaation', 'oksidaatiota'])),
K("Mitä pelkistyminen tarkoittaa?",
  "Elektronien vastaanottamista. Hiiliyhdisteissä usein vedyn liittymistä tai hapen poistumista.",
  "Pelkistymisessä atomi tai molekyyli vastaanottaa elektroneja, ja sen hapetusluku pienenee. Biosynteesissä hiili pelkistyy: hiilidioksidista rakennetaan sokereita fotosynteesissä, ja rasvahappojen synteesi pelkistää hiiliketjua vaihe vaiheelta. Elektronit tuo tavallisesti pelkistin, kuten NADH tai NADPH. Pelkistyminen ja hapettuminen ovat aina kytköksissä: kun yksi aine pelkistyy, toinen hapettuu. Kutsutaan myös: reduktio.",
  3, L('pelkistyminen', ['pelkistyä', 'pelkistyy', 'pelkistyvät', 'pelkistetään', 'pelkistää', 'pelkistys', 'pelkistyksen', 'pelkistystä', 'pelkistynyt', 'pelkistyneitä', 'reduktio', 'reduktion', 'reduktiota'])),
K("Mikä on Gibbsin vapaaenergia?",
  "Reaktion käyttökelpoinen energia: ΔG kertoo, tapahtuuko reaktio itsestään ja paljonko työtä siitä saa.",
  "Gibbsin vapaaenergia G yhdistää entalpian ja entropian: ΔG = ΔH − TΔS. Reaktio tapahtuu itsestään vakiopaineessa ja -lämpötilassa vain, jos ΔG on negatiivinen, ja ΔG:n itseisarvo on suurin työmäärä, jonka reaktiosta voi saada. Positiivisen ΔG:n reaktio vaatii energiaa ja etenee vain kytkettynä eksergoniseen reaktioon, kuten ATP:n vesikatkaisuun. Tasapainossa ΔG on nolla. Kutsutaan myös: vapaaenergia, ΔG.",
  3, L(['Gibbsin vapaaenergia', 'Gibbsin vapaaenergian', 'Gibbsin vapaaenergiaa', 'Gibbsin energia', 'Gibbsin energian', 'Gibbsin energiaa', 'vapaaenergia', 'vapaaenergian', 'vapaaenergiaa', 'vapaaenergiassa', 'vapaaenergiasta', 'vapaa energia', 'vapaan energian'])),
K("Mikä on spontaani reaktio?",
  "Reaktio, joka voi tapahtua itsestään ilman ulkoista energiaa, koska sen ΔG on negatiivinen.",
  "Spontaani reaktio etenee itsestään kohti tasapainoa, koska tuotteiden vapaaenergia on lähtöaineita pienempi. Spontaanius ei kerro nopeudesta: glukoosin palaminen on spontaania, mutta ilman entsyymiä tai kipinää se ei tapahdu havaittavasti, koska aktivaatioenergia on suuri. Ei-spontaani reaktio, jonka ΔG on positiivinen, saadaan tapahtumaan kytkemällä se spontaaniin, kuten ATP:n vesikatkaisuun.",
  2, L(['spontaani reaktio', 'spontaanin reaktion', 'spontaania reaktiota', 'spontaanit reaktiot', 'spontaani', 'spontaanin', 'spontaania', 'spontaanisti', 'spontaanius', 'spontaaniuden'])),
K("Mitä termodynamiikka on?",
  "Energian, lämmön ja työn muunnoksia tutkiva fysiikan ala, jonka pääsäännöt määräävät, mitkä reaktiot ovat mahdollisia.",
  "Termodynamiikka kuvaa energian säilymistä ja muuntumista. Ensimmäinen pääsääntö sanoo, että energia säilyy, ja toinen, että maailmankaikkeuden entropia kasvaa jokaisessa itsestään tapahtuvassa prosessissa. Biokemiassa termodynamiikka kertoo, voiko reaktio tapahtua ja paljonko energiaa siitä vapautuu, Gibbsin vapaaenergian avulla. Se ei kerro reaktion nopeutta, joka on kinetiikan ja entsyymien asia.",
  2, L('termodynamiikka')),
K("Mikä on entsyymin substraatti?",
  "Molekyyli, johon entsyymi sitoutuu ja jonka reaktiota se katalysoi.",
  "Substraatti on entsyymin lähtöaine: se sitoutuu entsyymin aktiiviseen keskukseen, jonka muoto ja kemia sopivat juuri siihen, ja muuttuu tuotteeksi. Sitoutumisen spesifisyys selittää, miksi kukin entsyymi katalysoi vain tiettyä reaktiota. Sanaa käytetään laajemminkin: myös kuljetusproteiinin kuljettama molekyyli tai bakteerin käyttämä ravinne on substraatti. Substraatin pitoisuus vaikuttaa entsyymireaktion nopeuteen.",
  3, L('substraatti', ['aktiivinen keskus', 'aktiivisen keskuksen', 'aktiivista keskusta', 'aktiivisessa keskuksessa', 'aktiiviseen keskukseen'])),
K("Mikä on kofaktori?",
  "Entsyymin toimintaan tarvittava ei-proteiininen apuaine: metalli-ioni tai orgaaninen koentsyymi.",
  "Monet entsyymit eivät toimi pelkkänä proteiinina vaan tarvitsevat kofaktorin. Se voi olla metalli-ioni, kuten sinkki, magnesium tai rauta, tai orgaaninen molekyyli, jota kutsutaan koentsyymiksi, kuten NAD<sup>+</sup>, FAD tai koentsyymi A. Kofaktori osallistuu katalyysiin esimerkiksi siirtämällä elektroneja tai ryhmiä, joita aminohapot eivät voi siirtää. Tiukasti sitoutunutta kofaktoria kutsutaan prosteettiseksi ryhmäksi, ja monet koentsyymit ovat vitamiinien johdannaisia.",
  3, L('kofaktori', 'koentsyymi', ['prosteettinen ryhmä', 'prosteettisen ryhmän', 'prosteettista ryhmää', 'prosteettiset ryhmät'])),
K("Mikä on inhibiittori?",
  "Aine, joka hidastaa tai estää entsyymin toimintaa sitoutumalla siihen.",
  "Inhibiittori sitoutuu entsyymiin ja vähentää sen aktiivisuutta. Kilpaileva inhibiittori muistuttaa substraattia ja kilpailee sen kanssa aktiivisesta keskuksesta, jolloin substraatin lisääminen kumoaa eston. Ei-kilpaileva inhibiittori sitoutuu muualle ja muuttaa entsyymin muotoa. Solut säätelevät reaktioteitään inhibiittoreilla, esimerkiksi reaktiotien lopputuote estää sen ensimmäistä entsyymiä. Monet lääkkeet ja myrkyt ovat entsyymi-inhibiittoreita. Kutsutaan myös: estäjä, inhibitio.",
  2, L('inhibiittori', 'inhibitio', ['estäjä', 'estäjän', 'estäjää', 'estäjät', 'estäjien', 'inhiboida', 'inhiboi', 'inhiboivat', 'inhiboituu'])),
K("Mikä on proteiinin alayksikkö?",
  "Yksi polypeptidiketju proteiinissa, joka koostuu useasta ketjusta.",
  "Monet proteiinit ovat useamman polypeptidiketjun yhdelmiä, ja kutakin ketjua kutsutaan alayksiköksi. Hemoglobiinissa on neljä alayksikköä, kaksi alfa- ja kaksi beetaketjua, ja ribosomissa kymmeniä proteiineja ja RNA-molekyylejä. Alayksiköt pysyvät yhdessä ei-kovalenttisin vuorovaikutuksin, ja niiden järjestys on proteiinin kvaternaarirakenne. Alayksiköiden yhteispeli mahdollistaa säätelyn: yhden alayksikön muutos välittyy toisiin.",
  2, L(['kvaternaarirakenne', 'kvaternaarirakenteen', 'kvaternaarirakennetta', 'kvaternäärirakenne', 'kvaternäärirakenteen'])),
K("Mikä on hormoni?",
  "Elimistön viestimolekyyli, jonka rauhanen erittää vereen ja joka säätelee kohdesolujen toimintaa reseptorin kautta.",
  "Hormoni on kemiallinen viesti, jonka umpirauhanen tai muu kudos erittää verenkiertoon ja joka vaikuttaa kaukaisiin kohdesoluihin sitoutumalla niiden reseptoreihin. Hormonit ovat peptidejä, kuten insuliini, aminohappojohdannaisia, kuten adrenaliini, tai steroideja, kuten estrogeeni ja testosteroni. Pieni pitoisuus riittää, koska reseptori vahvistaa viestin solun sisällä. Hormonit säätelevät aineenvaihduntaa, kasvua ja lisääntymistä.",
  3, L('hormoni', ['steroidihormoni', 'steroidihormonin', 'steroidihormonit', 'steroidihormoneja'])),
K("Mikä on immuunijärjestelmä?",
  "Elimistön puolustusjärjestelmä, joka tunnistaa ja tuhoaa taudinaiheuttajat ja vieraat rakenteet.",
  "Immuunijärjestelmä koostuu valkosoluista, vasta-aineista, komplementista ja imukudoksesta, jotka yhdessä erottavat oman vieraasta. Synnynnäinen puolustus, kuten fagosytoosi ja tulehdus, toimii heti ja yleisesti. Hankittu puolustus, B-solujen vasta-aineet ja T-solut, tunnistaa antigeenit tarkasti ja muistaa ne, mihin rokotteet perustuvat. Häiriöt aiheuttavat allergioita ja autoimmuunisairauksia. Kutsutaan myös: immuunipuolustus, immuunipuolustusjärjestelmä.",
  3, L('immuunijärjestelmä', ['immuunipuolustus', 'immuunipuolustuksen', 'immuunipuolustusta', 'immuunipuolustukseen', 'immuunipuolustusjärjestelmä', 'immuunipuolustusjärjestelmän', 'immuunipuolustusjärjestelmää', 'immuunivaste', 'immuunivasteen', 'immuunivastetta', 'immuunivasteessa', 'immuniteetti', 'immuniteetin', 'immuniteettia'])),
K("Mikä on patogeeni?",
  "Tautia aiheuttava mikrobi tai virus.",
  "Patogeeni on organismi tai virus, joka aiheuttaa isännässään sairauden: bakteeri, virus, sieni, alkueläin tai prioni. Sen taudinaiheuttamiskyky eli virulenssi perustuu kykyyn tarttua isännän kudokseen, lisääntyä siellä, väistää immuunipuolustusta ja usein tuottaa toksiineja. Suurin osa mikrobeista ei ole patogeenisia, ja monet ovat hyödyllisiä. Antibiootit, rokotteet ja diagnostiikka kohdistuvat patogeeneihin. Kutsutaan myös: taudinaiheuttaja.",
  3, L('patogeeni', ['taudinaiheuttaja', 'taudinaiheuttajan', 'taudinaiheuttajaa', 'taudinaiheuttajat', 'taudinaiheuttajien', 'taudinaiheuttajia', 'patogeeninen', 'patogeenisen', 'patogeenisia', 'virulenssi', 'virulenssin', 'virulenssia'])),
K("Mikä on mykoplasma?",
  "Pienin tunnettu vapaana elävä solu, soluseinätön bakteeri, halkaisijaltaan noin 300 nm.",
  "",
  1, L('mykoplasma')),
K("Mikä on punasolu?",
  "Hemoglobiinia sisältävä tumaton verisolu, joka kuljettaa happea.",
  "Punasolu on nisäkkäillä tumaton, kaksoiskoveran kiekon muotoinen solu, joka on täynnä hemoglobiinia. Se sitoo hapen keuhkoissa ja luovuttaa sen kudoksiin ja kuljettaa hiilidioksidia takaisin. Tumattomuus ja soluelinten puute antavat tilaa hemoglobiinille ja tekevät solusta taipuisan, jotta se mahtuu hiussuoniin. Punasolu elää noin 120 päivää, ja uusia syntyy luuytimessä. Kutsutaan myös: erytrosyytti.",
  2, L('punasolu', ['erytrosyytti', 'erytrosyytin', 'erytrosyytit'])),
K("Mikä on ravintoaine?",
  "Ruoan sisältämä aine, jota eliö käyttää energian lähteenä tai rakennusaineena.",
  "",
  2, L('ravintoaine')),
K("Mikä on monisoluinen eliö?",
  "Eliö, joka koostuu monista yhteistyötä tekevistä, erilaistuneista soluista.",
  "Monisoluisessa eliössä solut ovat erilaistuneet tehtäviinsä, kuten lihas-, hermo- ja ihosoluiksi, ja muodostavat kudoksia ja elimiä. Solut viestivät keskenään hormoneilla ja kosketuksin, ja yksittäinen solu ei selviä yksin. Eläimet, kasvit ja sienet ovat monisoluisia, ja monisoluisuus on kehittynyt evoluutiossa useita kertoja erikseen. Yksisoluinen eliö sen sijaan hoitaa kaikki elintoiminnot yhdessä solussa, kuten bakteerit ja hiiva.",
  3, L(['monisoluinen eliö', 'monisoluisen eliön', 'monisoluista eliötä', 'monisoluiset eliöt', 'monisoluisten eliöiden', 'monisoluisia eliöitä', 'monisoluinen', 'monisoluisen', 'monisoluista', 'monisoluiset', 'monisoluisilla', 'monisoluisuus', 'yksisoluinen eliö', 'yksisoluisen eliön', 'yksisoluista eliötä', 'yksisoluiset eliöt', 'yksisoluinen', 'yksisoluisen', 'yksisoluista', 'yksisoluiset', 'yksisoluisia'])),
K("Mikä on stromatoliitti?",
  "Syanobakteerien kerroksittain rakentama kivettymä, vanhimpia todisteita elämästä.",
  "",
  1, L('stromatoliitti')),
K("Mitä eukaryogeneesi tarkoittaa?",
  "Tumallisen solun syntyä: arkeonin ja bakteerin yhdistymistä endosymbioosissa noin 1,5–2 miljardia vuotta sitten.",
  "Eukaryogeneesi on evoluution tapahtumasarja, jossa prokaryoottisista esivanhemmista syntyi tumallinen solu. Nykykäsityksen mukaan Asgard-arkeoni otti sisäänsä alfaproteobakteerin, josta tuli mitokondrio, ja arkeonin kalvorakenteista kehittyivät tuma ja endoplasminen kalvosto. Kloroplastit syntyivät myöhemmin syanobakteerin endosymbioosista. Eukaryogeneesi tapahtui ilmeisesti vain kerran, ja kaikki tumalliset, kasvit, eläimet, sienet ja protistit, polveutuvat samasta esisolusta LECA:sta.",
  2, L('eukaryogeneesi')),
K("Mikä on gramvärjäys?",
  "Bakteerien luokittelumenetelmä, jossa soluseinän rakenne määrää, jääkö väri soluun.",
  "Gramvärjäyksessä bakteerit värjätään kristallivioletilla, käsitellään jodilla ja huuhdellaan alkoholilla. Gram-positiivisilla on paksu peptidoglykaanikerros, joka pidättää värin, ja ne näkyvät violetteina. Gram-negatiivisilla peptidoglykaani on ohut ja sitä ympäröi ulkokalvo, joten väri huuhtoutuu ja solut värjäytyvät vastavärillä punaisiksi. Menetelmän kehitti Hans Christian Gram 1884, ja se ohjaa yhä antibiootin valintaa.",
  2, L('gramvärjäys', ['gram-positiivinen', 'gram-positiivisen', 'gram-positiivista', 'gram-positiiviset', 'gram-positiivisia', 'grampositiivinen', 'grampositiiviset'])),
]
