# -*- coding: utf-8 -*-
"""Luento 2 - Vesi, osa 3: pH, puskurointi, elimistön pH, vesi reagenssina.
Jatkaa vesi_L2_kortit_2.py:n listaa (skripti yhdistää osat)."""
from vesi_L2_kortit import K

KORTIT = [
# ── H. pH ─────────────────────────────────────────────────────────────────────
K("Mikä on veden ionitulo K<sub>w</sub>?",
  "Vetyionien ja hydroksidi-ionien konsentraatioiden tulo, 1,0 × 10<sup>−14</sup> M<sup>2</sup> 25 °C:ssa.",
  "Autoprotolyysin tasapainovakio on K<sub>eq</sub> = [H<sup>+</sup>][OH<sup>−</sup>]/[H<sub>2</sub>O]. Koska veden konsentraatio vedessä on käytännössä vakio 55,5 mol/l, se voidaan sisällyttää vakioon, ja saadaan veden ionitulo K<sub>w</sub> = [H<sup>+</sup>][OH<sup>−</sup>] = 1,0 × 10<sup>−14</sup> M<sup>2</sup> lämpötilassa 25 °C. Ionitulo on vakio kaikissa laimeissa vesiliuoksissa: jos happoa lisätään ja [H<sup>+</sup>] kasvaa, [OH<sup>−</sup>] pienenee vastaavasti. Tästä seuraa suoraan, että pH + pOH = 14. Kutsutaan myös: veden ionisaatiovakio, veden autoprotolyysivakio.",
  3, "veden ionitulo, veden ionitulon, veden ionituloa, ionitulo, ionitulon, ionituloa, ionitulosta, Kw, Kw:n, veden ionisaatiovakio, veden ionisaatiovakion"),
K("Mikä on pH?",
  "Vetyionikonsentraation negatiivinen kymmenlogaritmi: pH = −log[H<sup>+</sup>].",
  "pH ilmaisee liuoksen happamuuden logaritmisella asteikolla: pH = −log[H<sup>+</sup>]. Puhtaassa vedessä [H<sup>+</sup>] = 10<sup>−7</sup> M, joten pH on 7 eli neutraali. Yhden pH-yksikön muutos tarkoittaa vetyionikonsentraation kymmenkertaistumista tai kymmenesosaan pienenemistä. Alle 7 liuos on hapan, yli 7 emäksinen. Vastaavasti pOH = −log[OH<sup>−</sup>], ja koska veden ionitulo on vakio, pH + pOH = 14. Elimistön normaali pH on 7,4, ja useimmat entsyymit toimivat vain kapealla pH-alueella.",
  3, "pH, pH:n, pH:ta, pH:ssa, pH:sta, pH:hon, pH:lle, pH:lla, pH-arvo, pH-arvon, pH-arvoa, pH-arvot, pH-arvoja, pH-asteikko, pH-asteikon, pH-asteikolla, pH-alue, pH-alueen, pH-aluetta, pH-alueella, happamuus, happamuuden, happamuutta, happamuudesta"),
K("Mikä on puhtaan veden pH ja miksi?",
  "7, koska [H<sup>+</sup>] = [OH<sup>−</sup>] = 10<sup>−7</sup> M ja −log 10<sup>−7</sup> = 7.",
  "Puhtaassa vedessä autoprotolyysi tuottaa yhtä paljon vetyioneja ja hydroksidi-ioneja, joten [H<sup>+</sup>] = [OH<sup>−</sup>]. Koska niiden tulo on K<sub>w</sub> = 1,0 × 10<sup>−14</sup> M<sup>2</sup>, kummankin konsentraatio on 10<sup>−7</sup> M. Silloin pH = −log 10<sup>−7</sup> = 7 ja samoin pOH = 7. Neutraali pH ei siis tarkoita, että vetyioneja ei olisi, vaan että niitä on yhtä paljon kuin hydroksidi-ioneja. Lämpötilan noustessa K<sub>w</sub> kasvaa ja neutraali pH laskee hieman alle seitsemän.",
  3),
K("Mikä on pOH?",
  "Hydroksidi-ionikonsentraation negatiivinen kymmenlogaritmi: pOH = −log[OH<sup>−</sup>].",
  "pOH kuvaa liuoksen emäksisyyttä samalla tavalla kuin pH happamuutta: pOH = −log[OH<sup>−</sup>]. Koska veden ionitulo K<sub>w</sub> = [H<sup>+</sup>][OH<sup>−</sup>] = 10<sup>−14</sup> M<sup>2</sup> on vakio, pH ja pOH ovat sidoksissa toisiinsa ja niiden summa on aina 14. Neutraalissa liuoksessa molemmat ovat 7, happamassa pH on pieni ja pOH suuri, emäksisessä päinvastoin. Käytännössä emäksisyyskin ilmoitetaan pH:na, mutta pOH tekee näkyväksi, että happo- ja emäskonsentraatiot muuttuvat aina yhdessä.",
  2, "pOH, pOH:n, pOH:ta, pOH:ssa, emäksisyys, emäksisyyden, emäksisyyttä"),
K("Millainen on tavallisten aineiden pH-asteikko?",
  "Mahahappo noin 1–2, kahvi noin 5, veri 7,4, merivesi noin 8, kotitalouden ammoniakki noin 12.",
  "pH-asteikko ulottuu 0:sta (1 M HCl) 14:ään (1 M NaOH). Happamassa päässä ovat mahaneste ja sitruunamehu (noin 1–2), kolajuomat ja viinietikka (noin 3), punaviini ja olut (noin 4) sekä kahvi (noin 5). Maito ja sylki ovat lähellä neutraalia, ihmisen veri ja kyynelneste ovat 7,4, merivesi ja kananmunan valkuainen noin 8. Emäksisiä ovat ruokasoodaliuos (noin 9), kotitalouden ammoniakki (noin 12) ja valkaisuaine (noin 13). Jokainen porras on kymmenkertainen ero vetyionikonsentraatiossa.",
  1, kuva="vesi_d38_155.jpeg"),
# ── I. Puskurointi ────────────────────────────────────────────────────────────
K("Mikä on heikko happo?",
  "Happo, joka dissosioituu vedessä vain osittain ja asettuu tasapainoon vastinemäksensä kanssa.",
  "Heikko happo HA luovuttaa protoninsa vedessä vain osittain: HA ⇌ H<sup>+</sup> + A<sup>−</sup>, ja liuoksessa on tasapainossa sekä happoa että sen vastinemästä A<sup>−</sup>. Vahva happo, kuten HCl, hajoaa käytännössä kokonaan. Heikon hapon taipumusta luovuttaa protoni kuvaa happovakio K<sub>a</sub>. Biokemiassa lähes kaikki merkitykselliset hapot ovat heikkoja: etikkahappo, hiilihappo, fosforihapon eri muodot ja aminohappojen sivuketjut, ja juuri niiden osittainen dissosiaatio tekee puskuroinnin mahdolliseksi. Kutsutaan myös: protonin luovuttaja.",
  3, "heikko happo, heikon hapon, heikkoa happoa, heikossa hapossa, heikkoon happoon, heikot hapot, heikkojen happojen, heikkoja happoja, vastinemäs, vastinemäksen, vastinemästä, vastinemäkseksi, vastinemäkset, vastinemäksiä, konjugaattiemäs, konjugaattiemäksen, konjugaattiemästä, protonin luovuttaja, protonin luovuttajan, protonin luovuttajaa, protonin vastaanottaja, protonin vastaanottajan, protonin vastaanottajaa, happo-emäspari, happo-emäsparin, happo-emäsparit"),
K("Mikä on happovakio K<sub>a</sub>?",
  "Heikon hapon dissosiaation tasapainovakio: K<sub>a</sub> = [H<sup>+</sup>][A<sup>−</sup>]/[HA].",
  "Kun heikko happo HA dissosioituu vedessä, HA ⇌ H<sup>+</sup> + A<sup>−</sup>, tasapainoon pätee K<sub>eq</sub> = [H<sup>+</sup>][A<sup>−</sup>]/[HA] = K<sub>a</sub>. Happovakio kertoo, kuinka hanakasti happo luovuttaa protoninsa: suuri K<sub>a</sub> tarkoittaa vahvaa, pieni heikkoa happoa. Koska arvot ovat hyvin pieniä lukuja, käytetään yleensä pK<sub>a</sub>-arvoa, joka on happovakion negatiivinen logaritmi samaan tapaan kuin pH on vetyionikonsentraation. Etikkahapon K<sub>a</sub> on 1,74 × 10<sup>−5</sup> M eli pK<sub>a</sub> 4,76. Kutsutaan myös: hapon dissosiaatiovakio.",
  3, "happovakio, happovakion, happovakiota, happovakiossa, happovakioon, happovakiot, happovakioiden, happovakioita, dissosiaatiovakio, dissosiaatiovakion, dissosiaatiovakiota, Ka, Ka:n"),
K("Mikä on pK<sub>a</sub>?",
  "Happovakion negatiivinen kymmenlogaritmi: pK<sub>a</sub> = −log K<sub>a</sub>. Se pH, jossa happo on puoliksi dissosioitunut.",
  "pK<sub>a</sub> = −log K<sub>a</sub> on happovakion logaritminen muoto, joka tekee happojen vertailusta helppoa: mitä pienempi pK<sub>a</sub>, sitä vahvempi happo. Käytännössä tärkein tulkinta on, että pK<sub>a</sub> on se pH, jossa hapon ja sen vastinemäksen konsentraatiot ovat yhtä suuret, eli happo on puoliksi titrattu. Alle pK<sub>a</sub>:n happo on pääosin protonoitunut, yli pK<sub>a</sub>:n pääosin dissosioitunut. Etikkahapon pK<sub>a</sub> on 4,76, fosforihapon toisen protonin 6,86 ja histidiinin sivuketjun 6,0.",
  3, "pKa, pKa:n, pKa:ta, pKa:sta, pKa:han, pKa-arvo, pKa-arvon, pKa-arvoa, pKa-arvot, pKa-arvojen, pKa-arvoja"),
K("Mitä titraus tarkoittaa?",
  "Hapon neutraloimista lisäämällä emästä vähitellen ja seuraamalla pH:ta.",
  "Titrauksessa heikon hapon liuokseen lisätään vahvaa emästä, kuten NaOH:a, pienissä erissä ja mitataan pH jokaisen lisäyksen jälkeen. Emäs sitoo protoneja, jolloin happo HA muuttuu vähitellen vastinemäkseksi A<sup>−</sup>. Kun pH piirretään lisätyn emäksen funktiona, saadaan titrauskäyrä, jonka keskikohdassa, hapon ollessa puoliksi titrattu, pH = pK<sub>a</sub>. Käyrän loivin osa pK<sub>a</sub>:n ympärillä on hapon puskurointialue. Kuvassa etikkahapon titrauskäyrä: pK<sub>a</sub> 4,76 ja puskurointialue pH 3,76–5,76.",
  2, "titraus, titrauksen, titrausta, titrauksessa, titrauksesta, titraukseen, titrata, titrattu, titrattaessa, titrauskäyrä, titrauskäyrän, titrauskäyrää, titrauskäyrässä, titrauskäyrät, titrauskäyriä", kuva="vesi_d40_161.jpeg"),
K("Miksi puoliksi titratun heikon hapon pH on yhtä kuin pK<sub>a</sub>?",
  "Silloin [HA] = [A<sup>−</sup>], jolloin Henderson–Hasselbalchin yhtälön logaritmitermi on nolla.",
  "Kun heikkoon happoon on lisätty emästä puoli ekvivalenttia, puolet haposta on muuttunut vastinemäkseksi ja [HA] = [A<sup>−</sup>]. Happovakion lausekkeessa K<sub>a</sub> = [H<sup>+</sup>][A<sup>−</sup>]/[HA] osamäärä [A<sup>−</sup>]/[HA] on silloin 1, joten K<sub>a</sub> = [H<sup>+</sup>] ja pK<sub>a</sub> = pH. Henderson–Hasselbalchin yhtälössä sama näkyy siten, että log([A<sup>−</sup>]/[HA]) = log 1 = 0. Tämä on käytännöllinen tapa mitata pK<sub>a</sub>: titrauskäyrän keskikohdan pH luetaan suoraan.",
  2),
K("Mikä on puskuriliuos?",
  "Heikon hapon ja sen vastinemäksen seos, joka vastustaa pH:n muutosta.",
  "Puskuriliuos sisältää heikkoa happoa ja sen vastinemästä suunnilleen yhtä suurina konsentraatioina. Kun liuokseen lisätään emästä, happo luovuttaa protonin ja neutraloi sen. Kun lisätään happoa, vastinemäs sitoo ylimääräisen protonin. Molemmissa tapauksissa pH muuttuu paljon vähemmän kuin puskuroimattomassa liuoksessa. Puskurointi toimii parhaiten pH:ssa, joka on lähellä hapon pK<sub>a</sub>:ta, ja ulottuu noin yhden pH-yksikön sen molemmin puolin. Solut ja veri ovat puskuroituja fosfaatti- ja bikarbonaattijärjestelmillä. Kutsutaan myös: puskuri.",
  3, "puskuriliuos, puskuriliuoksen, puskuriliuosta, puskuriliuoksessa, puskuriliuoksesta, puskuriliuokseen, puskuriliuokset, puskuriliuosten, puskuriliuoksia, puskuri, puskurin, puskuria, puskurissa, puskurista, puskuriin, puskurit, puskurien, puskureita, puskureissa, puskurointi, puskuroinnin, puskurointia, puskuroida, puskuroi, puskuroitu, puskuroituja, puskuroimaton, puskuroimattomassa"),
K("Mikä on puskurointialue?",
  "pH-alue noin pK<sub>a</sub> ± 1, jolla puskuri vastustaa pH:n muutosta tehokkaasti.",
  "Puskuri toimii parhaiten, kun happoa ja vastinemästä on liuoksessa suunnilleen yhtä paljon, eli pH:n ollessa lähellä pK<sub>a</sub>:ta. Alue ulottuu käytännössä noin yhden pH-yksikön pK<sub>a</sub>:n molemmin puolin, mikä vastaa protonin luovuttajan neutralisaation vaihetta noin 10 prosentista 90 prosenttiin. Etikkahapon pK<sub>a</sub> on 4,76, joten sen puskurointialue on pH 3,76–5,76. Kuvassa kolmen hapon titrauskäyrät: etikkahappo puskuroi noin pH 4,8:ssa, fosfaatti noin 6,9:ssä ja ammonium noin 9,3:ssa, ja puskurin valinta perustuu haluttuun pH:hon.",
  2, "puskurointialue, puskurointialueen, puskurointialuetta, puskurointialueella, puskurointialueelta, puskurointialueelle, puskurialue, puskurialueen, puskurialuetta, puskurialueella", kuva="vesi_d41_164.jpeg"),
K("Miten etikkahappopuskuri vastustaa lisättyä emästä?",
  "Etikkahappo luovuttaa protonin hydroksidille, joka neutraloituu vedeksi, ja tasapaino korjaa [H<sup>+</sup>]:n.",
  "Kun etikkahapon ja asetaatin seokseen lisätään hydroksidi-ioneja, ne sitovat protoneja ja muuttuvat vedeksi. Hetkellisesti [H<sup>+</sup>] laskee, jolloin K<sub>w</sub> = [H<sup>+</sup>][OH<sup>−</sup>] ja happovakion tasapaino K<sub>a</sub> = [H<sup>+</sup>][Ac<sup>−</sup>]/[HAc] eivät enää päde. Tasapainon palauttamiseksi etikkahappo HAc dissosioituu lisää ja vapauttaa protoneja, jotka korvaavat kulutetut. Lisätty happo toimii käänteisesti: asetaatti-ioni Ac<sup>−</sup> vastaanottaa ylimääräiset protonit ja muodostaa etikkahappoa. Kaksi kytkettyä tasapainoa, veden ja hapon, pitävät pH:n lähes vakiona.",
  2, kuva="vesi_d42_167.jpeg"),
K("Mikä on Henderson–Hasselbalchin yhtälö?",
  "pH = pK<sub>a</sub> + log([A<sup>−</sup>]/[HA]). Kertoo puskurin pH:n hapon ja emäksen suhteesta.",
  "Henderson–Hasselbalchin yhtälö pH = pK<sub>a</sub> + log([A<sup>−</sup>]/[HA]) johdetaan suoraan happovakion lausekkeesta ottamalla logaritmi. Siinä [A<sup>−</sup>] on vastinemäksen eli suolan ja [HA] hapon konsentraatio. Yhtälö kertoo, mihin pH:hon tietty happo-emäsparin seos puskuroi, ja käänteisesti, missä suhteessa happoa ja emästä on sekoitettava, jotta saadaan haluttu pH. Kun [A<sup>−</sup>] = [HA], pH = pK<sub>a</sub>. Kymmenkertainen suhde siirtää pH:ta yhden yksikön.",
  3, "Henderson–Hasselbalchin yhtälö, Henderson–Hasselbalchin yhtälön, Henderson–Hasselbalchin yhtälöä, Henderson–Hasselbalchin yhtälöllä, Henderson–Hasselbalchin yhtälössä, Henderson-Hasselbalchin yhtälö, Henderson-Hasselbalchin yhtälön, Henderson-Hasselbalchin yhtälöä, Henderson-Hasselbalchin yhtälöllä, Henderson-Hasselbalchin yhtälössä, Henderson–Hasselbalch, Henderson-Hasselbalch, Henderson–Hasselbalchia, Henderson-Hasselbalchia"),
K("Miten valmistetaan 0,1 mol/l natriumfosfaattipuskuri, jonka pH on 7,0?",
  "Henderson–Hasselbalchilla, pK<sub>a</sub> 6,86: emästä Na<sub>2</sub>HPO<sub>4</sub> 0,058 M ja happoa NaH<sub>2</sub>PO<sub>4</sub> 0,042 M.",
  "Fosforihapolla on kolme irtoavaa protonia, joiden pK<sub>a</sub>-arvot ovat 2,14, 6,86 ja 12,4. pH 7:n lähellä vain keskimmäinen tasapaino H<sub>2</sub>PO<sub>4</sub><sup>−</sup> ⇌ H<sup>+</sup> + HPO<sub>4</sub><sup>2−</sup> on merkityksellinen. Henderson–Hasselbalchin yhtälö antaa 7,0 = 6,86 + log([Na<sub>2</sub>HPO<sub>4</sub>]/[NaH<sub>2</sub>PO<sub>4</sub>]), joten log-suhde on 0,14 ja suhde 10<sup>0,14</sup> = 1,38. Kun kokonaiskonsentraatio on 0,1 mol/l, ratkaistaan [NaH<sub>2</sub>PO<sub>4</sub>] = 0,1/2,38 = 0,042 mol/l ja [Na<sub>2</sub>HPO<sub>4</sub>] = 0,058 mol/l. Käytännössä voi myös sekoittaa 0,05 M molempia, mitata pH:n ja säätää 0,1 M NaOH:lla.",
  2),
K("Miksi fosfaattipuskurissa pH 7:ssä vain toinen pK<sub>a</sub> on merkityksellinen?",
  "Vain pK<sub>a</sub> 6,86 on lähellä pH 7:ää. Muut tasapainot (2,14 ja 12,4) ovat kokonaan toisella puolella.",
  "Fosforihapon kolme protonia irtoavat eri pH-alueilla: ensimmäinen pK<sub>a</sub> 2,14, toinen 6,86 ja kolmas 12,4. Puskuri toimii vain noin yhden pH-yksikön päässä pK<sub>a</sub>:sta. pH 7:ssä ensimmäinen protoni on jo lähes kokonaan irronnut, joten H<sub>3</sub>PO<sub>4</sub>:ää ei käytännössä ole, ja kolmas protoni on tiukasti kiinni, joten PO<sub>4</sub><sup>3−</sup>:ää ei ole. Liuoksessa on siis vain H<sub>2</sub>PO<sub>4</sub><sup>−</sup> ja HPO<sub>4</sub><sup>2−</sup>, joiden välinen tasapaino, pK<sub>a</sub> 6,86, määrää pH:n. Siksi laskuun riittää yksi Henderson–Hasselbalchin yhtälö.",
  1),
# ── J. pH elimistössä ─────────────────────────────────────────────────────────
K("Miksi pH vaikuttaa proteiinien toimintaan?",
  "Eräiden aminohappojen sivuketjut ovat heikkoja happoja tai emäksiä, joiden varaus riippuu pH:sta.",
  "Osa aminohappojen sivuketjuista on heikkoja happoja tai emäksiä: esimerkiksi histidiinin imidatsolirenkaan pK<sub>a</sub> on 6,0. Sen alapuolella rengas on protonoitunut ja positiivinen, yläpuolella deprotonoitunut ja varaukseton. Koska pK<sub>a</sub> on lähellä fysiologista pH:ta, pieni pH:n muutos kääntää histidiinin varauksen. Varaus vaikuttaa ionisidoksiin, vetysidoksiin ja siten proteiinin laskostumiseen ja aktiivisen kohdan kemiaan. Siksi entsyymit toimivat vain kapealla pH-alueella ja solu puskuroi pH:taan tarkasti.",
  3, kuva="vesi_d43_170.jpeg"),
K("Mikä on histidiinin sivuketjun pK<sub>a</sub> ja miksi se on tärkeä?",
  "6,0. Lähellä fysiologista pH:ta, joten histidiini voi sekä luovuttaa että vastaanottaa protonin.",
  "Histidiinin imidatsolirenkaan pK<sub>a</sub> on 6,0. Fysiologisessa pH 7,4:ssä valtaosa histidiineistä on deprotonoituneita, mutta osuus on herkkä pH:n muutoksille ja proteiinin ympäristö voi siirtää pK<sub>a</sub>:ta lähemmäs seitsemää. Koska histidiini voi helposti sekä ottaa että antaa protonin, se on entsyymien aktiivisissa kohdissa tavallinen happo-emäskatalyytti, ja hemoglobiinissa histidiinit sitovat protoneja pH:n laskiessa, mikä säätelee hapen luovutusta kudoksiin.",
  2),
K("Mikä on elimistön normaali pH?",
  "7,4. Sen säätely on elintärkeää.",
  "Ihmisen veren ja solunulkoisen nesteen normaali pH on 7,4 ja se pysyy hyvin kapealla alueella, noin 7,35–7,45. Poikkeamat ovat vaarallisia, koska proteiinien varautuneet sivuketjut, kuten histidiini, muuttavat varaustaan ja entsyymien toiminta häiriintyy. pH:ta pitää vakiona bikarbonaatti-hiilihappopuskuri yhdessä hengityksen kanssa: aivorunko säätelee hengitystiheyttä veren pH:n mukaan ja munuaiset poistavat happoja pitkällä aikavälillä.",
  3),
K("Miten bikarbonaatti-hiilihappojärjestelmä puskuroi veren pH:ta?",
  "Bikarbonaatti sitoo protoneja hiilihapoksi, joka hajoaa hiilidioksidiksi ja poistuu hengityksessä.",
  "Veressä on tasapaino H<sup>+</sup> + HCO<sub>3</sub><sup>−</sup> ⇌ H<sub>2</sub>CO<sub>3</sub> ⇌ CO<sub>2</sub> + H<sub>2</sub>O, ja hiilidioksidi on lisäksi tasapainossa keuhkojen ilman kanssa. Kun veri happamoituu, esimerkiksi laktaatin tuoton vuoksi, bikarbonaatti sitoo protonit hiilihapoksi, joka hajoaa vedeksi ja hiilidioksidiksi. Hengitys nopeutuu ja poistaa ylimääräisen hiilidioksidin. Kun veri on liian emäksistä, esimerkiksi proteiinien katabolian vuoksi, hengitys hidastuu, hiilidioksidia kertyy ja siitä syntyvä hiilihappo laskee pH:ta. Järjestelmä on avoin, joten sen kapasiteetti on suurempi kuin suljetun puskurin.",
  3, "bikarbonaattipuskuri, bikarbonaattipuskurin, bikarbonaattipuskuria, bikarbonaattipuskurissa, bikarbonaatti-hiilihappopuskuri, bikarbonaatti-hiilihappopuskurin, bikarbonaatti-hiilihappojärjestelmä, bikarbonaatti-hiilihappojärjestelmän, bikarbonaatti, bikarbonaatin, bikarbonaattia, bikarbonaatti-ioni, bikarbonaatti-ionin, hiilihappo, hiilihapon, hiilihappoa, hiilihaposta, hiilihappoon, hiilihapoksi, vetykarbonaatti, vetykarbonaatin", kuva="vesi_d44_173.jpeg"),
K("Miksi hengitys nopeutuu, kun veren pH laskee?",
  "Aivorunko havaitsee happamuuden ja lisää hiilidioksidin poistoa, mikä vähentää hiilihappoa.",
  "Aivorungon hengityskeskus seuraa veren pH:ta ja hiilidioksidipitoisuutta. Kun veri happamoituu, esimerkiksi raskaassa liikunnassa laktaatin kertyessä, bikarbonaatti sitoo protoneja hiilihapoksi, joka hajoaa hiilidioksidiksi ja vedeksi. Nopeutunut hengitys tuulettaa hiilidioksidin pois keuhkojen kautta, jolloin tasapaino siirtyy vasemmalle ja protoneja kuluu lisää. Näin hengitys toimii puskurin poistokanavana, joka tekee bikarbonaattijärjestelmästä paljon tehokkaamman kuin suljettu kemiallinen puskuri olisi.",
  2),
K("Miksi eri entsyymeillä on eri pH-optimi?",
  "Ne toimivat eri ympäristöissä. Pepsiini mahassa pH 1,5:ssä, trypsiini suolessa neutraalissa pH:ssa.",
  "Entsyymin aktiivisen kohdan ryhmien varaus riippuu pH:sta, joten jokaisella entsyymillä on pH-alue, jolla se toimii parhaiten. Suurin osa solunsisäisistä entsyymeistä on sopeutunut pH 7,4:ään, mutta poikkeuksia on: pepsiini pilkkoo proteiineja mahalaukun pH 1,5:ssä, trypsiini toimii ohutsuolen lähes neutraalissa pH:ssa ja alkalisen fosfataasin optimi on lähellä yhdeksää. Optimin ulkopuolella aktiivisuus laskee jyrkästi, koska väärin protonoituneet ryhmät eivät sido substraattia tai katalysoi reaktiota.",
  2, kuva="vesi_d48_186.jpeg"),
K("Mitkä ovat pepsiinin, trypsiinin ja alkalisen fosfataasin pH-optimit?",
  "Pepsiini noin 1,5, trypsiini noin 7–8, alkalinen fosfataasi noin 9.",
  "Pepsiini on mahalaukun proteaasi, joka toimii parhaiten mahanesteen pH 1,5:ssä ja inaktivoituu neutraalissa. Trypsiini on haiman proteaasi, joka toimii ohutsuolen neutraalissa tai lievästi emäksisessä pH:ssa. Alkalinen fosfataasi irrottaa fosfaattiryhmiä ja sen optimi on lähellä pH 9:ää, mistä nimi tulee. Erot ovat esimerkki siitä, että entsyymi on sopeutunut toimintaympäristönsä pH:hon, ja ne hyödynnetään laboratoriossa säätämällä puskurin pH entsyymin mukaan.",
  1),
# ── K. Vesi reagenssina ───────────────────────────────────────────────────────
K("Miten vesi osallistuu biokemiallisiin reaktioihin reagenssina?",
  "Kondensaatiossa vettä syntyy tuotteena, hydrolyysissä vesi on lähtöaine, joka hajottaa sidoksen.",
  "Vesi ei ole vain liuotin vaan monessa reaktiossa suora osallistuja. Kondensaatioreaktiossa kaksi molekyyliä liittyy yhteen ja niistä irtoaa vesimolekyyli, esimerkiksi kun aminohapot liittyvät peptidiketjuksi tai monosakkaridit polysakkaridiksi. Hydrolyysi on käänteinen reaktio: vesimolekyyli hajottaa sidoksen ja jakautuu kahden tuotteen kesken, kuten ATP:n fosfoanhydridisidoksen tai polymeerien pilkkoutuessa. Joissain kondensaatioissa irtoaa veden sijaan muu pieni molekyyli.",
  3, kuva="vesi_d49_189.jpeg"),
K("Mitä hydrolyysi tarkoittaa?",
  "Sidoksen hajottamista vedellä: vesimolekyyli katkaisee sidoksen ja jakautuu tuotteiden kesken.",
  "Hydrolyysissä vesimolekyyli katkaisee kovalenttisen sidoksen niin, että toinen tuote saa vedestä hydroksyyliryhmän –OH ja toinen vedyn –H. Nimi tarkoittaa vedellä hajottamista. Hydrolyysi on kondensaation käänteisreaktio ja solun keskeinen tapa purkaa polymeerejä: proteiinit pilkotaan aminohapoiksi, polysakkaridit sokereiksi ja ATP hajotetaan ADP:ksi ja fosfaatiksi. Koska vettä on vedessä 55,5 mol/l, hydrolyysin tasapaino on vahvasti tuotteiden puolella ja reaktio vapauttaa energiaa. Kutsutaan myös: hydrolyysi, vedellä hajottaminen.",
  3, "hydrolyysi, hydrolyysin, hydrolyysiä, hydrolyysissä, hydrolyysistä, hydrolyysiin, hydrolyysit, hydrolyysejä, vesikatkaista, vesikatkaisee, hajoaa vesikatkaisussa, hajota vesikatkaisussa, vesikatkaisu, vesikatkaisun, vesikatkaisua, hajoavat vesikatkaisussa"),
K("Kuinka paljon energiaa ATP:n hydrolyysi vapauttaa?",
  "Noin 30,5 kJ/mol, kun fosfoanhydridisidos katkeaa ja syntyy ADP ja fosfaatti.",
  "Kun vesi katkaisee ATP:n uloimman fosfoanhydridisidoksen, syntyy ADP ja epäorgaaninen fosfaatti, ja standardiolosuhteissa vapautuu noin 30,5 kJ/mol. Energiaa vapautuu, koska tuotteet ovat lähtöainetta vakaammat: fosfaattiryhmien negatiiviset varaukset eivät enää hylji toisiaan, tuotteet hydratoituvat paremmin ja fosfaatilla on enemmän resonanssimuotoja. Fosfoesterisidoksen hydrolyysi vapauttaa selvästi vähemmän. Solu ei anna ATP:n hajota vesikatkaisussa vapaasti vaan kytkee sen muihin reaktioihin.",
  2, kuva="vesi_d50_197.jpeg"),
K("Miksi vettä sisältävien reaktioiden tasapaino on yleensä sillä puolella, jossa vettä ei ole?",
  "Veden konsentraatio vedessä on 55,5 mol/l, joten tasapaino työntyy pois vedestä.",
  "Vesiliuoksessa veden konsentraatio on 55,5 mol/l, valtavasti suurempi kuin minkään muun aineen. Tasapainoreaktiossa, jossa vesi on toisella puolella yhtälöä, näin suuri konsentraatio painaa tasapainoa toiselle puolelle: hydrolyysi etenee lähes loppuun, ja kondensaatio on vastaavasti epäedullinen. Siksi solu ei rakenna polymeerejä suoralla kondensaatiolla vaan kytkee synteesin ATP:n hydrolyysiin, joka kuljettaa reaktion tasapainon yli. Sama syy tekee ATP:n hydrolyysistä hyvän energialähteen.",
  2),
]
