# -*- coding: utf-8 -*-
"""Luento 2 - Vesi, osa 2: ei-kovalenttiset vuorovaikutukset, kolligatiiviset ominaisuudet,
veden ionisoituminen. Jatkaa vesi_L2_kortit.py:n listaa (skripti yhdistää osat)."""
from vesi_L2_kortit import K

KORTIT = [
# ── E. Ei-kovalenttiset vuorovaikutukset ja komplementaarisuus ────────────────
K("Mitä ovat ei-kovalenttiset vuorovaikutukset?",
  "Heikot sidokset, jotka liittävät makromolekyylejä toisiinsa ilman elektronien jakamista.",
  "Makromolekyylin sisällä atomit pitää yhdessä vahva kovalenttinen sidos, mutta makromolekyylit liittyvät toisiinsa ja laskostuvat heikommilla ei-kovalenttisilla vuorovaikutuksilla. Niitä on neljä: ionisidokset, vetysidokset, van der Waalsin vuorovaikutukset ja hydrofobiset vuorovaikutukset. Jokainen on yksinään heikko ja katkeaa lämpöliikkeessä, mutta monta yhdessä pitää rakenteen koossa, kunhan molekyylit ovat toisilleen komplementaarisia. Kutsutaan myös: heikot vuorovaikutukset, heikot sidokset.",
  3, "ei-kovalenttinen vuorovaikutus, ei-kovalenttisen vuorovaikutuksen, ei-kovalenttista vuorovaikutusta, ei-kovalenttiset vuorovaikutukset, ei-kovalenttisten vuorovaikutusten, ei-kovalenttisia vuorovaikutuksia, ei-kovalenttisilla vuorovaikutuksilla, ei-kovalenttinen sidos, ei-kovalenttisen sidoksen, ei-kovalenttiset sidokset, ei-kovalenttisia sidoksia, ei-kovalenttinen, ei-kovalenttisen, ei-kovalenttista, ei-kovalenttiset, ei-kovalenttisten, ei-kovalenttisia, heikko vuorovaikutus, heikon vuorovaikutuksen, heikot vuorovaikutukset, heikkoja vuorovaikutuksia, heikot sidokset, heikkoja sidoksia"),
K("Mitkä neljä ei-kovalenttista vuorovaikutusta pitävät biomolekyylejä yhdessä?",
  "Ionisidokset, vetysidokset, van der Waalsin vuorovaikutukset ja hydrofobiset vuorovaikutukset.",
  "Neljä heikkoa vuorovaikutusta: ionisidokset vastakkaisesti varattujen ryhmien välillä, vetysidokset happeen tai typpeen sitoutuneen vedyn ja toisen elektronegatiivisen atomin välillä, van der Waalsin vuorovaikutukset, jotka perustuvat hetkittäisiin osittaisvarauksiin kaikkien lähekkäisten atomien välillä, sekä hydrofobiset vuorovaikutukset, jotka pakkaavat ei-polaariset ryhmät yhteen pois vedestä. Tentissä ei-kovalenttisia vuorovaikutuksia kysyttäessä hydrofobinen vuorovaikutus on mainittava, jos haluaa täydet pisteet.",
  3),
K("Mikä on ionisidos?",
  "Vastakkaisesti varattujen ryhmien sähköinen vetovoima.",
  "Ionisidos syntyy vastakkaisten sähkövarausten välille, biomolekyyleissä esimerkiksi negatiivisen karboksylaatin (–COO<sup>−</sup>) ja positiivisen aminoryhmän (–NH<sub>3</sub><sup>+</sup>) välille. Samanmerkkiset varaukset puolestaan hylkivät toisiaan. Vedessä ionisidos on paljon heikompi kuin kiteessä, koska vesimolekyylien hydraatiokuori ja veden suuri eristävyys vaimentavat varausten vetovoimaa. Proteiineissa ionisidokset auttavat vakauttamaan laskostunutta rakennetta ja sitomaan varattuja substraatteja. Kutsutaan myös: suolasilta, sähköstaattinen vuorovaikutus.",
  2, "ionisidos, ionisidoksen, ionisidosta, ionisidoksessa, ionisidoksesta, ionisidokseen, ionisidokset, ionisidosten, ionisidoksia, ionisidoksissa, suolasilta, suolasillan, suolasiltaa, suolasillat, suolasiltoja, sähköstaattinen vuorovaikutus, sähköstaattisen vuorovaikutuksen, sähköstaattiset vuorovaikutukset"),
K("Mikä on dipoli-dipolisidos?",
  "Kahden polaarisen molekyylin vastakkaisten osittaisvarausten välinen vetovoima.",
  "Dipoli-dipolisidoksessa yhden polaarisen molekyylin osittain positiivinen pää vetää puoleensa toisen molekyylin osittain negatiivista päätä. Vuorovaikutus on heikompi kuin ionisidos, koska varaukset ovat vain osittaisia. Vetysidos on dipoli-dipolisidoksen erikoistapaus, jossa positiivinen pää on happeen tai typpeen sitoutunut vety, ja se on biomolekyylien tavallisin dipoli-dipolisidos. Sukulaisilmiö on ioni-dipoli-vuorovaikutus, jossa kokonainen ioni vetää puoleensa dipolin toista päätä, kuten hydraatiossa.",
  2, "dipoli-dipolisidos, dipoli-dipolisidoksen, dipoli-dipolisidosta, dipoli-dipolisidokset, dipoli-dipolisidoksia, dipoli-dipolivuorovaikutus, dipoli-dipolivuorovaikutuksen, dipoli-dipolivuorovaikutusta, dipoli-dipolivuorovaikutukset, dipoli-dipoli-vuorovaikutus, dipoli-dipoli-vuorovaikutuksen, ioni-dipoli-vuorovaikutus, ioni-dipoli-vuorovaikutuksen, ioni-dipoli-vuorovaikutusta, ioni-dipoli-vuorovaikutukset, ioni-dipoli-vuorovaikutuksia, ioni-dipolivuorovaikutus"),
K("Mikä on van der Waalsin vuorovaikutus?",
  "Hetkittäisiin osittaisvarauksiin perustuva heikko vetovoima kaikkien lähekkäisten atomien välillä.",
  "Elektronit liikkuvat atomin ympärillä jatkuvasti, joten elektronipilvi on joka hetki hieman epätasainen ja atomiin syntyy hetkellinen dipoli. Se indusoi vastakkaisen dipolin naapuriatomiin, ja atomit vetävät toisiaan heikosti puoleensa. Vuorovaikutus toimii kaikkien atomien välillä varauksesta riippumatta, mutta vain hyvin lyhyellä etäisyydellä, ja liian lähelle tultaessa se muuttuu hylkiväksi. Tiiviisti pakkautuneen proteiinin sisäosassa lukuisat van der Waalsin kontaktit tuottavat yhdessä merkittävän vakauden. Kutsutaan myös: dispersiovoimat, London-voimat, van der Waalsin sidos.",
  2, "van der Waalsin vuorovaikutus, van der Waalsin vuorovaikutuksen, van der Waalsin vuorovaikutusta, van der Waalsin vuorovaikutukset, van der Waalsin vuorovaikutusten, van der Waalsin vuorovaikutuksia, van der Waalsin sidos, van der Waalsin sidoksen, van der Waalsin sidokset, van der Waalsin sidoksia, van der Waalsin voima, van der Waalsin voimat, van der Waalsin voimia, van der Waalsin kontaktit, dispersiovoima, dispersiovoiman, dispersiovoimat, dispersiovoimia, dispersiovoimien, London-voima, London-voimat, London-voimia"),
K("Mikä on hydrofobinen vuorovaikutus?",
  "Ei-polaaristen ryhmien pakkautuminen yhteen vedessä, veden entropian kasvun ajamana.",
  "Hydrofobinen vuorovaikutus on vettä hylkivien molekyylien tai molekyylin osien yhteenliittymistä vesiliuoksessa. Toisin kuin ioni-, vety- ja van der Waalsin sidokset, se ei perustu vastakkaisten varausten vetovoimaan eikä ole varsinainen voima, vaan seuraa veden rakennemuutoksesta: kun hydrofobiset ryhmät pakkautuvat yhteen, niiden ympärille järjestäytynyt vesi vapautuu, entropia kasvaa ja vapaaenergia laskee. Se on siis pseudovoima, mutta biokemiassa keskeisen tärkeä: solukalvon rakenne ja proteiinien laskostuminen perustuvat siihen. Kutsutaan myös: hydrofobinen vaikutus, hydrofobinen efekti.",
  3, "hydrofobinen vuorovaikutus, hydrofobisen vuorovaikutuksen, hydrofobista vuorovaikutusta, hydrofobisessa vuorovaikutuksessa, hydrofobiseen vuorovaikutukseen, hydrofobiset vuorovaikutukset, hydrofobisten vuorovaikutusten, hydrofobisia vuorovaikutuksia, hydrofobinen vaikutus, hydrofobisen vaikutuksen, hydrofobista vaikutusta, hydrofobinen efekti, hydrofobisen efektin, pseudovoima, pseudovoiman, pseudovoimaksi"),
K("Miksi hydrofobinen vuorovaikutus ei ole varsinainen voima?",
  "Se ei perustu vetovoimaan vaan veden entropian kasvuun, kun hydrofobiset osat pakkautuvat yhteen.",
  "Ioni-, vety- ja van der Waalsin sidokset ovat kaikki tavalla tai toisella vastakkaisten sähkövarausten vetovoimaa. Hydrofobisten molekyylien välillä ei ole tällaista erityistä vetovoimaa, vaan niiden yhteenliittyminen johtuu ympäröivästä vedestä. Yhteen pakkautuminen vapauttaa järjestäytynyttä vettä, jolloin järjestelmän entropia kasvaa ja vapaaenergia laskee. Ajava voima on siis veden rakennemuutos, ei molekyylien keskinäinen veto, ja siksi hydrofobista vuorovaikutusta kutsutaan pseudovoimaksi.",
  2),
K("Miksi hydrofobinen vuorovaikutus on mainittava tentissä ei-kovalenttisia vuorovaikutuksia kysyttäessä?",
  "Se on biokemiassa keskeisin heikko vuorovaikutus ja jää helposti kemian luettelosta pois.",
  "Kemian oppikirjat luettelevat ei-kovalenttisiksi voimiksi tavallisesti dipoli-dipoli-vuorovaikutuksen, ioni-dipoli-vuorovaikutuksen ja dispersiovoimat, joissa kaikissa on kyse varausten vetovoimasta. Hydrofobinen vuorovaikutus puuttuu tästä luettelosta, koska se ei ole varsinainen voima. Biokemiassa se on kuitenkin keskeisen tärkeä: solukalvon kaksoiskalvo, proteiinien laskostuminen ja monien makromolekyylikompleksien kokoontuminen perustuvat siihen. Luennoitsijan ohje: täydet pisteet edellyttävät hydrofobisen vuorovaikutuksen mainitsemista.",
  3),
K("Miksi makromolekyylien on oltava komplementaarisia pysyäkseen yhdessä?",
  "Heikot sidokset pitävät lämpöliikkeessä vain, jos niitä syntyy monta, ja se vaatii yhteensopivat pinnat.",
  "Yksittäinen ei-kovalenttinen sidos on niin heikko, että lämpöliike katkaisee sen hetkessä. Kaksi makromolekyyliä pysyy yhdessä vain, jos niiden välille syntyy samanaikaisesti monta heikkoa sidosta, joiden yhteisvoima ylittää lämpöliikkeen. Monta sidosta voi syntyä vain, jos molekyylien pinnat sopivat toisiinsa muodoltaan ja kemialtaan: positiivinen varaus vastapäätä negatiivista, vetysidoksen luovuttaja vastapäätä vastaanottajaa, hydrofobinen pinta vastapäätä hydrofobista. Tätä yhteensopivuutta kutsutaan komplementaarisuudeksi.",
  3),
K("Miten komplementaarisuus tuottaa spesifisyyttä?",
  "Vain oikea molekyyli muodostaa tarpeeksi heikkoja sidoksia. Pienikin rakenne-ero estää sitoutumisen.",
  "Kun sitoutuminen vaatii monta samanaikaista heikkoa vuorovaikutusta, vain pintaan täsmällisesti sopiva molekyyli saa niitä riittävästi. Jo pieni ero rakenteessa, väärään paikkaan osuva varaus tai puuttuva vetysidoksen luovuttaja, vähentää sidosten määrää niin, että lämpöliike irrottaa molekyylin. Käytännöllisesti katsoen kaikki makromolekyylien toiminta biologiassa perustuu tähän: entsyymi tunnistaa substraattinsa, vasta-aine antigeeninsa ja DNA-juosteet toisensa komplementaarisuuden avulla. Esimerkki itsestään kokoontuvista rakenteista ovat viruksen kuoriproteiinit, jotka kokoontuvat kuoreksi ilman ohjausta.",
  2),
K("Miten vesi sitoutuu makromolekyyleihin?",
  "Makromolekyylit ovat aina veden peitossa. Vesimolekyylit sitoutuvat niihin heikoilla vuorovaikutuksilla.",
  "Solussa makromolekyyli ei ole koskaan kuivana vaan jatkuvassa kontaktissa vesimolekyylien kanssa, jotka sitoutuvat sen pinnan polaarisiin ja varattuihin ryhmiin vetysidoksilla ja ioni-dipoli-vuorovaikutuksilla. Kuvassa hemoglobiini näkyy sitoutuneiden vesimolekyylien kanssa (a) ja ilman niitä (b): pinta on tiheästi veden peitossa. Osa vedestä on niin lujasti sitoutunut, että se on käytännössä osa proteiinin rakennetta ja välttämätön sen toiminnalle.",
  2, kuva="vesi_d26_113.jpeg"),
# ── F. Kolligatiiviset ominaisuudet ja osmoosi ────────────────────────────────
K("Mitä ovat kolligatiiviset ominaisuudet?",
  "Liuoksen ominaisuudet, jotka riippuvat vain liuenneiden hiukkasten lukumäärästä, ei laadusta.",
  "Kun veteen tai mihin tahansa yhdestä molekyylilajista koostuvaan nesteeseen liukenee toista ainetta, tietyt fysikaaliskemialliset ominaisuudet muuttuvat tavalla, joka riippuu yksinomaan liuenneiden hiukkasten, molekyylien tai ionien, lukumäärästä eikä siitä, mitä ainetta ne ovat. Näitä kolligatiivisia ominaisuuksia ovat höyrynpaine, kiehumispiste, sulamispiste ja osmoottinen paine. Liuennut aine laskee höyrynpainetta ja sulamispistettä, nostaa kiehumispistettä ja synnyttää osmoottisen paineen.",
  3, "kolligatiivinen ominaisuus, kolligatiivisen ominaisuuden, kolligatiivista ominaisuutta, kolligatiiviset ominaisuudet, kolligatiivisten ominaisuuksien, kolligatiivisia ominaisuuksia, kolligatiivisiin ominaisuuksiin, kolligatiivinen, kolligatiivisen, kolligatiivista, kolligatiiviset, kolligatiivisten, kolligatiivisia"),
K("Mitkä neljä ominaisuutta ovat kolligatiivisia?",
  "Höyrynpaine, kiehumispiste, sulamispiste ja osmoottinen paine.",
  "Neljä kolligatiivista ominaisuutta ovat höyrynpaine, kiehumispiste, sulamispiste ja osmoottinen paine. Kaikki muuttuvat, kun nesteeseen liukenee toista ainetta, ja muutoksen suuruus riippuu vain liuenneiden hiukkasten määrästä. Höyrynpaine laskee, koska pinnalla on vähemmän vesimolekyylejä. Kiehumispiste nousee samasta syystä. Sulamispiste laskee, koska liuenneet hiukkaset häiritsevät jääkiteen muodostumista. Osmoottinen paine syntyy, kun vesi pyrkii puoliläpäisevän kalvon läpi laimentamaan väkevämpää liuosta.",
  3),
K("Miksi liuennut aine muuttaa veden kiehumista ja jäätymistä?",
  "Veden konsentraatio on liuoksessa pienempi kuin puhtaassa vedessä.",
  "Puhtaassa vedessä jokainen pinnan molekyyli on vettä ja voi höyrystyä, ja jokainen molekyyli voi liittyä jääkiteeseen. Liuoksessa osa pinnan ja nesteen paikoista on liuenneiden hiukkasten hallussa, joten veden tehollinen konsentraatio on pienempi. Höyrynpaine laskee ja kiehuminen vaatii korkeamman lämpötilan, ja jääkiteen kasvu hidastuu, joten jäätyminen vaatii matalamman lämpötilan. Jokainen liuennut molekyyli tai ioni vaikuttaa tähän vain lukumääränsä mukaan.",
  2, kuva="vesi_d29_120.jpeg"),
K("Miksi mooli NaCl:a vaikuttaa kolligatiivisiin ominaisuuksiin kaksi kertaa enemmän kuin mooli glukoosia?",
  "NaCl dissosioituu kahdeksi ioniksi, glukoosi pysyy yhtenä molekyylinä.",
  "Kolligatiiviset ominaisuudet riippuvat liuenneiden hiukkasten lukumäärästä. Glukoosi ei dissosioidu, joten mooli glukoosia on liuoksessa mooli hiukkasia. Natriumkloridi hajoaa vedessä kokonaan natrium- ja kloridi-ioneiksi, joten mooli NaCl:a tuottaa kaksi moolia hiukkasia. Siksi sama moolimäärä suolaa laskee sulamispistettä, nostaa kiehumispistettä ja nostaa osmoottista painetta kaksinkertaisesti glukoosiin verrattuna. Osmolariteetti lasketaan juuri hiukkasten, ei liuenneiden yhdisteiden, määrästä.",
  2),
K("Mitä on osmoosi?",
  "Veden siirtymistä puoliläpäisevän kalvon läpi laimeammasta väkevämpään liuokseen.",
  "Osmoosissa vesi siirtyy sellaisen kalvon läpi, joka läpäisee vettä mutta ei liuenneita aineita, laimeammasta liuoksesta väkevämpään. Solukalvo on tällainen kalvo. Siirtyminen jatkuu, kunnes liuosten osmolariteetti kalvon molemmilla puolilla on sama tai kunnes vastapaine pysäyttää sen. Ajava voima on veden konsentraatioero: puhtaassa vedessä vettä on enemmän kuin liuoksessa, joten vesi virtaa sinne, missä sitä on suhteellisesti vähemmän.",
  3, "osmoosi, osmoosin, osmoosia, osmoosissa, osmoosista, osmoosiin, osmoottinen, osmoottisen, osmoottista, osmoottisessa, osmoottisesta, osmoottiseen, osmoottisesti, puoliläpäisevä kalvo, puoliläpäisevän kalvon, puoliläpäisevää kalvoa, puoliläpäisevä, puoliläpäisevän"),
K("Mikä on osmoottinen paine?",
  "Paine, joka tarvitaan estämään veden osmoottinen virtaus väkevämpään liuokseen.",
  "Kun puoliläpäisevä kalvo erottaa puhtaan veden ja liuoksen, vesi virtaa liuokseen ja nostaa sen pintaa, kunnes nestepatsaan paine pysäyttää virtauksen. Tämä paine on liuoksen osmoottinen paine, ja sama vaikutus saadaan painamalla männällä. Osmoottinen paine on kolligatiivinen ominaisuus: se on suoraan verrannollinen liuenneiden hiukkasten lukumäärään eikä riipu niiden laadusta. Soluille osmoottinen paine on jatkuva haaste, koska solukalvo läpäisee vettä mutta ei useimpia liuenneita aineita.",
  3, "osmoottinen paine, osmoottisen paineen, osmoottista painetta, osmoottisessa paineessa, osmoottisesta paineesta, osmoottiseen paineeseen", kuva="vesi_d30_123.jpeg"),
K("Mitä osmolariteetti tarkoittaa?",
  "Liuenneiden hiukkasten kokonaiskonsentraatio liuoksessa.",
  "Osmolariteetti on kaikkien liuenneiden, kalvoa läpäisemättömien hiukkasten yhteenlaskettu konsentraatio litraa kohti. Dissosioituva aine lasketaan ioneittensa mukaan: 0,1 M NaCl-liuoksen osmolariteetti on 0,2 osmol/ℓ, 0,1 M glukoosiliuoksen 0,1 osmol/ℓ. Osmoosi tasaa osmolariteettia kalvon molemmin puolin, ja liuoksia verrataan sen mukaan: samaosmolariteettiset liuokset ovat isotonisia, väkevämpi hypertoninen ja laimeampi hypotoninen. Kutsutaan myös: osmoottinen konsentraatio.",
  2, "osmolariteetti, osmolariteetin, osmolariteettia, osmolariteetissa, osmolariteetista, osmolariteettiin, osmolaarisuus, osmolaarisuuden, osmolaarisuutta, osmoottinen konsentraatio, osmoottisen konsentraation"),
K("Mitä isotoninen, hypertoninen ja hypotoninen liuos tarkoittavat?",
  "Isotoninen: sama osmolariteetti kuin solussa. Hypertoninen: suurempi. Hypotoninen: pienempi.",
  "Liuoksia verrataan solun sisällön osmolariteettiin. Isotonisessa liuoksessa osmolariteetti on sama kuin solun sisällä, joten vettä ei siirry ja solu säilyttää muotonsa. Hypertonisessa liuoksessa ulkopuolella on enemmän liuenneita hiukkasia, joten vesi virtaa ulos ja solu kutistuu. Hypotonisessa liuoksessa ulkopuolella on vähemmän hiukkasia, vesi virtaa sisään, solu turpoaa ja voi lopulta haljeta. Fysiologinen 0,9 % NaCl-liuos on isotoninen ihmisen solujen kanssa.",
  3, "isotoninen, isotonisen, isotonista, isotonisessa, isotoniset, isotonisia, isotonisessa liuoksessa, hypertoninen, hypertonisen, hypertonista, hypertonisessa, hypertoniset, hypertonisia, hypotoninen, hypotonisen, hypotonista, hypotonisessa, hypotoniset, hypotonisia", kuva="vesi_d31_126.jpeg"),
K("Mitä solulle tapahtuu hypotonisessa ja hypertonisessa liuoksessa?",
  "Hypotonisessa vesi virtaa sisään ja solu turpoaa, hypertonisessa vesi virtaa ulos ja solu kutistuu.",
  "Vesi liikkuu solukalvon yli tasatakseen osmoottisen paineen, koska kalvo läpäisee vettä mutta ei useimpia liuenneita aineita. Hypotonisessa liuoksessa solun sisällä on enemmän liuenneita hiukkasia kuin ulkona, joten vesi virtaa sisään, solu turpoaa ja eläinsolu voi haljeta. Hypertonisessa liuoksessa vesi virtaa ulos ja solu kutistuu. Kasvi- ja bakteerisolut kestävät turpoamista soluseinänsä ansiosta, mutta eläinsolut tarvitsevat ympärilleen isotonisen nesteen, jonka elimistö pitää tarkasti vakiona.",
  3),
K("Miksi suolavesi ei kirvele silmissä tai haavassa, mutta makea vesi kirvelee?",
  "Suolavesi on lähes isotoninen solujen kanssa, makea vesi hypotoninen ja turvottaa soluja.",
  "Silmän pinnan ja haavan solut ovat tottuneet elimistön nesteisiin, joiden osmolariteetti vastaa noin 0,9 % NaCl-liuosta. Suolavesi on lähellä tätä, joten vettä ei siirry soluihin eikä niistä pois eikä ärsytystä synny. Makea vesi on hypotonista: vesi virtaa osmoottisesti soluihin, ne turpoavat ja kalvon venyminen ärsyttää hermopäätteitä, mikä tuntuu kirvelynä. Siksi haavan huuhteluun ja piilolinsseille käytetään fysiologista suolaliuosta, ei vesijohtovettä.",
  2),
K("Mikä on fysiologinen suolaliuos?",
  "0,9 % NaCl-liuos, joka on isotoninen ihmiselimistön kanssa.",
  "Fysiologinen suolaliuos sisältää 0,9 painoprosenttia natriumkloridia eli 9 g litrassa, mikä vastaa noin 0,15 mol/ℓ NaCl:a ja noin 0,3 osmol/ℓ osmolariteettia. Se on isotoninen ihmisen solujen ja veriplasman kanssa, joten se ei aiheuta veden siirtymistä soluihin tai niistä pois. Siksi sitä käytetään suonensisäisenä nesteenä, haavojen huuhteluun, nenähuuhteluun ja piilolinssien säilytykseen. Kutsutaan myös: keittosuolaliuos, isotoninen suolaliuos.",
  2, "fysiologinen suolaliuos, fysiologisen suolaliuoksen, fysiologista suolaliuosta, fysiologisessa suolaliuoksessa, fysiologiseen suolaliuokseen, fysiologisella suolaliuoksella, keittosuolaliuos, keittosuolaliuoksen, keittosuolaliuosta, keittosuolaliuoksessa, keittosuolaliuoksella"),
# ── G. Veden ionisoituminen ───────────────────────────────────────────────────
K("Mitä on veden autoprotolyysi?",
  "Veden vähäistä hajoamista vetyioneiksi ja hydroksidi-ioneiksi: H<sub>2</sub>O ⇌ H<sup>+</sup> + OH<sup>−</sup>.",
  "Puhtaassakin vedessä pieni osa molekyyleistä hajoaa jatkuvasti protoniksi ja hydroksidi-ioniksi ja yhtyy takaisin: H<sub>2</sub>O ⇌ H<sup>+</sup> + OH<sup>−</sup>. Käytännössä protoni ei ole vapaana vaan siirtyy toiselle vesimolekyylille hydroniumioniksi H<sub>3</sub>O<sup>+</sup>. Tasapaino on vahvasti vasemmalla: 25 °C:ssa vetyionien ja hydroksidi-ionien konsentraatio on vain 10<sup>−7</sup> mol/ℓ, ja niiden tulo K<sub>w</sub> = 1,0 × 10<sup>−14</sup> M<sup>2</sup> on vakio. Autoprotolyysi on pH-käsitteen perusta. Kutsutaan myös: veden ionisoituminen, veden autoionisaatio.",
  3, "autoprotolyysi, autoprotolyysin, autoprotolyysiä, autoprotolyysissä, autoprotolyysistä, autoprotolyysiin, autoprotolyysireaktio, autoprotolyysireaktion, autoprotolyysireaktiota, autoionisaatio, autoionisaation, veden ionisoituminen, veden ionisoitumisen, veden ionisoitumista"),
K("Mikä on hydroniumioni?",
  "Vesimolekyyli, joka on sitonut ylimääräisen protonin: H<sub>3</sub>O<sup>+</sup>.",
  "Vapaa protoni H<sup>+</sup> ei esiinny vedessä sellaisenaan, vaan se sitoutuu heti vesimolekyylin hapen vapaaseen elektronipariin hydroniumioniksi H<sub>3</sub>O<sup>+</sup>. Kun kirjoitetaan H<sup>+</sup> tai puhutaan vetyionista, tarkoitetaan käytännössä hydroniumionia. Hydroniumionilla ja hydroksidi-ionilla on vedessä epätavallisen suuri näennäinen liikkuvuus, koska varaus ei kulje molekyylin mukana vaan hyppii vesimolekyyliltä toiselle Grotthuss-mekanismilla. Kutsutaan myös: oksoniumioni, vetyioni, protoni.",
  2, "hydroniumioni, hydroniumionin, hydroniumionia, hydroniumionissa, hydroniumioniin, hydroniumionit, hydroniumionien, hydroniumioneja, hydroniumioniksi, oksoniumioni, oksoniumionin, vetyioni, vetyionin, vetyionia, vetyionit, vetyionien, vetyioneja, vetyioneiksi"),
K("Mikä on hydroksidi-ioni?",
  "Vesimolekyyli, jolta on irronnut protoni: OH<sup>−</sup>.",
  "Hydroksidi-ioni OH<sup>−</sup> syntyy, kun vesimolekyyli luovuttaa protonin, esimerkiksi autoprotolyysissä tai emäksen liuetessa veteen. Se on veden vastinemäs ja vahva protonin vastaanottaja: liuoksessa se sitoo protonin heti, kun sellainen on tarjolla, ja muodostaa vettä. Hydroksidi-ionien konsentraatio määrää liuoksen pOH:n, ja koska K<sub>w</sub> on vakio, [OH<sup>−</sup>] kasvaa aina, kun [H<sup>+</sup>] pienenee: pH + pOH = 14. Kutsutaan myös: hydroksyyli-ioni.",
  2, "hydroksidi-ioni, hydroksidi-ionin, hydroksidi-ionia, hydroksidi-ionissa, hydroksidi-ioniin, hydroksidi-ionit, hydroksidi-ionien, hydroksidi-ioneja, hydroksidi-ioneiksi, hydroksidi-ionille, hydroksidi, hydroksidin, hydroksidia, hydroksidiksi, hydroksyyli-ioni, hydroksyyli-ionin"),
K("Mikä on Grotthuss-mekanismi?",
  "Protonin hyppiminen vesimolekyyliltä toiselle vetysidoksia pitkin ilman molekyylien liikettä.",
  "Grotthuss-mekanismissa protoni ei kulkeudu vedessä yhtenä hiukkasena vaan siirtyy vetysidosta pitkin seuraavalle vesimolekyylille, joka luovuttaa oman protoninsa edelleen. Yksittäisten vesimolekyylien ei tarvitse liikkua, ja jokainen protoni siirtyy vain lyhyen matkan, joten positiivinen varaus etenee ketjureaktiona hyvin nopeasti. Siksi hydronium- ja hydroksidi-ioneilla on vedessä epätavallisen suuri näennäinen liikkuvuus. Sama ilmiö kuljettaa protoneja proteiinien vesitaskuissa. Kutsutaan myös: protonihyppely, proton hopping.",
  2, "Grotthuss-mekanismi, Grotthuss-mekanismin, Grotthuss-mekanismia, Grotthuss-mekanismissa, Grotthuss-mekanismilla, Grotthuss-mekanismiin, protonihyppely, protonihyppelyn, protonihyppelyä, protonihyppelyllä, proton hopping", kuva="vesi_d34_139.jpeg"),
K("Miksi hydronium- ja hydroksidi-ionit liikkuvat vedessä poikkeuksellisen nopeasti?",
  "Varaus hyppii vesimolekyyliltä toiselle Grotthuss-mekanismilla, eivätkä molekyylit itse liiku.",
  "Tavallinen ioni, kuten Na<sup>+</sup>, joutuu liikkumaan vedessä hydraatiokuorensa kanssa, mikä on hidasta. Protoni sen sijaan voi siirtyä hydroniumionilta vetysidosta pitkin viereiselle vesimolekyylille, joka puolestaan luovuttaa yhden vedyistään seuraavalle. Positiivinen varaus etenee siis ketjuna, vaikka jokainen protoni liikkuu vain sidoksen mitan. Hydroksidi-ionin kohdalla sama tapahtuu käänteisesti: vesimolekyyli luovuttaa protonin hydroksidille ja muuttuu itse hydroksidiksi. Näennäinen liikkuvuus on siksi moninkertainen muihin ioneihin verrattuna.",
  2),
K("Mikä on vesitasku proteiinissa?",
  "Proteiinin sisäinen onkalo, jonka vesimolekyylit sitoutuvat vetysidoksilla aminohappotähteisiin.",
  "Monissa proteiineissa on sisäisiä taskuja, joissa muutama vesimolekyyli on sitoutunut vetysidoksilla ympäröiviin aminohappotähteisiin, esimerkiksi asparagiinin, glutamiinin tai arginiinin sivuketjuihin. Nämä vesimolekyylit ovat käytännössä osa proteiinin rakennetta. Ketjuun järjestyneet vesimolekyylit toimivat protonijohtimena: protonit hyppivät niitä pitkin Grotthuss-mekanismilla proteiinin läpi. Kuvan esimerkissä sytokromi f:n vesiketju kuljettaa protoneja kalvon yli osana fotosynteesin elektronivuota.",
  1, "vesitasku, vesitaskun, vesitaskua, vesitaskussa, vesitaskusta, vesitaskuun, vesitaskut, vesitaskujen, vesitaskuja, vesitaskuissa", kuva="vesi_d35_143.jpeg"),
K("Miten protoneja pumpataan kalvon yli sytokromi f:ssä?",
  "Protonit hyppivät proteiinin vesitaskun vesiketjua pitkin, kytkettynä fotosynteesin elektronivuohon.",
  "Sytokromi f on fotosynteesin elektroninsiirtoketjun proteiini. Sen sisällä on ketju vesimolekyylejä, jotka on sidottu vetysidoksilla aminohappotähteisiin. Elektronien virtaus proteiinin läpi muuttaa ryhmien varauksia niin, että protoni siirtyy vesiketjun toisesta päästä toiseen Grotthuss-mekanismilla, vesimolekyyliltä toiselle vetysidoksia myöten. Näin elektronivuo ja protonien siirto kalvon yli kytkeytyvät toisiinsa, ja syntyvä protonigradientti käytetään lopulta ATP:n valmistukseen.",
  1),
]
